### ISSUE TITLE
Password not copied to clipboard if "Show the password" is disabled

### ISSUE THREAD

**Issue by djl** [zeapo/Android-Password-Store#100]
I'm seeing a bug where passwords are not copied to the clipboard if the "Show the password" field is unchecked, regardless of the "Automatically Copy Password" option.

Steps to reproduce:

1. Uncheck "Show the password" option
2. Check the "Automatically Copy Password" option
3. Copy a password to the clipboard
4. Notice the clipboard is empty

APK version: 1.2.0.23
OpenPGP provider: OpenKeyChain

**Comment by zeapo** [comment]
Indeed, thanks for the report.
