### ISSUE TITLE
[FEATURE] Notify user when there is nothing to push

### ISSUE THREAD

**Issue by matthijskooijman** [zeapo/Android-Password-Store#1000]
**Describe the bug**
When using "Push to remote", but the push is denied by the server (in my case because my remote repository is not bare and had the `master` branch checked out), I get no error message from Password Store.

**To Reproduce**
1. Configure an SSH remote that is a non-bare repository, with the master branch checked out
2. Generate a password on Password Store to have something to push
3. Use "Push to remote" from the three-dots-menu

**Expected behavior**
The error, as returned/shown by git should be returned.

**Device information (please complete the following information):**
 - Device: Fairphone2
 - OS: Fairphone Open Android 7
 - App version: 1.9.2

Note that changing the checked out branch in the remote repository allowed the push to work properly, so all other settings must have been configured properly. This report is also not about the fact that the push failed (it should have, I misconfigured things), but about that it fails silently.

**Comment by matthijskooijman** [comment]
Note that an error messages are not omitted on all push failures, when I messed up my SSH key forced-command just now, it did show an error message.

**Comment by msfjarvis** [comment]
@matthijskooijman out of [these](https://bin.msfjarvis.dev/~5f30f2f42757e30018410ce8) possible states, what would you have expected the app to see after that particular case?

**Comment by matthijskooijman** [comment]
I think only `REJECTED_OTHER_REASON` would be appropriate. I think the git process will have emitted a more specific error message, that could then be shown I think (which should be helpful enough, so I don't think there's any real reason to handle this case with its own error code specificially).

**Comment by msfjarvis** [comment]
> I think only `REJECTED_OTHER_REASON` would be appropriate. I think the git process will have emitted a more specific error message, that could then be shown I think (which should be helpful enough, so I don't think there's any real reason to handle this case with its own error code specificially).

Hm, we're already [handling it](https://github.com/android-password-store/Android-Password-Store/blob/develop/app/src/main/java/com/zeapo/pwdstore/git/GitCommandExecutor.kt#L91-L96) and passing along the raw message from JGit so hopefully you'll see improved behaviour in the 1.11.0 release. For an early sneak peek you can check out the snapshot build from [here](https://dl.msfjarvis.dev/APS). The free/nonFree distinction is explained in the README.

**Comment by matthijskooijman** [comment]
I tried the snapshot, but it still does not show an error. When I select "Push to remote", the screen becomes grey with "Running git operation..." at the bottom for a few seconds, then the repository is shown again normally as if the operation succeeded.

I checked logcat, but the only password store message there is meaningless to me:

    08-10 12:41:57.100  6554  6554 D PasswordStore: Check, dir: /storage/emulated/0/pass2                                                            

I only got this once, subsequent tries did not show any output from PasswordStore.

**Comment by msfjarvis** [comment]
I tried this right now. I pointed the app to my `~/.password-store` repository which has the `main` branch checked out, then I created a new password in the app, and attempted to push. To the best of my abilities, I believe this is the exact scenario you described in the issue. This is what I get:

<details>
<summary>Screenshot</summary>

![screenshot-20200810-200309](https://user-images.githubusercontent.com/13348378/89794369-973f7980-db44-11ea-9f62-b683ad230500.png)

</details>

In the logs, `REJECTED_OTHER_REASON` is correctly marked as the reason for this failure, and `PushException` is also correctly thrown.

**Comment by matthijskooijman** [comment]
> I pointed the app to my ~/.password-store repository which has the main branch checked out, then I created a new password in the app, and attempted to push. To the best of my abilities, I believe this is the exact scenario you described in the issue.

Yes, sounds like exactly what I did. Thanks for diving in!

Maybe there's something specific in my setup then. I am using some specific SSH-key-based limitations, so maybe that is relevant somehow.

I'll try reproducing this with an ssh push outside of PasswordStore, to see if git is actually providing the right error message at all, or disable the SSH key limitations and see if that fixes it. I'll get back to you.

Is there a way to enable some more debug output in PasswordStore? E.g. show git commands ran or so?

**Comment by msfjarvis** [comment]
> > I pointed the app to my ~/.password-store repository which has the main branch checked out, then I created a new password in the app, and attempted to push. To the best of my abilities, I believe this is the exact scenario you described in the issue.
> 
> Yes, sounds like exactly what I did. Thanks for diving in!
> 
> Maybe there's something specific in my setup then. I am using some specific SSH-key-based limitations, so maybe that is relevant somehow.
> 
> I'll try reproducing this with an ssh push outside of PasswordStore, to see if git is actually providing the right error message at all, or disable the SSH key limitations and see if that fixes it. I'll get back to you.
> 
> Is there a way to enable some more debug output in PasswordStore? E.g. show git commands ran or so?

Not at the moment but I can provide an APK with extra logs added if you want it.

**Comment by matthijskooijman** [comment]
> Not at the moment but I can provide an APK with extra logs added if you want it.

If it's easy, then yes please. If it's a (bit of a) bother for you, then let me do some other testing first :-)

**Comment by msfjarvis** [comment]
> > Not at the moment but I can provide an APK with extra logs added if you want it.
> 
> If it's easy, then yes please. If it's a (bit of a) bother for you, then let me do some other testing first :-)

No trouble at all, [here](https://dl.msfjarvis.dev/share/APS_1.11.0-SNAPSHOT_git_debug.apk) you go. It'll log the fields as given in [this diff](https://bin.msfjarvis.dev/~5f3160092757e30018410cec/raw).

**Comment by matthijskooijman** [comment]
Ok, tried again, now it worked as expected (in both the snapshot build I used previously and the debug build you provided). It seems that the commit I wanted to push had gotten lost, probably because it was overwritten by a fresh clone and I did not realize this, or I did something else to lose it. So in my previous test, nothing happened because there was not actually anything to push.

So, seems that 1.11 wil indeed fix this. Feel free to close this, or leave it open until released, whichever you prefer.

Thanks!

**Comment by msfjarvis** [comment]
> Ok, tried again, now it worked as expected (in both the snapshot build I used previously and the debug build you provided). It seems that the commit I wanted to push had gotten lost, probably because it was overwritten by a fresh clone and I did not realize this, or I did something else to lose it. So in my previous test, nothing happened because there was not actually anything to push.
> 
> So, seems that 1.11 wil indeed fix this. Feel free to close this, or leave it open until released, whichever you prefer.
> 
> Thanks!

There's been a to-do to handle the 'nothing to push' case for a while so I'll just convert this to be about that.
