### ISSUE TITLE
[BUG] Unable to properly enter bitbucket git server settings in version 1.11.0-SNAPSHOT

### ISSUE THREAD

**Issue by eklebanow** [zeapo/Android-Password-Store#1002]
**Describe the bug**
Cannot get proper git server settings to utilize app connection to remote bitbucket repo

**To Reproduce**
1. Attempt to enter bitbucket git server settings under settings
2. no matter what combo of username, server URL and Repo Path I get error messages suggesting git settings are set up wrong
3. Instead of git@bitbucket.org:klebane/password_store.bare.git I get errors when I try to sync that say repo path was klebane@git@bitbucket.org/password_store.bare.git

**Expected behavior**
In legacy version of password store I can enter proper server settings

**Screenshots**

**Device information (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: gentoo
 - App version 1.11.0 SNAPSHOT vs 1.3.3 (legacy)

**Additional context**

**Comment by msfjarvis** [comment]
What settings were you using in the legacy version? Can I see a screenshot?

**Comment by eklebanow** [comment]
Here are screenshots from the new version
[Screenshot (Aug 10, 2020 10_50_59).pdf](https://github.com/android-password-store/Android-Password-Store/files/5052513/Screenshot.Aug.10.2020.10_50_59.pdf)
[Screenshot (Aug 10, 2020 10_50_01).pdf](https://github.com/android-password-store/Android-Password-Store/files/5052514/Screenshot.Aug.10.2020.10_50_01.pdf)
Here is a screenshot from the legacy version:
[Screenshot (Aug 10, 2020 11_02_00).pdf](https://github.com/android-password-store/Android-Password-Store/files/5052516/Screenshot.Aug.10.2020.11_02_00.pdf)

In legacy version git settings end up being correct (i.e git@bitbucket.org:klebane/password_store.bare.git)

In new version I cannot get git settings to be of syntax necessary for bitbucket

**Comment by eklebanow** [comment]
mistake in closing ....

**Comment by fmeum** [comment]
@eklebanow Please try again with the following settings:
Username: git
Server URL: bitbucket.org
Port: doesn't have to be specified, 22 is the default
Repo path: klebane/password_store.bare.git
