### ISSUE TITLE
[BUG] Confusing state when initial git clone fails

### ISSUE THREAD

**Issue by matthijskooijman** [zeapo/Android-Password-Store#1003]
**Describe the bug**
For #1000, I just tested the snapshot build linked there. That started me from a clean install, so I had to reclone my repository. I messed up the hostname, so clone failed, leaving me without any obvious way to retry the clone.

**To Reproduce**
1. On a clean install, select the "clone from server" option in the main screen
2. Fill in incorrect details (e.g. non-existent hostname)
3. Click "clone" (IIRC), see that it fails
4. You are now presented with an empty password repository, without any git options (no push/pull in the menu, no git settings under setttings, no "clone from server" on the main screen anymore).

**Expected behavior**
Ideally, it would just reshow the git clone window, so I can correct the settings and try again. If I would then cancel, I think it would be better if the pass repo is not created at all, so the home screen with "use local" and "clone from server" (or something like that) is shown again.

Alternatively, or additionaly, it might be useful to actually show git settings even when the current repository is not a git repo, to allow converting it to one (might also be useful when you start with a local repo, adding passwords and then want to push it somewhere, but this might be trickier to get right).

**Device information (please complete the following information):**
 - Device: Fairphone2
 - OS: Fairphone Open Android 7
 - App version: 1.11.0-SNAPSHOT-free (downloaded today)

**Comment by matthijskooijman** [comment]
Note that I saw this when using an external SD path for the repo, but I suspect the same would happen for an internal path.

As a workaround, I changed the repo path to a new directory, after which the home screen with e.g. "Clone from server" is shown again and I can try again.

**Comment by matthijskooijman** [comment]
This might be a new problem in the snapshot 1.11 build. I just switched back to 1.9.2 and messed up the authentication, which shows an "auth failed" error message and then drops me back into the git clone settings window, so there's either a difference between auth failure and invalid hostname, or a difference between 1.9.2 and 1.11 (the latter seems more likely to me).

**Comment by msfjarvis** [comment]
> This might be a new problem in the snapshot 1.11 build. I just switched back to 1.9.2 and messed up the authentication, which shows an "auth failed" error message and then drops me back into the git clone settings window, so there's either a difference between auth failure and invalid hostname, or a difference between 1.9.2 and 1.11 (the latter seems more likely to me).

Well, that one's gonna hurt.

```bash
$ git diff v1.9.2 --stat
<snip>
242 files changed, 5076 insertions(+), 2947 deletions(-)
```

I'll look into it before release.

**Comment by msfjarvis** [comment]
Turns out, not that hard!
