### ISSUE TITLE
[BUG] UI flow when using external SD path with git clone interrupted

### ISSUE THREAD

**Issue by matthijskooijman** [zeapo/Android-Password-Store#1004]
**Describe the bug**
When you use an external directory for the pass repo together with a git clone, the UI flow is a bit weird.

**To Reproduce**
1. On a clean install, select the "clone from server" option in the main screen
2. When asked to use internal or external path, select external
3. In the file browser, select some path on the SD card
4. You are now dumped in the settings screen, rather than continuing with the git clone
5. If you press back, you are back in the home screen
6. Select "clone from server" again
7. When asked to use internal or external path, select external again
8. When asked to use the previously selected path, select "Yes" (or "Use" maybe, don't recall exactly)
9. You are now (finally) in the clone settings screen

**Expected behavior**
Step 4-8 should not be needed, it should jump from 3 to 9 directly.

**Device information (please complete the following information):**
 - Device: Fairphone2
 - OS: Fairphone Open Android 7
 - App version: 1.11.0-SNAPSHOT-free (downloaded today), also saw this with 1.9.2 before.

**Comment by msfjarvis** [comment]
Fixed by #1022
