### ISSUE TITLE
[FEATURE] Do not create empty sync commits

### ISSUE THREAD

**Issue by fmeum** [zeapo/Android-Password-Store#1014]
**Is your feature request related to a problem? Please describe.**
Currently, APS creates a commit on every sync operation. Most of the time, if not always, this is an empty commit that unnecessarily pollutes the Git history.

**Describe the solution you'd like**
Either never make the commit (if all other operations commit their changes correctly, it shouldn't be needed at all) or only make it if there are actual changes.

**Describe alternatives you've considered**
Just leaving this as is, since it is not much of an issue.

**Additional context**
Tracking https://github.com/android-password-store/Android-Password-Store/pull/1012#issuecomment-672798759

**Comment by msfjarvis** [comment]
Ah forgot to mention this yesterday. I looked at this, and the fix is to bring back the `git.status()` invocations which then regress committing completely. I'll try again after work.

**Comment by haansn08** [comment]
This problem is reappearing in version 1.13.1. Empty "[Android Password Store] Sync" commits are being pushed to remote every time the "Synchronize repository" button is pressed. Could this issue be reopened?

**Comment by msfjarvis** [comment]
Filed #1238 separately to track this as a regression.
