### ISSUE TITLE
cloning from gitlab

### ISSUE THREAD

**Issue by r8b7xy** [zeapo/Android-Password-Store#102]
I can't clone gitlab's repo. I'm curious whether or not this problem is reproducible.

**Comment by zeapo** [comment]
I don't understand yet why I get an "Auth failed" on gitlab.

**Comment by davidstrauss** [comment]
I am using this app with GitLab without any issues.

**Comment by zeapo** [comment]
I will re-try with a different type of key. The keys I generated both with and without passphrase gave "Auth failed".

**Comment by r8b7xy** [comment]
Weird. It works now as expected. I think that I've failed with my credentials somewhere - still I was retyping them for at least 10 min...

**Comment by zeapo** [comment]
Great, I probably failed miserably when testing it too..
