### ISSUE TITLE
question: regarding general operation

### ISSUE THREAD

**Issue by doomster** [zeapo/Android-Password-Store#1027]
i have a pass installation on my homeserver, and i want two android phones using it. i have installed the application to my phone and setup the repository. i cloned the repo from server and see my passwords. When i create a new password, i push changes to the repo (server) , but when i  "pass list" on the server, i don't see my new password.
am i missing something?

**Comment by msfjarvis** [comment]
Does the push show any kind of error? Are you cloning the `~/.password-store` directory onto your phone?

**Comment by doomster** [comment]
ok i must have done something wrong with the server repository, cause mobile app works correctly. i thought that the app was an "GUI" for the server application, but it does work as standalone. 
This being said, i removed the pass application on my server, and created a private repository on my programming GIT server (i use GoGs) . 
All work correctly now, if i use the ssh 22 port. 

Since it is a general question thread, you might aswell help me with this:

the repo path currently is set to "doomster/password-storage" , as Gogs is a github selfhosted clone. I want to be able to use custom ssh port to connect to my server , but then it requires a / to start the repo-path, and i cannot find a way to find a hardlink for it.   any ideas whhat it might be? (like if github started receiving ssh connections to port 2222, what would the correct path be?)

**Comment by msfjarvis** [comment]
> ok i must have done something wrong with the server repository, cause mobile app works correctly. i thought that the app was an "GUI" for the server application, but it does work as standalone. 
> This being said, i removed the pass application on my server, and created a private repository on my programming GIT server (i use GoGs) . 
> All work correctly now, if i use the ssh 22 port. 
> 
> Since it is a general question thread, you might aswell help me with this:
> 
> the repo path currently is set to "doomster/password-storage" , as Gogs is a github selfhosted clone. I want to be able to use custom ssh port to connect to my server , but then it requires a / to start the repo-path, and i cannot find a way to find a hardlink for it.   any ideas whhat it might be? (like if github started receiving ssh connections to port 2222, what would the correct path be?) 
> 

The current URL system is a bit iffy and as evident from your question, extremely confusing to users. If you're comfortable with it, you can download the latest snapshot from [here](https://dl.msfjarvis.dev/APS) (difference between free/nonFree is in the wiki FAQ) and then set your git server as a single URL field as opposed to the different parts. When we release this on the 22nd of this month you'll be able to update to the Play Store version.

**Comment by doomster** [comment]
Thank you for the quick reply. I will wait untill the 22th to update, and then revert back to custom port that i usually use on my server. 

Keep up the good work!

ps: im crossing my fingers and wishing for an import-extension implementation on the android application 👍

**Comment by msfjarvis** [comment]
> Thank you for the quick reply. I will wait untill the 22th to update, and then revert back to custom port that i usually use on my server. 
> 
> Keep up the good work!
> 

Thanks!

> ps: im crossing my fingers and wishing for an import-extension implementation on the android application 👍 

I've considered it in the past but it's a lot of work and encrypting a lot of files is going to be extremely slow given how OpenKeychain works. If there's ever an alternative to it that offers a better performing integration, we'll certainly add support for it and then work on batch operations like importing from other store formats. For now your best bet continues to be [pass-import](https://github.com/roddhjav/pass-import).
