### ISSUE TITLE
[QUESTION] Why put Git configuration into `config` file in repo?

### ISSUE THREAD

**Issue by leetking** [zeapo/Android-Password-Store#1038]
Dear developers, thank you for your awesome software.

The question shown as the title. I think there may be a way to put Git configuration such as "username" or "email" in a inner file of this software not the `config` file in password repository, or we have some reason must to do this.

**Comment by msfjarvis** [comment]
We don't elect to do it, it's simply how Git does it. Every non-global property is written into `.git/config`. What's the issue that you're facing with this?

**Comment by leetking** [comment]
My `config` file is not under `.git/` directory, but in the root of repository directly. It isn't functional problem, but I think it may be invasive into my repository directory. Shown as picture bellow:
![Screenshot_20200821-131440__01__01](https://user-images.githubusercontent.com/11045233/90854792-7aab0900-e3b0-11ea-9971-0ed3151c2040.jpg)

**Comment by msfjarvis** [comment]
> My `config` file is not under `.git/` directory, but in the root of repository directly. It isn't functional problem, but I think it may be invasive into my repository directory. Shown as picture bellow:
> ![Screenshot_20200821-131440__01__01](https://user-images.githubusercontent.com/11045233/90854792-7aab0900-e3b0-11ea-9971-0ed3151c2040.jpg)

That should be fixable. I'll take a look.

**Comment by leetking** [comment]
Thank you very much. 🌹
