### ISSUE TITLE
Clipboard is not cleared

### ISSUE THREAD

**Issue by oceans112** [zeapo/Android-Password-Store#104]
The clipboard is not cleared nor overwritten after the timeout expiring.
Actually if I long press on text area for example in text message compositor and then I press on clipboard I can see  the new "MyPasswordIsDaBest!" as the last entry AND my real password as an older entry.

(sorry for the poor english and infos, you can ask me further details)

**Comment by zeapo** [comment]
Are you using the version 1.2.0.24?

**Comment by wongma7** [comment]
Also, are you using a Samsung phone? Clipboard history is a feature that is not present in stock Android (or most other phones, I think). http://www.tech-recipes.com/rx/52309/how-do-i-recover-clipboard-history-on-my-samsung-phone/

**Comment by oceans112** [comment]
I am using version 1.2.0.23 (the latest one I found on playstore) and yes, I'm using a samsung phone (galaxy 4 mini GT-I9195).
There is anything I can do to deal with Samsung history feature?
Thanks for the replies.

**Comment by wongma7** [comment]
It looks like there is no easy way to disable the feature, you have to use an xposed module http://repo.xposed.info/module/tungstwenty.xposed.securesamsungclipboard or you will have to manually clear/delete entries.

What the app could do is write to the clipboard 20x instead of once. A bit silly but, if it is an acceptable solution, zeapo, I could try to write it.

**Comment by oceans112** [comment]
I tried this one https://github.com/zoff99/DisableSamsungClipboard and it seems to work. Not sure cause today i heard for the first time about xposed modules

**Comment by zeapo** [comment]
@oceans112 glad you found a solution
@wongma7 if you want to add, it has to be in a **misc** preferences, and disabled by default.

**Comment by wongma7** [comment]
Preference to copy to clipboard 20 times added in https://github.com/zeapo/Android-Password-Store/commit/d95286660ad5e626c75f4bc9f70e51277be67273
