### ISSUE TITLE
[BUG] `LockFailedException` when creating a new password

### ISSUE THREAD

**Issue by fmeum** [zeapo/Android-Password-Store#1042]
**Describe the bug**
I have somehow gotten my repositories (both the Play Store and a dev version) into a state where creating a new password leads to the following exception:

```
GitCommandExecutor$execute: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
GitCommandExecutor$execute: 	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:48)
GitCommandExecutor$execute: 	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:1)
GitCommandExecutor$execute: 	at com.zeapo.pwdstore.git.GitCommandExecutor$execute$3.invokeSuspend(GitCommandExecutor.kt:2)
GitCommandExecutor$execute: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
GitCommandExecutor$execute: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
GitCommandExecutor$execute: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
GitCommandExecutor$execute: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:13)
GitCommandExecutor$execute: Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /data/user/0/dev.msfjarvis.aps/files/store/.git/index
GitCommandExecutor$execute: 	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:19)
GitCommandExecutor$execute: 	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:6)
GitCommandExecutor$execute: 	... 6 more
```

This is not fixed by deleting and re-cloning the repository and likely caused by `.git/index.lock` sticking around after another Git operation.

Additionally, the error dialog box that accompanies the exception is only shown briefly and there is a warning about a leaked `DecorView`, which hints at some logic involving `finish` and errors being incorrect.

**To Reproduce**
1. Cause some unknown corruption during/after a Git operation.
2. Create a password, which triggers a git add.

**Expected behavior**
The password is added and committed.

As a bandaid fix, we could potentially delete `.git/index.lock` e.g. when the app starts. But we should see whether we can reproduce the underlying repo corruption.

**Screenshots**
N/A

**Device information (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android 11 Beta 3
 - App version: 1.11.1

**Comment by msfjarvis** [comment]
The problem isn't that `.git/index.lock` already exists, its that creation of it fails. I just tested a completely clean repository on a debug build, and peeked into the data. The file is not present before I create a password, and its not present after it fails. Something's botched heavily here.

```shell
# This is how I checked the private app data dir
adb shell
run-as dev.msfjarvis.aps.debug sh
cd files/store/.git
find
```

**Comment by msfjarvis** [comment]
@FabianHenneke is it possible we screwed something in 152d86ec3a951bd6cb797128094d933d2c3a5697? AFAIK we both use OpenKeychain authentication, and if this was an issue on the stable build we'd *definitely* have heard from users.

**Comment by fmeum** [comment]
> @FabianHenneke is it possible we screwed something in 152d86ec3a951bd6cb797128094d933d2c3a5697? AFAIK we both use OpenKeychain authentication, and if this was an issue on the stable build we'd *definitely* have heard from users.

I'm not using OpenKeychain auth with the stable build currently. I'll see whether I can do a bisect later.

**Comment by fmeum** [comment]
This is getting weirder by the minute: Both v1.10.0 and v1.11.0 don't seem to have the issue, but it does show up in v1.11.1.
