### ISSUE TITLE
HTTPS authentication does not prompt user for password

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1048]
**Describe the bug**

Using HTTPS to authenticate with a private GitHub repository fails due to the user not being presented a password dialog

**To Reproduce**
1. Create a private GitHub repository
2. Generate a personal access token to authenticate over HTTPS
3. Install APS, set protocol to HTTPS, authentication mode to Password
4. Enter URL to repository
5. Press clone, observe unauthorized exception

**Expected behavior**
User is prompted for HTTPS password and then clone completes successfully

**Screenshots**

![Exception message in dialog](https://i.imgur.com/kMigIA2.png)

**Device information (please complete the following information):**
 - Device: Google Pixel 2
 - OS: Android 11 Beta 2
 - App version: v1.11.1

**Additional context**

I've received multiple emails for this so this needs to be fixed for v1.11.2 as early as we can.

**Comment by fmeum** [comment]
Can reproduce and will take a look tomorrow morning.
