### ISSUE TITLE
Crashes since Version 1.2.0.24

### ISSUE THREAD

**Issue by Brottweiler** [zeapo/Android-Password-Store#105]
Just updated today via F-Droid to version Version 1.2.0.24, and now it crashes upon launch. "Has stopped working" is just the message.

**Comment by zeapo** [comment]
Yup, there was a mistake in the 24 a newer version has been created, should be available tomorrow.

**Comment by wongma7** [comment]
@zeapo I get a crash on launch even on the newest version when I run a release build. First it warns: W/SupportMenuInflater﹕ Cannot instantiate class: android.support.v7.widget.SearchView
    java.lang.NoSuchMethodException: <init> [class android.content.Context] then I get a NullPointerException. So since it is only in the release build I think it has something to do with https://github.com/zeapo/Android-Password-Store/commit/d2b48099fa2f99c79db8384ecd99eaa07cf4b4d9 . I don't know what these things mean so I'm reluctant to touch it, but here it says to add a line to proguard '-keep class android.support.v7.widget.SearchView { *; }' http://stackoverflow.com/questions/22582006/cannot-instantiate-class-android-support-v7-widget-searchview which worked for me.

**Comment by zeapo** [comment]
I see, proguard is here to optimise the apk. It seems like it did a little bit too much with the latest v7 support api.

If adding that line in proguard-rules.pro does not fix the issue, then comment the lines 26 to 32 in app/build.gradle. I will delete the tags right now.

**Comment by wongma7** [comment]
Okay, I have pushed the extra line. I will let you handle tagging & releasing?

**Comment by zeapo** [comment]
I will take of it, thx :)

**Comment by zeapo** [comment]
disabled proguard until I make cleaner rules.

The new release apk works as expected. @Brottweiler please revert to .23 and wait for the .26 tomorrow. Thanks.

**Comment by Brottweiler** [comment]
:+1:

**Comment by zeapo** [comment]
https://github.com/zeapo/Android-Password-Store/releases/tag/v1.2.0.26 contains an APK signed with the same key as the PlayStore.

**Comment by Brottweiler** [comment]
@zeapo I get (De-)installation error when downgrading via F-Droid. Is it *required* that I downgrade? I can just wait otherwise.

**Comment by zeapo** [comment]
you can wait, of course :)

**Comment by Brottweiler** [comment]
Thanks for the help!

**Comment by zeapo** [comment]
you're welcome.

**Comment by Brottweiler** [comment]
Just wanted to tell you F-Droid still hasn't gotten the update. Is it still pending? Worried since you said it would come the next day but it has gone 2-3 days now. :stuck_out_tongue:

**Comment by zeapo** [comment]
Almost there https://f-droid.org/wiki/page/com.zeapo.pwdstore#1.2.0.26
