### ISSUE TITLE
[FEATURE] Support new gopass MIME secret encoding

### ISSUE THREAD

**Issue by tomkel** [zeapo/Android-Password-Store#1055]
As opposed to YAML or key-value encoding.

https://github.com/gopasspw/gopass/blob/master/docs/features.md#mime-secrets

**Comment by msfjarvis** [comment]
gopass seemingly has [plans to completely break pass compatibility](https://github.com/gopasspw/gopass/issues/1365) so I'm not too excited about supporting all these weird things they're up to.

**Comment by rounakdatta** [comment]
@msfjarvis are we determined we wouldn't be supporting gopass?
Otherwise, I can start some work on the required compatibility changes

**Comment by msfjarvis** [comment]
> @msfjarvis are we determined we wouldn't be supporting gopass?
> Otherwise, I can start some work on the required compatibility changes

I'm not averse to offering support for gopass-specific things up to a limit I deem reasonable, but I will certainly not be working directly on them. Feel free to create a pull request.
