### ISSUE TITLE
[BUG] HTTP Status 401 on pull/push to remote origin

### ISSUE THREAD

**Issue by euh2** [zeapo/Android-Password-Store#1058]
**Describe the bug**
I consistenly get 401 (forbidden) status code when trying to pull or push to or from remote repository. On pull my git-server first shows 401 in the logs, then 200, and the repo is updated locally (on my phone). So pull seems to work despite the first triggering 401 on my remote. Maybe the first request does not include authentication?

I then edit someting locally (on my phone) and try to synchronize. On push (or sync) my remote issues 401 and this app asks again for the password (token).

I read previous issues and recent updates addressing this (or similar) issues, but maybe this is something different, I assume.

**To Reproduce**
1. Have a remote Git-server (Gitea ie.)
2. Add server URL in this app as https://USERNAME@DOMAIN/URI_ON_SERVER, ie. https://bill@mygit.fqdn.com/bill/secrets.git. When saving this info in the app and pull, you will be prompted for a password (I use app token from Gitea)
3. Pull seems to work somehow, but try to push or sync and you will again be asked for the password. Server shows only 401, no 200 as when pulling.
4. When reproduced, comment on this issue!

**Expected behavior**
Hmm, I really like the Just Works™ philosophy. But I have lots of appreciation for developers working their ways.

**Screenshots**
Probably not necessary. 

**Device information (please complete the following information):**
 - Device: OnePlus6
 - OS: Stock (Android 10, I believe)
 - App version 1.11.2 (latest available)

**Additional context**
Gitea is the remote, but I assume this is not relevant (ie. GitNex Android App works with same config)
By the way, when I enable debugging in this app, where are the logs stored? Couldn't find them.

**Comment by fmeum** [comment]
Thanks for the detailed report!

I think this broke in https://github.com/android-password-store/Android-Password-Store/pull/1012. I completely missed that the `InteractivePasswordFinder` in `SshjSessionFactory.kt` was also responsible for getting the HTTPS password. Unfortunately that may mean that we have to reintroduce the hacky reuse logic from before...

**Comment by fmeum** [comment]
Well, that was fun: I uncovered two bugs and a regression in how we handle HTTPS passwords. Will submit those as separate PRs.
 
While I cannot fully reproduce the issue @euh2 is experiencing, I'm pretty sure that their situation will drastically improved with these PRs.

**Comment by fmeum** [comment]
@euh2 We believe that we have resolved the issue you are experiencing. Could you verify that the issue is fixed for you with the snapshot builds available at https://dl.msfjarvis.dev/APS/?

**Comment by euh2** [comment]
Thanks! 

Unfortunately I can't test out this build due to local install policies. I have to wait for Play Store or F-Droid updates :/

**Comment by fmeum** [comment]
> Thanks!
> 
> Unfortunately I can't test out this build due to local install policies. I have to wait for Play Store or F-Droid updates :/

Don't worry, I have been able to test with gitea and found everything to be working well with our fixes. It would be great if you could confirm the fixes work after 1.11.3 has shipped to you.

**Comment by fmeum** [comment]
@euh2 I just checked that 1.11.3 is out for me, it may also be for you.

**Comment by euh2** [comment]
> @euh2 I just checked that 1.11.3 is out for me, it may also be for you.

Yes! Installed and tested. It seems to work fine now. 

Ganz herzlichen Dank!
