### ISSUE TITLE
keep private instead of public repo.

### ISSUE THREAD

**Issue by dlagg** [zeapo/Android-Password-Store#1071]
I don't feel safe sharing all my users accounts on a public repo, but seems it's needed to use this app. Is there any way to have a cloud backup but encrypt or keep private your file names?

**Comment by msfjarvis** [comment]
> I don't feel safe sharing all my users accounts on a public repo, but seems it's needed to use this app. Is there any way to have a cloud backup but encrypt or keep private your file names?

You most definitely do not require a public Git repository to use Password Store. Any and every Git repository that you can access and authenticate to is suitable for use with the app.

**Comment by dlagg** [comment]
> > I don't feel safe sharing all my users accounts on a public repo, but seems it's needed to use this app. Is there any way to have a cloud backup but encrypt or keep private your file names?
> 
> You most definitely do not require a public Git repository to use Password Store. Any and every Git repository that you can access and authenticate to is suitable for use with the app.

I get 'not authorized' error when I type my github password for my private pass-store repo.

**Comment by msfjarvis** [comment]
> > > I don't feel safe sharing all my users accounts on a public repo, but seems it's needed to use this app. Is there any way to have a cloud backup but encrypt or keep private your file names?
> > 
> > You most definitely do not require a public Git repository to use Password Store. Any and every Git repository that you can access and authenticate to is suitable for use with the app.
> 
> I get 'not authorized' error when I type my github password for my private pass-store repo.

Are you using SSH or HTTPS? If on HTTPS, do you have two factor authentication enabled? You can only use personal access tokens for HTTPS authentication with 2FA enabled.

**Comment by dlagg** [comment]
> > > > I don't feel safe sharing all my users accounts on a public repo, but seems it's needed to use this app. Is there any way to have a cloud backup but encrypt or keep private your file names?
> > > 
> > > 
> > > You most definitely do not require a public Git repository to use Password Store. Any and every Git repository that you can access and authenticate to is suitable for use with the app.
> > 
> > 
> > I get 'not authorized' error when I type my github password for my private pass-store repo.
> 
> Are you using SSH or HTTPS? If on HTTPS, do you have two factor authentication enabled? You can only use personal access tokens for HTTPS authentication with 2FA enabled.

Okey, I didn't know I had to have 2FA to use it.

**Comment by dlagg** [comment]
> > > > I don't feel safe sharing all my users accounts on a public repo, but seems it's needed to use this app. Is there any way to have a cloud backup but encrypt or keep private your file names?
> > > 
> > > 
> > > You most definitely do not require a public Git repository to use Password Store. Any and every Git repository that you can access and authenticate to is suitable for use with the app.
> > 
> > 
> > I get 'not authorized' error when I type my github password for my private pass-store repo.
> 
> Are you using SSH or HTTPS? If on HTTPS, do you have two factor authentication enabled? You can only use personal access tokens for HTTPS authentication with 2FA enabled.

2FA enabled, same error.

**Comment by msfjarvis** [comment]
> > > > > I don't feel safe sharing all my users accounts on a public repo, but seems it's needed to use this app. Is there any way to have a cloud backup but encrypt or keep private your file names?
> > > > 
> > > > 
> > > > You most definitely do not require a public Git repository to use Password Store. Any and every Git repository that you can access and authenticate to is suitable for use with the app.
> > > 
> > > 
> > > I get 'not authorized' error when I type my github password for my private pass-store repo.
> > 
> > 
> > Are you using SSH or HTTPS? If on HTTPS, do you have two factor authentication enabled? You can only use personal access tokens for HTTPS authentication with 2FA enabled.
> 
> Okey, I didn't know I had to have 2FA to use it.

You don't, but if you had 2FA then you can't directly use your password. Things should be working fine otherwise, but since you did not follow the issue template and add the required information I can't really deduce the reason for the issue you're facing.

**Comment by msfjarvis** [comment]
It'll be easier to continue this discussion over in our Gitter room: https://gitter.im/android-password-store/public. Make sure you're not using F-Droid's releases because they're very outdated, either download from the Play Store or from [GitHub releases](https://github.com/android-password-store/Android-Password-Store/releases/latest).

**Comment by dlagg** [comment]
> > > > > > I don't feel safe sharing all my users accounts on a public repo, but seems it's needed to use this app. Is there any way to have a cloud backup but encrypt or keep private your file names?
> > > > > 
> > > > > 
> > > > > You most definitely do not require a public Git repository to use Password Store. Any and every Git repository that you can access and authenticate to is suitable for use with the app.
> > > > 
> > > > 
> > > > I get 'not authorized' error when I type my github password for my private pass-store repo.
> > > 
> > > 
> > > Are you using SSH or HTTPS? If on HTTPS, do you have two factor authentication enabled? You can only use personal access tokens for HTTPS authentication with 2FA enabled.
> > 
> > 
> > Okey, I didn't know I had to have 2FA to use it.
> 
> You don't, but if you had 2FA then you can't directly use your password. Things should be working fine otherwise, but since you did not follow the issue template and add the required information I can't really deduce the reason for the issue you're facing.

I try with personal access token unsuccessfully. Maybe I haven't given sufficient permissions?

**Comment by msfjarvis** [comment]
> I try with personal access token unsuccessfully. Maybe I haven't given sufficient permissions?

It's possible. Did you set the `repo` scope for the token?

**Comment by dlagg** [comment]
> > I try with personal access token unsuccessfully. Maybe I haven't given sufficient permissions?
> 
> It's possible. Did you set the `repo` scope for the token?

repo scope only

**Comment by msfjarvis** [comment]
> > > I try with personal access token unsuccessfully. Maybe I haven't given sufficient permissions?
> > 
> > 
> > It's possible. Did you set the `repo` scope for the token?
> 
> repo scope only

Hm that's very weird then. Are you on version 1.11.3 of the app? I can successfully authenticate with HTTPS repositories both public and private on a fresh installation from Play Store.

**Comment by fmeum** [comment]
@dlagg Are you specifying the repository URL in the form `https://username@github.com/foo/bar`? Note the `username@` to specify the username that goes with your token.

**Comment by dlagg** [comment]
> @dlagg Are you specifying the repository URL in the form `https://username@github.com/foo/bar`? Note the `username@` to specify the username that goes with your token.

Using that form I get: `invalid remote: origin`
Using `https://www.github.com/username/repo` at least ask me for password.

**Comment by fmeum** [comment]
The following steps allow me to clone a private repo on v1.11.3 without any issues:

1. Create a new GitHub account with username `john` and a new repository called `foo`.
1a. Push some content to `foo`.
2. Create a new Personal Access token with `repo` scope (which includes all `repo` subscopes), say the token is `abcdef123456`.
3. On Password Store's `Repository information` screen that is shown after selecting `Clone from server`, choose `HTTPS` as the protocol and `Password` as the authentication mode. 
4. Use `https://john@github.com/john/foo` as the repository URL and specify the branch if different from `master`.
5. Tap Save and wait for the password prompt.
6. Enter `abcdef123456` as the password, optionally check `Remember password` and confirm.

Please try the step above and report back where this goes wrong.

Edit: I just noted that I missed step 1a. Are you trying to clone an empty repository? That might not work @msfjarvis

**Comment by msfjarvis** [comment]
> Are you trying to clone an empty repository? That might not work @msfjarvis

Hm that's true. I'll see if we can do something about it.

**Comment by dlagg** [comment]
> The following steps allow me to clone a private repo on v1.11.3 without any issues:
> 
> 1. Create a new GitHub account with username `john` and a new repository called `foo`.
>    1a. Push some content to `foo`.
> 2. Create a new Personal Access token with `repo` scope (which includes all `repo` subscopes), say the token is `abcdef123456`.
> 3. On Password Store's `Repository information` screen that is shown after selecting `Clone from server`, choose `HTTPS` as the protocol and `Password` as the authentication mode.
> 4. Use `https://john@github.com/john/foo` as the repository URL and specify the branch if different from `master`.
> 5. Tap Save and wait for the password prompt.
> 6. Enter `abcdef123456` as the password, optionally check `Remember password` and confirm.
> 
> Please try the step above and report back where this goes wrong.
> 
> Edit: I just noted that I missed step 1a. Are you trying to clone an empty repository? That might not work @msfjarvis

works! , I was missing the **/username**/repo in the URL and using password instead of token. Thanks!
