### ISSUE TITLE
[BUG] ssh port is ignored

### ISSUE THREAD

**Issue by ael-code** [zeapo/Android-Password-Store#1085]
**Describe the bug**
SSH port specified through the `Repository URL` configuration field is ignored.
 
**To Reproduce**
1. Click on 'Clone from server'
2. Click on 'hidden (preferred)'
3. Select `SSH` protocol and `openkeychain` authentication mode.
4. Specify a custom port in the repository URL in the form `[username@]host[:port]/path`. For instance `ael@myhost.com:123/home/ael/.password-store`.

**Expected behavior**
The app should use `123` as the ssh port, but instead is using the default `22` port

**Device information (please complete the following information):**
 - Device: Xiaomi mi 9 lite
 - OS: MIUI 12.0.3 - android 10
 - App version: 1.11.3

**Comment by fmeum** [comment]
You can't specify custom ports with this URL format as they can't be distinguished from a directory: `ael@myhost.com:123/home/ael/.password-store` does afaik indicate that you would like to access the path `123/home/ael/.password-store` relative to the user `ael`'s home directory.
Please try again with `ssh://ael@myhost.com:123/home/ael/.password-store`.

**Comment by ael-code** [comment]
Thanks, it worked.

I think it would be helpful to add an in-app documentation of the Repository URL field that can help the user understand which format of URL are accepted.
