### ISSUE TITLE
Introduce contribution guidelines and source documentation

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1087]
We currently do not have any explicit contribution guidelines regarding common situations like discussing with us over an issue before working on a large feature and other general commandments typically found in open source projects, and it would certainly be nice to have some.

While at it, I'd also like to create a separate document (or set of documents) where we go through and record reasonings and explanations for certain patterns or one-off "hacks" as both an easier way for contributors to get familiar with the code as well as for existing maintainers to be able to document the "implicit knowledge" that needs to be preserved for the next crop of developers who take over this project as and when the current leadership steps away.

**Comment by xdevs23** [comment]
I would love to see best practices as well as dos and donts when working with the libraries used in this project and the project in general itself that rhe IDEs or the compiler don't already tell you. (e. g. don't do X in the build script; Y is required for Z to work; foo always needs to be specified when using bar).

This might already be covered by _implicit knowledge_ but I just wanted to mention it explicitly.

**Comment by msfjarvis** [comment]
> I would love to see best practices as well as dos and donts when working with the libraries used in this project and the project in general itself that rhe IDEs or the compiler don't already tell you. (e. g. don't do X in the build script; Y is required for Z to work; foo always needs to be specified when using bar).
> 
> This might already be covered by _implicit knowledge_ but I just wanted to mention it explicitly.

That's perfectly fine, direct examples are helpful. Thanks!

**Comment by aodhan-domhnaill** [comment]
Along these lines, I am having a hard time setting up the tooling for development so I can contribute. I have been battling through a variety of errors. Perhaps if we just work through them here, it could later be cleaned up into a SETUP.md or something

My current setup in VS Code on Fedora 32.

Get the code and check SDK version,
```
git clone -b release git@github.com:android-password-store/Android-Password-Store.git
grep compileSdkVersion buildSrc/src/main/java/BaseProjectConfig.kt
#    compileSdkVersion(29)
```

Find most recent commandline tools link https://developer.android.com/studio#downloads and download.

```
unzip commandlinetools-linux-6858069_latest.zip
cd cmdline-tools/

# Accept all licenses and install SDK. Use version from above
yes | ./bin/sdkmanager --sdk_root=. `./bin/sdkmanager --sdk_root=. --list | grep android-29 | cut -f1 -d\|`
```

~/.bashrc
```
export ANDROID_SDK_ROOT=~/.local/cmdline-tools/
export GRADLE_OPTS=-XX:MaxPermSize=1024m
```

At this point, I start getting a variety of build errors when I run `gradle build --stacktrace`. Sometimes I get different errors.

```
FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon has been stopped: JVM garbage collector thrashing and after running out of JVM memory

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.launcher.daemon.server.api.DaemonStoppedException: Gradle build daemon has been stopped: JVM garbage collector thrashing and after running out of JVM memory
```

**Comment by msfjarvis** [comment]
If you're running out of memory then you're going to need to provide some more. Create `~/.gradle/gradle.properties` and add this to it:

```properties
org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
```

Ideally you want a computer with at least 8 gigabytes of system memory for Gradle, and 16 or more if you are planning to use Android Studio as an IDE.

**Comment by aodhan-domhnaill** [comment]
Thanks. I've gotten to this next error with less memory before, but more memory seems faster

```
Fix the issues identified by lint, or add the following to your build script to proceed with errors:
...
android {
    lintOptions {
        abortOnError false
    }
}
...
The first 3 errors (out of 6) were:

/home/aidan/foss/Android-Password-Store/app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillResponseBuilder.kt:33: Error: Call requires API level 26 (current min is 23): formOrigin [NewApi]
    private val formOrigin = form.formOrigin
                                  ~~~~~~~~~~
/home/aidan/foss/Android-Password-Store/app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillResponseBuilder.kt:34: Error: Call requires API level 26 (current min is 23): scenario [NewApi]
    private val scenario = form.scenario
                                ~~~~~~~~
/home/aidan/foss/Android-Password-Store/app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillResponseBuilder.kt:35: Error: Call requires API level 26 (current min is 23): ignoredIds [NewApi]
    private val ignoredIds = form.ignoredIds
                                  ~~~~~~~~~~
```

**Comment by aodhan-domhnaill** [comment]
Got it to build. Minor changes that probably don't need to be checked in. Linting seems to be a problem with Android SDK version

```
diff --git a/app/build.gradle.kts b/app/build.gradle.kts
index d400c737..78c4645f 100644
--- a/app/build.gradle.kts
+++ b/app/build.gradle.kts
@@ -41,7 +41,7 @@ android {
     }
 
     lintOptions {
-        isAbortOnError = true
+        isAbortOnError = false
         isCheckReleaseBuilds = false
         disable("MissingTranslation", "PluralsCandidate", "ImpliedQuantity")
     }
diff --git a/gradle.properties b/gradle.properties
index ced8321c..de303e30 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -51,3 +51,4 @@ android.defaults.buildfeatures.shaders=false
 
 # Disable warnings about unsupported features, we know what we're doing
 android.suppressUnsupportedOptionWarnings=android.enableR8.fullMode,android.enableResourceOptimizations,android.nonTransitiveRClass,android.suppressUnsupportedOptionWarnings
+org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
```

**Comment by msfjarvis** [comment]
Lint seems to be wrong here, [this](https://github.com/android-password-store/Android-Password-Store/blob/354687e3a60f348af75c1a2f901270264d7e0313/app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillResponseBuilder.kt#L30) should have told it that we're only going to use this code on API 26 and above. I'll take a look.

**Comment by msfjarvis** [comment]
What Gradle command did you use to trigger this? I can't reproduce it with either `gradle check` or `gradle assemble` on the develop branch.

**Comment by aodhan-domhnaill** [comment]
`gradle build`

**Comment by msfjarvis** [comment]
> `gradle build`

I can't reproduce with that either, both on `develop` or `release`. Pretty odd :/

**Comment by aodhan-domhnaill** [comment]
Maybe my gradle version or SDK versions?

```
$ gradle -version
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0

------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.8 (Red Hat, Inc. 11.0.8+10)
OS:           Linux 5.8.16-200.fc32.x86_64 amd64
```

**Comment by msfjarvis** [comment]
Your Gradle version is what the app uses in CI, so that's not it either. I have a couple questions for the Android Jetpack team either way, will bundle this in as well.
