### ISSUE TITLE
[QUESTION] Key ID is too short

### ISSUE THREAD

**Issue by btimofeev** [zeapo/Android-Password-Store#1089]
Previously, the application worked fine, but today I found out that when I try to create a new password, I get the following message: 
"Key ID in .gpg-id is too short, please use  either long key IDs (16 characters) or fingerprints (40 characters)". 

I use "hidden repository", and since I do not have root access, I cannot change anything in this file.

 - Device: Xiaomi Mi A3
 - OS: Android 10
 - App version: 1.11.3

**Comment by msfjarvis** [comment]
Is the repository not synced with Git? You will have to make this change from a computer if you can't do so on your phone.

**Comment by btimofeev** [comment]
Thanks for the advice. Changed the GPG ID on the computer and that solved my problem.

**Comment by ahstro** [comment]
Sorry, but how do I make the change to fix this? Not seeing any info on gpg ids in the man page for `pass` other than when initalizing.

Edit: Ok, I was just not reading carefully enough. `pass init` could be used to reencrypt with a new gpg id.

**Comment by orsinium** [comment]
A little guide for future generations.

Get the long version of the key:

```bash
cd ~/.password-store
gpg --list-keys | grep $(cat .gpg-id) | xargs
```

Now, just write it into `.gpg-id` instead of the short key and commit:

```bash
echo 'YOUR_KEY\n' > .gpg-id
git add .gpg-id
git commit -m "use log key id"
git push
```
