### ISSUE TITLE
Version 1.2.0.24 crashes while opening

### ISSUE THREAD

**Issue by inirudebwoy** [zeapo/Android-Password-Store#110]
Hi,

Very useful soft.
Unfortunately version 1.2.0.24 will not open. 
Does not happen on 1.2.0.23.
What details or logs do you need?

**Comment by Brottweiler** [comment]
https://github.com/zeapo/Android-Password-Store/issues/105
https://github.com/zeapo/Android-Password-Store/issues/109

Update from F-Droid, it's fixed.

**Comment by inirudebwoy** [comment]
Sweet. For some strange reason F-Droid was not showing there is an update.
Issue to close.

**Comment by zeapo** [comment]
Yup F-Droid acted strange lately as it took  3 days to update the version.
