### ISSUE TITLE
Autofill Support for Iceweasel

### ISSUE THREAD

**Issue by dfrost16** [zeapo/Android-Password-Store#1104]
Autofill Support for [Iceweasel](https://github.com/fork-maintainers/iceraven-browser) 
**Bug**
![10505](https://user-images.githubusercontent.com/24663673/93511465-7f77c400-f940-11ea-906f-39c388926b5b.png)
Shows browser name Instead of site name
**Intended Behaviour**
![10507](https://user-images.githubusercontent.com/24663673/93511683-cfef2180-f940-11ea-9bb5-3158740c3575.png)

**Comment by msfjarvis** [comment]
Seems like the name is being changed to Iceraven? Has the package name been updated to reflect that?

**Comment by dfrost16** [comment]
> Seems like the name is being changed to Iceraven? Has the package name been updated to reflect that?
Am really sorry, idk much about that

**Comment by fmeum** [comment]
A quote from the linked repository:
```
No warranties or guarantee of security or updates. Binaries are currently are manually built and are not meaningfully signed.
```
Our policy is to only allow browsers that are 1) engineered to be secure (especially against origin bypasses) and 2) meaningfully signed so that other apps cannot pretend to be them.

As per that policy, I can't see us adding Iceraven support at this point.

**Comment by plant7403** [comment]
Hey, did anything change on this?
It seems they automated builds, rebranded, and other stuff
