### ISSUE TITLE
Ssh port not respected

### ISSUE THREAD

**Issue by tdltdl** [zeapo/Android-Password-Store#1105]
Probable regression of "one url to rule them all". When I try to clone repo on a server where ssh is not running on port 22, I specify it with ':12345' after the host name. There is then an error stating that ip address corresponding to host name port 22 is not responding. So the prot is ignored

Also on another phone that already had the url specified frol a previous version sync was going fine until I entered the settings and lost ssh settings :-( as it is on a server running on a non 22 port I cannot synch and will have to reclone. 

Thanks for your great work!!!

**Comment by fmeum** [comment]
You need to use the `ssh:` scheme to specify a non-standard port:
```
ssh://[user@]host.xz[:port]/path/to/repo.git
```
@msfjarvis Maybe we should show a warning if the path portion of the url starts with digits?

**Comment by msfjarvis** [comment]
> You need to use the `ssh:` scheme to specify a non-standard port:
> ```
> ssh://[user@]host.xz[:port]/path/to/repo.git
> ```
> @msfjarvis Maybe we should show a warning if the path portion of the url starts with digits?

We should really just make `ssh://` mandatory for all SSH URLs.

**Comment by fmeum** [comment]
> > You need to use the `ssh:` scheme to specify a non-standard port:
> > ```
> > ssh://[user@]host.xz[:port]/path/to/repo.git
> > ```
> > @msfjarvis Maybe we should show a warning if the path portion of the url starts with digits?
> 
> We should really just make `ssh://` mandatory for all SSH URLs. 

Downside is that people don't know them well as they are not what you copy from GitHub & Co. Plus only a minority uses non-standard ports, so I'm not sure that would make things better.

**Comment by tdltdl** [comment]
Or maybe default it to ssh:// when button on top says ssh or https:// when user selects https?

**Comment by tdltdl** [comment]
It is indeed working. Thanks.
For the upgrade drol previous version that lost my settings, hoz to proceed? Delete an reclone?

**Comment by msfjarvis** [comment]
> > > You need to use the `ssh:` scheme to specify a non-standard port:
> > > ```
> > > ssh://[user@]host.xz[:port]/path/to/repo.git
> > > ```
> > > @msfjarvis Maybe we should show a warning if the path portion of the url starts with digits?
> > 
> > We should really just make `ssh://` mandatory for all SSH URLs. 
> 
> Downside is that people don't know them well as they are not what you copy from GitHub & Co. Plus only a minority uses non-standard ports, so I'm not sure that would make things better.

:(

Add them in automatically if missing?

**Comment by tdltdl** [comment]
+1 for adding if missing :-)

**Comment by fmeum** [comment]
> > > > You need to use the `ssh:` scheme to specify a non-standard port:
> > > > ```
> > > > ssh://[user@]host.xz[:port]/path/to/repo.git
> > > > ```
> > > > @msfjarvis Maybe we should show a warning if the path portion of the url starts with digits?
> > > 
> > > We should really just make `ssh://` mandatory for all SSH URLs. 
> > 
> > Downside is that people don't know them well as they are not what you copy from GitHub & Co. Plus only a minority uses non-standard ports, so I'm not sure that would make things better.
> 
> :(
> 
> Add them in automatically if missing?
> 
> 
> 
> 

If we assume that nobody would want to have the first part of their path consist of digits, that would work. But I think that a snackbar warning in that case could be sufficient. Not sure though.

**Comment by tdltdl** [comment]
Not sure I understand, the url must start with a scheme in the followed by "://". I do not see the issue with digits. Sorry

**Comment by msfjarvis** [comment]
> Not sure I understand, the url must start with a scheme in the followed by "://". I do not see the issue with digits. Sorry 

git@github.com is a valid SSH URL and so is 192.168.0.101

192.168.0.101:12345 isn't a valid SSH URL, but ssh://192.168.0.101:12345 is.

The first category is both more common as well as the one most tools and platforms will output by default.

**Comment by fmeum** [comment]
A url such as `git@example.org:12345/example.git` is somewhat ambiguous since there might be paths starting with a digit, right?

**Comment by msfjarvis** [comment]
> A url such as `git@example.org:12345/example.git` is somewhat ambiguous since there might be paths starting with a digit, right?

Yeah... What's the final verdict then?

**Comment by tdltdl** [comment]
But if we always prefix it with ssh:// (or https://) would it cause any problem? The absolute url syntax is not ambiguous so why not enforce it?

**Comment by fmeum** [comment]
> But if we always prefix it with ssh:// (or https://) would it cause any problem? The absolute url syntax is not ambiguous so why not enforce it?

It's not ambiguous, but also not compatible: The path in `git@example.org:foo/bar` is interpreted as a relative path, whereas the path in `ssh://git@example.org:123/foo/bar` is necessarily absolute. GitHub, Gitlab and the likes don't treat absolute and relative paths as different afaik, but self-hosted alternatives might.

I see the following options and do prefer option 2 right now:

1. Rewrite `git@example.org:1234/foo/bar` to `ssh://git@example.org:1234/foo/bar`, assuming that nobody uses relative paths starting with a digit-only component. If they do, they can still fix this by providing the absolute path via the `ssh://` scheme.
2. Show a warning (or, perhaps, an actual dialog with the option to do the conversion of option 1) when a "port" is supplied without using the `ssh://` scheme.
3. Demand `ssh://` URLs in the first place. This puts more of a burden on users as most (me included) have likely never seen this scheme in practice before.

**Comment by msfjarvis** [comment]
Without the `ssh://` prefix JGit's URIish will see that `msfjarvis@192.168.0.102:39758/mnt/ro/pass-store` has no port and leave the value at `-1` so guess it's time to meet my old friend RegExp...

**Comment by doak** [comment]
> It's not ambiguous, but also not compatible: The path in `git@example.org:foo/bar` is interpreted as a relative path, whereas the path in `ssh://git@example.org:123/foo/bar` is necessarily absolute. GitHub, Gitlab and the likes don't treat absolute and relative paths as different afaik, but self-hosted alternatives might.

There seems to be another syntax to specify a relative path with a non-default SSH port. It is supported at least by Git, (though not documented):
`[git@example.org:123]:foo/bar`

Example:
`git ls-remote [git@github.com:22]:android-password-store/Android-Password-Store`
