### ISSUE TITLE
Replace Snackbars that contain relatively long texts with BasicBottomSheet

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1114]
Snackbars are unwieldy for any message going past 3 to 6 words and often ellipsize out important parts of the message that then creates usability issues for users who can't read the entirety of that text. This became extremely clear in the support email I received over the weekend, where the URL misconfigured their repository URL to `https://username@github.com/repo-name` rather than `https://username@github.com/username/repo-name`, because the example URL was cut off and they had to rely on guessing.

<details>
<summary>Screenshot</summary>

![Image of git server config activity with Snackbar suggesting username be added to the URL but truncated mid way in the example URL](https://user-images.githubusercontent.com/13348378/93743383-9a328d00-fc0d-11ea-8488-88b1cd8a638e.png)

</details>

5d5a068591e16a97f6cbbf6b75ecc2e5aed5bbf3 adds the necessary infrastructure for this issue to be tackled, and I'll refactor this shortly to make it a bit more extensible for general use-cases.

I'm open to any other UI patterns that would resolve our current problem, but the bottom sheet seemed like the least intrusive one.

**Comment by Skrilltrax** [comment]
I think we should also change the dialog boxes into bottom sheets just to make the whole UI consistent.

**Comment by ashoksinghal** [comment]
I would like to work on this if it's available

**Comment by msfjarvis** [comment]
> I would like to work on this if it's available

Certainly available, have at it!

**Comment by ashoksinghal** [comment]
thanks, @msfjarvis. working on it

**Comment by ashoksinghal** [comment]
@msfjarvis, Just to confirm, we have to replace the SnackBars with BasicBottomSheet in all parts of the app, right? And basicBottomBar will have the functionality to autoHide in such cases as snackBars do

**Comment by msfjarvis** [comment]
> @msfjarvis, Just to confirm, we have to replace the SnackBars with BasicBottomSheet in all parts of the app, right? And basicBottomBar will have the functionality to autoHide in such cases as snackBars do

We want to make the change at least in places where we require user interaction, such as git command errors and validation errors in server configuration activity. Doesn't have to be every single Snackbar, because like you said we want to be able to automatically hide in some places and the Snackbar just works better for it, for example, the "Running git operation..." one in `GitCommandExecutor`.

**Comment by ashoksinghal** [comment]
> > @msfjarvis, Just to confirm, we have to replace the SnackBars with BasicBottomSheet in all parts of the app, right? And basicBottomBar will have the functionality to autoHide in such cases as snackBars do
> 
> We want to make the change at least in places where we require user interaction, such as git command errors and validation errors in server configuration activity. Doesn't have to be every single Snackbar, because like you said we want to be able to automatically hide in some places and the Snackbar just works better for it, for example, the "Running git operation..." one in `GitCommandExecutor`.

Thanks for the clarification, will do as you suggested.

**Comment by msfjarvis** [comment]
Fixed by #1157
