### ISSUE TITLE
Tracking issue for removal of Git support w/ external repositories

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1118]
This is a discussion thread for users to comment on our proposal to remove support for Git features in external repositories. For the v1.12.0 release, we're doing a soft launch of our plans by taking away the ability to clone a repository to external storage. This is done as a means to gather feedback about the change and evaluate if this can be done without breaking too many users.

Our reasons for making this change are multifold:

- Android is increasingly restrictive with what apps will be able to get full filesystem access, and while we welcome these crucial privacy improvements, it is very hard for us to be compatible with these changes as the library we use for Git is a Java-focused product and doesn't allude to most Android-specific nuances.

- As far as we know, the only reason for putting your repository in a public directory on your device is using a third-party sync system like Syncthing, Nextcloud, a WebDAV server or something along those lines. This, in our opinion, makes Git pointless because it's sync guarantees are violated by arbitrary external entities.

- Dropping support for this allows us to rewrite the entire core of our repository handling system, making it more robust, maintainable and clean.

What this change would mean for users:

- If your repository does not use Git, nothing changes for you.

- If you used the "hidden" option for the repository location, nothing changes for you.

- If you used the "SD Card" option for the repository location, you will be able to use it as if it is not a Git repo. The `.git` directory will be ignored by the app and it will not attempt to make commits for any changes to the store. No sync operations will be available from the app, and no Git settings options will be visible.

**Comment by msfjarvis** [comment]
The silence here suggests that either nobody reads my release notes or this change is going to affect no-one, so I'm going to prepare a patch for this tonight.

**Comment by msfjarvis** [comment]
On second thoughts, going to push this to a longer [v2.0.0 timeline](https://twitter.com/MSF_Jarvis/status/1314943278173745152).

**Comment by plant7403** [comment]
I'm up for git, git is essential, but it's hard to make it work 😑

**Comment by msfjarvis** [comment]
> I'm up for git, git is essential, but it's hard to make it work 😑

Do you have any reason in particular to use Git but not let the app place the repository in its private directory?

**Comment by Holzhaus** [comment]
This just applies to people who use *external* git repos on the SD card, right? Git support for repos cloned from within the app remains unaffected? Because the ability to sync my passwords using git is one of the key features for me.

**Comment by Skrilltrax** [comment]
Yes, this applies only to the external repos.

**Comment by sevmonster** [comment]
> Yes, this applies only to the external repos.

I completely missed that part. Well, it's nice to be able to access things via Termux and other solutions, but then you can always just push inside Termux and pull inside the app... I'm thinking this is an easily-adjusted-to change.

**Comment by benrhughes** [comment]
This would break how I currently use `pass`, and unfortunately the legacy version of the app don't appear to work on Android 10. 

My use-case may be somewhat out of the ordinary: I store some non-encrypted files in my pass repo and edit them in other apps. For whatever reason, your implementation of git syncing on Android is by far the most convenient to use, so I've been piggy-backing on it rather than using something like mgit. 

Of course I understand if you need to pull this functionality for ongoing maintainability, and I'll just figure out another way to move my files around.

**Comment by msfjarvis** [comment]
> This would break how I currently use `pass`, and unfortunately the legacy version of the app don't appear to work on Android 10.
> 
> My use-case may be somewhat out of the ordinary: I store some non-encrypted files in my pass repo and edit them in other apps. For whatever reason, your implementation of git syncing on Android is by far the most convenient to use, so I've been piggy-backing on it rather than using something like mgit.
> 
> Of course I understand if you need to pull this functionality for ongoing maintainability, and I'll just figure out another way to move my files around.

Thanks for your understanding, it is unfortunate but we really cannot support this specific use-case.

**Comment by Filip62** [comment]
As long as the git functionality stays in the internal app storage, I'm totally fine with it.

**Comment by sevmonster** [comment]
> My use-case may be somewhat out of the ordinary: I store some non-encrypted files in my pass repo and edit them in other apps. For whatever reason, your implementation of git syncing on Android is by far the most convenient to use, so I've been piggy-backing on it rather than using something like mgit.

Off topic: You should really consider using https://github.com/Catfriend1/syncthing-android for your needs. If version control/file history is a concern, you can store old versions of synced files with Syncthing up to a user-defined limit; keep the whole history on your main device if storage there is sufficient, and keep a few past versions on the phone—that's what I do. It isn't as storage-efficient as Git is with text files since Git uses deltas, but it's about the same for binary files.

**Comment by indeedwatson** [comment]
I'm sorry if this is not the right place for this, but after having issues with open gpg I procrastinated setting up password-store. Today I opened the app and tried to set it up with git. I am reading this and it doesn't really clear anything up.

I have a git repo where I backup my pass directory. I have the app open. What do I do? Where do I go? Where am I supposed to read what to do? The wiki is outdated and the new documentation contains no information about this.

Am I meant to have a separate app on my phone for managing git repos and select that directory with password-store?

**Comment by msfjarvis** [comment]
> I'm sorry if this is not the right place for this, but after having issues with open gpg I procrastinated setting up password-store. Today I opened the app and tried to set it up with git. I am reading this and it doesn't really clear anything up.

Because it's not really related :)

> I have a git repo where I backup my pass directory. I have the app open. What do I do? Where do I go? Where am I supposed to read what to do? The wiki is outdated and the new documentation contains no information about this.

Sorry about that, documentation's been a sore point for a while. When you first launch the app, select the "Clone Git repo" option which will lead you to the clone configuration screen. Enter your repository URL, pick how you want to authenticate and hit the clone button.

> Am I meant to have a separate app on my phone for managing git repos and select that directory with password-store?

You certainly are not, but can elect to do it if you so desire. We don't personally recommend doing it unless you have a good reason to.

If you have any follow up questions, I'd encourage you to start a thread in the [Discussions](https://github.com/android-password-store/Android-Password-Store/discussions) section rather than reply here since this issue is unrelated.

**Comment by fourstepper** [comment]
I think this is fine, as long as both git and external directory workflows work

**Comment by colonelpanic8** [comment]
I'm not sure what is meant by: "This is a discussion thread for users to comment on our proposal to remove support for Git features in external repositories"

Surely you're not talking about removing git support entirely right? This would be a huge step backwards and a terrible idea. If thats not what is meant I think you should clarify what "Git features in external repositories" means.

**Comment by Holzhaus** [comment]
> I'm not sure what is meant by: "This is a discussion thread for users to comment on our proposal to remove support for Git features in external repositories"
> 
> Surely you're not talking about removing git support entirely right? This would be a huge step backwards and a terrible idea. If thats not what is meant I think you should clarify what "Git features in external repositories" means.
> 

I wondered about the same thing, but this question is already answered in the thread above. It *only* refers to git repos cloned by another app. The built-in git support will stay unaffected.

**Comment by msfjarvis** [comment]
> I'm not sure what is meant by: "This is a discussion thread for users to comment on our proposal to remove support for Git features in external repositories"
> 
> Surely you're not talking about removing git support entirely right? This would be a huge step backwards and a terrible idea. If thats not what is meant I think you should clarify what "Git features in external repositories" means.

As Holzhaus mentioned, this has been clarified already but I've reworded the OP in terms of app settings anyways.

**Comment by oblitum** [comment]
Hi, just landed here out of this discussion https://github.com/android-password-store/Android-Password-Store/discussions/1406.

Just wanna say I'm looking forward for bare password store directory support without involvement of Git, personally I don't use Git for this, but seems the app requires it at the moment.

**Comment by msfjarvis** [comment]
This issue is no longer relevant as we've had to make the decision to completely drop support for external storage to allow ourselves to actually be able to release the nearly two years of development work that's sitting in our develop branch. Context here: https://github.com/android-password-store/Android-Password-Store/issues/1849

**Comment by oblitum** [comment]
Sad day...

**Comment by daraul** [comment]
It is disappointing, but I've had luck using termux instead.
