### ISSUE TITLE
Password Store is not prompting for my Yubikey NEO pin and requires my passphrase

### ISSUE THREAD

**Issue by karlgrz** [zeapo/Android-Password-Store#112]
Hello,

I'm not sure what I did incorrectly here. 

I have set up my keychain to have a detached primary master key stored safely offline (4096 bit), 1 2048 bit encryption key and 1 2048 bit signing key, both exported to my Yubikey NEO. I can confirm that the NEO works properly on my laptop (ubuntu 15.04) and that it only requires my pin to encrypt / decrypt data, and also that I do not require my entire passphrase. Also, I cannot encrypt or decrypt at all without the NEO plugged in. So far so good.

I paired my Yubikey with my android phone (OnePlus One running Cyanogen 12)  and it imported it successfully, allegedly. 

I selected that key from Password Store, deleted my old one, and did a pull from remote. 

When I try to open a password, I am prompted for my passphrase, and when I enter it, my password is decrypted. I thought the NEO enabled just using the user pin? I think I missed something, is there something else I need to do?

**Comment by phryneas** [comment]
If you have to use your passphrase, most likely you imported a full key and not just a stub. You will have to delete your key from Openkeychain and re-import a key stub.

**Comment by karlgrz** [comment]
Gotcha. Are you referring to something like this? When I imported the key I just used NFC and my phone and Openkeychain detected it.

```
gpg -a --output gpg-secret-key.asc --export-secret-keys <insert key id or name>
```

**Comment by karlgrz** [comment]
I did that procedure, and it's still prompting for my full passphrase. 

Another weird thing I'm seeing is some of my entries in pass on my laptop are decrypting using the yubikey neo, and some are requiring the full passphrase. Oi. I think I have more problems here. F***.

**Comment by karlgrz** [comment]
Ok, so for the entries that I have saved WITH the yubikey neo, they are prompting for the pin. Weird, I expected the new encryption key would be just picked up. So I need to just update my entries myself? That's a bit annoying. Oh well, closing this, sorry for the bother and thanks for the nudge in the right direction!

**Comment by karlgrz** [comment]
So, this worked for me quite well:

```
pass init <my_new_encryption_subkey_id_here>
```

This went through the whole pass hierarchy and re-encrypted everything using my new subkey that is stored on the Yubikey. Now on my phone it prompts for yubikey pin successfully!
