### ISSUE TITLE
[BUG] Cannot synchronise with git repo

### ISSUE THREAD

**Issue by DAMO238** [zeapo/Android-Password-Store#1123]
**Describe the bug**
Upon selecting pull from git, or synchronise, the following error is thrown:
```
An error occured during a Git operation

Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference
```

**To Reproduce**
1. Initialise a pass git repo on a Linux machine
2. Create some entries (in this case, I imported my lastpass)
3. Initialise a bare git repo on a server
4. Push the pass git repo to the bare git repo
5. Import the bare git repo to the app and attempt to sync. 

**Expected behavior**
The app would pull all my passwords from my server to be available.

**Device information (please complete the following information):**
 - Device: Xiami Poco F1
 - OS: /e/ 0.11 (LineageOS llama fork (Android 9 fork))
 - App version 1.11.3

**Comment by msfjarvis** [comment]
I do exactly this so not sure what's going wrong here. I fixed the only known cause of this particular type of bug all the way back in April (#738). You're also behind our releases, since we pushed out `v1.12.0` 5 days ago.

How do I reproduce this issue? Are you cloning the bare repository or creating one on your device and using the external storage option to make the app use it?

**Comment by DAMO238** [comment]
I was using the 'local (hidden) repository'. I have solved the issue by going into 'git utils' and doing a 'hard reset to remote branch'. I think the issue may have been that there was an issue during the cloning, and the repository was just initialised but not cloned, which would lead to conflicting histories. Why we don't see the error saying that git refuses to merge conflicting histories, I don't know.

**Comment by msfjarvis** [comment]
> I was using the 'local (hidden) repository'. I have solved the issue by going into 'git utils' and doing a 'hard reset to remote branch'. I think the issue may have been that there was an issue during the cloning, and the repository was just initialised but not cloned, which would lead to conflicting histories. Why we don't see the error saying that git refuses to merge conflicting histories, I don't know.

Hm that'd explain it. The initial repository we create is pretty incomplete and mostly unusable so I guess I'll finally get around to fixing that.
