### ISSUE TITLE
[FEATURE] Allow additional fields per credential

### ISSUE THREAD

**Issue by zanona** [zeapo/Android-Password-Store#1126]
It would really great to be able to store additional fields per credential. Like, recovery keys, email linked to the account, or any contextual notes, really ;)  Perhaps even storing credit card numbers like on 1 password?

**Comment by msfjarvis** [comment]
You can already do that by entering whatever you want into the extra content field. We're not going to add separate handling for them.

**Comment by zanona** [comment]
Oh my, so sorry. I completely missed that field.
