### ISSUE TITLE
"Internal exception occured" when deleting password.

### ISSUE THREAD

**Issue by 0x24D** [zeapo/Android-Password-Store#116]
I have just updated to version 1.2.0.28 through F-Droid and when I tried to delete a password I received the following error:

```
Internal exception occured
Message from jgit:
Commit on repo without HEAD
currently not supported
```

After closing the error popup I noticed that the password hadn't been deleted. I tried to delete the password multiple times with the same error occuring.

**Comment by wongma7** [comment]
@zeapo deletePassword passes a 'new File("")' to getRepository function. So localDir is not null and with the new  'localDir != null' condition there is a potential to return a null repository. Not sure if this is what's happening/how it could happen, but hope this helps track the bug down.
 https://github.com/zeapo/Android-Password-Store/blob/master/app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.java#L40

**Comment by zeapo** [comment]
@wongma7 nice catch

**Comment by zeapo** [comment]
@xDanneee could you try the apk https://github.com/zeapo/Android-Password-Store/blob/4845300730e366821abf4f5dacf0e234d4ff9da9/app/app-release.apk?raw=true

It's signed with my key (used in the PlayStore App)

**Comment by xDanneee** [comment]
I have downloaded the apk but when I try to install it the package installer keeps crashing.

**Comment by zeapo** [comment]
you have to uninstall the old version before

**Comment by xDanneee** [comment]
Just installed but I get the same error when deleting.

**Comment by zeapo** [comment]
Are you able to push / pull?

**Comment by xDanneee** [comment]
I'm using a local repository.

**Comment by edrex** [comment]
I am also using a non-git password store ¶ and am saying this error when deleting, or adding, a password. When adding, the file is created but empty (deleting proceeds despite the error though). Thanks for supporting plain (non-git) repos.

¶ I'm using Syncthing to synchronize the password store instead of git. Works great!

**Comment by edrex** [comment]
Tried the linked build, same behavior.

Also noticed: the first time I see the error, an empty `.git` folder is created, and the next time, `.git/index` is created.

**Comment by zeapo** [comment]
I see, good thing you made reference to the non-git repo fact. I will try
to get it done during this week

Le mar. 18 août 2015 04:04, Eric Drechsel <notifications@github.com> a
écrit :
