### ISSUE TITLE
Automatic synchronization on app start is flawed

### ISSUE THREAD

**Issue by TinfoilSubmarine** [zeapo/Android-Password-Store#1163]
When I enable the new automatic synchronization in settings and then re-open the app, the "Syncing..." screen shows seemingly indefinitely.

Is there a bug causing it to never actually synchronize? Probably, but regardless of that, there should be some sort of timeout or ability for the user to cancel the sync. Otherwise, the inability to synchronize blocks the user from entering the app. There are several use cases that this breaks the flow of, e.g....

- user is in airplane mode
- user does not have internet access
- internet access blocks access to remote server holding user's password repo
- internet access is slow and user has a time-sensitive action requiring viewing a password from the repo
- and probably more :/

**Comment by msfjarvis** [comment]
Certainly overlooked cancellation, that's my bad. I guess I'm just gonna revert the feature and ship it with 2.0 after giving it some more thought.
