### ISSUE TITLE
Enable Kotlin explicit API mode in autofill parser

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1167]
Kotlin 1.4 comes with an [explicit API mode](https://kotlinlang.org/docs/reference/whatsnew14.html#explicit-api-mode-for-library-authors) that requires all public API of a Kotlin library to be marked as public manually and to be provided with concrete, user-defined types as opposed to relying on automatic type inference. Our openpgp-ktx﻿ library already utilises this feature, and we should have autofill-parser follow suit.

While here, it might also make sense to flesh out the documentation.

**Comment by fmeum** [comment]
Sounds very useful. I'll take care of this, albeit not with the highest priority.

**Comment by fmeum** [comment]
I added
```kotlin
kotlin {
    explicitApi()
}
```
to `autofill-parser`'s `build.gradle.kts`, but I'm not getting any build warnings/errors even though `public`s are missing. Do you know whether I need to do something else to enable the feature?

**Comment by msfjarvis** [comment]
> I added
> ```kotlin
> kotlin {
>     explicitApi()
> }
> ```
> to `autofill-parser`'s `build.gradle.kts`, but I'm not getting any build warnings/errors even though `public`s are missing. Do you know whether I need to do something else to enable the feature?

You'll also need to pass a compiler argument

https://github.com/android-password-store/openpgp-ktx/commit/dec55e549a41998cd33adce4f054287ab201b8ca
