### ISSUE TITLE
Search returns not complete results

### ISSUE THREAD

**Issue by inirudebwoy** [zeapo/Android-Password-Store#118]
Hi,

Suppose you have such keys:
```bash
  % pass find skype 
Search Terms: skype
├── praca
│   └── skype
└── prywatne
    └── internet
        └── skype
```
This is taken from passwordstore on linux, which find function find all occurrences of "skype".
Password Store app on phone when performing search for "skype" will return only first result ignoring rest.
Version of app: 1.2.0.28

**Comment by wongma7** [comment]
Hm, although this is technically fixed, the name of the result should include the path, otherwise you can't tell which result is what you want. @zeapo Should the path be shown for all search results or just duplicate names (or not at all)?

**Comment by zeapo** [comment]
@wongma7 I think we should change the way we display the passwords by using a CardView in the recyclerview and display the full path.

I will handle this, unless you want to.
cf. https://developer.android.com/training/material/lists-cards.html

**Comment by wongma7** [comment]
@zeapo Okay, you can handle it.

**Comment by zeapo** [comment]
@inirudebwoy @wongma7 Enjoy the new version, apk available on master :)
