### ISSUE TITLE
[BUG] Algorithm negotiation fail

### ISSUE THREAD

**Issue by 532910** [zeapo/Android-Password-Store#1183]
Just noticed the app id change `com.zeapo.pwdstore` -> `dev.msfjarvis.aps` and trying to configure the latest version from f-droid, bug get `Algorithm negotiation fail` cloning repository from server.

![2020_11_02_080012](https://user-images.githubusercontent.com/14617699/97902055-157b7880-1d4e-11eb-981c-056e514a58c6.png)

In the both case OpenKeychain is used for ssh authentication. URL is `<user>@h<host>:<port>/~/.password-store`. Server is debian stable.
Key in OpenKeychain is 25519. Only 25519 keys are in `.ssh/authorized_keys` but two `HostKey`s are specified in `/etc/ssh/sshd_config`: ecdsa and ed25519. Commenting out ecdsa breaks `com.zeapo.pwdstore` the same way, it starts fail with `Algorithm negotiation fail`.

OP3T LineageOS 17.1 Android 10
version 1.11.3 from F-Droid

**Comment by msfjarvis** [comment]
This has been fixed with #1142 and was rolled out with the v1.12.1 release. F-Droid is slow as usual and we can't do anything about that.

**Comment by 532910** [comment]
Thank you! Could you say, is it will be possible to disable ecdsa with 1.12.1?

**Comment by msfjarvis** [comment]
> Thank you! Could you say, is it will be possible to disable ecdsa with 1.12.1?

Yes it should be possible to safely disable ECDSA. Try it once you get the current version from F-Droid (v1.13.1 as of this second) and file a separate issue, without removing the template, if you encounter any issues.

**Comment by 532910** [comment]
It looks f-droid built will not be soon https://forum.f-droid.org/t/is-password-sore-stalled-again/11550/2
So I installed v2.0.0 snapshot build and can confirm it works fine.

**Comment by msfjarvis** [comment]
> It looks f-droid built will not be soon [forum.f-droid.org/t/is-password-sore-stalled-again/11550/2](https://forum.f-droid.org/t/is-password-sore-stalled-again/11550/2)
> So I installed v2.0.0 snapshot build and can confirm it works fine.

Awesome to hear it works. F-Droid's very lax about staying up-to-date with build tools unlike us so unfortunately these build issues keep happening. Gradle 6.7 is 3 weeks old at this point though :(
