### ISSUE TITLE
Provide a user-configurable denylist for Autofill

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1188]
**Is your feature request related to a problem? Please describe.**
We currently have a [very small list](https://github.com/android-password-store/Android-Password-Store/blob/354687e3a60f348af75c1a2f901270264d7e0313/app/src/main/java/com/zeapo/pwdstore/autofill/oreo/OreoAutofillService.kt#L41-L50) of packages that are never autofilled into. This is hard-coded and not particularly useful as-is.

**Describe the solution you'd like**
Allow users to extend this allowlist through a settings option to add any apps that intentionally misbehave with Autofill or just shouldn't be autofilled into.

**Describe alternatives you've considered**
Have users submit bugs for apps that should be excluded and then extend this list manually.

**Additional context**
The deleted accessibility autofill code contained an activity that listed all apps, so that part can possibly be re-used here.

**Comment by rounakdatta** [comment]
@msfjarvis can I start an attempt at implementing this feature?

**Comment by msfjarvis** [comment]
> @msfjarvis can I start an attempt at implementing this feature?

Sure thing! Please start a new [discussion](https://github.com/android-password-store/Android-Password-Store/discussions/new) if you need any help during the process.

**Comment by msfjarvis** [comment]
@rounakdatta do you need help with this?

**Comment by msfjarvis** [comment]
Unassigned since @rounakdatta hasn't responded in 20 days.

**Comment by msfjarvis** [comment]
Nobody's really expressed interest in this functionality so it might not be worth pursuing after all.
