### ISSUE TITLE
Slow decryption

### ISSUE THREAD

**Issue by untitaker** [zeapo/Android-Password-Store#119]
passwordstore takes 7 seconds to find the right key, then takes another 7 seconds to decrypt the password after having unlocked the key. I use a 2048-bit RSA key. I have no such performance problems on my PCs.

If there is no way to improve the performance of this, it'd be nice if the UI provided immediate feedback about that process instead of being blank.

**Comment by zeapo** [comment]
Are these 7 seconds before getting the prompt for the gpg passphrase or after?

**Comment by untitaker** [comment]
They are both before and after, but the actual timespans wildly vary. It sums up to 14 seconds.

**Comment by untitaker** [comment]
Also, this is Motorola G (2nd gen) with CyanogenMod 12.

**Comment by gabm** [comment]
I have the same problem using a key with detached master key... are u using the same configuration? whenever i import the full key with all secret keys (master and subkeys) it works immediately...

**Comment by untitaker** [comment]
I don't really know what that means. I see that the key I use for pass has two subkeys.

On 19 August 2015 12:18:07 CEST, gabm <notifications@github.com> wrote:
>I have the same problem using a key with detached master key... are u
>using the same configuration? whenever i import the full key with all
>secret keys (master and subkeys) it works immediately...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zeapo/Android-Password-Store/issues/119#issuecomment-132529580

-- 
Sent from my phone. Please excuse my brevity.

**Comment by wongma7** [comment]
I did `gpg --export-secret-subkeys SUBKEYID!` and the subkey seemed to work fine. My phone has similar hardware, Moto G 1st gen with CM 12.1, and I can't replicate the long decryption times.

In 1.2.0.32 there is a loading spinner. When app determines you need to enter your key password, it will say 'Authentication Required.' Then the OpenKeychain activity (the password box) is started and loading. Does 'Authentication Required' take long to appear? & does decryption take long if you've already authenticated?

**Comment by untitaker** [comment]
I just wiped OpenKeychain's store and reimported everything. For some reason everything is faster (auth + decryption still take 6s, but oh well). I have no idea what is going on, but I strongly suspect that Password Store is not the cause.

I've experienced similar problems with the SGS3 and CM11 btw.

On 29 August 2015 10:24:38 CEST, wongma7 <notifications@github.com> wrote:
>I did `gpg --export-secret-subkeys SUBKEYID!` and the subkey seemed to
>work fine. My phone has similar hardware, Moto G 1st gen with CM 12.1,
>and I can't replicate the long decryption times.
>
>In 1.2.0.32 there is a loading spinner. When app determines you need to
>enter your key password, it will say 'Authentication Required.' Then
>the OpenKeychain activity (the password box) is started and loading.
>Does 'Authentication Required' take long to appear? & does decryption
>take long if you've already authenticated?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zeapo/Android-Password-Store/issues/119#issuecomment-135961200

-- 
Sent from my phone. Please excuse my brevity.

**Comment by DirtYiCE** [comment]
I have similar problems. When I select an item in the password list, it takes about 45 seconds for the password prompt to appear (the majority of time is after the "Authentication Required" text appears). After entering the password it still needs about 70 seconds to actually decrypt the password.
Manually opening the gpg files with OpenKeychain takes about 12s until the password prompt appears, then about 14s until it actually decrypts it. Yes, even this is annoyingly slow, but significantly faster.  On the other hand encrypting (storing a new password) is fast, takes less than (say) 500ms.

I'm on One Plus One with Cyanogen OS 11.0, using OpenKeychain 3.5.1 with Password Store 1.2.0.32, both from F-Droid. Also tried wiping the whole OpenKeychain, exporting my key with `gpg --export-secret-subkeys`, then importing into OpenKeychain, but no change.

If I enable show CPU usage, org.sufficentlysecure.keychain:remote_api tops the list, so yeah, probably OpenKeychain is at the fault here.

**Comment by wongma7** [comment]
Yes, it seems the time is spent waiting for a response from OpenKeychain api. It would be best to repeat what you have said to https://github.com/open-keychain/open-keychain/issues and link back here, because investigating this issue further than 'is the OpenKeychain api being used correctly?' is beyond me.

**Comment by untitaker** [comment]
Will post there.

**Comment by untitaker** [comment]
I just ditched F-Droid and it turns out that all performance problems are gone. I recommend everybody to do the same: F-Droid liberally patches software beyond recognition.

**Comment by zeapo** [comment]
@untitaker You should open an issue on their gitlab and put a link to both this issue and the one you referenced on OpenKeychain. Their build of OpenKeychain might have an issue. AFAIK, they do not patch anything except build scripts in some cases.

**Comment by polyzen** [comment]
@untitaker, have you tried this? https://github.com/open-keychain/open-keychain/issues/1530#issuecomment-171857405. Worked for me, and I'm using f-droid's password store.

**Comment by polyzen** [comment]
Did you build it yourself or install it from the Play Store?

**Comment by polyzen** [comment]
Also, open-keychain 3.9 has performance imprivements. It was released in the Play Store a couple days ago. Perhaps that did the trick?

**Comment by rfjord** [comment]
OpenKeychain 3.9 (from F-Droid) solved this for me, everything is really snappy now.
