### ISSUE TITLE
[BUG] Current weightage of search results differs from expectations

### ISSUE THREAD

**Issue by 532910** [zeapo/Android-Password-Store#1197]
**Describe the bug**
exact search result must be the first

**To Reproduce**
1. Search something
2. See results

**Expected behavior**
Exact search result must be the first

**Screenshots**
N/A

**Device information (please complete the following information):**
 - Device: OP3T
 - OS: Lineageos 17.1
 - App version: 1.13.1

**Additional context**

I have the *only one* record that contains the `raif` substring, but when I search it, the record is shown on the 7th position.

**Comment by 532910** [comment]
1. This is not a feature request, this is a bug.
2. "non-fuzzy search algorithm" is not that I'm asking for.

I'm not against the fuzzy search, but exact results must be sorted first.

**Comment by fmeum** [comment]
It may be easier to just drop our custom fuzzy search implementation and roll with https://github.com/xdrop/fuzzywuzzy

**Comment by msfjarvis** [comment]
Yeah I wanted to try that for a while, have had positive experiences with it in the past. I'll take a stab at this tonight or over the weekend.

**Comment by fmeum** [comment]
I have started a pull request with test cases for our fuzzy search at #1217. @532910 It would be great if you could offer some concrete examples of unexpected search results. I would then try to find a valuation function that fits our requirements.

**Comment by msfjarvis** [comment]
@532910 is OP's username, you pinged the wrong Sergio :P

**Comment by fmeum** [comment]
This is what browserpass uses: https://github.com/farzher/fuzzysort/blob/master/fuzzysort.js
The results are great, but this looks very hacky and difficult to port. Look at line 590 if you don't believe me.

**Comment by msfjarvis** [comment]
> This is what browserpass uses: https://github.com/farzher/fuzzysort/blob/master/fuzzysort.js
> The results are great, but this looks very hacky and difficult to port. Look at line 590 if you don't believe me.

I now feel slightly less confident in my daily usage of browserpass. Someone reverse engineered the algorithm in detail a while ago and received feedback from the author of Sublime Text as well. So if you're looking for a weekend project, go crazy: https://www.forrestthewoods.com/blog/reverse_engineering_sublime_texts_fuzzy_match/

**Comment by msfjarvis** [comment]
Hey @532910 can you please answer Fabian's question so he can get started?

**Comment by 532910** [comment]
All search results are expected, but exact must be the first. For example: if you have records:
1. abco
2. abcp
3. abcq
4. abtr

and the search query is `abt` the result must be:
1. abtr
2. anything else

while not the result is:
1. abco
2. abcp
3. abcq
4. abtr
