### ISSUE TITLE
[FEATURE] a control for disable pull to synchronize

### ISSUE THREAD

**Issue by 532910** [zeapo/Android-Password-Store#1199]
Every occasional swipe down breaks my repository and I need to revert it.

Please disable push by swipe down, untill #636 is fixed.

similar issue #387

**Comment by msfjarvis** [comment]
I'm definitely not going to do that. Most users _do not_ use symlinks, so this does not affect them. The simpler solution here is for you to switch to an SSH key generated in-app for authentication, and to protect it with your screen lock. This way every time you manage to scroll too far, you'll be prompted to use your Fingerprint/Face/Iris scanner/PIN/Password/Pattern to unlock the key, which you can conveniently dismiss.

**Comment by 532910** [comment]
> Most users do not use symlinks, so this does not affect them.

Why should those who use them suffer?
Please don't tell people how they should use their passwordstore. It allows to create symlinks and swipe down completele breaks them.


I'm using the same key in OpenKeychain for encryption and ssh authentication and am not going to change this.

And I'm already prompted to unlock this key, but only once it locked.

**Comment by msfjarvis** [comment]
> > Most users do not use symlinks, so this does not affect them.
> 
> Why should those who use them suffer?

They don't need to suffer, they just need to learn how to scroll. I'm not going to cripple functionality to workaround a bug in a manner that doesn't even solve it.

> Please don't tell people how they should use their passwordstore. It allows to create symlinks and swipe down completele breaks them.

The app doesn't allow you to create symlinks.

**Comment by 532910** [comment]
> The app doesn't allow you to create symlinks.

Not out of the box, the same as OTP.

https://github.com/bhhaskin/pass-symlink

Moreover there were several bugs fixed to support symlinks well:

google( site:lists.zx2c4.com/pipermail/password-store symlink )

**Comment by msfjarvis** [comment]
> > The app doesn't allow you to create symlinks.
> 
> Not out of the box, the same as OTP.
> 
> [bhhaskin/pass-symlink](https://github.com/bhhaskin/pass-symlink)
> 
> Moreover there were several bugs fixed to support symlinks well:
> 
> google( site:lists.zx2c4.com/pipermail/password-store symlink )

When I say 'app', I mean Android Password Store, not the pass CLI. I am very interested in fixing this bug, we do have a clear plan around it, but I am not willing to add completely unrelated workarounds that don't do anything towards fixing the actual problem.

**Comment by 532910** [comment]
On the one hand, I'm completely agree and understand that you don't want to waste energy on workarounds to fix another bug.

On the other, how about just adding a control to disable pull down, it doesn't take long, does it? For example fenix has it:
![Screenshot_20201115-103424_Firefox_Nightly](https://user-images.githubusercontent.com/14617699/99179376-2a80e000-272e-11eb-9e01-b7ad05325bc5.png)
