### ISSUE TITLE
Edit entry

### ISSUE THREAD

**Issue by pank** [zeapo/Android-Password-Store#120]
Hi,

It seems it is not possible to edit passwords after initial creation.  This is a bit annoying when typos are spotted, or you need to update your password, and you do not have a git backend.

Also, I think the password generator doesn't allow for editing of the generated password (no keyboard shows up).

Thanks

**Comment by wongma7** [comment]
Re: generator, that was intended as the generated password can be edited after it's OK'd into the password field. I will either get rid of the blinking cursor/edittext or make it editable

**Comment by wongma7** [comment]
Implemented from https://github.com/zeapo/Android-Password-Store/commit/c54d28af8a0366b195019e153b276e5d570684ec

**Comment by pank** [comment]
wongma7 <notifications@github.com> writes:

> Implemented from
> https://github.com/zeapo/Android-Password-Store/commit/c54d28af8a0366b195019e153b276e5d570684ec

Thanks. I'm just updated to `.29`.

However, I'm still unable to edit the password I've already got a typo in
on the phone.  Do you want a separate bug report for that or is that a
feature?

Rasmus

**Comment by wongma7** [comment]
Ah, I'm sorry. I released .29 without this feature. I will release .30 today with this feature.

**Comment by wongma7** [comment]
In my haste I overlooked a git issue. In .30 you will be able to edit passwords, but the app will not know to create a commit when a file changes. I will implement it for .31. Once again, sorry!

**Comment by pank** [comment]
Editing works great. Thanks!
