### ISSUE TITLE
[BUG] App skips 'Documents' folder when selecting local repo

### ISSUE THREAD

**Issue by ghost** [zeapo/Android-Password-Store#1201]
**Describe the bug**
When selecting external repo in local folder like Documents/{anything}, app skips 'Documents' and shows repo path as /storage/emulated/0/{anything}, and hence repo is shown as empty

**To Reproduce**
1. Go to setting
2. Click on 'select external repo'
3. Navigate to Documents/{anything} that has copy of pass files
4. Click 'Allow access'
5. See that app shows repo path as /storage/emulated/0/{anything} but no 'Documents'
6. Go back and see empty repo in app main screen
7. Restart app and see nothing has changed

**Expected behavior**
App can see and use this repo

**Screenshots**

![Screenshot_20201113-191500](https://user-images.githubusercontent.com/74420473/99094587-11b8e300-25e5-11eb-8e84-2ac662d40e5a.jpg)

**Device information (please complete the following information):**
 - Device: Xiaomi Redmi 4 Pro
 - OS: HavocOS 3.9 (Lineage fork) Android 10
 - App version: latest, 1.13.1

**Additional context**
If selecting e.g. Download/Documents/pass, it works fine. So the issue is not in capital letters or the word itself

**Comment by Skrilltrax** [comment]
Hey, I checked creating a new external repo inside the Documents folder. It's showing the correct path for me in the settings screen. Can you try a debug build and send some logs?

**Comment by msfjarvis** [comment]
Closing as stale since OP has not responded.
