### ISSUE TITLE
[FEATURE] create shortcut for some selected record

### ISSUE THREAD

**Issue by 532910** [zeapo/Android-Password-Store#1205]
**Is your feature request related to a problem? Please describe.**

Please add a way to create shortcut for a some selected record

**Describe the solution you'd like**

Place to the desktop button should be shown by long tap the record and inside the record.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by msfjarvis** [comment]
Fixed with #1392 and #1393﻿
