### ISSUE TITLE
[BUG] password is requested for key auth only server

### ISSUE THREAD

**Issue by 532910** [zeapo/Android-Password-Store#1209]
**Describe the bug**
Password is requested for key auth only server

**To Reproduce**
0. Disable password auth on the server
```
PasswordAuthentication no
ChallengeResponseAuthentication no
```
1. Request git synchronization (Synchronize, Pull or Push)
2. Choose `Cancel` for OpenKeychain request
3. Password is requested

**Expected behavior**
Nothing should happen.

**Screenshots**
![Screenshot_20201115-135118_Password_Store](https://user-images.githubusercontent.com/14617699/99183005-cf5ce680-2749-11eb-9686-a3c6058a08ee.png)

**Device information (please complete the following information):**
 - Device: op3t
 - OS: LineageOS 17.1
 - App version: v1.13.1

**Additional context**
N/A

**Comment by fmeum** [comment]
This has been deliberate so far. Our ssh library can't tell which authentication methods the server offers and by always providing the user the option to enter a password, we can deal with servers requesting a key first and then a password.

**Comment by 532910** [comment]
Actually I see two bugs here. The password is requested regardless of:
1. server settings
2. openkeychain auth mode configured in git settings

**Comment by msfjarvis** [comment]
> Actually I see two bugs here. The password is requested regardless of:
> 
> 1. server settings
> 2. openkeychain auth mode configured in git settings

You're ignoring what we're saying. The password is always requested upon failure of primary authentication because our SSH backend cannot tell what authentication methods are advertised by the server, so password is treated as a fallback.

**Comment by msfjarvis** [comment]
This is blocked on SSHJ gaining the ability to parse authentication modes and we can't do anything about it on our end short of sending a pull request. Personally I don't see this as important enough to do that, so I'm closing it until SSHJ can handle this.

**Comment by 532910** [comment]
I'm not ignoring. SSH backend doesn't know advertised methods. OK. But I configured openkeychain and expect this is the only method that will be used. And I refuse to understand why it fallbacks to password!

**Comment by msfjarvis** [comment]
> I'm not ignoring. SSH backend doesn't know advertised methods. OK. But I configured openkeychain and expecte this is the only method that will be used. And I refuse to understand why it fallbacks to password!

Because servers have fallbacks.

**Comment by 532910** [comment]
servers doen't fallback, it has two user keys and tries them all

This could be called fallback, it doesn't matter, but this is not a reason to ask a password.

**Comment by msfjarvis** [comment]
I can't deal with your arrogance and ignorance anymore. You are no longer welcome, and are blocked from further interaction with the project.
