### ISSUE TITLE
[BUG] Password looks like comment to app and is ignored

### ISSUE THREAD

**Issue by ctag** [zeapo/Android-Password-Store#1211]
**Describe the bug**

Hi,

I started using pass from the shell on my desktop, and then migrated to git and cloned to this app on my phone. Recently I noticed that a password which was auto generated from the shell program happens to begin with a '#' and is ignored, with the app using the next line (which had an old, unused password) instead. In my experience this is not the same behavior as the shell program.

**To Reproduce**
1. Create a password which begins with '#'.
2. Open the password in the app to use it.
3. The app will automatically skip to line 2

**Expected behavior**
Though I believe skipping comments is a valuable feature, I believe the app should function similarly to pass in which the 1st line is the password regardless.

**Screenshots**

**Device information (please complete the following information):**
 - Device: OnePlus 5t
 - OS: LineageOS 17.1 no gapps
 - App version 1.13.1

**Additional context**

**Comment by msfjarvis** [comment]
I can't reproduce this on the latest snapshot, nor have we ever had any functionality around comments. Creating a test password from my PC with the first line as `#password` correctly works on my phone.

**Comment by ctag** [comment]
Thank you msfjarvis. 

I made assumptions about the bug and was incorrect. What is actually happening is an old password further down in the file was imported from KeePass originally and the line reads `Password: origpass` which is then selected instead of the 1st line and used by the app. 

The redacted file looks like this:
```
$ pass banking/paypal
#newpassword
origpass
UserName: me@mail.com
URL: https://www.website.com/
Notes: Security question:
Tacos

[imported from keepass]
---------
Password: origpass
UserName: me@mail.com
URL: https://www.website.com/
Notes: Security question:
Tacos
```
So I didn't notice it was going down to the second instance of the old password and using that.

I believe it would be fair to say I simply need to clean up the file, but again this behavior is different from the shell program.

Thanks!

**Comment by msfjarvis** [comment]
> Thank you msfjarvis.
> 
> I made assumptions about the bug and was incorrect. What is actually happening is an old password further down in the file was imported from KeePass originally and the line reads `Password: origpass` which is then selected instead of the 1st line and used by the app.
> 
> The redacted file looks like this:
> 
> ```
> $ pass banking/paypal
> #newpassword
> origpass
> UserName: me@mail.com
> URL: https://www.website.com/
> Notes: Security question:
> Tacos
> 
> [imported from keepass]
> ---------
> Password: origpass
> UserName: me@mail.com
> URL: https://www.website.com/
> Notes: Security question:
> Tacos
> ```
> 
> So I didn't notice it was going down to the second instance of the old password and using that.
> 
> I believe it would be fair to say I simply need to clean up the file, but again this behavior is different from the shell program.
> 
> Thanks!

The behavior difference is intentional and will stay that way for now. The password search algorithm is a bit more involved than "first line is a password" due to different usecases that have been reported over the years, and the current system works as designed. The fix would be to drop the `Password:` prefixed field on your end.
