### ISSUE TITLE
[BUG] password screen is shown after phone unlock

### ISSUE THREAD

**Issue by 532910** [zeapo/Android-Password-Store#1215]
**Describe the bug**
A password screen is shown after phone unlock.

**To Reproduce**
1. Open some password
2. Lock the phone
3. Unlock the phone

**Expected behavior**
A password screen should be closed on phone lock.

**Screenshots**

**Device information (please complete the following information):**
 - OS: Lineage 17.1
 - App version: 1.13.1

**Additional context**

Though this looks like a feature request, I believe it's a security regression, as the old app was closing the password screen after a timeout.

**Comment by msfjarvis** [comment]
The activity will now finish itself after 60 seconds, I will not be making it configurable or complicate it with an additional screen lock listener.
