### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by posix4e** [zeapo/Android-Password-Store#1218]
**Is your feature request related to a problem? Please describe.**
I would like to be able to to re-rencrypt everything with whatever .gpg-id file is in the repo. Bonus points if I can update the .gpg-id with a drop down for the public keys I have

**Describe the solution you'd like**
1) User goes to settings
2) Clicks re-attempt all passwords
3) It goes through 1 by 1 re-encrypting all the password files

**Describe alternatives you've considered**
I usually use pass init blah

**Comment by msfjarvis** [comment]
This will be ungodly levels of slow when implemented in the app due to the nature of how we need to interact with OpenKeychain.

Also, please take care when filling in an issue template, you're entirely missing the title.
