### ISSUE TITLE
[BUG]Autofill doesn't work on Oreo on Instagram

### ISSUE THREAD

**Issue by ghost** [zeapo/Android-Password-Store#1219]
**Describe the bug**
Autofill doesn't work on Instagram, Discord and others

**To Reproduce**
1. Install and open Instagram
2. Click on login
3. Click on the username field
4. A password autofill suggestion is seen for instagram, along with a search autofill
5. On choosing either of them, first the password has to been entered which works as expected, but after entering the password, instead of filling in the password, the default username, which has been set in settings, under autofill is filled

**Expected behavior**
Expected my Instagram password to be filled instead of default username.

**Screenshots**
Couldn't take screenshot due to security policy on the login page.

**Device information (please complete the following information):**
 - Device: Samsung SM-T585
 - OS: Stock Android 8.1.0 Oreo
 - App version 1.13.1

**Additional context**
This is my current layout:
social:
     instagram.com
instagram.com has my instagram password. I have selected password file organization as the first one - work/example.org(.gpg).
I was using the Instagram app, not the website.

**Comment by msfjarvis** [comment]
I'd like an exact list of apps if you can provide one. I'm aware that Instagram is broken because of a problem with their app, and I can confirm Discord does work on Android 10 and 11, so maybe we need to see if something changed between Android versions.

**Comment by BobSpams** [comment]
Sure, here it is



Sent from my Galaxy Tab A



-------- Original message --------

**Comment by ghost** [comment]
Sure, here it is:
![20201124_084208](https://user-images.githubusercontent.com/73415110/100042696-0447f800-2e32-11eb-834b-b60f970bc85c.jpg)
![20201124_084226](https://user-images.githubusercontent.com/73415110/100042697-04e08e80-2e32-11eb-876c-a5c1769d851f.jpg)
![20201124_084255](https://user-images.githubusercontent.com/73415110/100042698-05792500-2e32-11eb-8286-7db894b9284d.jpg)
![20201124_084312](https://user-images.githubusercontent.com/73415110/100042700-0611bb80-2e32-11eb-8544-54e1e082c82d.jpg)
By the way, it would be nice to have autofill for OTPs too, as well as create a new field for adding TOTPs. Currently I have to scan a QR code to create an OTP, or manually write otpauth://totp&key=foobar in the extra content
, which isn't easy on a mobile device
As for discord, I am very sorry, it works fine, but firefox doesn't.

**Comment by msfjarvis** [comment]
> Sure, here it is:
> ![20201124_084208](https://user-images.githubusercontent.com/73415110/100042696-0447f800-2e32-11eb-834b-b60f970bc85c.jpg)
>[snip]

This appears to be a list of _all_ your apps, I only want to know which ones are broken with Autofill.

> By the way, it would be nice to have autofill for OTPs too, as well as create a new field for adding TOTPs. Currently I have to scan a QR code to create an OTP, or manually write otpauth://totp&key=foobar in the extra content
> , which isn't easy on a mobile device

OTP fields _are_ autofilled in apps, and Password Store will let you include a TOTP secret into any password file by scanning a QR code which to my knowledge is one thing that every website supporting two factor authentication does use. I do not plan to change that in any way for now.

> As for discord, I am very sorry, it works fine, but firefox doesn't.

Firefox works extremely well in my testing. Can I know the exact version you are using?

**Comment by ghost** [comment]
Firefox is the only one that doesn't work.
I am using Firefox v83.1

**Comment by msfjarvis** [comment]
> Firefox is the only one that doesn't work. I am using Firefox v83.1

That's odd, we support basically every Firefox variant I can think of. Can you check if the package name for your variant is present in this list below, and share yours if it's not?

```
"org.mozilla.fenix"
"org.mozilla.fenix.nightly"
"org.mozilla.fennec_aurora"
"org.mozilla.fennec_fdroid"
"org.mozilla.firefox"
"org.mozilla.firefox_beta"
"org.mozilla.focus"
"org.mozilla.klar"
```

**Comment by ghost** [comment]
org.mozilla.firefox
Sorry to disturb you, and thanks for the reply
I think it might have something to do either specifically with my device
or Android Oreo. I might try it on a another rom

**Comment by fmeum** [comment]
Oreo doesn't support Autofill in legacy browsers. You might want to try Firefox Focus or Fenix instead.

**Comment by ghost** [comment]
Can confirm it is reporducable in org.mozilla.firefox, but not on org.mozilla.focus

**Comment by msfjarvis** [comment]
Alright then guess this is one for the docs.

**Comment by afreakk** [comment]
Could we maybe have a list of browsers working with autofill for android 8?
For now the only browser I know works is firefox focus.

**Comment by msfjarvis** [comment]
> Could we maybe have a list of browsers working with autofill for android 8?
> For now the only browser I know works is firefox focus.

Firefox Focus is pretty much it to be honest. I'll collate all autofill related information in a docs page today.

**Comment by fmeum** [comment]
[This is a list](https://github.com/android-password-store/Android-Password-Store/blob/develop/autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FeatureAndTrustDetection.kt#L142-L150) of all browsers that we determined to have native Autofill support, which means that they should work on Android 8.
