### ISSUE TITLE
Authentication is required but no CredentialsProvider has been registered.

### ISSUE THREAD

**Issue by emanrdesu** [zeapo/Android-Password-Store#1221]
I keep getting this message when I try to clone a repository.
This repository is private.
I tried to use my private key, and also a generated key (I addded it to deploy keys section) but still the same message.
I don't know what to do.
I really want to use this software.

**Comment by msfjarvis** [comment]
Your issue fails to follow our template and thus makes it impossible for us to help. Please open a new issue with all the requested details.
