### ISSUE TITLE
Notification timer should count down from clipboard clear timeout

### ISSUE THREAD

**Issue by 532910** [zeapo/Android-Password-Store#1227]
**Describe the bug**
Timout is counted up on notification.

**To Reproduce**
1. Copy password

**Expected behavior**
Count down timer on notification.

**Screenshots**
![Screenshot_20201201-201846_Trebuchet](https://user-images.githubusercontent.com/14617699/100774536-3c8f9d80-3413-11eb-8b6d-c3c4588599d0.png)

**Device information (please complete the following information):**
 - App version: 1.13.1

**Additional context**
~~Add any other context about the problem here.~~

**Comment by msfjarvis** [comment]
When you file issues please remove the instructional boilerplate so we can actually see what you've added.

**Comment by 532910** [comment]
It's too hard to remove them on mobile. They should be commented out.

**Comment by msfjarvis** [comment]
> It's too hard to remove them on mobile. They should be commented out.

It's not and they won't be.

**Comment by msfjarvis** [comment]
I just edited it on my phone with zero problems. If you want to do nothing more than the bare minimum then I will have no other option than to block you from further participation with the APS repository. We don't expect a lot of our users, but I feel we do enough to earn the basic courtesy of having users properly fill a pre-made template.
