### ISSUE TITLE
[BUG] Change Hostkey external git repo, could not be verified

### ISSUE THREAD

**Issue by xundeenergie** [zeapo/Android-Password-Store#1232]
**Describe the bug**
I have an own server, hosting my external git-repo for password-store. The ssh-hostkey has changed, and now my andoid app says "Could not verify ssh-rsa-cert-v01@openssh.com host key with fingerpring...."
I'm not able to say ok to the new hostkey (i know, it changed, because I made the new key)

**To Reproduce**
1. Change ssh Hostkey on remote server for git repo
2. Click on "Git pull"
3. See error

**Expected behavior**
I expected on a new hostkey, that i get asked if i know, that hostkey has changed and i want to say "yes" or "no" to the new hostkey. When i sey "yes", the hostkey-fingerprint for this host should be updated.

**Screenshots**

**Device information (please complete the following information):**
 - Device: HUAWAI P30Pro
 - OS: Android 10
 - App version: 1.13.1

**Additional context**

**Comment by fmeum** [comment]
You can simply change the Git server settings and hit save (and then change them back). That will clear the pinned host key. 

@msfjarvis We might want to leave this open and implement a dialog as described by the reporter.

**Comment by msfjarvis** [comment]
> You can simply change the Git server settings and hit save (and then change them back). That will clear the pinned host key. 
> 
> @msfjarvis We might want to leave this open and implement a dialog as described by the reporter.

Yeah this should have been a dialog all along. I'll look into it.
