### ISSUE TITLE
[BUG] Synchronize repository generates empty commits

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1238]
> This problem is reappearing in version 1.13.1. Empty "[Android Password Store] Sync" commits are being pushed to remote every time the "Synchronize repository" button is pressed.

We previously fixed this so it appears we've somehow regressed.

**Comment by msfjarvis** [comment]
I can't seem to reproduce it on my devices, @haansn08 can you try the [snapshot builds](https://android-password-store.github.io/docs/users/release-channels) and confirm that it's still broken for you?

**Comment by haansn08** [comment]
I can reproduce it with `aps-free_2.0.0-SNAPSHOT.apk` and a fresh clone of the repo.

**Comment by msfjarvis** [comment]
I have been unable to repro with GitHub, Bitbucket, and a locally hosted repository on my computer; so now I'm extremely tilted. Any extra information you think might be useful? Git host, authentication mode and such. I'd also be grateful if you can record a log of you running the synchronize operation so I can look for any specific pointers there.

**Comment by haansn08** [comment]
The repository is hosted on a private GitLab instance. Authentication is ssh ed25519 public key.
I see there is a "Enable debug logging" option in the settings, but I don't know how to find or access the log files.

**Comment by msfjarvis** [comment]
> The repository is hosted on a private GitLab instance. Authentication is ssh ed25519 public key.
> I see there is a "Enable debug logging" option in the settings, but I don't know how to find or access the log files.

Thanks for the info. The log is generated in the form of files, but instead written into the device's `logcat` stream. If you don't have prior experience with it then it's fine, I'll try to debug it on my end.

**Comment by msfjarvis** [comment]
Yeah I tried every Git host including Bitbucket and Gitlab and I just can't reproduce this. My original fix is still intact and I have yet to see any other report of this happening.

Sorry, but I'm going to have to close this as a wontfix.
