### ISSUE TITLE
[FEATURE] please allow multiple decryption keys

### ISSUE THREAD

**Issue by bjmgeek** [zeapo/Android-Password-Store#1244]
My wife and I both have separate openpgp keys.  We share a password store, with passwords encrypted to both keys.  Both keys are in OpenKeychain, on the same phone.  Currently, the first key that is found is the only one that the app uses forever, and it doesn't offer the user the option to choose which key to decrypt with.

**Describe the solution you'd like**
When the user selects a password from the password store to decrypt, and there are multiple private keys available that would decrypt the password, there should be a dialog to choose which key to use.  The user would choose a key, then input the passphrase for that key.

**Describe alternatives you've considered**
Another way to do it is the way gnupg on linux does.  It tries one key, then if the user selects Cancel, tries the next key that would decrypt the message.

**Comment by msfjarvis** [comment]
I feel this is something that needs to be fixed in OpenKeychain but I'll check anyway.

**Comment by bjmgeek** [comment]
So, it turns out it is in openkeychain.  I looked in openkeychain, and there's a connected apps section.  In that section, I was able to choose the keys that were allowed by password store.  Once I selected both keys, I could type either pass phrase and decrypt the password.  There is still some UI strangeness, as it no longer shows the name associated with the key, but it does decrypt
