### ISSUE TITLE
[BUG] Can't clone to external 

### ISSUE THREAD

**Issue by benrhughes** [zeapo/Android-Password-Store#1245]
**Describe the bug**
In older versions of Password Store, it was possible to clone to an external directory. Currently, it seems that I can point Password Store at an already-cloned directory on the SD card, but I cannot get it to create the clone itself.

**To Reproduce**
1. Clean install the app
1. 'Let's Go'
1. 'Clone Remote Repo'

**Expected behavior**
At this point I would expect to be given the option of hidden or external.

If I set the external directory in Settings before cloning, then go through the steps above, it switches to using the internal/hidden directory.

**Device information (please complete the following information):**
 - Device: Moto G8 Plus
 - OS: stock Android 10
 - App version 1.13.1

**Comment by msfjarvis** [comment]
This is an intended change, see https://github.com/android-password-store/Android-Password-Store/issues/1118
