### ISSUE TITLE
[FEATURE] sign commit message

### ISSUE THREAD

**Issue by dingwen07** [zeapo/Android-Password-Store#1249]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Provide an option to sign commit messages using PGP keys.

**Describe alternatives you've considered**
For `pass` on desktop, it could be configured by globally enable signature for gpg.

**Comment by msfjarvis** [comment]
JGit does not support signing commits on v3.6 and it's impossible that we will be able to use the latest version without having to completely drop support for multiple currently supported Android versions.
