### ISSUE TITLE
[BUG] Autofill pop-up won't show

### ISSUE THREAD

**Issue by dfrost16** [zeapo/Android-Password-Store#1253]
**Describe the bug**
Sometimes the Autofill pop-up on won't show up, the behaviour is pretty random. I have already granted the app all the permission and removed battery optimization, 
Though after force stopping the app the pop-up works just fine again

**Device information (please complete the following information):**
 - Device: Xiaomi Redmi Note 5 Pro
 - OS: Custom ROM Android version 11
 - App version 1.13.1

**Additional context**

**Comment by fmeum** [comment]
What are the apps that are affected? Can you provide screenshots of situations in which you would expect the pop-up to show but it doesn't?

We also need the requested device information or we can't look into this.

**Comment by msfjarvis** [comment]
> We also need the requested device information or we can't look into this.

It's there, they just edited out the example values to match their device. I've fixed the OP.

**Comment by dfrost16** [comment]
> What are the apps that are affected? Can you provide screenshots of situations in which you would expect the pop-up to show but it doesn't?
> 
> We also need the requested device information or we can't look into this.

Before Force Stopping

![Screenshot_20201218-170849](https://user-images.githubusercontent.com/24663673/102610766-be8dff00-4153-11eb-92b9-0d5bb8a7f96e.png)

After Force stopping

![Screenshot_20201218-171006](https://user-images.githubusercontent.com/24663673/102610853-e67d6280-4153-11eb-8f7f-dbe213136c74.png)

**Comment by msfjarvis** [comment]
Brave is based on an older Chromium version so a lot of autofill bugs still affect it. See #926 for details.
