### ISSUE TITLE
[BUG] When cloning a password repository, not all authentication modes fit on the screen

### ISSUE THREAD

**Issue by omentic** [zeapo/Android-Password-Store#1260]
**Describe the bug**
The authentication mode "openkeychain" is squashed, with the left "o" being clipped and cut off while being truncated enough to the right to be illegible. 

**To Reproduce**
1. Get a Samsung Galaxy S7 (it's unclear to me if this is caused by screen size or Android 8.0)
2. Install and open this app
3. Select "Clone remote repo"
4. See screenshot

**Expected behavior**
All three authentication modes should fit on the screen - by scaling them down, or truncating "openkeychain" more legibly than it is currently.

**Screenshots**
![foo](https://user-images.githubusercontent.com/35242550/102963962-4e5ae280-449f-11eb-84f4-30185dd1b74b.jpeg)

**Device information (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android 8.0
 - App version 1.13.1

**Comment by msfjarvis** [comment]
This looks incomplete

**Comment by omentic** [comment]
@msfjarvis What the heck? I'm absolutely sure I had filled this out completely... perhaps GitHub mangled it, or I somehow pasted a blank template over it?

It's now complete, if you wouldn't mind reopening.

**Comment by msfjarvis** [comment]
> @msfjarvis What the heck? I'm absolutely sure I had filled this out completely... perhaps GitHub mangled it, or I somehow pasted a blank template over it?
> 
> It's now complete, if you wouldn't mind reopening.

You also filed #1261 which is the same bug, which I've triaged and assigned.

**Comment by omentic** [comment]
That's extremely weird, I didn't even notice. Apologies for whatever appears to be happening on my end.
