### ISSUE TITLE
[BUG] Onboarding view does not work well on lower densities

### ISSUE THREAD

**Issue by franklinbill** [zeapo/Android-Password-Store#1262]
**Describe the bug**
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the button and the following text overlap each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
App version is 1.13.2, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!

**To Reproduce**
1. Go to first page
2. See error

**Expected behavior**
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.

**Screenshots**
<img width="552" alt="bug-11320@2x" src="https://user-images.githubusercontent.com/18572115/103147126-e6e9af00-478c-11eb-9c0c-adb8694d4321.png">

**Device information (please complete the following information):**
 - Device: [e.g. Google nexus 6]
 - OS: [e.g. stock ROM Android version 8.0]
 - App version [e.g. 1.13.2]

**Additional context**
Maybe a display bug.

**Comment by Skrilltrax** [comment]
Thanks for reporting, I'll take a look at it.
