### ISSUE TITLE
[FEATURE] Autofill service for Google Chrome

### ISSUE THREAD

**Issue by senthilbaboo** [zeapo/Android-Password-Store#1278]
**Is your feature request related to a problem? Please describe.**
Autofill Service works great when I use other Android apps. However the same does not seem to work when I try to use it in a chrome browser.

**Describe the solution you'd like**
It will be great to have autofill popups available when using chrome.

**Describe alternatives you've considered**
An android keyboard implementation would also be great, where we could select a custom keyboard (Android Password Store Keyboard), which can give options to select password (or other encrypted text) that are available in the store. This will also be useful when filling other private information like SSN, credit card details, secret answers etc.

**Additional context**

**Comment by msfjarvis** [comment]
Autofill is supported in Google Chrome. Their implementation was extremely buggy, and the known issues are being tracked in #926. @fmeum has been doing excellent work for the last half year, getting these fixed in Chromium and you can see the benefits of that by using Chrome Dev, Beta or Canary releases.

**Comment by fmeum** [comment]
@senthilbaboo  Chrome Beta hasn't received most of the fixes yet, but you could try again with Chrome Dev. Which version of Android are you using?

**Comment by senthilbaboo** [comment]
I am using chrome beta. May be I will wait for the fix.

Also slightly out of the context, would it possible to integrate autofill with GBoard, It seems Dashlane did something similar: https://9to5google.com/2020/08/26/dashlane-android-11-keyboard/

**Comment by msfjarvis** [comment]
> Also slightly out of the context, would it possible to integrate autofill with GBoard, It seems Dashlane did something similar: https://9to5google.com/2020/08/26/dashlane-android-11-keyboard/
> 
> 

We have (#1181). It's not shipped in the v1.13 cycle because it's part of larger breaking changes that will be released in v2.0 in the next few months.

**Comment by msfjarvis** [comment]
Closing since there's nothing to do here.
