### ISSUE TITLE
Autofill: RESULT_CODE_USER_INTERACTION_REQUIRED infinite loop

### ISSUE THREAD

**Issue by Nis2** [zeapo/Android-Password-Store#128]
Using autofill, when OpenPgpApi returns a RESULT_CODE_USER_INTERACTION_REQUIRED (for example when using an yubikey), the dialog is restarted infinitely.
This happens because the intent data is not fed back to OpenPgpApi. Instead a new intent is created at the beginning of decryptAndVerify.
See https://github.com/open-keychain/openpgp-api part 4 of the tutorial.

**Comment by wongma7** [comment]
Thanks for report + solution. Missed this and it still somehow worked with password authentication.

**Comment by wongma7** [comment]
Will still need to be tested with a yubikey/any form of authentication besides password

**Comment by Nis2** [comment]
Tested. It fixes the issue. Thanks.
