### ISSUE TITLE
Default directory is hazardous when prompted to "Clear repository"

### ISSUE THREAD

**Issue by jecxjo** [zeapo/Android-Password-Store#129]
The default directory after installing was /storage/0/legacy. When cloning my git repo I was prompted if I wanted to clear the current storage. When selecting delete I cleared my entire device. All files in my Download folder, pictures, etc. were all lost.

The default directory should be something not so potentially hazardous.

**Comment by zeapo** [comment]
That's odd, as far as I recall the default external dir is not set until the user sets it.
The internal directory is /usr/data/com.zeapo.pwdstore/files/store or something like that.

**Comment by zeapo** [comment]
fixed in #148
