### ISSUE TITLE
[FEATURE] Git Token Authentication

### ISSUE THREAD

**Issue by youben11** [zeapo/Android-Password-Store#1290]
**Is your feature request related to a problem? Please describe.**
[Github will no longer support](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/) (June 2021) password based authentication, and will require either SSH, or token based authentication.

**Describe the solution you'd like**
I know SSH is already supported, but it would be also great to have the token authentication mechanism.

**Comment by msfjarvis** [comment]
It's already supported. Simply swap out your password for a personal access token.

**Comment by youben11** [comment]
Oups! Thanks for the quick reply, I did search on the CHANGELOG though, but didn't find something about it.

**Comment by msfjarvis** [comment]
> Oups! Thanks for the quick reply, I did search on the CHANGELOG though, but didn't find something about it.

It's not mentioned because it's not actually a special cased feature. Both PATs and passwords work the same way on GitHub aside from actually logging you in on the website.
