### ISSUE TITLE
[FEATURE] Data stored in JSON format

### ISSUE THREAD

**Issue by cbcoutinho** [zeapo/Android-Password-Store#1293]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I store some non-password data as JSON in my password store, and on my laptop, I use `jq` to parse/filter the data I need, but on mobile, this is difficult or close to impossible depending on the structure of the data.

It would be great if there existed a simple toggle to parse password content as JSON data so that you could easily select whichever field you need. The current behavior of extracting the first line and "username" entries is useful for autofill but doesn't work as well for other custom fields.

**Describe alternatives you've considered**

I tap/hold the text I need and adjust using the text-selection markers. This is difficult if the data structure is somewhat nested or contains special characters.

**Comment by msfjarvis** [comment]
I'm not very convinced that this is worth building out.

`pass` itself doesn't support it, I personally don't see it being something a lot of people use, and it's going to be a _lot_ of work.
