### ISSUE TITLE
Possible to copy .password-store to Android and use directly from there

### ISSUE THREAD

**Issue by rightaway** [zeapo/Android-Password-Store#130]
I've created the .password-store git directory on my computer with all the passwords in it, and instead of running a git server somewhere, I prefer to copy that directory to my Android and run this app directly from it there. Is that possible? It'd be useful for people who don't run their own git server but can copy over the .password-store from their computer to their android regularly.

**Comment by zeapo** [comment]
You can but it's not well supported. There are two ways:
- Click on **Clone Existing**, select external, then select the directory where you copied the store.
- Click on **Settings**, check **External repository**, then select the directory you copied.
Until we support non-git repositories, be sure to keep the `.git` directory inside the `.password-store` directory.

**Comment by rightaway** [comment]
Thanks, I can see the list of password files in the app now! When you say it isn't well supported, are there any gotchas I should watch out for?

I'm quite new to PGP in general, so could you tell me how I go about setting the right values under "Select key" and "Select OpenPGP Key Id" so that I can view the passwords? I've got password-store working fine on my computer, what files do I need to prepare and move from my computer to the phone?

**Comment by Aeyoun** [comment]
The above method both result in a dialog like this:

“Directory not empty. You’ve selected a non-empty directory for the store. This is extremely dangerous and you will loose your data as its content will be deleted. [Remove Everything]”

I do have my .git inside the same directory, but the app wants to delete the folder regardless. There are no other files in the directory.

**Comment by wongma7** [comment]
As noted here, https://github.com/zeapo/Android-Password-Store/issues/161 the message is wrong and the app doesn't actually delete the contents of the folder. So it will see the passwords and hopefully the .git too

**Comment by zeapo** [comment]
see https://github.com/zeapo/Android-Password-Store/issues/161#issuecomment-214519766
