### ISSUE TITLE
Design of the V2

### ISSUE THREAD

**Issue by zeapo** [zeapo/Android-Password-Store#131]
Hi everybody,

I started working on the design for the new version. It will be written (almost) from scratch and thought from the ground up to solve all the issues we have right now. It will also be developed in the open on a different repository.

The features that we will have are (list to be updated regularly):
- [x] Multiple stores
- [ ] Git stores
- [x] Non-Git stores
- [ ] Dropbox and Drive sync
- [ ] Encrpyt/Decrypt as done currently
- [ ] Password generation
- [ ] Password edit
- [ ] GPG re-encryption of store
- [ ] Application specific passwords

Here is the current status of the design: (Sketch3 files available if anybody wants them)

![multiple stores](https://cloud.githubusercontent.com/assets/270342/9799222/25a8632a-5806-11e5-9cb0-e93cfd8917d6.png)
![passwords list](https://cloud.githubusercontent.com/assets/270342/9799223/25a92ab2-5806-11e5-8699-7b98c105b9cb.png)
![password creation](https://cloud.githubusercontent.com/assets/270342/9799224/25aaa5cc-5806-11e5-9d93-8af020d02dc1.png)

**Comment by JasperWeiss** [comment]
Looking good so far,
Will it support websites?

**Comment by JasperWeiss** [comment]
Just wondering, why is the status bar the same color as the navigation bar? I've seen this on the developer built of firefox aswell. Is this android marshmallow design? (If so, shame on you Google for coppying Ios)

**Comment by JasperWeiss** [comment]
Just wondering, even with PGP encryption.. Github doesn't seem like a place you'd want to store passwords, right?

**Comment by wongma7** [comment]
Website support is coming soon, there is a pull request #146 with a rough implementation.

No, there's no good reason to put your files up publicly. Plus, people will see what websites you have passwords for. Bitbucket and gitlab are popular alternatives for hosting a private repository

**Comment by rndstr** [comment]
> Just wondering, why is the status bar the same color as the navigation bar? I've seen this on the developer built of firefox aswell. Is this android marshmallow design?

It's not. [Material design says](https://www.google.com/design/spec/style/color.html#color-color-palette) the following

> Toolbars and larger color blocks should use the 500 color of the primary color of your app. The status bar should be the darker 700 tint of your primary color.

**Comment by JasperWeiss** [comment]
Any chance you could add keepass support for this? That's be really cool

**Comment by Diagoras** [comment]
One solution for public/insecure storage would be to encrypt the entire password store folder before pushing it to the remote/uploading it to Dropbox.

**Comment by JasperWeiss** [comment]
@Diagoras Each individual password is already encrypted using GPG/PGP

**Comment by polyzen** [comment]
Pressing copy to clipboard should restart the timer.

**Comment by Diagoras** [comment]
@JasperWeiss I assumed your comment about GitHub was a worry about leaking metadata - while the passwords are encrypted, an adversary could figure out which websites you have accounts for by checking the names of the *.gpg files. Or were you concerned about something else?

**Comment by JasperWeiss** [comment]
@Diagoras My concern was the fact that github doesn't allow a repository to be private (unless you pay) therefore anyone can look at my password repository and look at the list of accounts I have stored there.

**Comment by Diagoras** [comment]
@JasperWeiss My point exactly, something I believe can be mitigated by encrypting the files before push and decrypting after pull so that metadata is only available locally and not on Git. However, if desktop pass doesn't implement this functionality as well then it'll be difficult for the app to do so.

**Comment by JasperWeiss** [comment]
It might be noteworthy that KeePass does this, all passwords reside in 1 encrypted database file which can be stored on e.g dropbox, ftp, ssh etc. For android there is keepass2android.
Personally I feel more comfortable storing my passwords all in one AES 256 bit database on a private dropbox account than in seperate pgp encrypted files on a public github repo

**Comment by phryneas** [comment]
@JasperWeiss I opened a separate issue that have a solution for your problem. #165

**Comment by JasperWeiss** [comment]
@phryneas Great, Encrypting filenames is definitely something that needs to be worked on in my opinion.

**Comment by gregorlarson** [comment]
I put TOTP private keys in my password store also, however, it would be nice if the pwdstore app would support the TOTP algorithm so I could do multi-factor sign-in without a separate authenticator app like freeotp etc.

**Comment by gregorlarson** [comment]
The ability to fetch, merge, push with the desktop git password-store is important to me. Extra layers of encryption are ok, as long as it doesn't break inter-op with Linux pass.

**Comment by zeapo** [comment]
The repository of the v2 will be public soon, and I will move a lot of the issues there. We'll discuss the features that are really important, when and how we'll implement them.

Sorry for the delay, I'm quite busy IRL :)

**Comment by jwoudenberg** [comment]
I'm not sure if this is already planned, but it would be great if bittorrent sync support would also be added to the list of sync clients (dropbox, google drive).

Depending on what you have in mind for to implement this, that might already be a given of course :). Right now I have a bare git repo in my btsync directory and it would be great if I could get my database out of there.

**Comment by rbuzatu90** [comment]
I guess v2 will not come out anytime soon :(

**Comment by OffifialMITX** [comment]
Don't want to add any load, but I think that Nextcloud really should be included in the lists of upload possibilities.

**Comment by zeapo** [comment]
To be re-opened when we finish cleaning all v1 and start thinking about a v2.
