### ISSUE TITLE
[FEATURE] Alternative OTP configuration

### ISSUE THREAD

**Issue by Holzhaus** [zeapo/Android-Password-Store#1311]
Scanning QR codes to enable 2FA OTP is convenient when scanning your computer screen, but it's hard to scan a QR code with your phone if the code is displayed on the same phone. 

Gitlab 2FA also provides a text configuration:

> Can't scan the code?
> 
> To add the entry manually, provide the following details to the application on your phone.
> 
> Account: gitlab.com:user@example.com
> Key:  <key>
> Time based: Yes

It would be nice to add a way to add an OTP config using that data.

As an alternative where such information is not provided, it might be nice to allow selecting a screenshot from the gallery as QR code, but it should be noted that such a feature could pose a security risk if the user forgets to delete the screenshot afterwards.

**Comment by msfjarvis** [comment]
That's a fair request. I'll see what we can do.
