### ISSUE TITLE
[BUG] Repository import fails when the server HTTPS certificate is signed by a custom CA.

### ISSUE THREAD

**Issue by kalipka** [zeapo/Android-Password-Store#1318]
**Describe the bug**
I get the following error when importing my Pass repository from a private server through HTTPS:
`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found`

The server certificate is signed by my own Certification Authority. The CA certificate is properly installed on my device. I don't know the application but it seems like the application does not use the system certificate store (perhaps because the underlying Git library does not). Other applications I use daily appear to be using the system certificate store without any issue.

Is there anyway to circumvent it (apart from moving to SSH)? If not, can I expect to see this corrected in a near future?

Thanks for this great app by the way ;)

**To Reproduce**
1. Go to 'Settings'
2. Set up a Git repository pointing to a Git repository accessible through HTTPS and using a custom CA.
3. Go back to the main activity.
4. Open the menu and click 'Import from server'.
5. See the error.

**Expected behavior**
Repository import succeeds.

**Device information (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: GrapheneOS
 - App version: 1.13.2

**Comment by fmeum** [comment]
@kalipka According to https://developer.android.com/training/articles/security-ssl#CommonProblems, the error you are seeing should only occur if the CA is *not* included in the system store. 

Are you sure that the CA certificate is properly installed on your device? If so, can you give an example of an open-source app that successfully connects to your server?

**Comment by kalipka** [comment]
@fmeum

Yes, the CA certificate is installed on my device, in the _user_ certificate store.

I use Vanadium (a hardened version of Chromium) but since it's a system application provided by GrapheneOS this might not be a good candidate.

I'm also using [DAVx⁵](https://www.davx5.com/), for synchronizing calendars and contacts. The source code is available here: [https://gitlab.com/bitfireAT/davx5-ose](https://gitlab.com/bitfireAT/davx5-ose). I haven't dived into it yet but the application _seems_ to work with my certificate.

I am going to test with other apps and I will let you know of the results

**Comment by fmeum** [comment]
DAVx is using a custom `TrustManager`, which might be a lead: https://gitlab.com/bitfireAT/davx5-ose/-/blob/dev-3.x-ose/app/src/main/java/at/bitfire/davdroid/HttpClient.kt

**Comment by kalipka** [comment]
I ended up testing with a small application doing basically:
```
URLConnection urlConnection = url.openConnection();
InputStream in = urlConnection.getInputStream();
```
Same error as with Password Store, which makes me think of the user certificate store as being pointless since extra work is required for user applications to establish a simple HTTPS connection with a server not certified by a public CA...

**Comment by mannp** [comment]
I am getting the same error trying to use my own ca cert.

Successfully connected with gitea and bitwarden android apps to name a couple.

**Comment by msfjarvis** [comment]
Bitwarden is written with Xamarin in C# so that is useless to us, and I cannot find any mention of an official Gitea app to reference.

**Comment by mannp** [comment]
https://codeberg.org/gitnex/GitNex/issues/316

**Comment by msfjarvis** [comment]
> https://codeberg.org/gitnex/GitNex/issues/316

No resolution happened in this linked issue, it was closed by a PR which added caching to their image loading implementation.

**Comment by giuliano108** [comment]
Just to confirm the same behaviour on Android 12. I've installed the self signed CA cert, Chrome can access the HTTPS server (Caddy) without security prompts, APS gives the `Trust anchor for certification path not found`.

#1454 would make this use case (git server located on the local network) so much simpler... As a workaround you can install Termux via f-droid, at which point you can use git from the command line.

**Comment by msfjarvis** [comment]
> Just to confirm the same behaviour on Android 12. I've installed the self signed CA cert, Chrome can access the HTTPS server (Caddy) without security prompts, APS gives the `Trust anchor for certification path not found`.
> 
> #1454 would make this use case (git server located on the local network) so much simpler... As a workaround you can install Termux via f-droid, at which point you can use git from the command line.
> 

I don't see how unencrypted access makes any of this easier. You can just as easily use an SSH key which I've personally done for years and get the same benefits.

**Comment by giuliano108** [comment]
> I don't see how unencrypted access makes any of this easier. You can just as easily use an SSH key which I've personally done for years and get the same benefits.

Because there's no setup: you just run `git daemon ...` on the server machine and you're good to go (no SSH keys to create/install, no SSL certs to generate or web servers to configure). Once APS is done pulling the repo, the daemon can be stopped. I find this preferable than giving my phone SSH access to my laptop but hey, that's a personal preference and a matter of convenience, not taking security into account. I'd only use `git://` on a local/trusted network, even though the contents of the repo are encrypted I wouldn't feel comfortable giving away `git log` information  to a potential snooper. 
HTTPS at least is definitely more complicated and until this issue is solved/worked around, not viable with self-signed certs.

Hope my comment didn't come across as argumentative, I use and I like APS, thank you and the other maintainers for it!

**Comment by msfjarvis** [comment]
> > I don't see how unencrypted access makes any of this easier. You can just as easily use an SSH key which I've personally done for years and get the same benefits.
> 
> Because there's no setup: you just run `git daemon ...` on the server machine and you're good to go (no SSH keys to create/install, no SSL certs to generate or web servers to configure). Once APS is done pulling the repo, the daemon can be stopped. I find this preferable than giving my phone SSH access to my laptop but hey, that's a personal preference and a matter of convenience, not taking security into account. I'd only use `git://` on a local/trusted network, even though the contents of the repo are encrypted I wouldn't feel comfortable giving away `git log` information to a potential snooper. HTTPS at least is definitely more complicated and until this issue is solved/worked around, not viable with self-signed certs.
> 
> Hope my comment didn't come across as argumentative, I use and I like APS, thank you and the other maintainers for it!

Oh no you're completely fine, I only asked because I wanted to see if there's any legitimate use cases for the plaintext git protocol that we overlooked.

**Comment by msfjarvis** [comment]
With https://github.com/android-password-store/Android-Password-Store/commit/f7766bc67aa3aa808bd40fac13dcdae5126017ed it should be possible to connect to servers that are behind self-signed certs but I'm not confident about the security implications of this change.

**Comment by msfjarvis** [comment]
Closing as part of [issue tracker cleanup](https://github.com/android-password-store/Android-Password-Store/discussions/1836).
