### ISSUE TITLE
Loop when using Fill with Yubikey

### ISSUE THREAD

**Issue by thundernode** [zeapo/Android-Password-Store#132]
![image](https://j.gifs.com/yXoQV8.gif)
Not sure if this gif will work, but basically when trying to use the password fill function with a yubikey it keeps looping around back to asking for the yubikey and never fills the password.  Works fine when not using a yubikey.
Tested with:
3.5.1 Openkeychain (also 3.5 and 3.4.1)
1.2.0.32 Password Store version

**Comment by wongma7** [comment]
Thanks for report. Fixed this in latest master #128 but didn't push out new version to fdroid. Will do so tonight!!

**Comment by wongma7** [comment]
New version is out on fdroid, sorry for the delay. If any other issues, please report

**Comment by thundernode** [comment]
Everything works perfectly now, thank you.
