### ISSUE TITLE
[BUG] Does not show any passwords from SD card

### ISSUE THREAD

**Issue by buzz** [zeapo/Android-Password-Store#1326]
**Describe the bug**

Can't open configured password repository, only shows "Password Store" and "Let's Go" button.

**To Reproduce**
1. Have a password store folder on your SD card.
2. Open app, click on "Let's go" -> "Create local repo" (the doc says "Use local directory" but this option doesn't exist, so it might be the doc is wrong)
3. Select "SD-Card" -> Select password store folder (that's the folder with all the *.gpg files in it)

**Expected behavior**
It should show available passwords and let me decrypt and read them or at least give *some* user feedback on what is going on.

**Device information (please complete the following information):**
 - Device: Xiaomi Redmi 5A
 - OS: Android version 11
 - App version 1.13.2

**Additional context**
Actually I want to sync this folder using the Nextcloud app. But this might be irrelevant because to the APS app it's just some folder with GPG files in it.

The app asked for permissions to read the file system which I granted. I have the correct GPG key added using OpenKeyChain and I opened OpenKeyChain to add APS to the list of allowed apps.

I used the Issues to look for a similar behavior but could not find anything related. Also, there's no (up-to-date?) documentation which shows correct usage.

I also tried setting up things as explained here: [Setting up Password Store to sync with a local computer](https://github.com/android-password-store/Android-Password-Store/wiki/Setting-up-Password-Store-to-sync-with-a-local-computer) btw. This page should be removed or revised. It's not clear at all what should be achieved there.

**Update**
I was able to open a local password folder by opening a folder from the internal memory instead of using the SD card.

**Comment by msfjarvis** [comment]
Android has extremely poor removable storage support so there isn't a lot we can do on our end at this stage. We have a longer term goal of reimplementing how we interact with storage and will probably attempt to improve on this aspect if there any options available to do so.

Edit: that being said we are also in the progress of rewriting our documentation and will ensure it matches the app's actual flow much more accurately.
