### ISSUE TITLE
[BUG] No autofill on 7-eleven log in, but on reset password textbox

### ISSUE THREAD

**Issue by stephen304** [zeapo/Android-Password-Store#1336]
**Describe the bug**
In the 7-Eleven app, autofill doesn't show up on the login screen, but it does show up on the reset password screen.

**To Reproduce**
Download 7-Eleven app
Go to login with username / password
Tap username field

**Expected behavior**
Autofill should show up

**Screenshots**
![image](https://user-images.githubusercontent.com/981915/109719293-75f0ba00-7b76-11eb-87ab-b650d1ccfd3b.png)
![image](https://user-images.githubusercontent.com/981915/109719309-7b4e0480-7b76-11eb-91df-3257b2804ce7.png)

**Device information (please complete the following information):**
 - Device: Google Pixel 2
 - OS: stock ROM Android version 11
 - App version 1.13.2

**Comment by msfjarvis** [comment]
If Autofill works on one screen and not the other that most likely means 7-Eleven either uses incorrect autofill hints or just disables autofill outright on those fields. I'll investigate once I have some more time, but the chances of us being able to fix it on our end are slim to none in the abovementioned scenarios.

**Comment by fmeum** [comment]
I just tried out the app with debug logging enabled. When tapping into any of the login form fields, I don't see an Autofill request at all, which hints at them doing something weird.

@stephen304 However, I am able to long-tap on the password field and then select the Autofill action manually, which leads to a successful fill. Does that work for you? This workaround applies to many apps.

**Comment by stephen304** [comment]
@fmeum Ah I didn't realize that was a thing. I'm used to struggling a ton with LastPass autofill. That's a pretty easy workaround.

**Comment by msfjarvis** [comment]
Since it's an app bug and our workaround does it's job I'm going to close this issue.
