### ISSUE TITLE
[BUG] Autofill in latest Chrome/Chromium still not working

### ISSUE THREAD

**Issue by Pantamis** [zeapo/Android-Password-Store#1339]
**Describe the bug**
I can't make AutoFill work in latest Chrome (89.0.4389.72)/Chromium browser. The Autofill pop up never appears for Chrome or Brave browser while it works with any Firefox based browser.

**To Reproduce**
1. Set APS as Autofill app in Android
2. Update Chrome to the latest version
3. Open a login page like github.com/login and select a password field
4. Nothing happens (it only shows the keyboard as usual)

**Expected behavior**
The Autofill pop up should appear, like it does in Firefox on the same phone, with the same APS settings.

**Screenshots**

**Device information (please complete the following information):**
 - Device: Samsung J7 (2016)
 - OS: Android 8.1.0 (SM-J710F Build/M1AJQ)
 - App version 1.13.2 (latest on Play store)

**Additional context**
I know this is a long standing issue with Chrome and I followed a lot the work of @fmeum to solve the issue of Chrome implementation of Autofill (and big thanks for the incredible work on AutoFill in general). I am quite sad to see that all his effort do not show good result on my smartphone (I waited so long for the best password management UX with AutoFill and U2F 2FA on Android, which is only possible with Chrome ffs). I saw other people succeded to make it work, I really don't understand what I am doing wrong...

Thanks for the help, I still hope Autofill will work completely one day...

**Comment by fmeum** [comment]
While Android supports Autofill as of Oreo (8), this only applies to apps that use native UI elements or have explicit support for Autofill (like Firefox).
Support for web browsers and their highly custom views is only provided via an accessibility-based compatibility layer that has been added with Pie (9).

Your main option is thus to update to a more recent version of Android. There's also [ongoing work](https://chromium.googlesource.com/chromium/src/+/master/weblayer/shell/) to make Chrome interact directly with the Autofill APIs, but I haven't seen any statements about when this will be ready.

**Comment by Pantamis** [comment]
Thank you for your reply, I understand now !

Sadly my phone is quite old and I don't think it will receive update to get Android 9... I will see if it is possible to install custom OS on it.

Otherwise => time for a new smartphone !


It could be nice to add information about this minimum required Android version somewhere in the app when we activate Autofill.

Thanks again for all the work you have done for Autofill to work !

(Closing the issue because there is nothing to do from APS side.)
