### ISSUE TITLE
Support ed255519 SSH keys

### ISSUE THREAD

**Issue by Celti** [zeapo/Android-Password-Store#134]
The app does not appear to support anything except RSA keys for cloning (ECDSA and ED25519 do not work, haven't tried DSA) and also do not support the new OpenSSH private key format (for higher key security, important on a mobile device).

**Comment by wongma7** [comment]
What happens when you attempt clone? Blank ui or an error?

**Comment by wongma7** [comment]
The app is limited in what it can support by the jsch library it uses. Now, jsch should support ecdsa at least so I don't know why it doesn't work. I will test it myself when I get a chance

**Comment by Celti** [comment]
Sorry about the delay in responding; I got an error with an earlier version of the app; with the latest version I get blank UI.

**Comment by Celti** [comment]
Some poking about indicates the problem is solely a lack of support for the new (bcrypt-based and much more secure) OpenSSH private key format instead of the older PEM format. ED25519 keys do not support the old PEM format at all, and all other keys *may* be encoded in either format.

**Comment by zeapo** [comment]
This is a jsch issue, jgit uses an old version, (even the new version of jsch does not support ED25519 AFAIK).

**Comment by zeapo** [comment]
@Celti Can you check in [jsch#setConfig](http://epaul.github.io/jsch-documentation/javadoc/com/jcraft/jsch/JSch.html#setConfig(java.lang.String, java.lang.String)) which algorithms should be enabled? Thanks.

**Comment by Celti** [comment]
It looks like jsch (according to those docs) doesn't have support for the new key format, only OpenSSL and PKCS#8. I guess I'll file a feature request upstream against jsch, then.

**Comment by dllud** [comment]
+1

When using an ed25519 key I get:

    W/System.err(15936): com.jcraft.jsch.JSchException: invalid privatekey: [B@41c1bbb0
    W/System.err(15936): 	at com.jcraft.jsch.KeyPair.load(KeyPair.java:664)
    W/System.err(15936): 	at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
    W/System.err(15936): 	at com.jcraft.jsch.KeyPair.load(KeyPair.java:532)
    W/System.err(15936): 	at com.zeapo.pwdstore.git.GitOperation.executeAfterAuthentication(GitOperation.java:139)
    W/System.err(15936): 	at com.zeapo.pwdstore.git.GitActivity.syncRepository(GitActivity.java:581)
    W/System.err(15936): 	at com.zeapo.pwdstore.git.GitActivity.onCreate(GitActivity.java:261)
    W/System.err(15936): 	at android.app.Activity.performCreate(Activity.java:5104)
    W/System.err(15936): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
    W/System.err(15936): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2262)
    W/System.err(15936): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358)
    W/System.err(15936): 	at android.app.ActivityThread.access$600(ActivityThread.java:153)
    W/System.err(15936): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
    W/System.err(15936): 	at android.os.Handler.dispatchMessage(Handler.java:99)
    W/System.err(15936): 	at android.os.Looper.loop(Looper.java:137)
    W/System.err(15936): 	at android.app.ActivityThread.main(ActivityThread.java:5227)
    W/System.err(15936): 	at java.lang.reflect.Method.invokeNative(Native Method)
    W/System.err(15936): 	at java.lang.reflect.Method.invoke(Method.java:511)
    W/System.err(15936): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
    W/System.err(15936): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
    W/System.err(15936): 	at dalvik.system.NativeStart.main(Native Method)

@Celti Have you opened the feature request with jsch?

**Comment by Celti** [comment]
I kinda just gave up on it after being unable to find a bugtracker for jsch, sorry.

**Comment by dllud** [comment]
Their bugtracker is on SourceForge: [JSch tickets](https://sourceforge.net/p/jsch/_list/tickets).

I've opened a new feature request: [Add support for Ed25519 keys and bcrypt KDF format](https://sourceforge.net/p/jsch/feature-requests/7/).

There are other tickets already opened which are related:
[Add support for ecdsa-sha2-nistp256 host keys](https://sourceforge.net/p/jsch/feature-requests/5/)
[Enable DH-SHA2 key exchange](http://sourceforge.net/p/jsch/patches/7/)

**Comment by flussence** [comment]
It looks like JSch upstream isn't completely dead yet, ecdsa was added [2 months ago](http://www.jcraft.com/jsch/ChangeLog) and their latest release is last week. I'm not convinced they ever read their own SF project tracker though.

Are there any alternatives to that one library? My phone *does* have non-ancient openssh/sshd binaries in `$PATH` (thanks CM) but I have no idea if regular apps besides the terminal can even use those.

**Comment by dasJ** [comment]
Maybe someone could try what's explained in the comments [here](https://stackoverflow.com/questions/47075187/jsch-support-for-ed25519-keys).

**Comment by zidhuss** [comment]
Related to #448.

**Comment by themightyoarfish** [comment]
Is this addressed these days? I can not import ecdsa keys into the app.

**Comment by msfjarvis** [comment]
Please file new issues rather than commenting on 5 year old ones.
