### ISSUE TITLE
[BUG] .gpg-id created by Android Password Store is rejected by pass v1.7.3

### ISSUE THREAD

**Issue by amberin** [zeapo/Android-Password-Store#1343]
**Describe the bug**
I was experiencing bug #998, and I followed this workaround: https://github.com/android-password-store/Android-Password-Store/issues/1277#issuecomment-759265495.

The new .gpg-id file created by Android Password Store works well for creating new passwords in the app, but not for creating new passwords using pass (v1.7.3) and gnupg2 (v2.2.20) on my laptop.

Pass says:
`gpg: no valid addressees`
`gpg: /dev/shm/pass.wr7YR2EMG5xSx/tf9B1Q-folder-domain.com.txt: encryption failed: No user ID`

I will try to use an email as ID instead, but I wanted to notify you about this.

**To Reproduce**
1. Delete the .gpg-id file from the Password Store repo.
2. Create a new password using the Android Password Store.
3. Sync repo.
4. Create a new password using pass 1.7.3 on a computer.

**Expected behavior**
The GPG key ID written by Android Password Store should be understood by pass on the computer.

**Screenshots**
N/A

**Device information (please complete the following information):**
 - Device: Sony Xperia 10 ii
 - OS: stock ROM Android version 11.0
 - App version: 1.13.3
 - Desktop programs: gnupg2-2.2.20-2.fc32.x86_64, pass-1.7.3-5.fc32.noarch

**Additional context**
N/A

**Comment by msfjarvis** [comment]
I tried to reproduce your issue by deleting my `.gpg-id` file and having APS recreate it but I'm not having any luck.

My pass and GPG versions

```
~ ➜ gpg --version
gpg (GnuPG) 2.2.27
libgcrypt 1.9.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/msfjarvis/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
~ ➜ pass --version
============================================
= pass: the standard unix password manager =
=                                          =
=                  v1.7.3                  =
=                                          =
=             Jason A. Donenfeld           =
=               Jason@zx2c4.com            =
=                                          =
=      http://www.passwordstore.org/       =
============================================
```

My store's Git history

```
~ ➜ pass git log --oneline | head -n3
e0606ba478d2 Add generated password for test using Android Password Store.
951eda3bae4f Initialize GPG IDs in .gpg-id.
32817b6be053 Remove .gpg-id from store.
```

What APS put into my `.gpg-id`

```
~ ➜ cat $PASSWORD_STORE_DIR/.gpg-id
0xb7843f823355e9b9
```

keyserver.ubuntu.com's result for that fingerprint: [link](https://keyserver.ubuntu.com/pks/lookup?search=0xB7843F823355E9B9&fingerprint=on&op=index)

GPG's successful lookup of my key from that fingerprint

```
~ ➜ gpg --list-key 0xb7843f823355e9b9
pub   rsa4096/0xB7843F823355E9B9 2020-02-07 [SC]
      Key fingerprint = 8F87 050B 0F9C B841 1515  7399 B784 3F82 3355 E9B9
uid                   [ultimate] Harsh Shandilya (msfjarvis) <me@msfjarvis.dev>
sub   rsa4096/0x3115CE1787078171 2020-02-07 [E]
sub   rsa4096/0x1D59AB72E3DB2CE5 2020-03-02 [A]
sub   rsa4096/0x366D7BBAD1031E80 2020-03-02 [SE]
```

And `pass test` correctly shows me the decrypted contents of the file `$PASSWORD_STORE_DIR/test.gpg`.

Fingerprints are probably the _most_ portable format of keys in the PGP ecosystem, so I am perplexed as to how your specific GPG installation fails to handle it.

**Comment by amberin** [comment]
Decrypting files was never a problem, only encrypting new files.

It turned out that the .gpg-id file created by APS did not contain a newline at the end:

```
[victor@tinkpad ~]$ cat .password-store/.gpg-id
0xb3a99eaa1fd79131[victor@tinkpad ~]$ 
```

When I added one, pass accepted the ID, and I could encrypt files again.

**Comment by msfjarvis** [comment]
Didn't expect that'd be a problem... Thanks, I'll push a fix .
