### ISSUE TITLE
allow user to view notes before closing password file

### ISSUE THREAD

**Issue by travisfw** [zeapo/Android-Password-Store#135]
I decrypt a password and the password is copied into my clipboard and the file immediately closed. I wrote a note in the file which I should be able to view. Disabling the option to copy the password in the settings changes the behavior to copy "MyPasswordIsDaBest!". This is useless. Nothing should be copied, and I should be able to view the file.

**Comment by travisfw** [comment]
Submitted before done due to a glitch.
"MyPasswordIsDaBest!" is copied into the clipboard. This is useless. Nothing should be copied, and I should be able to view the file.

**Comment by wongma7** [comment]
Can you list all your 'General' settings? Password show time, Show the password, and Automatically copy password

**Comment by travisfw** [comment]
Password Show Time: 0
Show the password: checked
Automatically Copy Password unchecked

So it's password show time, right? I can view the file if I set that higher. How do I disable that feature entirely? I can't seem to enter -1...

**Comment by wongma7** [comment]
Yes, i see you want it to be indefinite so you can exit when you want to. I agree 0 or -1 could mean indefinite and if a user wants the password to show for 0 seconds/not at all they could uncheck 'show password.' I'll work on this and in the meantime you may set the show time to an arbitrarily high value.

I will also look into the app clearing the clipboard with 'mypasswordisdabest' unnecessarily

**Comment by wongma7** [comment]
hope this is okay; should probably document this somewhere!
