### ISSUE TITLE
[BUG] Timeouts on open with large GIT respository

### ISSUE THREAD

**Issue by hcbraun** [zeapo/Android-Password-Store#1352]
**Describe the bug**
The app seems to do a GIT operation when opening a directory or file. With a large and unoptimized GIT repository opening anything takes 20+ seconds and causes a "the app is none responsive popup"

**To Reproduce**
1. Use a GIT repository with 10,000+ files in .git/
2. Click on a directory or file
3. Get the timeout

**Expected behavior**
No GIT operation at all when browsing / opening

**Comment by msfjarvis** [comment]
I scripted the creation of over 15K files in a password repository [here](https://github.com/android-password-store/pass-test/commits/large-repo) and cannot observe any lag let alone ANR. Can you provide any more information about your setup that could help diagnose this?

**Comment by hcbraun** [comment]
Hi Harsh,

the repository is stored on the external storage media. Syncing is done via other / 3rd party software and not with GIT / password-store. 

GIT stats for the repository:

Report Period: 2015-08-20 10:48:38 to 2021-03-22 13:24:18
Age: 2042 days, 232 active days (11.36%)
Total Files:    316
Total Lines of Code:    50 (66 added, 16 removed)
Total Commits:    884 (average 3.8 commits per active day, 0.4 per all days)
Total files:    316
Total lines:    50
Average file size:    620.40 bytes

A new GPG key Id was set a couple of times.

**Comment by msfjarvis** [comment]
Nothing there seems out of the ordinary, aside from the potential that your storage media is *just* slow enough for the directory listing to time out the main thread. I'll try to replicate it in an emulator, thanks for getting back.

**Comment by dschrempf** [comment]
FYI: I also had big timeouts. Funnily enough, they mostly happened when clicking on an entry, which should be fast. Anyways, git garbage collection helped to get rid of the lags.
