### ISSUE TITLE
[FEATURE] Support ChromeOS

### ISSUE THREAD

**Issue by drewrisinger** [zeapo/Android-Password-Store#1361]
**Describe the bug**
The application is not available on the Play Store for Chrome OS.

**To Reproduce**
1. From a Chromebook, go to the Play Store & search for "Password Store"
2. See error message "Password Store by ... is not available for Chromebooks"

**Expected behavior**
There are no native Chromebook Password Store applications, though I thought this app could be a good candidate because of the native ChromeOS support for Android apps. It seems that this app would be relatively straightforward to switchover to ChromeOS, because I don't think that this requires many hardware-specific features.

**Screenshots**
From web browser, not on the ChromeOS device:
![Screenshot 2021-03-28 171228](https://user-images.githubusercontent.com/10198051/112768218-f2957d80-8fe8-11eb-95ed-2f7d82f0d0f1.png)

**Device information (please complete the following information):**
 - Device: HP Chromebook
 - OS: ChromeOS 89.0.4389.95
 - App version: Latest (not installed)

**Additional context**
Lack of ANY native ChromeOS app for PasswordStore seems like an oversight, and one that could be easily resolved by enabling this Android-Password-Store app for ChromeOS. Lack of any ChromeOS app stymied me on deploying PasswordStore, because a user-friendly non-Linux CLI app on ChromeOS is needed for less-technical people that I support.

It looks like the main thing missing for ChromeOS support is a line in the manifest saying that touchscreen is not required? https://developer.android.com/topic/arc
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          ... >
    <!-- Some Chromebooks don't support touch. Although not essential,
         it's a good idea to explicitly include this declaration. -->
    <uses-feature android:name="android.hardware.touchscreen"
                  android:required="false" />
</manifest>
```

**Comment by msfjarvis** [comment]
Can you install the apps manually to check if they actually work? I don't have ChromeOS devices to test this myself. OpenKeychain can be installed from [here](https://f-droid.org/repo/org.sufficientlysecure.keychain_56200.apk), and APS from [here](https://f-droid.org/repo/dev.msfjarvis.aps_11340.apk).

**Comment by msfjarvis** [comment]
No response from reporter for over a week, closing until they reply.

**Comment by liljenstolpe** [comment]
On chromeos, you need to change the Android sub-system to use the 'user' linux container vs. the hidden android container.  While doable, it does mean your android system disappears whenever you burn down your user linux container.  Are you asking for the APS install to test it, or if the sideload is a viable option for end-users?  If the former, I can, if the later, the answer is probably not.

**Comment by msfjarvis** [comment]
> On chromeos, you need to change the Android sub-system to use the 'user' linux container vs. the hidden android container. While doable, it does mean your android system disappears whenever you burn down your user linux container. Are you asking for the APS install to test it, or if the sideload is a viable option for end-users? If the former, I can, if the later, the answer is probably not.

I asked to attempt sideloading it because Play Store not marking the app as compatible relies on declaring certain features in the application manifest which I ended up doing myself anyway in #1375.

**Comment by liljenstolpe** [comment]
So do you want me to test that side-load?  If it's already in, I'm still not able to install via the playstore as of 2 hours ago.

**Comment by msfjarvis** [comment]
> So do you want me to test that side-load? If it's already in, I'm still not able to install via the playstore as of 2 hours ago.

You can test it out, Play Store still shows the app as incompatible because the fix was never released to the Play Store.

**Comment by liljenstolpe** [comment]
Ok - just sent the chromebook back - other problems with it.  Will do a test as soon as I get a replacement.

**Comment by nexus-uw** [comment]
is it possible to re-open this issue? 

it would be great to be able to use pass on chromeos without having to install the linux container

**Comment by msfjarvis** [comment]
> is it possible to re-open this issue?

No, you should file a new issue with details on the side loading test I asked the original issue author to do.
