### ISSUE TITLE
[BUG] No Autofill on Firefox or Chrome

### ISSUE THREAD

**Issue by morciej** [zeapo/Android-Password-Store#1369]
**Bug description**
Neither Chrome nor Firefox display prompt or anything else to fill out username or password. The only way the app works is by copy from Password Store, and paste into fields, manually.

**To Reproduce**
1. Set up autofill in Password Store, and disable autofill in Firefox (or Chrome)
2. Open Password Store and make sure the password is there and stored in correct folder.
3. Go back to Firefox and open a page with known-to-work login. Tap on username or password.
4. Error: Firefox shows prompt on the bottom of the screen suggesting passwords from its own store.

**Expected behavior**
Some kind of prompt shows up from Password Store to enable filling the password from it.

**Workaround**
Copy and paste.

**Device information (please complete the following information):**
 - Device: Samsung Galaxy S8 SM-G950W
 - OS: Android 8.0.0
 - App version 1.13.4 and Firefox 87.0.0

**Additional information**

F.Y.I. Keepass solved it by 1. own keyboard (cringe), 2. Helper app not on Google App Store (great!)

**Comment by fmeum** [comment]
Autofill in most browsers is only supported with Android 9. You could give Firefox Focus a try, which comes with native Autofill support suitable for Android 8.

**Comment by msfjarvis** [comment]
We should probably add this information to the Autofill information dialog itself.

**Comment by morciej** [comment]
Good to know. It's OK. Jumping between these screens, while not fancy, is entirely practical. These are the joys of hand-me-down hardware. ;-)

**Comment by morciej** [comment]
Confirmed: after upgrading from Oreo to Pie, the prompt to fill password from Password-store does appear. Thanks Fabian @fmeum
