### ISSUE TITLE
Show autofill popup on all passowrd fields.

### ISSUE THREAD

**Issue by kevincox** [zeapo/Android-Password-Store#139]
It would be nice if the autofill popup was shown on all password fields regardless of whether a match could be found. This is because if I am in a password field the answer is almost certainly in my password vault so it should give me an option to select which one I want to use. It would be awesome if after selecting what password to use I could select "Add this as a pairing" or "Ask me every time" so that depending on the app I could select each time or save that association.

**Comment by wongma7** [comment]
Good suggestions. I will add an 'Ask me every time' option for always showing the autofill popup for all apps. Useful for setting up associations for the first time in an app. I am not sure if it should be the default setting though. (side note, the auto match is not too good to begin with and could be improved...)

As for being asked for which password to use...right now in the popup if you want to use a different password you have to tap Settings -> Match with... -> then find the other password -> OK -> then go back to the original app and fill the field. A better solution could be maybe a spinner of your saved associations in the popup, not sure if that's possible.

**Comment by kevincox** [comment]
That sounds great. Setting up the associations is exactly what my use case is. Going back and forth between the two apps to do it isn't ideal.

Better auto-matching is always welcome but there are a bunch of cases where I wouldn't expect auto-matching to work no matter how intelligent. For example logging into the "Hearthstone" app requires the credentials for "battle.net" in my password store. Another example is apps that use "Facebook Connect" login in an in-app browser. The app can be anything but I want to use my "facebook.com" password.

Thanks for looking into this and if you need a beta tester I would be pleased to help you out.

**Comment by Nis2** [comment]
This is the way to go as it would also allow filling password for web sites. AFAIK you can't right now because doing so would associate a password with the chrome app instead of the url.

**Comment by kevincox** [comment]
As @nis2 said this would also fix https://github.com/zeapo/Android-Password-Store/issues/144

**Comment by wongma7** [comment]
#146 is pretty much done, I am just doing some basic testing for a couple days then I suppose I should get it released for you guys to test
