### ISSUE TITLE
[BUG] Unable to sync/push/pull when server is using Fish shell

### ISSUE THREAD

**Issue by adamrutter** [zeapo/Android-Password-Store#1390]
**Describe the bug**
I'm unable to sync/push/pull my repo when the Git server is using Fish as the login shell. I _am_ able to sync/push/pull when bash is set as the login shell on the server.

**To Reproduce**
1. `chsh -s /usr/bin/fish` (or whatever path Fish is installed to) on the server
2. Perform any git operation (including the utilities in `Settings/Git configuration`) on the Android app
3. See error `**An error occured during a Git operation** Invalid packet line header: ]4;`

**Expected behavior**
To be able to perform Git operations the same as when bash is set as the login shell on the server.

**Device information**
 - Device: Google Pixel 3
 - OS: stock Android 11
 - App version: 1.13.4 (also occurs on 1.3.3 downloaded from F-Droid)

**Additional context**
Steps to workaround:
1. `chsh -s /bin/bash` on the server
2. Sync/push/pull on the app as usual

Skimming through this [report on bugs.eclipse.org](https://bugs.eclipse.org/bugs/show_bug.cgi?id=416504) led me to deduce it was the login shell causing the problem.

**Comment by msfjarvis** [comment]
This is quite interesting. I'm trying to backport changes to the `PacketLineIn` class where this exception is coming from, assuming it has been fixed in `master`. Will find out soon enough I guess.

**Comment by msfjarvis** [comment]
Nevermind the backporting, I was unable to reproduce this at all :/

I created a new user on my desktop PC, changed its login shell to fish, and created a password repository with fake data and it worked just fine for cloning.

What fish version are you on? Maybe that makes a difference :shrug:

**Comment by adamrutter** [comment]
I've just tried creating/cloning a new repo myself, and the behaviour is the same as before.

I'm on version 3.1.2-1ubuntu1.

**Comment by msfjarvis** [comment]
The exception is thrown [here](https://github.com/eclipse/jgit/blob/720adcebb5b880665aef6a5b0d22a58b33bff4d6/org.eclipse.jgit/src/org/eclipse/jgit/transport/PacketLineIn.java#L190). Attaching a debugger at line 188 for both Bash and Fish login shells does not change the contents of the `lineBuffer` field, so I'm even more perplexed as to how things differ for you 😕

**Comment by adamrutter** [comment]
Yeah, it's an odd one... Although I think it's clear the problem is on my end, you can't reproduce it and someone _must_ have used the app with Fish before, and seemingly hasn't had this issue.

I have a workaround that I can live with, so feel free to close this if you don't think there's any fix to apply to the app.

**Comment by adamrutter** [comment]
I've worked it out, it's a line in my `config.fish` causing the error.

Specifically, it doesn't like tilde expansion. Changing `~` to `/home/adam` resolves the issue, and the app behaves as expected.

Thanks for your help!

**Comment by msfjarvis** [comment]
> I've worked it out, it's a line in my `config.fish` causing the error.
> 
> Specifically, it doesn't like tilde expansion. Changing `~` to `/home/adam` resolves the issue, and the app behaves as expected.
> 
> Thanks for your help!

That's rather peculiar, thanks for letting me know!
