### ISSUE TITLE
[BUG] Remote clone with ssh password method fail

### ISSUE THREAD

**Issue by estiloinfo** [zeapo/Android-Password-Store#1395]
**Describe the bug**
I cant initialize ssh remote repo with password method

**To Reproduce**
Open new installation app  (V 1.13.4)

1. Click on "Let's go"
2. Click on "CLONE REMOTE REPO"
3. On Repository URL:  "username@domain:repo"
4. On Branch: master  
5. Click on Auth mode: PASSWORD
6. Click: CLONE
7. On Authenticate put the password  (and verify) 
8. Click: OK
9. Pop up error box with message:  An error occurred during a Git operation -  Exhausted available authentication methods
10. Click: OK  an return to server config screen

Extra info:
11. In server side cant view established connection (openssh 8.5)

**Expected behavior**
Connect to server whit password auth

Authentication with SSH KEYS works fine.

**Device information (please complete the following information):**
 - Device: Motorola Edge plus
 - OS: Stock ROM Android version 11
 - App version :  1.13.4

**Comment by msfjarvis** [comment]
What is the value of `AuthenticationMethods` from `/etc/ssh/sshd_config` on the host you're trying to connect to? Can you send the URL you entered into the app (with domain redacted if necessary).

**Comment by estiloinfo** [comment]
Hi, the domain is oficina.estilo.ar

APP URL: ***@***.***:repo

Same URL with asymetric auth works fine.

(if you try some times server banned you IP)

This is auth enabled method from server side

=== cipher ===
3des-cbc
aes128-cbc
aes192-cbc
aes256-cbc
aes128-ctr
aes192-ctr
aes256-ctr
***@***.***
***@***.***
***@***.***

=== cipher-auth ===
***@***.***
***@***.***
***@***.***

=== compression ===
none
***@***.***
zlib

=== kex ===
diffie-hellman-group1-sha1
diffie-hellman-group14-sha1
diffie-hellman-group14-sha256
diffie-hellman-group16-sha512
diffie-hellman-group18-sha512
diffie-hellman-group-exchange-sha1
diffie-hellman-group-exchange-sha256
ecdh-sha2-nistp256
ecdh-sha2-nistp384
ecdh-sha2-nistp521
curve25519-sha256
***@***.***
***@***.***

=== key ===
ssh-ed25519
***@***.***
***@***.***
***@***.***
ssh-rsa
ssh-dss
ecdsa-sha2-nistp256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp521
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***

=== key-cert ===
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***

=== key-plain ===
ssh-ed25519
***@***.***
ssh-rsa
ssh-dss
ecdsa-sha2-nistp256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp521
***@***.***

=== key-sig ===
ssh-ed25519
***@***.***
***@***.***
***@***.***
ssh-rsa
rsa-sha2-256
rsa-sha2-512
ssh-dss
ecdsa-sha2-nistp256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp521
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***

=== mac ===
hmac-sha1
hmac-sha1-96
hmac-sha2-256
hmac-sha2-512
hmac-md5
hmac-md5-96
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***

=== protocol-version ===
2

=== sig ===
ssh-ed25519
***@***.***
ssh-rsa
rsa-sha2-256
rsa-sha2-512
ssh-dss
ecdsa-sha2-nistp256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp521
***@***.***
***@***.***

Regards

Ricardo Brisighelli

**Comment by msfjarvis** [comment]
From what you're telling it seems like the server simply does not support password authentication, or you need a different password from what you're using.

**Comment by estiloinfo** [comment]
Server support password i pull some git repo via ssh-client with user 
and password

I assume you try connect and this is the log of ssh server

sshd[26078]: Unable to negotiate with 134.209.202.38 port 55738: no 
matching key exchange method found. Their offer: 
diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1

**Comment by estiloinfo** [comment]
This is de debug of connection fail

sshd[31164]: debug1: Set /proc/self/oom_score_adj to 0
sshd[31164]: debug1: rexec start in 5 out 5 newsock 5 pipe 10 sock 11
sshd[31164]: debug1: inetd sockets after dupping: 4, 4
sshd[31164]: Connection from 181.12.218.10 port 44824 on 192.168.100.200 port 22 rdomain ""
sshd[31164]: debug1: Local version string SSH-2.0-OpenSSH_8.5
sshd[31164]: debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
sshd[31164]: debug1: compat_banner: match: OpenSSH_8.2p1 Ubuntu-4ubuntu0.1 pat OpenSSH* compat 0x04000000
sshd[31164]: debug1: permanently_set_uid: 22/22 [preauth]
sshd[31164]: debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
sshd[31164]: debug1: SSH2_MSG_KEXINIT sent [preauth]
sshd[31164]: debug1: SSH2_MSG_KEXINIT received [preauth]
sshd[31164]: debug1: kex: algorithm: curve25519-sha256 [preauth]
sshd[31164]: debug1: kex: host key algorithm: ssh-ed25519 [preauth]
sshd[31164]: debug1: kex: client->server cipher: aes128-gcm@openssh.com MAC: <implicit> compression: none [preauth]
sshd[31164]: debug1: kex: server->client cipher: aes128-gcm@openssh.com MAC: <implicit> compression: none [preauth]
sshd[31164]: debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
sshd[31164]: debug1: SSH2_MSG_KEX_ECDH_INIT received [preauth]
sshd[31164]: debug1: rekey out after 4294967296 blocks [preauth]
sshd[31164]: debug1: SSH2_MSG_NEWKEYS sent [preauth]
sshd[31164]: debug1: Sending SSH2_MSG_EXT_INFO [preauth]
sshd[31164]: debug1: expecting SSH2_MSG_NEWKEYS [preauth]
sshd[31164]: debug1: SSH2_MSG_NEWKEYS received [preauth]
sshd[31164]: debug1: rekey in after 4294967296 blocks [preauth]
sshd[31164]: debug1: KEX done [preauth]
sshd[31164]: debug1: userauth-request for user xxxxxx service ssh-connection method password [preauth]
sshd[31164]: debug1: attempt 0 failures 0 [preauth]
sshd[31164]: debug1: PAM: initializing for "xxxxxx"
sshd[31164]: debug1: PAM: setting PAM_RHOST to "181.12.218.10"
sshd[31164]: debug1: PAM: setting PAM_TTY to "ssh"
sshd[31164]: fatal: Timeout before authentication for 181.12.218.10 port 44824

Password never comes

**Comment by msfjarvis** [comment]
Closing as part of [issue tracker cleanup](https://github.com/android-password-store/Android-Password-Store/discussions/1836).
