### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hammerheadlemon** [zeapo/Android-Password-Store#140]
Hi - I am trying **pass** on my Linux machines and pushing to a repo on my server. Want to be able to use this repo on Android and this app clearly looks like a great option, but I'm a little lost trying to set it up and I think the documentation could be a little clearer for those of us with little experience coming to it for the first time.

I have a remote repo I want to clone and have included the ssh protocol, server url, path and other settings in the "Edit git server settings" page. I have generated a new SSH keypair and placed the public key on the server, but from here I am a little confused.

When I choose **Clone Existing**, I presume this is where I can pull down my remote repo, but it asks me "Select where to create or clone your password repository - Internal or External". Clearly, I want to clone to internal (phone storage?, or does this refer to a SD card?), but when I do this I get a "Directory already exist" error. I opt to delete the existing directory, then I'm asked for my ssh key passphrase, then I get an "Internal exception occurred - Message from jgit: Attempt to get length of null array" error.

Whichever way I try, I end up with the same thing.

I'm clearly doing something wrong but I'm not finding much help with the documentation. The jgit error whilst useful for a developer debugging isn't user-friendly either.

Hoping there may be some help here? Really enthusiastic about the app and willing to put some time and effort into getting it to work.

**Comment by wongma7** [comment]
It doesn't sound like you're doing anything wrong and it could just be a bug. Here https://github.com/zeapo/Android-Password-Store/issues/94 there are others who get the same error message, and I don't know why it happens (yet). There are plenty of places for jgit to return exceptions so it's difficult to translate them into stuff that makes sense. How did you generate the keypair i.e. the command you used? Does cloning work if you use a (throwaway) keypair generated by the app?

"Internal" and "external" storage are terms used by Android and basically Internal means your files will be stored in the app's data folder that nobody but the app should be able to access (unless you have root permission), and external means you can choose a folder yourself. I was confused by this myself the first time I set up the app. The "directory already exists" error is probably another bug, in fact I encountered it myself recently when I reinstalled the app so I can try to track that down.

I agree, better documentation is needed. I guess part of the reason that doesn't exist yet is a rewrite of the app/just the setup process is in progress.

**Comment by hammerheadlemon** [comment]
Hi - thanks for the quick response!

I generated the keypair in-app. Thanks for clearing up the "internal/external" point - it wasn't obvious what that was referring to but see it now.

I'll try a few other things and see how I get on. Keep up the good work.
