### ISSUE TITLE
Don't work at all

### ISSUE THREAD

**Issue by jvillasante** [zeapo/Android-Password-Store#141]
I was really exited about this app, but it just don't work at all. I have passwordstore working on my pc and wanted to clone my passwords on this app, the "Enable git" option is grayed out and it don't seem to respond to anything.

**Comment by wongma7** [comment]
Sorry for the confusion, the "Enable git" option doesn't actually do anything. In the initial setup it should tell you to enter git settings then hit a 'Clone' button. If that didn't happen: to clone your repo, go to settings then 'edit git server settings,' import your ssh key if you are using one, and attempt to pull.

**Comment by garyschulte** [comment]
Another question answered... I was wondering what was up with that checkbox.  That adds confusion to an already confusing setup
