### ISSUE TITLE
[FEATURE] Own field for each prefix

### ISSUE THREAD

**Issue by TheLastProject** [zeapo/Android-Password-Store#1412]
**Is your feature request related to a problem? Please describe.**
I prefix every single field that is not a password. To make it easier to scan through and select things, I would prefer each prefix to be each own field. Currently, it seems only 4 fields are ever created: Password, OTP, Username and Extra content.

A semi-related issue is that if my OTP field is prefixed with `OTP: `, it is completely ignored.

**Describe the solution you'd like**
Every line should be scanned for a prefix and put into each own field instead of under "Extra content:"

I understand that showing more fields could lead to unclarity about which field the app would use in autofill. Perhaps an icon next to

**Describe alternatives you've considered**
More prefixes to autodetect as Username or so? But that just seems unclean.

**Additional context**
I sadly can't seem to disable the anti-screenshot protection, so I can't take a screenshot. I hope my description is clear enough anyway.

I am willing to work on this myself if it would be accepted.

**Comment by msfjarvis** [comment]
This has already been implemented in #1321, but has not made its way into a stable release. The passfile content is now parsed as lines of `$key: $value` pairs, and any lines that can't be parsed into distinct KV pairs are lumped into a catch-all 'Extra content' field like before.

**Comment by TheLastProject** [comment]
Oh, awesome, thank you. Sorry for the duplicate, the original didn't show up in my multiple GitHub search attempts.
