### ISSUE TITLE
[FEATURE] Add support for Keybase git repositories

### ISSUE THREAD

**Issue by joelchrono12** [zeapo/Android-Password-Store#1413]
**Is your feature request related to a problem? Please describe.**
I want to be able to access my keybase private passwords repo
**Describe the solution you'd like**
Add support for keybase private repos, expanding the git functionality, maybe using root to access termux with keybase installed
**Describe alternatives you've considered**
All I know is that I could use termux and such. But I have the keybase app installed and I wish I could access my passwords repo
**Additional context**
I have a keybase repo that I cannot really acces from my phone, and the git integration in the app is not enough

**Comment by msfjarvis** [comment]
Duplicate of #344
