### ISSUE TITLE
[BUG] can't insert ssh key

### ISSUE THREAD

**Issue by xmoooz** [zeapo/Android-Password-Store#1416]
I use this tut to manage my keys and subkeys:
https://github.com/drduh/YubiKey-Guide

when I want to import ssh keys that generated via the above guide,
in this app for cloning my github repo,
I encounter with error that is about ssh key is not valid.

**Comment by Skrilltrax** [comment]
Hey, are you adding the public ssh key or the private ssh key to the application?

P.S: Please use the issue template in the future so that we can get all the required information.

**Comment by Skrilltrax** [comment]
Hey, can you please use the issue template? that would help us in getting all the information that we need to debug the problem.

**Comment by msfjarvis** [comment]
Reposting the same incomplete issue after I closed your previous one is simply spamming. Please read what we're asking of you so that we can actually provide help.
