### ISSUE TITLE
Crash when auto filling 

### ISSUE THREAD

**Issue by kevincox** [zeapo/Android-Password-Store#142]
After selecting "Fill"  the following error occurs. 

![tmp_25888-img_20151028_084426-1249675327](https://cloud.githubusercontent.com/assets/494012/10788872/a6645752-7d50-11e5-8dd8-fa65ca8ba7a6.jpg)

**Comment by wongma7** [comment]
Thanks for report. The temporary fix is to turn the service off and on again. Does this happen often? Or only after a while? Somehow the service loses connection to the OpenKeyChain service, I think.

**Comment by wongma7** [comment]
Quite confident that fixes it. Will release a new version.

**Comment by kevincox** [comment]
I've only had this occur once, but as I didn't restart my phone for a while it was happening every time. After restarting my phone it appears to be "fixed". Hopefully that patch fixes it for good and thanks again for the fantastic response time.
