### ISSUE TITLE
[BUG] Bromite browser, no autofill

### ISSUE THREAD

**Issue by plant7403** [zeapo/Android-Password-Store#1422]
**To Reproduce**
1. Go to 'bromite browser'
2. Click on 'any password/login field'
4. See no autofill or password suggestion

**Expected behavior**
Password suggestion

**Device information (please complete the following information):**
 - Device: Xiaomi Mi 9
 - OS: xiaomi.eu MIUI, Android 11
 - App version 1.13.4

**Comment by msfjarvis** [comment]
Where did you install Bromite from? We already [support](https://github.com/android-password-store/Android-Password-Store/blob/373a46f73a51bda3900b895f72fba5ca619e5884/autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FeatureAndTrustDetection.kt#L74) it, but it's strongly tied to the official signing key to prevent phishing attacks from a compromised build of the source code. Does Autofill work on other Chromium browsers for you?

**Comment by plant7403** [comment]
@msfjarvis F-Droid? F-Droid privileged extension? 🤔

**Comment by msfjarvis** [comment]
> @msfjarvis F-Droid? F-Droid privileged extension? 🤔

Bromite's on F-Droid? Curious...

I'll take a look, thanks!

**Comment by plant7403** [comment]
There's Bromite official F-Droid repository
I thought this is the only one correct way to install it 😅😅😅

**Comment by msfjarvis** [comment]
> There's Bromite official F-Droid repository
> I thought this is the only one correct way to install it

I'm not an F-Droid user so I typically download their releases directly from GitHub whenever I do end up using Bromite. That being said, the APKs being distributed through F-Droid are identical to what is published on GitHub Releases, and should work just fine.

Are you sure Autofill has been enabled in Password Store? If so, can you try a different Chromium-based browser and see if that works for you?

**Comment by msfjarvis** [comment]
Nevermind, it seems Bromite has [completely removed Autofill support](https://github.com/bromite/bromite/blob/master/FAQ.md#does-bromite-support-the-android-autofill-framework).

**Comment by plant7403** [comment]
@msfjarvis no plan to add support? 😄
I see many new features for 2.0, and maybe it's a good time 😅

**Comment by msfjarvis** [comment]
It's not on me to support.

**Comment by plant7403** [comment]
> It's not on me to support.

From bromite statement:
> Some apps use accessibility services as a workaround.

Some password managers have this workaround 🤔
I have no idea how hard it is, but maybe it's worth for 2.0 😄

**Comment by msfjarvis** [comment]
> > It's not on me to support.
> 
> From bromite statement:
> 
> > Some apps use accessibility services as a workaround.
> 
> Some password managers have this workaround 🤔
> I have no idea how hard it is, but maybe it's worth for 2.0 😄

I've _removed_ accessibility Autofill for 2.0 and have absolutely no intention to add it back. Bromite's paranoia is not my problem to deal with.
