### ISSUE TITLE
Add Styx browser to supported

### ISSUE THREAD

**Issue by plant7403** [zeapo/Android-Password-Store#1428]
Sorry, but I didn't know what to write 😅
Please add Styx browser to the supported browsers
I've heard this browser is actively developing and becoming popular among privacy fans
https://github.com/jamal2362/Styx
Available from Google play, Github, F-droid(Izzy repo)

**Comment by msfjarvis** [comment]
Can't help with an empty issue body.

**Comment by plant7403** [comment]
@msfjarvis, master, reopen please 😅

**Comment by msfjarvis** [comment]
Fixed by #1431, should be available in the latest [snapshot](https://android-password-store.github.io/docs/users/release-channels) in the next few minutes.
