### ISSUE TITLE
OpenPGP API v9

### ISSUE THREAD

**Issue by dschuermann** [zeapo/Android-Password-Store#143]
OpenKeychain dev here.

I saw you still use v7 of our API. We are now at v9 with OpenKeychain 3.6 also fixing several bugs inside the API and library. We have a changelog at https://github.com/open-keychain/openpgp-api/blob/master/CHANGELOG.md for migration help. If you have any remaining questions I am here to assist :)

**Comment by wongma7** [comment]
Thanks! Wasn't much to change on our end to maintain functionality.
