### ISSUE TITLE
[FEATURE] Allow setting a subdir of the repo as a base directory

### ISSUE THREAD

**Issue by reisraff** [zeapo/Android-Password-Store#1438]
I don't know if it is related to https://github.com/android-password-store/Android-Password-Store/issues/111 but I hacked the way it works to work the way I want.

I mean.

```bash
reisraff@reisraff:~/Projects/reisraff/personal$ ls -la
total 40
drwxrwxr-x  8 reisraff reisraff 4096 jun 17 17:10 .
drwxrwxr-x 30 reisraff reisraff 4096 jun 17 16:33 ..
drwxrwxr-x  2 reisraff reisraff 4096 jun 17 16:54 bin
drwxrwxr-x  3 reisraff reisraff 4096 jun 17 16:28 documents
drwxrwxr-x  8 reisraff reisraff 4096 jun 17 17:25 .git
drwxrwxr-x  2 reisraff reisraff 4096 jun 17 16:11 .gnupg
-rw-rw-r--  1 reisraff reisraff 2538 jun 17 16:51 GPG.md
drwx------  6 reisraff reisraff 4096 jun 17 17:24 .password-store
-rw-r--r--  1 reisraff reisraff  442 jun 17 17:13 README.md
drwx------  2 reisraff reisraff 4096 jun 17 16:04 .ssh
reisraff@reisraff:~/Projects/reisraff/personal$ ls -la ~/ | grep pass
lrwxrwxrwx  1 reisraff reisraff       58 jun 17 17:11 .password-store -> /home/reisraff/Projects/reisraff/personal/.password-store/
```

I have a repository where I created the `.password-store` and I create a symlink to my `~` (home) to keep track not even the passwords in the repo but also more info that is confidential.

I'd like to have a way in the app, to clone this repo that has a different structure, and just set the path where is supposed to be my `.password-store`, and then start work that way.

Is it possible?

**Comment by msfjarvis** [comment]
The other issue is not related, but we're not currently planning on supporting a custom 'base' directory.
