### ISSUE TITLE
Autofill

### ISSUE THREAD

**Issue by JasperWeiss** [zeapo/Android-Password-Store#144]
Hi, I enabled autofill but it doesn't seem to do anything. It should automatically match although I've no idea what is supposed to match with what since I'm not sure what is supposed to go behins the /. 
I also tried to manually select a password but when I go to any site and fill in my user name nothing happens.
How does autofill work?

**Comment by wongma7** [comment]
Hi, sorry for the confusion. It doesn't yet work with websites. A major missing feature, but it's being worked on. Documentation also ought to be on the way. In apps, the automatic match will simply search for the app name in your stored passwords and if it doesn't find anything no popup will show.

**Comment by JasperWeiss** [comment]
Great I got it to work with spotify,
It should include usernames. 
So that, I can store multiple accounts and pick one from the list. And then it should fill in the username automatically. That would be awesome!
Also, what keeps me from replacing all passwords with strong randomly generated ones is the fact that there isn't a nice client for other platforms like windows. So there's no way to login without my phone (ignoring the linux command line utillity this is modelled after)

**Comment by wongma7** [comment]
Yeah, having usernames would be a great addition. The #1 priority for me atm is getting websites to work nicely; ability to quickly choose from multiple accounts will probably follow as a result.

https://github.com/IJHack/qtpass may be an option on windows, don't use it myself though.

**Comment by JasperWeiss** [comment]
Great idea here.
What if, I could use my android device to fill in passwords on other devices.
Essentially, using root passwordstore could act as a keyboard over usb. So I could plug in my phone and have it paste the password like a ubikey does.
With usernames it could paste the username, tab, and then password.

This is especially great in case you're not on your own computer. Would it be possible?
Because that would take away the problem of not having my password on any other device than my phone. (Just typing it over is really quite inconvenient)

**Comment by wongma7** [comment]
Interesting idea, i'm sure that's possible...but it's infeasible. For the phone to act like a USB keyboard it needs a modified kernel. I'm sure in any case it would be more feasible to just improve pass on windows.

Another possibility, if you're comfortable with your passwords going through the internet and somebody else's servers, is using something like pushbullet universal copy and paste... I assume that is unacceptable to the vast majority of this app's users, but worth pointing out if we're exhausting all possibilities...

**Comment by JasperWeiss** [comment]
Having to install an application every time I use a computer at school will only make managing passwords harder.
Is there really no way to have a Ubikey like way to paste my logins onto computers without custom kernel?
Drivedroid (https://play.google.com/store/apps/details?id=com.softwarebakery.drivedroid)
Seems to be able to manipulate the usb interface without custom kernel?
I could ask the developer if he knows a way to do this?

**Comment by wongma7** [comment]
Yes unfortunately there is no better way than typing it in at least for the foreseeable future...

It says "most kernels support emulating USB drives" so he is still bound by what the kernel can do.

**Comment by zeapo** [comment]
Do you think that #145 could solve the keyboard issue?

**Comment by JasperWeiss** [comment]
@zeapo This seems very promising! If that could be done, that'd be really cool. This also takes away the need of a usb cable.
So you'd couple the computer to you're phone (This could also be a device without usb port, too) and then you could simple go to password store and hit insert on external device or something like that.
