### ISSUE TITLE
[BUG] Git files appearing in search

### ISSUE THREAD

**Issue by colonelpanic8** [zeapo/Android-Password-Store#1453]
Seems like these should be ignore by default

![gitfilesappearinresults](https://user-images.githubusercontent.com/1246619/124522984-5bdc1800-ddb2-11eb-8dfc-571afc89740b.jpg)

**Comment by msfjarvis** [comment]
Do you have "Show hidden files" turned on in the app settings?

**Comment by colonelpanic8** [comment]
> Do you have "Show hidden files" turned on in the app settings?

Shouldn't it be possible to show "hidden files" without showing git files?

I had "Show all files and folders" checked.

**Comment by msfjarvis** [comment]
> > Do you have "Show hidden files" turned on in the app settings?
> 
> Shouldn't it be possible to show "hidden files" without showing git files?

We don't yet have a blocklist of file patterns that are always excluded. Can probably add it at some point.

**Comment by rk0n** [comment]
> > > Do you have "Show hidden files" turned on in the app settings?
> > 
> > 
> > Shouldn't it be possible to show "hidden files" without showing git files?
> 
> We don't yet have a blocklist of file patterns that are always excluded. Can probably add it at some point.

Do you think it's possible to just exclude .git folder from search instead of add the complexity of removing specific file patterns?

**Comment by colonelpanic8** [comment]
Agreed. I don't think there is any legitimate reason to ever show the underlying git files in this search.
