### ISSUE TITLE
[BUG] Error from OpenKeyChain

### ISSUE THREAD

**Issue by bat9r** [zeapo/Android-Password-Store#1456]
Hello!
I created a repository on local and configured it on remote using this example
https://git.zx2c4.com/password-store/about/#EXTENDED%20GIT%20EXAMPLE
Remote was configured on Github, cloning made by ssh key.
OpenKeyChain version 5.7.5
Password store version 1.13.4
Phone Samsung Galaxy s21
Android version 11

I received this error, every time when I try to open the password.
```
Error from OpenKeyChain: Encountered an error reading input data!
```

I already tried the solutions described in these threads
https://github.com/android-password-store/Android-Password-Store/issues/173
https://github.com/android-password-store/Android-Password-Store/issues/560

And tried to recreate password-store directory, but it still didn't work

In OpenKeyChain program accesses from password-store granted/

**Comment by msfjarvis** [comment]
The source of this bug is your GPG version being too new for OpenKeychain. You can refer to [this](https://github.com/android-password-store/Android-Password-Store/discussions/1429) discussion for solutions. The corresponding OpenKeychain issue is [here](https://github.com/open-keychain/open-keychain/issues/2096).

**Comment by bat9r** [comment]
It's working, thank you very much! :)

Steps:
```
brew install gnupg@2.2
echo 'export PATH="/opt/homebrew/opt/gnupg@2.2/bin:$PATH"' >> /Users/bat9r/.bash_profile
source ~/.bash_profile
pass init [gpg_id]
pass git push
# Export again gpg private key and upload it to the phone, after import to OpenKeyChain
gpg --export-secret-keys [gpg_id] > private.key
