### ISSUE TITLE
[FEATURE] Add a login input box when creating a new password

### ISSUE THREAD

**Issue by arnaudmorin** [zeapo/Android-Password-Store#1458]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to add a new password in because I need to add an extra `login: ` before my login in the extra field.

**Describe the solution you'd like**
Most of my passwords are related to a login, so I'd like to a have a field to add a login just below the password, before the extra field.

**Describe alternatives you've considered**
A clear alternative is to add `login: ` in front of my login in extra field, but this is harder for beginners (I converted my wife to password store, and she was not able to figure that out).

**Additional context**
N/A

**Comment by plant7403** [comment]
@arnaudmorin there's "encrypt login" button actually 😅
By default Unix Pass uses the file name as login, optionally you can specify login inside therefore encrypt login 😄

**Comment by msfjarvis** [comment]
> there's "encrypt login" button actually 

It's only for when a password is being created by Autofill and the directory structure is set to file-based.

**Comment by plant7403** [comment]
@msfjarvis sorry, I got confused, it shouldn't be somewhere? I have "encrypt username" switch on both pages 😅
Sorry if I didn't understand something, can you explain, please?  😅

**Comment by msfjarvis** [comment]
> @msfjarvis sorry, I got confused, it shouldn't be somewhere? I have "encrypt username" switch on both pages 
> Sorry if I didn't understand something, can you explain, please?

You're right, I slightly misread the code [here](https://github.com/android-password-store/Android-Password-Store/blob/fd6d0e52fc378eefd3de35bc9e7778897ccc396f/app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt#L229-L232). The button shows if you use the second option for 'Password file organization' and there is no username being provided through Autofill.
