### ISSUE TITLE
[BUG]steam otp show error

### ISSUE THREAD

**Issue by hsingll** [zeapo/Android-Password-Store#1459]
**Describe the bug**
import my passstore repository.and steam otp show error.
steam uri is 5 digits.

**To Reproduce**
1. import steam's uri like otpauth://totp/Steam:uname?secret=xxx&issuer=Steam&period=30&digits=5.

**Expected behavior**
I think your otp tool didn't support custom parameter like digits.

**Comment by msfjarvis** [comment]
Fill the issue template properly.
