### ISSUE TITLE
[FEATURE] Support multiple recipients in `.gpg-id`

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1461]
**Is your feature request related to a problem? Please describe.**

`pass` allows supplying multiple GPG recipients as individual lines in `.gpg-id` and encrypts to all of them, allowing multiple distinct keys to decrypt.

**Describe the solution you'd like**

APS should be able to do the same by parsing `.gpg-id` as lines of GPG identifiers.

**Describe alternatives you've considered**

None exist.

**Additional context**

Requested via email, reproduced below as-is

<details><summary>Email text</summary>

```plaintext
hi there! I'm using password store on my phone, and loving it, thank you for making the app! I hope you accept feature requests, as I ran into a problem just now, after adding a second id to .gpg-id. With the original pass, this allows me to decrypt passwords with either one of the two gpg keys identified there, but on android, creating a new password encrypted for both doesn't work. I think openkeychain supports this no problem, it's hopefully just a matter of parsing .gpg-id to lines. I'd really appreciate if you could get that working!
```

</summary>

**Comment by msfjarvis** [comment]
@crazyh I see you starred the issue, are you able to test for this on the latest Play Store release? The code for supporting this [already exists](https://github.com/android-password-store/Android-Password-Store/blob/release-1.13/app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt#L361-L368) so if it doesn't work then we might be looking at yet another OpenKeychain bug.

**Comment by sza-1** [comment]
> @crazyh I see you starred the issue, are you able to test for this on the latest Play Store release? The code for supporting this [already exists](https://github.com/android-password-store/Android-Password-Store/blob/release-1.13/app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt#L361-L368) so if it doesn't work then we might be looking at yet another OpenKeychain bug.

Hmm, yeah, just tried it on the following versions:

```
$ adb shell pm list packages --show-versioncode dev.msfjarvis.aps
package:dev.msfjarvis.aps versionCode:11340

$ adb shell pm list packages --show-versioncode org.sufficientlysecure.keychain
package:org.sufficientlysecure.keychain versionCode:57500
```
It works properly with the .gpg-id which contains two keys: test password was created in APS and properly encrypted with both keys.

**Comment by msfjarvis** [comment]
> > @crazyh I see you starred the issue, are you able to test for this on the latest Play Store release? The code for supporting this [already exists](https://github.com/android-password-store/Android-Password-Store/blob/release-1.13/app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt#L361-L368) so if it doesn't work then we might be looking at yet another OpenKeychain bug.
> 
> Hmm, yeah, just tried it on the following versions:
> 
> ```
> $ adb shell pm list packages --show-versioncode dev.msfjarvis.aps
> package:dev.msfjarvis.aps versionCode:11340
> 
> $ adb shell pm list packages --show-versioncode org.sufficientlysecure.keychain
> package:org.sufficientlysecure.keychain versionCode:57500
> ```
> 
> It works properly with the .gpg-id which contains two keys: test password was created in APS and properly encrypted with both keys.

Thanks for testing it for me!

Closing this since it's already supported.

**Comment by Rudd-O** [comment]
This still does not work in the version installed from F-Droid.  I can reliably reproduce the problem.
