### ISSUE TITLE
[BUG] Infinite Loop while syncing repo or pushing it to remote 

### ISSUE THREAD

**Issue by dfrost16** [zeapo/Android-Password-Store#1463]
![Screenshot_20210719-064707](https://user-images.githubusercontent.com/24663673/126089428-946ce034-055b-4d0f-85c1-f03c5f08ad2e.jpg)
Lately I have been facing this issue where the app keeps syncing forever 
And it always ends with this 
![Screenshot_20210719-065243](https://user-images.githubusercontent.com/24663673/126089559-76eb7f96-1b65-4acb-af46-f2a59fcbc761.jpg)
Though, if I use a vpn this issue seems to be solved.
App version: Version 1.13.4

**Comment by msfjarvis** [comment]
As you've already noticed through your use of a VPN, this is an issue with your network and not the app.
