### ISSUE TITLE
[FEATURE] Support for Kiwi Browser

### ISSUE THREAD

**Issue by dfrost16** [zeapo/Android-Password-Store#1466]
Support for kiwi Browser since autofill doesn't works on kiwi browser.

**Comment by msfjarvis** [comment]
Kiwi is [already supported](https://github.com/android-password-store/Android-Password-Store/blob/c60a2534d5f63d448f9c26d6ac8a933a74249d84/autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FeatureAndTrustDetection.kt#L83), if something doesn't work then it's broken on their end and you should contact Kiwi's devs.
