### ISSUE TITLE
[FEATURE] Enable fuzzy search in auto fill dialogue

### ISSUE THREAD

**Issue by kolaente** [zeapo/Android-Password-Store#1476]
**Is your feature request related to a problem? Please describe.**
When searching for a password entry in the autofill dialogue it only finds entries with an exact match of the name. That can be a problem when I don't know the exact name but only eg enter the site name but that's not the exact name of the password entry.

Maybe related to https://github.com/android-password-store/Android-Password-Store/issues/1200

**Describe the solution you'd like**
When searching from within the app (not autofill) it seems to find entries which do not have the exact name. Ideally, that would also work in the autofill dialogue.

**Describe alternatives you've considered**
Not using autofill but that kind of defeats the purpose of autofill.

**Additional context**
None.

**Comment by msfjarvis** [comment]
Turn off 'Phishing-resistant search' from the Autofill dialog to enable fuzzy matching.

**Comment by kolaente** [comment]
Ah, missed that option. Thanks!
