### ISSUE TITLE
[FEATURE] customize ssh port when configuring git repo.

### ISSUE THREAD

**Issue by Brli** [zeapo/Android-Password-Store#1499]
**Is your feature request related to a problem? Please describe.**
it is always suggested to use non-default port when setting up ssh daemon, thus this request.

**Describe the solution you'd like**
Add another input area when editing git repo config.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by msfjarvis** [comment]
You can provide the port as part of URL string as `ssh://github.com:$port/path`
