### ISSUE TITLE
[BUG] Hangs on "Running git operation…"

### ISSUE THREAD

**Issue by ieure** [zeapo/Android-Password-Store#1500]
**Describe the bug**

When I finish the first run of Password Store on a new phone (or, subsequently, run "Pull from Remote"), it displays "Running git operation…" and does nothing else until I close it.

**To Reproduce**
1. Set up Password Store.
2. Attempt to clone or update the remote repo.
3. It displays "Running git operation…", but never completes, and my repo is never cloned.

**Expected behavior**

I should receive an OpenKeychain prompt

**Device information (please complete the following information):**
 - Device: Unihertz Titan Pocket
 - OS: Stock ROM, Android 11.
 - App version: 1.13.5, from F-Droid

**Additional context**

- This is a brand new phone I received today.  Is has an unusually small display, which, maybe that's related?  Seems like a stretch for this issue, though.
- I have a YubiKey which has both my SSH private key (to clone the repo) and GPG private key (to decrypt the passwords) on it.
- The YK is set up in OpenKeychain.
- I also recently set up Password Store on a Pixel 3a running CalyxOS.  The same config & version of Password Store works perfectly on it.
- I enabled debug logging, but I don't know where it ends up

**Comment by msfjarvis** [comment]
I have no clue how the Unihertz handles apps launching from the background, which is what OpenKeychain attempts to do. If you can find any info on that, it could explain what's happening.

Enabling debug logging does not start writing to disk, but it increases verbosity of the logs written to [logcat](https://developer.android.com/studio/command-line/logcat#Overview). If you can find a way to enable USB debugging then you can extract logs with [adb](https://developer.android.com/studio/command-line/adb) and share them here.

**Comment by ieure** [comment]
> I have no clue how the Unihertz handles apps launching from the background, which is what OpenKeychain attempts to do. If you can find any info on that, it could explain what's happening.

Aha, this was the exact clue I needed.  Unihertz ships an "app blocker" which allows you to disable certain features, I guess in order to improve battery life.  Going into Settings -> Intelligent assistance -> App blocker -> OpenKeychain and disabling the "Start blocker" fixed my issue.

Sorry for the noise, thank you very much for the lead, and for Password Store generally.  It's indispensable.
