### ISSUE TITLE
Replace Timber with logcat

### ISSUE THREAD

**Issue by Skrilltrax** [zeapo/Android-Password-Store#1505]
Currently the app and all other libs are using `Timber` for logging. Timber itself is pretty nice and solves a ton of issues but now Square released a new logging library called `logcat`.

Logcat improves upon timber and hence we should migrate to it.

https://github.com/square/logcat for reference.

**Comment by pt2121** [comment]
Can I take a stab at this?

**Comment by msfjarvis** [comment]
> Can I take a stab at this?

All yours.

**Comment by rohitjakhar** [comment]
Logcat still in beta, is it good choice use instead of Timmber ?

**Comment by msfjarvis** [comment]
> Logcat still in beta, is it good choice use instead of Timmber ?

Logging libraries this simple are hard to get wrong, and I find logcat's API to be complete enough for our needs. In any case there are a few months we're going to be able to ship this code so if anything breaks we'll be able to fix it.
