### ISSUE TITLE
Convert issue templates to forms

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1506]
GitHub supports [Issue Forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) that replaces issue templates and convert the wall of text that is a template into an interactive web form, improving UX for reporters which results in filed issues being more likely to be complete.

**Comment by SanchithHegde** [comment]
I'll take this up. 

@msfjarvis Should I also update the RFC template, or only the bug report and feature request templates?

**Comment by msfjarvis** [comment]
> I'll take this up.
> 
> @msfjarvis Should I also update the RFC template, or only the bug report and feature request templates?

Skip the RFC template.
