### ISSUE TITLE
[BUG] Root .gpg-id is ignored (missing key for encryption %s)

### ISSUE THREAD

**Issue by svvac** [zeapo/Android-Password-Store#1519]
### Describe the bug

When generating a new password in a subfolder that does not have a `.gpg-id`, the root `$PASSWORD_STORE_DIR/.gpg-id` is ignored and the app reports the following error:

    Error from OpenKeyChain: missing key for encryption %s

This only seems to apply to the root id file ; nested `.gpg-id` appear to work.

### Steps to reproduce

1. Create a new root folder `test` without setting gpg key
2. Attempt to create a new password in `test`
3. The error appears

If instead :
1. Create a new root folder `test` and set gpg key
2. Create subfolder `test/test2`
2. Attempt to create a new password `test/test2`
3. The password is sucessfully saved

### Expected behavior

Should properly fallback to `$PASSWORD_STORE_DIR/.gpg-id` 

### Device information

- OS: Android 11
- App version 1.13.5

**Comment by msfjarvis** [comment]
Interesting theory w.r.t. root `.gpg-id` being ignored, but tests disprove it.

```kotlin
package dev.msfjarvis.aps.util

import java.io.File
import kotlin.test.assertEquals
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder

class FindTillRootTest {

  @get:Rule
  val temporaryFolder = TemporaryFolder()

  @Test
  fun finding_file_till_root() {
    val rootGpgIdFile = temporaryFolder.newFile(".gpg-id")
    val items = List(30) { idx -> "child$idx" }.toTypedArray()
    val child = temporaryFolder.newFolder(*items)
    val foundGpgIdFile = child.findTillRoot(".gpg-id", temporaryFolder.root)
    assertEquals(rootGpgIdFile, foundGpgIdFile)
  }
}
```

```shell
➜ gradle :app:testFreeDebugUnitTest -PslimTests --offline --tests dev.msfjarvis.aps.util.FindTillRootTest
Type-safe dependency accessors is an incubating feature.
Type-safe project accessors is an incubating feature.
Configuration on demand is an incubating feature.

> Task :app:testFreeDebugUnitTest

dev.msfjarvis.aps.util.FindTillRootTest > finding_file_till_root PASSED

BUILD SUCCESSFUL in 2s
76 actionable tasks: 1 executed, 75 up-to-date
```

This has come up multiple times in the past, and the error is thrown in open-keychain [here](https://github.com/open-keychain/open-keychain/blob/6f38af15828e07f0186109a89b7aa57f54101cfa/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptOperation.java#L671-L674), which seems fairly legit. Unfortunately actionable information on this is very scant, and I have never been able to reproduce it. If someone can create a minimal repro by starting from [pass-test](https://github.com/android-password-store/pass-test), I'd be more than happy to dig further.

**Comment by msfjarvis** [comment]
Just remembered where I've seen this before, it's definitely an OpenKeychain bug https://github.com/open-keychain/open-keychain/issues/2588
