### ISSUE TITLE
KeePass Suport

### ISSUE THREAD

**Issue by arkhan** [zeapo/Android-Password-Store#152]
Its posible to open keepass file to manage passwords

**Comment by JasperWeiss** [comment]
That'd be nice actually. Keepass works differently in that it encrypts the database (it used databases) with aes 256. So I can imagine this would take some work.

**Comment by polyzen** [comment]
[keepass2android](https://keepass2android.codeplex.com/) is a great application, and considerably more mature/advanced than this. You may want to give it a try, if you haven't already.
