### ISSUE TITLE
[BUG] Misconfigured Proguard rule causes app to not be minified

### ISSUE THREAD

**Issue by alexanderbezverhni** [zeapo/Android-Password-Store#1520]
### Describe the bug

`-keep class !org.bouncycastle.jce.provider.X509LDAPCertStoreSpi { *; }` keeps Proguard/R8 compilers from minifying the **whole** app. It basically says "exclude everything but org.bouncycastle.jce.provider.X509LDAPCertStoreSpi".

More details here:
- https://github.com/stripe/stripe-android/pull/2271
- https://github.com/stripe/stripe-android/issues/2586
- https://github.com/stripe/stripe-android/pull/2587

**Comment by msfjarvis** [comment]
Thanks for the report!
