### ISSUE TITLE
Allow importing QR codes from images

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1529]
### Discussed in https://github.com/android-password-store/Android-Password-Store/discussions/1528

<div type='discussions-op-text'>

<sup>Originally posted by **Quintasan** October 29, 2021</sup>
I have a plenty of OTP keys in andOTP which I would like to import to pass but manually typing in the otpauth:// string on a phone is tedious and error-prone and the Add OTP button only offers scanning a QR code which is physically impossible. I know that andOTP can show you the QR code and you can save it as an image but that doesn't help since you can't use an image.

My two ideas
- allow using an image file
- show a dialog window for putting in just the secret

I'm aware that there can be different algorithms for generating the OTP and can have more digits but as far as I'm aware 60 second expiry, 6 digits and SHA1 is the de-facto standard.

I did dabble in Android development so I could try contributing this feature but I'd like to ask if there's interest in it beforehand.</div>

I believe the ability to import from images is a practical use case that we should have supported from the beginning, so we can take a PR for it.

**Comment by msfjarvis** [comment]
@Quintasan are you still planning to work on this?

**Comment by Quintasan** [comment]
> 
> 
> @Quintasan are you still planning to work on this?

Yup, my previous weekend was less weekend-ish than I wanted, but I'll try tackling it this week.

**Comment by msfjarvis** [comment]
> > @Quintasan are you still planning to work on this?
> 
> Yup, my previous weekend was less weekend-ish than I wanted, but I'll try tackling it this week.

No worries, take your time.

**Comment by msfjarvis** [comment]
@Quintasan anything I can help with on this?
