### ISSUE TITLE
[BUG] No encrypted data with known key found in stream with newer gopass secrets

### ISSUE THREAD

**Issue by skewballfox** [zeapo/Android-Password-Store#1530]
### Describe the bug

this is sort of a duplicate of [another closed issue](https://github.com/android-password-store/Android-Password-Store/issues/1309) but with a more limited scope, and hopefully some relevant context.

When I try to unlock a secret that has been made on my desktop(using gopass) approximately in the last 5-7 months(from the ages according to the github commit history), I get the error `no encrypted data with known key found in stream` despite the associated key being in my keychain. However, older secrets from the same password store do work and correctly prompt me to unlock my keyring. so this seems to be an incompatibility between what gopass is currently creating and what android store is expecting when parsing.

 I sort of accidentally confirmed this was not a bug with openkeychain when setting up the repo on a new phone. because I hadn't yet gave Password store permission to access the keyring when first encountering this bug on the new phone, and was prompted for permission to access the keyring when accessing an older secret, so this statement is being printed before the request even makes it to openkeychain.

also I'm running 1.13.5, which I believe is the current version listed for the main branch.

if you need me to run a command to display different information about the secrets (to help diagnose what's going wrong) I can. 

### Steps to reproduce

1. Go to a recent secret created with gopass on linux (fedora 34-35)
2. Attempt to unlock the secret

Either the statement appears or OpenKeychain prompts to unlock, depending on secret age

### Expected behavior

All secrets to prompt to unlock

### Device information

- Device: [Google pixel 4a, Google pixel 3a]
- OS: [GrapheneOS 11,12]
- App version [e.g. 1.13.5(happened for a while though)]

### Additional context

looking through some stuff related to my repos update history relative to the ages of the secrets, it looks like something  changed with gopass version 1.12

**Comment by msfjarvis** [comment]
> I sort of accidentally confirmed this was not a bug with openkeychain when setting up the repo on a new phone. because I hadn't yet gave Password store permission to access the keyring when first encountering this bug on the new phone, and was prompted for permission to access the keyring when accessing an older secret, so this statement is being printed before the request even makes it to openkeychain.

This reasoning is incorrect. The error about encrypted data matching no known key originates entirely in OpenKeychain, and you can see the string for it [here](https://github.com/open-keychain/open-keychain/blob/6f38af15828e07f0186109a89b7aa57f54101cfa/OpenKeychain/src/main/res/values/strings.xml#L1165). APS does not attempt to parse any encrypted data, and passes it along as-is to OpenKeychain.

The previous issue was resolved [here](https://github.com/android-password-store/Android-Password-Store/discussions/1310) , and I'm fairly confident it is user error and not a bug. I'd suggest taking a look at the comments there and checking if they apply to you.

**Comment by skewballfox** [comment]
> The previous issue was resolved here , and I'm fairly confident it is user error and not a bug. I'd suggest taking a look at the comments there and checking if they apply to you.

well, the key has been directly imported from keys.openpgp.org, and both the secrets that decrypt and the secrets that fail to decrypt are using the same key, and I can create new secrets on the phone(though having trouble pushing them due to some issue with jgit).  

the secrets that I created on the phone, the secrets I had created on my previous phone, and the secrets I had created on my desktop prior to upgrading to gopass 1.12 all work and all use the same secret key. the same secret key that was used to create the passwords that don't work (it's a subkey on a yubikey)

**Comment by skewballfox** [comment]
found the issue. around january I migrated to a new gpg-key and with a hardened gpg config, which included the option `throw-keyids` and apparently this option isn't supported by openkeychain. it's odd though because despite the older passwords being created with another key, they were migrated to the new key, yet still work anyway

[basically same issue as this](https://github.com/android-password-store/Android-Password-Store/issues/560)

**Comment by skewballfox** [comment]
@msfjarvis how could I help with the 2.0 release? I think that might fix the issues I've been having with password-store (which have tended to be related to openkeychain), and generally I'm using password-store effectively read-only (generate almost all passwords on my pc, could easily adapt to become 100%) so I'm not to worried about anything which might bork the setup on the phone

**Comment by msfjarvis** [comment]
> @msfjarvis how could I help with the 2.0 release? I think that might fix the issues I've been having with password-store (which have tended to be related to openkeychain), and generally I'm using password-store effectively read-only (generate almost all passwords on my pc, could easily adapt to become 100%) so I'm not to worried about anything which might bork the setup on the phone

Testing the [snapshot builds](https://android-password-store.github.io/docs/users/release-channels) periodically is a good way to contribute without writing code. If you'd like to contribute to the development directly, the tracking issue for our RFC to replace OpenKeychain is available [here](https://github.com/android-password-store/Android-Password-Store/issues/1523).
