### ISSUE TITLE
[BUG] Android 12 autofill won't work in Chromium based browsers

### ISSUE THREAD

**Issue by plant7403** [zeapo/Android-Password-Store#1535]
### Describe the bug

Autofil will not show up in chromium based browsers, and no "autofill" option on long press
Android 12
Although it works with Firefox based browsers

### Steps to reproduce

1. Go to Chromium/Brave
2. Go to any website that supports autofil
3. Tab on the field, or enter the login and then tap on password
4. Nothing happens

### Expected behavior

1. Go to Chromium/Brave
2. Go to any website that supports autofill
3. Tab on the field, or enter the login and then tap on password
4. Get the window window with create or choose password, or get the same in inline 

### Screenshots

![Screenshot_20211105-095930_Ungoogled Chromium](https://user-images.githubusercontent.com/24483751/140451107-4e39fc5d-4066-4e2f-94e2-7cde99f7b5ec.png)
![IMG_20211105_100128](https://user-images.githubusercontent.com/24483751/140451276-7f2e1d10-4b5c-424d-9114-6c4e43f78874.jpg)

### Device information

- Device: Xaiomi mi 9
- OS: Custom Android 12
- App version snapshot 2.0 

### Additional context

Tried to clear data for all apps

**Comment by msfjarvis** [comment]
It most definitely works in Chrome, so this is not a Chromium issue. If Brave is doing something on their end to break things I can't help it.

**Comment by plant7403** [comment]
@msfjarvis but it's not only brave, chromium too 😅
I'm going to check chrome, will let you know the result

UPD: i can't install chrome 😂 it says something about missing library. I should investigate why, maybe it's somehow related to the face that i don't have any google on my phone 😅

**Comment by plant7403** [comment]
Checked Edge browser, not working either

**Comment by msfjarvis** [comment]
@fmeum is there anything for us to do here? I can confirm Chrome and Firefox work, and [Chromium Snapshots](https://download-chromium.appspot.com/?platform=Android&type=snapshots) and [MS Edge](https://play.google.com/store/apps/details?id=com.microsoft.emmx&hl=en_IN&gl=US) do not.

**Comment by fmeum** [comment]
I'm a bit confused. Did this work before? I will have to take a deeper look.

**Comment by msfjarvis** [comment]
> I'm a bit confused. Did this work before? I will have to take a deeper look.

I've never really tested with these specific browsers before so I'm not sure. I'll walk back through stable releases for APS and see if I can find one where it worked.

**Comment by plant7403** [comment]
@fmeum it should have worked on android 11, i think i used chromium, and i think it worked
And it worked with brave, but around a year ago, for sure because i was using brave when started to use aps

**Comment by fmeum** [comment]
@xxxcrow Could you run `adb shell settings get global autofill_compat_mode_allowed_packages` and provide me with the result? I suspect that the problem is that your browsers are missing from that list.

Something like the following fixed the issue with Edge for me: 
```
adb shell settings put global autofill_compat_mode_allowed_packages "$(adb shell settings get global autofill_compat_mode_allowed_packages):com.microsoft.emmx[url_bar]"
```

**Comment by plant7403** [comment]
@fmeum ``` adb shell settings get global autofill_compat_mode_allowed_packages ``` gave the output of: null
😃
And the second command helped, and the autofill started working for edge! 🎉
~~But it didn't help brave, i did the same command but with brave package name and still nothibg 😇~~

UPD: Brave needed a restart, now working!

**Comment by fmeum** [comment]
I contacted someone working on Edge, maybe they can convince vendors to add Edge to the compat list by default. But that's a very long shot, so I think we are done here.

**Comment by plant7403** [comment]
@fmeum so it's a fault of firmware manufacturers? 🤒 and what's about brave?

**Comment by msfjarvis** [comment]
> @fmeum so it's a fault of firmware manufacturers? 🤒 and what's about brave?

It's nobody's fault. Things work with Chrome because it owns enough market share to be included by default in that list. Re: Brave, they'll have to lobby OEMs themselves. Just because Fabian said they've asked people at Edge to try and get themselves added doesn't mean it'll happen anytime in the next few years, so I wouldn't really worry about it and stick with the manual adb steps.

**Comment by plant7403** [comment]
@msfjarvis it seems that the solution worked.. but not for very long, i will try do adb steps and try understand why it did reset
