### ISSUE TITLE
[FEATURE] XKPasswd -> Diceware

### ISSUE THREAD

**Issue by pinusc** [zeapo/Android-Password-Store#1547]
### Is your feature request related to a problem? Please describe.

Current XKPasswd-generated passwords (with the default wordlist) are... pretty bad. They don't even follow the format (simple everyday lowercase space-separated words) from [the original XKCD comic](https://xkcd.com/936/), to which I assume the feature owes its name.

This form of passphrase generation was popularized (and perfected) by the [Diceware Method](https://theworld.com/~reinhold/diceware.html). I have had much better luck with using their [wordlist](https://theworld.com/%7Ereinhold/diceware.wordlist.asc) to generate human-readable, memorable passphrases. 

Example of passphrase generated with Diceware wordlist:
```relay crept knee skies```

Example of passhprase generated with default wordlist:
```Somnic.ciala.yanned```

One of these is clearly better than the other.

### Describe the solution you'd like

The Diceware wordlist should be the default wordlist. 

Also, I propose changing the name of the feature to "Passphrase generator" or "Diceware Passphrase" or "XKCD passphrase". While many people recognize the XKCD comic, it's not a very descriptive name, wherease Passphrase _is_.

### Describe alternatives you've considered

While technically it's possible to import the diceware wordlist in the app, this requires first editing the file to remove the first word (numeric ID) from each line (For maximum security, they recommend generating each word by rolling a 6-sided die 5 times to obtain a 5-digit number corresponding with a word). This is cumbersome and I expect that non-vim/shell-users would find the editing process not immediate and be discouraged.

**Comment by msfjarvis** [comment]
I've never been a massive fan of the output from the XKPasswd generator, so I'd be open to taking a PR that replaces it with Diceware.
