### ISSUE TITLE
[BUG] cannot add/change passwords due to .gpg-id being invalid

### ISSUE THREAD

**Issue by SpecialBomb** [zeapo/Android-Password-Store#1548]
For some strange reason, APS finds my .gpg-id to be invalid. I am not sure why this is, as `pass` works fine on all of my desktop devices without issue. My gpg-id is just `quen@quen`, so I'm wondering if this has to do something with expecting a valid email address for a key's `uid`.

Other than this, APS works perfectly fine and I can decrypt my passwords using my nfc gpg device. It sometimes has trouble syncing though, but that's inconsistent.

**Comment by msfjarvis** [comment]
It's an OpenKeychain limitation, we've submitted a fix for it upstream (https://github.com/open-keychain/open-keychain/pull/2699) but they have not made a release with that included yet and since the app is now in maintenance mode, it's unlikely they ever will.

**Comment by SpecialBomb** [comment]
Why exactly is that? I thought open keychain was a pretty important app for
a lot of people. Is there anything I could do about it?

**Comment by msfjarvis** [comment]
> Why exactly is that? I thought open keychain was a pretty important app for
a lot of people. Is there anything I could do about it?

It's the reality of open source, the app being useful or crucial does not ensure its continued maintenance. To get the fix for yourself you'll need to build the app yourself from the GitHub repository, there's nothing else to be done.

**Comment by SpecialBomb** [comment]
I see, thats quite frustrating. I was reading the implementation switch RFC
and looked at OK's maintenance commit. It's certainly a shame. I really
wish I could actively contribute to projects like this, but development is
simply something I can't do.

With that said though, I find what you're doing extremely awesome and
important in the context of the current proprietary mess of the password
manager ecosystem. If there's anything I can do to assist the project that
isn't necissarily development related, I'd be willing to do it.

**Comment by msfjarvis** [comment]
> I see, thats quite frustrating. I was reading the implementation switch RFC
and looked at OK's maintenance commit. It's certainly a shame. I really
wish I could actively contribute to projects like this, but development is
simply something I can't do.
> 
> With that said though, I find what you're doing extremely awesome and
important in the context of the current proprietary mess of the password
manager ecosystem. If there's anything I can do to assist the project that
isn't necissarily development related, I'd be willing to do it.

Thank you for your kind words. If you wish to contribute, there's a lot to do even without writing code. Documentation is a very sore point thanks to GPG and its complexities, so if you can think of anything that should go into to our [docs](https://github.com/android-password-store/docs) repo that'd be a huge help to the community at large.
