### ISSUE TITLE
[FEATURE] Is there any plans to add APS to "Connected apps" for working profile?

### ISSUE THREAD

**Issue by plant7403** [zeapo/Android-Password-Store#1589]
### Is your feature request related to a problem? Please describe.

It's not very convenient when autofil is not working in working profile
I know i should have a separate password manager for working profile, but it's one more setup

### Describe the solution you'd like

Can't find ANY info about this topic, but maybe you android experts know better
Connected apps in android! Install APS on both profile, connected apps, and now APS is the same for regular and working profile

### Describe alternatives you've considered

Manually copying and pasting passwords and logins?
Installing one more password store on working profile?
Maybe some adb command is available to connect the app, it would be good too

**Comment by msfjarvis** [comment]
Work profile intentionally isolates apps so there's no such thing as "connected apps". There's nothing to do here.

**Comment by plant7403** [comment]
I'm sorry, but... 🙁
Here it is 😥 it should actually have more descriptions(it had in a11, but my a12 rom is too fresh and lacks a lot of ui)
![Screenshot_20211213-223321_Settings](https://user-images.githubusercontent.com/24483751/145840913-df1ec844-40a5-49a0-a93c-03ea2023dd7e.png)
![Screenshot_20211213-223317_Settings](https://user-images.githubusercontent.com/24483751/145840955-7305f174-a1e0-4bf6-8a47-8e912517df37.png)
Also here's some documentation
https://developers.google.com/android/work/connected-apps

**Comment by msfjarvis** [comment]
This requires a separate library, extra work to handle all of the storage related interactions, and has a waitlist for a specific permission you need to be approved for before you can publish to Play Store. For something I will never ever use, this is way too much work. I'm hesitant to even accept a PR for this simply because of how much overhead it adds in terms of Play Store review.
