### ISSUE TITLE
[FEATURE] Password authentication as fallback to biometric when launching the app

### ISSUE THREAD

**Issue by byter11** [zeapo/Android-Password-Store#1626]
### Is your feature request related to a problem? Please describe.

Fingerprint scanners aren't very reliable in some phones, especially in winter it needs to be constantly recalibrated

### Describe the solution you'd like

It should work like it does while generating an ssh key, after a failed attempt it shows the password option as an alternative

### Describe alternatives you've considered

An alternative could be a separate password authentication option

### Additional context

Let me know if it's a practical feature request, maybe I can help implementing it :)

**Comment by byter11** [comment]
Actually just realised that after 5 invalid attempts at opening the app, it asks for password. So this is more of a bug report I guess, the biometric prompt shouldn't close after 1 attempt

**Comment by msfjarvis** [comment]
The offending line is [here](https://github.com/android-password-store/Android-Password-Store/blob/527b09ee5fbe9d70e6078fb9840c9c4786da280f/app/src/main/java/dev/msfjarvis/aps/ui/main/LaunchActivity.kt#L36). To fix it you'll need to tweak the [checks in BiometricAuthenticator](https://github.com/android-password-store/Android-Password-Store/blob/527b09ee5fbe9d70e6078fb9840c9c4786da280f/app/src/main/java/dev/msfjarvis/aps/util/auth/BiometricAuthenticator.kt#L47-L64) to take in account [all return values](https://github.com/androidx/androidx/blob/androidx-main/biometric/biometric/src/main/java/androidx/biometric/BiometricPrompt.java#L66-L183) from the AndroidX `BiometricPrompt` API and return appropriate values.
