### ISSUE TITLE
[FEATURE] Autofill for Vanadium and Bromite

### ISSUE THREAD

**Issue by Rudd-O** [zeapo/Android-Password-Store#1631]
### Is your feature request related to a problem? Please describe.

Autofill does not work with either of these browsers.

### Describe the solution you'd like

Autofill to work.

### Describe alternatives you've considered

Uh, none.

**Comment by msfjarvis** [comment]
Bromite had removed the Android autofill service a while ago (https://github.com/android-password-store/Android-Password-Store/issues/1422) which caused it to be removed from our supported browsers list. It seems they've [backtracked on it](https://github.com/bromite/bromite/commit/76add6b7dcf68ce4d259b58dc85ae6fb9e990787) around October. Nobody's asked for Vanadium support yet, I'll test and see if it works and then add it.

**Comment by msfjarvis** [comment]
Vanadium cannot be supported since they [use the Chromium package name](https://github.com/GrapheneOS/Vanadium/issues/34) and I can't allocate it to a third-party build of the Chromium codebase that doesn't even have an easy way to use outside GrapheneOS.

**Comment by ljrk0** [comment]
I wonder how Bitwarden does this since there autofill works fine even on Vanadium.

**Comment by msfjarvis** [comment]
> I wonder how Bitwarden does this since there autofill works fine even on Vanadium.

Password Store maintains an internal list of browsers it knows the autofill capabilities of, I'm assuming Bitwarden does not care for feature and trust detection.

**Comment by ljrk0** [comment]
Ah, I see.  A bit unfortunate of course in this case.  Hopefully this can be resolved on GrapheneOS' side soon-ish.

Thanks for answering!

**Comment by thestinger** [comment]
Vanadium now uses the app.vanadium.browser app id.

**Comment by Rudd-O** [comment]
Please reopen @msfjarvis thanks.

**Comment by thestinger** [comment]
Worth noting: Chromium itself only supports Vanadium with the Play API for it and Vanadium is currently the same way since we haven't yet merged patches for native Android autofill API. It should already work for this regardless. We'd ideally like to get native autofill patches upstream because it's quite invasive and we think of invasive changes as having a substantial cost and need to budget them to the most important use cases for improving privacy / security.

**Comment by msfjarvis** [comment]
@Rudd-O [I've added Vanadium](https://msfjarvis.dev/aps/9975034053d3) but I can't test it myself so you'll have to do it yourself [using the snapshot builds](https://docs.passwordstore.app/docs/users/release-channels).

**Comment by jceloria** [comment]
> 
My pixel 5 still shows:
```
version 110.0.5481.61

org.chromium.chrome
versionCode 548106133

targetSdk 33
minSdk 29

Installed: Dec 31, 2008; 19:00
```

**Comment by msfjarvis** [comment]
This issue tracker is not for help with your GrapheneOS installation, please get in touch with the GrapheneOS project through one of their own support channels.

**Comment by jceloria** [comment]
My apologies, I followed another issue here and replied without thinking
about it.

**Comment by Rudd-O** [comment]
When is this slated for release in F-Droid?

**Comment by msfjarvis** [comment]
> When is this slated for release in F-Droid?

There's no set date, it'll go out when the [v2.0.0 release board](https://github.com/orgs/android-password-store/projects/1/views/1) is done.
