### ISSUE TITLE
Cloning from git : Internat Exception Occured

### ISSUE THREAD

**Issue by Ulrar** [zeapo/Android-Password-Store#164]
Hi,

When I try to clone my repo (from my gitlab), I get this :

 Message from jgit:
 invalid advertisment of
 {"GL_ID":"user-2","RepoPath":"<My path here>"}

Is that because it's not a bare repo ? Not an expert in git, I admit. Does that mean you can't actually use a "real" repo with this app ? Is it planned ?

Thanks

**Comment by DSIW** [comment]
I think your remote repository has to be a bare repository. You can check it by running `mkdir ~/pass.git; cd ~/pass.git; git init --bare` on your server. Then add this remote to your local git repository by running `cd ~/.password-store; git remote add origin2 ssh://user@your_server/pass.git; git checkout master; git push origin2 master`. Then add your public ssh-key on your phone to ~/.ssh/authorized_keys on your server and change your git settings in Password Store. If it works this way, I think you have a problem with your gitlab instance.

**Comment by bignose-debian** [comment]
This is difficult for the developers and impossible for the users to even diagnose, because the message should not be this uninformative. Issue #219 requests better treatment of exceptions like this one.

**Comment by zeapo** [comment]
Closing as we'll regroup everything in #219
