### ISSUE TITLE
Android full disk encryption and autofill

### ISSUE THREAD

**Issue by JasperWeiss** [zeapo/Android-Password-Store#166]
When enabling Autofill Android says "If you turn on password store, your device won't use your screen-lock to enhance data encryption."

I'm not sure if I understand, what does autofill have to do with full disk encryption?

**Comment by wongma7** [comment]
Unfortunate android limitation there is no way around :/ https://lastpass.com/support.php?cmd=showfaq&id=8936 https://code.google.com/p/android/issues/detail?id=79309

**Comment by JasperWeiss** [comment]
From what I can understand, Android figures because my password manager isn't available on boot it disables the the encryption password. 
Can I just re-enable it or will my encryption be permanently rendered useless?

**Comment by wongma7** [comment]
Yes, you should be able to just re-enable it. The message makes it sound like there's no way around it but I read more and I understand now. I found more/newer discussion here http://code.google.com/p/android/issues/detail?id=196830 .

**Comment by DSIW** [comment]
DSIW
