### ISSUE TITLE
[BUG] "Cant' show protected content on your computer." error in Samsung DeX

### ISSUE THREAD

**Issue by sjevtic** [zeapo/Android-Password-Store#1665]
### Describe the bug

Opening a stored password when the app is shown in Samsung DeX produces a black window accompanied by a toast stating "Cant' show protected content on your computer. ..."

### Steps to reproduce

Open any password while app is displayed in Samsung DeX.

### Expected behavior

Password and supporting data is shown after decryption.

### Device information

- Device: Samsung Galaxy S20+
- OS: Android 11 (G986BXXUBDUI5)
- App version 1.1.3.5

### Additional context

While the described behavior may represent a reasonable default, not having a setting to override such protection is unwelcome and wholly unacceptable.

**Comment by msfjarvis** [comment]
I'm not going to offer settings to turn off each security feature that ever inconveniences a user.
