### ISSUE TITLE
Internal exception occured after first git-pull

### ISSUE THREAD

**Issue by DSIW** [zeapo/Android-Password-Store#167]
After I run "Pull from remote" I get this message:

> Internal exception occured
> Message from jgit: Could not read an object while parsing commit abc123

`abc123` is the commit hash of origin/master. After I commited something and pushed it to remote repository and pulled again, I get the same message with the commit hash of last commit in origin/master.

I also tried "Synchronize repository", but the message is the same. I checked my git settings, but these are correct.

Password Store 1.2.0.38 is installed from f-droid.

What can I do to fix this? Thank's!

**Comment by yxth** [comment]
I'm having the same issue. I've tried Bitbucket and GitLab.

**Comment by Brottweiler** [comment]
@yxth So, you go into settings and "Delete repository", then you press "Create New", "Hidden", then "Pull from remote"? This results in "No value for key remote.origin.url found in configuration" for me.

**Comment by Brottweiler** [comment]
@zeapo Do you have any clue about the above issue?

The first thing I did after setting up this app on my new phone, was the OpenKey things, then this app. I added the git repo information, and generated a SSH key and put it on BitBucket. First thing I pressed after creating new hidden repo, was sync repo. I got the issue the others are reporting, and pulling from remote got same issue. Now, after deleting and then setting up again and pulling, I get the `No value for key remote.origin.url found in configuration` problem.

**Comment by Brottweiler** [comment]
I guess I should update. So on the first screen you select either create new repo, or clone existing. For some reason, I thought that new repo means creating a new one empty, then pulling from the remote, and existing repo would mean there was already a repo on the phone and you would "add it", or something.

So in my earlier comments, I had pressed "Create New → Hidden" repo, when I was supposed to press "Clone existing → Hidden". So sorry guys for the mistake!

**Comment by zeapo** [comment]
Sorry for the delay.

@DSIW This message (as cryptic as it is) means that you have a conflict during the rebase, the **pull** is in fact a rebase. We sadly are unable to handle the conflicts on our end and as long as you are not rooted, the only (actual solution) is to delete the store on your phone and clone back. Sorry for this issue, I'll try to address as soon as I can.

@Brottweiler A new version will be available next few days to clear the confusion about "Clone Existing" and "Create New" see https://github.com/zeapo/Android-Password-Store/issues/161#issuecomment-214519766 Sorry that you used the wrong option. I will try to update the readme to explain the difference.
