### ISSUE TITLE
Autofill actions broken on snapshots

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1681]
### Discussed in https://github.com/android-password-store/Android-Password-Store/discussions/1680

<div type='discussions-op-text'>

<sup>Originally posted by **xxxcrow** January 24, 2022</sup>
Recently reinstalled many apps, and noticed that aps password search stopped working
I'm using latest snapshots, tried openkeychain and builtin pgp, both don't do anything on "show passwords" from autofil</div>

Regression from #1655, specifically [`b8ce4f3` (#1655)](https://github.com/android-password-store/Android-Password-Store/pull/1655/commits/b8ce4f314538749384b65201bd6ed0bd301a81dc).

**Comment by plant7403** [comment]
Now it's working 🤩 thank you
