### ISSUE TITLE
[BUG] SSH key authentication won't work after switching to openkeychain/password(?)

### ISSUE THREAD

**Issue by plant7403** [zeapo/Android-Password-Store#1688]
### Describe the bug

If i try to use password or openkeychain authentication for the git repo i can't go back to ssh key
It says "valid authentication modes for ssh: openkeychain, password, sshkey"
And i even managed to get some error, will attach below, because it's not that related

### Steps to reproduce

1. Go to the setting, repository tab
2. Click on openkeychain
3. Go back and use it
4. Come back to the settings
5. Be not able to switch back to ssh key

### Expected behavior

Switching back to ssh key

### Device information

- Device: Xiaomi Mi 9
- OS: AOSP 12.0
- App version: snapshot, recent

### Additional context

Oh, while i was filling the issue i was pressing all the buttons in different combinations, and managed to make it work

**Comment by plant7403** [comment]
## Here's the error by the way
![Screenshot_20220127-075625_Password Store](https://user-images.githubusercontent.com/24483751/151272444-e98e3a17-6cfc-430f-b55d-636d16ad53dd.png)

## And the problem itself
![Screenshot_20220127-075838_Password Store](https://user-images.githubusercontent.com/24483751/151272662-ab183424-1890-479c-b686-62811044238e.png)

**Comment by trev-dev** [comment]
I'm trying to use my GPG Auth key for cloning my repo and I can unlock my key but I'm being repeatedly asked for an ambiguous "repo password". Is this related?

Password Store is triggering my fail2ban with repeated failed attempts. I assume it's sending something invalid over. My Auth key works fine from my desktop.

**Comment by msfjarvis** [comment]
> I'm trying to use my GPG Auth key for cloning my repo and I can unlock my key but I'm being repeatedly asked for an ambiguous "repo password". Is this related?

It's not. If you're being asked for a password it means the previous authentication method failed and the app is falling back to password auth.

> 
> Password Store is triggering my fail2ban with repeated failed attempts. I assume it's sending something invalid over. My Auth key works fine from my desktop.

If you can find what exactly is invalid in the request then please file a separate issue. I have no experience with fail2ban and zero interest in spending time to replicate your setup so you'll need to debug this on your end and give me actionable information.

**Comment by trev-dev** [comment]
> It's not. If you're being asked for a password it means the previous authentication method failed and the app is falling back to password auth.

Ok, thanks

> If you can find what exactly is invalid in the request then please file a separate issue. I have no experience with fail2ban and zero interest in spending time to replicate your setup so you'll need to debug this on your end and give me actionable information.

Understood. If it's helpful to know my key is a newer ed25519 with gpg 2.3.4. On my laptop I'm using gpg-agent for ssh authentication. If anything, I think this isn't a possible setup with Password Store. I exported a normal SSH key and I can pull the repos down, but I had to re-encrypt my whole password store without the AEAD features to decrypt my passwords (OpenKeychain issue?)

Anyway, I only had this thought because I was attempting to use OpenKeychain for Auth and assumed the SSH auth wasn't getting sent up as intended. I am open to generating whatever debug logs you would like.

**Comment by msfjarvis** [comment]
OpenKeychain has been removed in the development builds so this no longer applies.
