### ISSUE TITLE
Custom ssh port ignored

### ISSUE THREAD

**Issue by maxmil** [zeapo/Android-Password-Store#169]
I configure the server settings with a custom ssh port, in the resulting url field I see something like

user@server:customport/path/to/repo

However when trying to synchronize I get

failed to connect to ..... (port 22): connect failed.

It looks like it is ignoring my config. This was working not long ago so might have been broken recently.

**Comment by wongma7** [comment]
What version are you using? Is it from the Play store? I fixed a bug with saving configs recently. What could happen is 'Save' doesn't work correctly even though the first time you made a config and hit 'Clone' it worked.

**Comment by zeapo** [comment]
I've just published the 59 in the play store.

**Comment by maxmil** [comment]
Thanks for the speedy response. I updated and that fixed it. Looks like it
was save not working as you mentioned. I had to re save my configuration to
get it to work.
