### ISSUE TITLE
Can't enable autofill while Lux is running

### ISSUE THREAD

**Issue by maufl** [zeapo/Android-Password-Store#171]
I was unable to enable autofill in the accessibility settings. It did not report an error, the OK button simply was not working.

After googleing, I found out that it was because I was running Lux, which adjusts the color temperature of my display. It seems that you can not enable an accessibility service while another service is accessing the whole screen.

There's probably no fix for that, I just wanted this information to be in this repo. Maybe it can be added to the README.

**Comment by polyzen** [comment]
Probably a good fit for the faq.

You may want to check [Twilight](http://twilight.urbandroid.org/) out (not that it works around this "issue"). Scheduled use doesn't require buying the unlock. Afaik it doesn't have the ambient light feature..

**Comment by wongma7** [comment]
I put it in the wiki https://github.com/zeapo/Android-Password-Store/wiki . Since the README is already quite lengthy I'm hoping the wiki can be used for this kind of info.
