### ISSUE TITLE
[FEATURE] Use domain name as search rather than app name

### ISSUE THREAD

**Issue by raxod502** [zeapo/Android-Password-Store#1715]
### Is your feature request related to a problem? Please describe.

Please correct me if I'm wrong about how this works, but it seems like APS uses the name of the current app as a search query in my password store, rather than a domain name. For example, if I'm in the `Paper Karma` app, then `Paper Karma` is used as the search query, rather than `paperkarma.com`, which is what I would expect and prefer, since `Paper Karma` will not match my store entry at `paperkarma.com/radon.neon@gmail.com`. So, I then have to delete `Paper Karma` and type in `paperkarma` to find the entry I want.

For apps whose names are only a single word, usually the app name is a substring of the domain name, so it works well enough, though still not ideally.

<p align="center"><img src="https://user-images.githubusercontent.com/6559064/152661190-8b17169b-841c-4b1b-933f-798501ac990d.png" width="300px"/></p>

The most difficult part would presumably be to determine what domain name should be used for a given native app UI. This may not be possible in general, in which case there's nothing to be done, but I wasn't able to find any past issues on the APS tracker that seemed related, so I thought maybe it had never been considered.

### Describe the solution you'd like

Ideally, the default autofill search query would "just work", as in it would be a domain name that was related to the app and was usually the one that I have an entry under in my password store.

### Describe alternatives you've considered

If information about the mapping from app name to domain name can't be retrieved automatically, perhaps there could be a way for the user to submit that information and it would then be remembered on future occasions. Or, perhaps there could be a central database that could grow to contain entries for most common apps over time.

### Additional context

I'm happy to spend some time working on an implementation for this feature if there is interest. I would just like to know if I have a correct understanding of the situation, and whether such a change would be desired, before doing so.

**Comment by msfjarvis** [comment]
This is simply not possible, which is why the search option is present. Autofill matches are remembered by default so you only need to search and select once, and every subsequent time the app will know to fill from `paperkarma.com`.
