### ISSUE TITLE
Service stops when switching tabs in Firefox

### ISSUE THREAD

**Issue by seylerius** [zeapo/Android-Password-Store#172]
CyanogenMod 12.1, Firefox 44.0.2, PwdStore 1.2.0.39

If I have the auto-fill service running and attempt to switch tabs in Firefox, the service crashes with an "Unfortunately, Password Store has stopped" messag most times I enter and exit the tab list. After three crashes, it stays crashed and I have to disable and re-enable the service to regain auto-fill.

**Comment by wongma7** [comment]
Confirmed, I'll figure out what's happening

**Comment by seylerius** [comment]
I can also confirm it *doesn't* happen on Lightning Browser, but doesn't offer auto-fill in Lightning either.

**Comment by wongma7** [comment]
If you are interested in autofill support for Firefox/Lightning/other browsers please feel free to open another issue for them. I can't promise anything though.
