### ISSUE TITLE
[BUG] PGP key with multiple identities fails to import

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1735]
### Describe the bug

A GPG key with more than one identity fails to import with the PGPainless backend

### Steps to reproduce

1. Get test keys from https://msfjarvis.dev/apsg/pass-test/406de9b7f0fc
2. Attempt to import private key with PGPainless backend

### Expected behavior

Key imports successfully

### Screenshots

N/A

### Device information

- Device: Pixel 4a
- OS: Android 12
- App version: 3939003dececfec80cf7e8d3d776b50686e0f125

**Comment by vanitasvitae** [comment]
Let me know if I can help you out with anything :)

**Comment by msfjarvis** [comment]
> Let me know if I can help you out with anything :)

PGPainless seems to be doing its job correctly, the failure is in the formatting code [here](https://github.com/android-password-store/Android-Password-Store/blob/f6dd7e338f9e9a58fd7ae641f0aa95f976ed2b6e/crypto-pgpainless/src/main/kotlin/dev/msfjarvis/aps/crypto/KeyUtils.kt#L36) which appears to overflow a Long. Still investigating why that happens.

**Comment by moppman** [comment]
Continued from [here](https://github.com/android-password-store/Android-Password-Store/issues/1523):
I deleted the second identity from the key, but I'm still getting the same error on import, which was surprising to me at first, but then I [read](https://superuser.com/questions/1062512/updating-openpgp-keyserver-adding-and-removing-identities)  that removed identities aren't actually "deleted" but only revoked via special signature. 
So the overflow bug would still make sense here. :face_with_spiral_eyes:

**Comment by vanitasvitae** [comment]
I'm still a bit confused... Why does an additional user-id have an impact on key-id calculation? :thinking: 

Edit: Looking at the code, why are you hex-encoding the key-id [here](https://github.com/android-password-store/Android-Password-Store/blob/f6dd7e338f9e9a58fd7ae641f0aa95f976ed2b6e/crypto-pgpainless/src/main/kotlin/dev/msfjarvis/aps/crypto/KeyUtils.kt#L36), and then immediately decoding it again to calculate the key-id? Shouldn't just passing `keyRing.publicKey.keyID` to the `KeyId` constructor be sufficient?

Still, there might be a bug in the encode/decode function?

I'm not fluent in Kotlin, so maybe I'm missing something?

**Comment by msfjarvis** [comment]
> Edit: Looking at the code, why are you hex-encoding the key-id [here](https://github.com/android-password-store/Android-Password-Store/blob/f6dd7e338f9e9a58fd7ae641f0aa95f976ed2b6e/crypto-pgpainless/src/main/kotlin/dev/msfjarvis/aps/crypto/KeyUtils.kt#L36), and then immediately decoding it again to calculate the key-id? Shouldn't just passing `keyRing.publicKey.keyID` to the `KeyId` constructor be sufficient?

goddamnit 🤦🏼

I wish I could tell what was going on in my head when I wrote that. 1956b66c6d2d fixes the failing test for me, once #1741 lands and I get snapshots rolling again this should be fixed.
