### ISSUE TITLE
stock email app crashes due to autofill

### ISSUE THREAD

**Issue by zeapo** [zeapo/Android-Password-Store#174]
A comment on the play store:
>When I open the app itself everything works awesome, but when I open other apps most noticeably the stock email app I always get a notification that pass has crashed. I'm guessing this is the service that runs in the background.

phone: Galaxy S5
version: 59 (1.2.0.39)
OS: Android 5.1

@wongma7 could your fix for the firefox crash be also a fix for this case?

**Comment by wongma7** [comment]
Probably, I wrongly assumed accessibilityNodeInfos couldn't have null packagename leading to NPE, so the fix wasn't specific to firefox, it could potentially apply to any app. Obviously I did not find this issue in my own bit of testing when I used the stock email app/other apps myself, I'm guessing this is one of those Samsung-specific quirks I've heard so much about...

**Comment by zeapo** [comment]
Thanks for your feedback. I will put the 1.2.0.40 on the play store and see if it happens again.

For Kotlin, I will write a small post about what I'm doing and once I finish adding encrypt/decrypt I will put it on github.

**Comment by zeapo** [comment]
BTW, there are some other issues related to Samsung, especially on kitkat that I discarded as they require a lot of specific work and no time to test.
