### ISSUE TITLE
[BUG] XkPassword generator crashes if param == ""

### ISSUE THREAD

**Issue by max-ishere** [zeapo/Android-Password-Store#1757]
### Describe the bug

Empty password generator fields crash the app or just the generator.

### Steps to reproduce

1. Open XkPassword generator
2. Set fields to empty. I think its only the separator field
3. Try to generate the password
4. App or only the generator crashes

### Expected behavior

Error message or logical behavior (e.g. separator == "": no separator, just words together)

### Device information

- Device: Samsung J730
- OS: stock ROM Android version 9
- App version 1.13.5

**Comment by msfjarvis** [comment]
The XkPasswd generator has been removed in the development branch, and we do not intend to make any further releases for the 1.13.x track so I'm going to close this issue as a wontfix.
