### ISSUE TITLE
Autofill not working in Firefox 

### ISSUE THREAD

**Issue by daniel-sousa-me** [zeapo/Android-Password-Store#176]
Currently autofill is not working in Firefox. Is there any way around this?

**Comment by wongma7** [comment]
Unfortunately no, Firefox doesn't send accessibility events out like Chrome and webviews https://bugzilla.mozilla.org/show_bug.cgi?id=961540 



    _____________________________

**Comment by brainard52** [comment]
I've created a question on support.mozilla.org for this problem:
https://support.mozilla.org/en-US/questions/1184142

**Comment by wiktor-k** [comment]
By the way I wonder how the Accessibility Service support in Password Store continue after this: http://www.androidpolice.com/2017/11/12/google-will-remove-play-store-apps-use-accessibility-services-anything-except-helping-disabled-users/

**Comment by brainard52** [comment]
To be honest, I think Password Store will be fine. It's available on f-droid. On top of that, Android O is supposed to have good autofill support. If Firefox takes advantage of that, it should be fine.

**Comment by zeapo** [comment]
Sadly I've received an email asking me to remove the accessibility service.
In the next few days I'll see how to build two versions of the app to avoid having to unpublish it from Play Store.

**Comment by zidhuss** [comment]
The new Autofill API is discussed in #410.
