### ISSUE TITLE
how to edit entries

### ISSUE THREAD

**Issue by regagain** [zeapo/Android-Password-Store#177]
There is an edit icon in the upper-right corner but I'm never able to touch it: after entering the password I am taken back to previous screen. If I had already entered the password, I am also taken back to the previous screen. 

The "automatically copy password" setting is disabled.

The version I use is 1.2.0.40, from F-Droid. 

How can I edit entries?

Thank you,

**Comment by zeapo** [comment]
Can you check the "Password show time" in the settings?

**Comment by regagain** [comment]
Thank you! **Password show time** was set to 45, but **Show the password** was disabled. It works now.

...but I think it would be a nice enhancement to allow editing even when **Show the password** is disabled.

**Comment by zeapo** [comment]
It would be indeed interesting to have an edit button after a long press.

**Comment by wongma7** [comment]
Commited to master, now there is a button beside the trash when you have selected one password with long press.

**Comment by wongma7** [comment]
sorry for taking so long to push this, this will be in the next version .44

**Comment by regagain** [comment]
This is great, thank you!
