### ISSUE TITLE
[BUG] Unable to use Syncthing for syncing

### ISSUE THREAD

**Issue by DokStook** [zeapo/Android-Password-Store#1775]
### Describe the bug

Hello, I am unable to use Syncthing for syncing my database. When I try to sync the repo I get "Git url is not set!". I have seen olher issues with the same or similar problems but the sollutions from there didn't help me. 

### Steps to reproduce

1. Open the app for first time
2. Select "create local repo"
3. Select "SD-Card"
4. Allow storage access
5. Select repo path
6. Select GPG key
7. The thing mentioned above

### Expected behavior

See all my passwords in my local repo

### Device information

- Device: Xiaomi Redmi Note 10 PRO
- OS: OmniROM
- App version 2.0.0-SNAPSHOT

**Comment by DokStook** [comment]
I also suggest to add option where you disable the git repo and allow other syncing methods

**Comment by msfjarvis** [comment]
Creating repositories in external storage is broken in the development builds IIRC, can you try the [Play Store](https://play.google.com/store/apps/details?id=dev.msfjarvis.aps) version instead? We already have plans w.r.t. external repos and Git: see #1118.

**Comment by msfjarvis** [comment]
FWIW, syncing not working is completely intentional. We can't "sync" if you do not have a Git repository in the first place, but if there's an external repository with a `.git` directory the app will still make attempts to treat it as a proper Git repository and thus asks for a Git remote URL to be set. As mentioned in the comment above, we plan to change that.

**Comment by DokStook** [comment]
I would at least like to see all the files in the selected folder. In my experience this is impossible...

**Comment by msfjarvis** [comment]
> I would at least like to see all the files in the selected folder. In my experience this is impossible...

Did you try the stable release like I asked?

**Comment by DokStook** [comment]
Yes, but it didn't work either. I decided to create private gitlab repo and clone it that way. It works for now. I will wait until I can use the app without rely on 3rd parties. Love for the work you do and I will donate as soon as possible!
