### ISSUE TITLE
Unable to use pre-populated external directory

### ISSUE THREAD

**Issue by rqcy** [zeapo/Android-Password-Store#178]
Hi, I have a directory with passwords on /sdcard which is synchronized using an external tool.

I'm unable to select it as an “external repository” without Password Store trying to “remove everything.”

Thanks in advance for fixing it!

**Comment by wongma7** [comment]
You can safely select it, the app won't remove everything as reported here: https://github.com/zeapo/Android-Password-Store/issues/161 . I will change the message when I get a chance, keep forgetting about it

**Comment by rqcy** [comment]
> You can safely select it, the app won't remove everything as reported
> here: https://github.com/zeapo/Android-Password-Store/issues/161 . I
> will change the message when I get a chance, keep forgetting about it

Thanks for the info and sorry for the duplicated issue.

When you change the message, please have a look on “Crypto” menu too.
There are two items “Select key” and “Select OpenPGP Key id” and it's
not clear what the difference is.

Thanks for the software!

**Comment by zeapo** [comment]
see https://github.com/zeapo/Android-Password-Store/issues/161#issuecomment-214519766
