### ISSUE TITLE
[FEATURE] Support sk-ssh-ed25519 keys stored at Yubikey

### ISSUE THREAD

**Issue by S-o-T** [zeapo/Android-Password-Store#1786]
### Is your feature request related to a problem? Please describe.

sk-ssh-ed25519 keys seems to be unsupported, following message displayed on pull attempt: "Don't know how to decode key:unknown"

### Describe the solution you'd like

Add support for sk-ssh-ed25519 keys stored in yubikey.

### Describe alternatives you've considered

Nothing.

**Comment by msfjarvis** [comment]
[tadfisher](https://github.com/tadfisher) appears to have [made significant progress](https://github.com/android-password-store/Android-Password-Store/discussions/2129) on using PGP keys over USB/NFC so there should be news on this front sooner than later.

**Comment by sebastianrasor** [comment]
It'd be awesome to see this implemented, I'm not sure if sk SSH keys *can* be read over NFC though

**Comment by SpyHoodle** [comment]
@sebastianrasor They can - [Termius](https://support.termius.com/hc/en-us/articles/5618120162457-FIDO2-based-SSH-keys-ed25519-sk-and-ecdsa-sk-) does this on iOS and I have used this feature before

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
