### ISSUE TITLE
Allow setting password store to existing store folder

### ISSUE THREAD

**Issue by stuartlangridge** [zeapo/Android-Password-Store#181]
I've synced my password store folder with my phone using an existing sync tool: I'm not using this app to do the syncing. However, I can't then tell Password Store to use that existing folder; it tells me that the contents of the folder will all be deleted. I'm glad that message was there (thank you!) but it would be good if the message wasn't needed and Password Store could use my existing folder.

**Comment by zeapo** [comment]
Please see #161 and https://github.com/zeapo/Android-Password-Store/wiki/First-time-setup

TL;DR use "Create New" if you are in a version prior to 41 or "Use local directory" on newer versions.

**Comment by stuartlangridge** [comment]
So, to confirm from reading #61, although choosing Create New and picking an existing folder shows a warning saying "You have selected a non-empty directory for the store. This is extremely dangerous and you will lose your data as its content will be deleted", that warning isn't actually the truth and my data will actually not be deleted?

**Comment by zeapo** [comment]
You're absolutely right and I have to fix that. I forgot about it before closing #161 

I will reformulate it as being "you might potentially lose your data if you decide to delete the repository".
Which in itself wont be right as I am going to disable the removal of the files if the user decides to delete an external repository.

**Comment by zeapo** [comment]
fixed in c866596d135937f768b060c24c6e7b17e49d03ee
