### ISSUE TITLE
Errors in display folder list

### ISSUE THREAD

**Issue by pbeckmann** [zeapo/Android-Password-Store#182]
Hello,

since the update to .42 via FDroid the distance between two folder/passwords is as big AS the screen is high. 

OnePlus One (Bacon)
380 DPI
Android 6.0.1 (CM13 by SultanXDA)

Screenshots are incoming...

![tmp_27075-screenshot_20160428-1938011319020887](https://cloud.githubusercontent.com/assets/4943721/14895560/8f6e2fa0-0d79-11e6-878f-d0c44f06ec56.png)
![tmp_27075-screenshot_20160428-1938041875315960](https://cloud.githubusercontent.com/assets/4943721/14895562/91673f04-0d79-11e6-818c-4b7ad48c613f.png)

Greetings

**Comment by zeapo** [comment]
fixed in https://github.com/zeapo/Android-Password-Store/commit/82403f262d35edd2987f558037e907a5f720de1e

Sorry for this issue, I didn't test it on Marshmallow before tagging. The .43 was tagged this morning, hopefully it will be available by tomorrow. You can downgrade to .40 in the meantime.

**Comment by pbeckmann** [comment]
Thanks for the quick reply. 

Saw the commit messages and the code changes. Was just a bit unsure if it addresses the issue. 

No need to downgrade. The search runs very well 😊👍👍

**Comment by pbeckmann** [comment]
Its fixed in the new app.

Its really a great app. 

Thank for your work!
