### ISSUE TITLE
[BUG] Documentation: importing extra IDs

### ISSUE THREAD

**Issue by nyarly** [zeapo/Android-Password-Store#1835]
### Describe the bug

(c.f. https://github.com/open-keychain/open-keychain/issues/2588#issuecomment-1093188404)

In a store with multiple keys, OpenKeychain returns an error when creating new passwords: `Missing key for encryption: %s` unless all the keys are imported into OpenKeychain.

In cases where APS is being used for a single user, and the keypair is shared between devices, this wouldn't occur. But if there are multiple keys needed, they need to be manually imported, and no documentation indicates this requirement.

### Steps to reproduce

Create a `pass` store with multiple keys; the .gpg-id file will have more than one line.

Set up APS on your phone. Generate a new key on the phone in OpenKeychain, and add its ID to the `.gpg-id` file on your workstation. Push the updated store, and pull into APS.

Create a new password in APS.

See `Missing key for encryption: %s` error, and wonder how to fix it.

The fix is: import the keys generated elsewhere into OpenKeychain on the phone (easiest approach appears to be: manually write vcards for those IDs, and use `qrencode` to generate QR code and import into OpenKeychain...)

### Expected behavior

The error reported when adding a password should indicate that there are public keys missing from the local keychain, which would prompt a user to import them.

Documentation somewhere about initial phone setup that mentions the import.

### Device information

- Device: [e.g. Google Pixel 2]
- OS: [e.g. stock ROM Android version 9.0]
- App version [e.g. 3.1.0]

**Comment by msfjarvis** [comment]
The missing key error is entirely coming from OpenKeychain so that needs to be fixed on their end. Password Store has no way of knowing which keys OpenKeychain has so we can't tell users what they're missing.
