### ISSUE TITLE
[FEATURE] Document workarounds for XiaoMi bugs in-app

### ISSUE THREAD

**Issue by lippfi** [zeapo/Android-Password-Store#1884]
### Is your feature request related to a problem? Please describe.

https://github.com/android-password-store/Android-Password-Store/issues/518

### Describe the solution you'd like

It took me a while to figure out that it is a known bug and there is an easy solution for this, so some additional info for future xiaomi users during setup would be grate.
The solution is to make a pop-up that asks xiaomi users to give the "Display pop-up windows while running in the background permission" permission and disable battery optimization for the Open Keychain app

### Describe alternatives you've considered

-

### Additional context

Thank's a lot for the app, I love it!

**Comment by msfjarvis** [comment]
No longer relevant with #2004 removing the OpenKeychain dependency from the app
