### ISSUE TITLE
[BUG] Empty modal for picking public key / No `.gpg-id` file created with PGPainless 

### ISSUE THREAD

**Issue by kevinnlsamuel** [zeapo/Android-Password-Store#1888]
### Describe the bug

There is no modal that should be presented to pick a PGP public key for encryptions. Normally this/these key(s) would be added to a file named `.gpg-id`. If the app is forcibly restarted at this time, the `.gpg-id` file is not created and no feedback from the app indicates the failure.

Attempting to pick a key (initial setup -> select key/new folder -> set key for dir) darkens the background, but there is no visible modal.

Possibly related to #1880 

#### Initial setup
1. Tap on `Let's go`
2. Setup repo however
3. Tap on `Select key`
**blank screen**
4. Force close app and restart
**APS set up with no feedback of failure; no `.gpg-id` file**

#### Folder creation
1. Tap on `+`
6. Choose `Folder`
7. Enable `Set GPG Key` and set a valid name
8. Tap `Create`
**blank screen**
9. Force close app
**Folder created; but no `.gpg-id`**

### Expected behavior

1. A modal popup to pick public key
2. Failure/interrupt during this modal should
	a. Revert initial setup
    b. **Not** create a folder

#### Inital setup screen at Pick GPG step
![Inital setup screen at Pick GPG step](https://user-images.githubusercontent.com/57634663/166165864-9fb80cf4-46be-4d3f-a7ea-ca1879de595e.png)

#### Blanked out screen after tapping on "Select key" button
![Blanked out screen after tapping on "Select key" button](https://user-images.githubusercontent.com/57634663/166166060-24ba0010-d0f3-4cac-a72a-266bc9b4b17a.png)

### Device information

- Device: Windows Subsystem for Android
- OS: Android 11
- App version: SNAPSHOT e025b120ed18668418e8cf66830a0590dbc4ab08

### Additional context

Checked presence of `.gpg-id` using `adb shell` with `run-as dev.msfjarvis.aps.debug`

**Comment by msfjarvis** [comment]
Creating new repos isn't fully supported with PGPainless yet, primarily because none of the key management UI is built out. There is no `.gpg-id` because that button launches [GetKeyIdsActivity](https://github.com/android-password-store/Android-Password-Store/blob/e025b120ed18668418e8cf66830a0590dbc4ab08/app/src/main/java/dev/msfjarvis/aps/ui/crypto/GetKeyIdsActivity.kt) which is very clearly just OpenKeychain code.

**Comment by kevinnlsamuel** [comment]
ah, gotcha. i was testing around and thought it might be related to #1880 where passwords weren't being encrypted with the public key

**Comment by msfjarvis** [comment]
Fixed by c4edf7f0e6203037384b042c8d450fb180d0c0f0
