### ISSUE TITLE
[BUG] No provision for ~CR~UD operations keys under PGPainless

### ISSUE THREAD

**Issue by kevinnlsamuel** [zeapo/Android-Password-Store#1889]
### Describe the bug

Importing a public key first makes it impossible to import a private key afterwards. There are no ways to delete or update (or list) installed keys.

### Steps to reproduce

1. Go to `Settings`
2. Click on `PGP Settings`
3. Import a public key
4. Import the private key of the same pair

### Expected behavior

Prompt confirming overwrite and updating existing file, or creating a different file. And also a way to browse list of available keys and a way to delete them.

#### preexisting key
![image](https://user-images.githubusercontent.com/57634663/166166927-7f1b3f66-015b-4a6f-98ef-9a763af23e85.png)

#### attempt to import the secret key
![image](https://user-images.githubusercontent.com/57634663/166166933-5939e3b3-aea1-459a-84d0-b7c36b5d81c8.png)

### Device information

- Device: Windows Subsystem for Android
- OS: Android 11
- App version: SNAP e025b120ed18668418e8cf66830a0590dbc4ab08

### Additional context

having two separate directories for public and private keys might help? but this would also mean having to generate pub keys from private keys in cases where none is provided. but also since encryption needs only the public key, it may be useful there and also wrt #1888? 

```mermaid
graph TD;
files --> pgp_keys
pgp_keys --> pub
pgp_keys --> sec
```

**Comment by msfjarvis** [comment]
As with the other issue, it's just something that hasn't been built yet. Separating keys out based on type is an interesting idea that could make this easier to implement.

**Comment by kevinnlsamuel** [comment]
we may also need a `diff` check. what do you think?

or there is a OpenPGP packet that has a date last updated that we could compare maybe?

i am not sure how PGPainless handles expired keys tbf. i have a keyring where i set a short duration and renew regularly. 

`gnupg` complains when the pubkey has expired "unusable public key."

i think OKC did say something similar, but refreshing keys from the keyserver makes everyone happy

**Comment by msfjarvis** [comment]
> we may also need a `diff` check. what do you think?

Maybe later, more basic building blocks need to come in first :)

> 
> or there is a OpenPGP packet that has a date last updated that we could compare maybe?
> 
> i am not sure how PGPainless handles expired keys tbf. i have a keyring where i set a short duration and renew regularly.
> 
> `gnupg` complains when the pubkey has expired "unusable public key."
> 
> i think OKC did say something similar, but refreshing keys from the keyserver makes everyone happy

I'm confident PGPainless does whatever's correct according to the spec, but it'll have to be thought about when the need arises. I do not plan to implement anything to do with keyservers, that is a cursed domain.

**Comment by vanitasvitae** [comment]
For the record, Bouncycastle (and PGPainless) now provide functionality to merge copies of PGPPublicKeyRings with another, e.g. to merge in updates from a key server into the local copy of a key.

See the corresponding [method in PGPainless](https://github.com/pgpainless/pgpainless/blob/main/pgpainless-core/src/main/java/org/pgpainless/PGPainless.java#L70-L83).
