### ISSUE TITLE
[BUG] Github: "You're using an RSA key with SHA-1, which is no longer valid."

### ISSUE THREAD

**Issue by freud14** [zeapo/Android-Password-Store#1899]
### Describe the bug

I just got my new Pixel 6 phone. I installed Android Password Store, generated an SSH key and then entered settings ot the repo which is on Github. I also put the SSH public key in my Github settings. When trying to pull I get the error message "You're using an RSA key with SHA-1, which is no longer valid.".  In the screenshot field below, I put a screenshot of the dialog. It is not doing that on my old phone.

### Steps to reproduce

1. Install Android Password Store
2. Generate SSH key from the setting menu.
3. Put given generated SSH public key in Github settings.
4. Enter the Github repo in the settings.
5. Pull the repo.

### Expected behavior

I should be able to pull the repo.

### Screenshots

![Screenshot_20220505-120311](https://user-images.githubusercontent.com/1090012/166965736-c2a1f5ab-f18e-4b10-b53b-f211909fc42c.png)

### Device information

- Device: Google Pixel 6
- OS: Android 12
- App version: 1.3.3

**Comment by msfjarvis** [comment]
You need to generate a new SSH key in the app and make sure to not pick RSA, this isn't something wrong the app. GitHub rightfully discontinued support for RSA keys and your other device doesn't use that key type which is why it still works but this does, which is why you see the error.

**Comment by freud14** [comment]
Hmm that's weird. I'm not sure why but I had a really old version. The SSH key I had generated with my old phone with the old version was still working fine but the SSH key generated with my new phone would give me the error. I upgraded the app and generated a new key and it works fine now.
