### ISSUE TITLE
[FEATURE] Save passphrase for gpg key on figerprint/pattern (new PGPainless)

### ISSUE THREAD

**Issue by sfrique** [zeapo/Android-Password-Store#1900]
### Is your feature request related to a problem? Please describe.

Need to type my passphrase every time I need to decrypt one pass isn't perfect.

### Describe the solution you'd like

If possible would like to add the passphrase to the fingerprint, like it does for the ssh key

### Describe alternatives you've considered

Also could be possible to save this passphrase until app is closed or until we "close" the "store"

By the way, I am using the latest snapshot from: https://github.com/android-password-store/Android-Password-Store/commit/169769d0d49183349c0733678ee625c591e8cf9e

### Additional context

Just some ideas, not sure if this should be in fact implemented as we don't need to check too many passwords often.

**Comment by msfjarvis** [comment]
Caching is already tracked in #1523, we're not planning to add a fingerprint prompt.

**Comment by raxod502** [comment]
@msfjarvis Am I correct in understanding from the combination of https://github.com/android-password-store/Android-Password-Store/issues/1523 and this issue that while passphrases were cached in 1.x, there is currently not support for passphrase caching in 2.x, but that this is part of the future roadmap for the project?

**Comment by msfjarvis** [comment]
Correct

**Comment by raxod502** [comment]
I'd be willing to contribute work to (re-)add this feature to 2.x as a pull request. Do you think that would be worthwhile, or does it involve too many design decisions to be worked on by someone who is not already a highly involved contributor?

**Comment by msfjarvis** [comment]
> I'd be willing to contribute work to (re-)add this feature to 2.x as a pull request. Do you think that would be worthwhile, or does it involve too many design decisions to be worked on by someone who is not already a highly involved contributor?

There are definitely design decisions to be made. I have a [very basic implementation](https://github.com/android-password-store/Android-Password-Store/blob/29ca93854a57a97bf08122f2523f9114c5052a97/app/src/main/java/app/passwordstore/data/crypto/GPGPassphraseCache.kt) in the main branch that has no concept of timeouts or in-memory storage but does encrypt the passphrase at rest, while OpenKeychain [uses an Android service](https://github.com/open-keychain/open-keychain/blob/8d69181b65c2d5364f40845466a9e5305ca8c91b/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/PassphraseCacheService.java) to hold the passphrases in-memory and offers timeouts and manual clearing support.

I don't know which one is strictly better, nor am I really sure on what factors even decide "better" here. The ambiguity makes this an uphill feature to contribute towards.
