### ISSUE TITLE
[FEATURE] support multiple repositories

### ISSUE THREAD

**Issue by Loki-Afro** [zeapo/Android-Password-Store#1909]
### Is your feature request related to a problem? Please describe.

I am using multiple pass-repositories. on my dekstop computer i am using the browserpass extension which has support for that, kinda missing it here.

### Describe the solution you'd like

supporting multiple repositories

### Describe alternatives you've considered

maybe it works in some cases but this is really ugly: having a 3rd repository which uses submodules or similar?

### Additional context

https://github.com/browserpass/browserpass-extension

**Comment by msfjarvis** [comment]
https://github.com/android-password-store/Android-Password-Store/issues/260

https://github.com/android-password-store/Android-Password-Store/discussions/1836
