### ISSUE TITLE
[BUG] Arbitrary extra is treated as user

### ISSUE THREAD

**Issue by koiuo** [zeapo/Android-Password-Store#1915]
### Describe the bug

Passwords in pass can be organized using different schemes:
- `domainname/username.gpg → content [ pass, extra: ... ]`
- `domainname.gpg → content [ pass, user: ... ]`

Mine are organized using the first approach, where filename is the login, the first line of the content is password, and any extra can come after.

This works as I expect unless there's extra. The problem is that it doesn't matter which extra it is, it can be `foo: definitely-not-a-user-name`, and _android-password-store_ will use it as login anyway

### Steps to reproduce

1. create two entires
   ```
   entry1.gpg
   password

   entry2.gpg
   password
   foo: entry1
   ```
2. autofill some inputs using the `entry1`. Observe `entry1` used as a user
3. autofill some inputs using the `entry2`. Observe `entry1` used as a user

### Expected behavior

I can suggest an approach used by https://github.com/carnager/rofi-pass as a source of inspiration.

It always uses the extra with the name `user` for the login. It supports a special value `:filename` which, if specified, will be substituted by the entry name in the password store.

_rofi-pass_ then exposes a configuration option `default_user`. Setting one to `:filename` will effectively configure _rofi-pass_ to use the filename as the user.

Such approach also seems very flexible, because it allows overriding the behavior on the per-entry basis.

### Device information

- Device: Asus Zenfone 8
- OS: stock ROM Android version 12.0
- App version: 1.13.5

**Comment by msfjarvis** [comment]
There's a `Password file organization` setting that changes how Password Store decides the 'fallback' username to use. There is a list of field prefixes [here](https://github.com/android-password-store/Android-Password-Store/blob/4a5bd337c3b981af3bc5751676571837f672bea7/format-common/src/main/kotlin/dev/msfjarvis/aps/data/passfile/PasswordEntry.kt#L201-L213) that decide if a field is regarded as the username so I highly doubt that `foo: entry1` will _ever_ get picked up as a username by Autofill.

That said, there don't seem to be any good ways to be able to write tests for Autofill services so figuring out what exactly is happening will take a bit of time and manual labour after which I can say for certain what's happening in this specific case.

**Comment by koiuo** [comment]
@msfjarvis , thanks for the explanation. And I'm sorry I forgot to mention this: I had the repositioning organization setting set like this all the time

<details>
<summary>Screenshot</summary>

![Screenshot_20220516-114238375 (1)](https://user-images.githubusercontent.com/787439/168565225-8d2a5b22-5c65-43e5-b691-90c8cebecd28.png)

</details>

**Comment by msfjarvis** [comment]
Thanks, I'll try and reproduce it on my end and see what's up.

**Comment by msfjarvis** [comment]
I can't reproduce this issue and I've reviewed the code path for this and found no possible way where arbitrary keys can be picked up as an username. Please feel free to try the [snapshot builds](https://docs.passwordstore.app/docs/users/release-channels) and check if you are facing this issue still.
