### ISSUE TITLE
Add more fields to autofill

### ISSUE THREAD

**Issue by jumper047** [zeapo/Android-Password-Store#192]
I think it will be very useful to have easy bash to input login automatically. You can see example in pass firefox extension. It gets login name from 
"login: lapels" string, etc.

**Comment by robinvd** [comment]
Does the current implementation do anything with the login or url data?

**Comment by zeapo** [comment]
nothing much. we use the title of the password for autofill, but we do not decrypt the password (and extra content)

**Comment by jumper047** [comment]
I also think, that it will be very useful. Some apps don't remember user name, or somebody can use more than one account on one device. 

27 сентября 2016 г. 12:53:37 GMT+03:00, Mohamed Zenadi <notifications@github.com> пишет:
>nothing much. we use the title of the password for autofill, but we do
>not decrypt the password (and extra content)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/zeapo/Android-Password-Store/issues/192#issuecomment-249819620

-- 
Простите за краткость, создано в K-9 Mail.
