### ISSUE TITLE
Autofill tries to fill in lock screen; can't be disabled for lock screen

### ISSUE THREAD

**Issue by oatberry** [zeapo/Android-Password-Store#193]
When autofill is enabled, I get the autofill prompt dialog after unlocking my lock screen. This is pretty annoying. If I hit the "settings" button in the dialog, it takes me to the matching settings for the SystemUI app. I can set it to "never match" but it'll still prompt me after unlocking my phone.

**Comment by wongma7** [comment]
What version of Android are you using? I have made an exception for systemUI so it should stop showing up in the latest app version. Do you have 'always show dialog' enabled? Right now that overrides 'never match,' I will need to change that.

**Comment by oatberry** [comment]
@wongma7 ah yeah, that'd explain it. Thanks!
