### ISSUE TITLE
The app exits immediately on launch, with nothing displayed v1.2.0.45

### ISSUE THREAD

**Issue by GreenHex** [zeapo/Android-Password-Store#194]
Bug in latest version 1.2.0.45 (3 July 2016) on my Meizu M2 running Android 5.1.

The app exits immediately on launch, with nothing displayed.

I also did the following:
1. Cleaned up everything. Uninstalled Password Store and reinstalled it. With this I was able to get to the UI. (It allowed me to configure GitHub settings and generate the SSH key pair).
2. On syncing back passwords from GitHub, it fails to launch and display the UI.

**Comment by lgaticaq** [comment]
Some error in my Alcatel idol 3 whit android 5.0.2

**Comment by zeapo** [comment]
I understand you come from the play store, right?

Here is an APK with the latest fix for lollipop, could you try it?
https://play.google.com/apps/testing/com.zeapo.pwdstore

**Comment by GreenHex** [comment]
Yes, from the playstore.

**Comment by zeapo** [comment]
I just pushed the apk to the play store, you should get it soon.

**Comment by zeapo** [comment]
seems like 3d5a448566aae50bc116e5ccc9017854ab292b5a fixed the issue.

**Comment by GreenHex** [comment]
Fixed, thanks!!!
