### ISSUE TITLE
Blank activity

### ISSUE THREAD

**Issue by btimofeev** [zeapo/Android-Password-Store#196]
If you open the app and press the back button, the contents of the activity disappears and the application does not close. If you then click the search button, the application will crash.

App version: 1.2.0.47
Android version: 6.0.1

**Comment by wongma7** [comment]
Thanks for report, fixed with https://github.com/zeapo/Android-Password-Store/commit/017650bf373e3ccc3a45680088297543a1470eff. Might have to test I didn't break anything before releasing
