### ISSUE TITLE
[FEATURE] Read only mode

### ISSUE THREAD

**Issue by dschrempf** [zeapo/Android-Password-Store#1982]
### Is your feature request related to a problem? Please describe.

Usually, I manage passwords on my computer and only need to access passwords on the phone. Actually, I do not really want to change anything in my store on the phone by accident.

Further, `git` related actions are really slow on my phone, I constantly have to `git clean` to reduce the lag when searching or opening password files.

### Describe the solution you'd like

A global read-only mode also removing all `git` related actions would be perfect. It would remedy my fear that I mess up my files using the touch screen (even though I know I can go back using `git`), and also the problems related to speed (I think there are various issues about this in the tracker).

### Describe alternatives you've considered

Per-file read only mode. This would probably not have an impact on speed though.

### Additional context

Thanks for considering this!

**Comment by alanorth** [comment]
I agree. I only edit passwords on my computer and never add them on Android. A read-only mode would be useful.

On a related note, when I re-sync my git repository in Android Password Store, the application re-writes some of my password entries with this commit message: `[Android Password Store] Sync`. In my experience it always re-writes symbolic links to be normal files. I use symlinks for sites that use the same credentials across different domains (for example stackexchange, superuser, stackoverflow, etc).

Edit: there seem to be two issues filed about this symlink problem: https://github.com/android-password-store/Android-Password-Store/issues/636 and https://github.com/android-password-store/Android-Password-Store/issues/1013

**Comment by raxod502** [comment]
The fundamental issue for me is that if I accidentally swipe down, then my repo is broken (because symlinks) and I have to manually fix it. Possible changes to Android Password Store which would resolve or workaround the issue:
1. Ability to disable the swipe shortcut
2. Ability to assign the swipe shortcut to "pull" instead of "sync"
3. Ability to disable pushing/syncing entirely, only allow pulls
4. Fix https://github.com/android-password-store/Android-Password-Store/issues/636

@msfjarvis Would a pull request implementing one of 1-3 be acceptable from a design perspective? If so do you have a preference? (I am gathering from prior discussion that the state of Git symlink support on Android Java is pretty nasty and 4 might not be worth the time.)

**Comment by msfjarvis** [comment]
> The fundamental issue for me is that if I accidentally swipe down, then my repo is broken and I have to manually fix it. Possible changes to Android Password Store which would resolve or workaround the issue:
> 1. Ability to disable the swipe shortcut
> 2. Ability to assign the swipe shortcut to "pull" instead of "sync"
> 3. Ability to disable pushing/syncing entirely, only allow pulls
> 4. Fix https://github.com/android-password-store/Android-Password-Store/issues/636
> 
> @msfjarvis Would a pull request implementing one of 1-3 be acceptable from a design perspective? (I am gathering from prior discussion that the state of Git symlink support on Android Java is pretty nasty and 4 might not be worth the time.)
> 

Option 1 was already implemented as #1922.

**Comment by raxod502** [comment]
Ah, silly me. I did not realize you had already fixed the issue. I went ahead and sideloaded the [snapshot apk](https://github.com/android-password-store/Android-Password-Store/releases/tag/latest), which I see is from the 2.x refactor branch that is dropping OpenKeychain among other changes. Thank you for the pointer! I experience some new issues with the 2.x apk, but I will file those separately (if I can't find resolutions already in the documentation and prior reports).

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
