### ISSUE TITLE
Clear clipboards with more than 20 slots

### ISSUE THREAD

**Issue by FelipeResende** [zeapo/Android-Password-Store#1985]
On my phone, the clipboard contains 35 slots, but version 1.13.5 only clears 20 of them. I saw that this feature was reworked in 318aeae50072d575c975bbf1f708d526c41adc20 to clear 35 slots, but it wasn't included in the last release.

Would it be possible to publish a new release with this change? Or  a hotfix in 1.13.5 only changing 20 to a bigger value?

Thanks

**Comment by msfjarvis** [comment]
A new release of any kind is not on the horizon right now. If you urgently require this change you can use the [snapshot builds](https://docs.passwordstore.app/docs/users/release-channels/).
