### ISSUE TITLE
[BUG] Pull to sync will not auth 

### ISSUE THREAD

**Issue by worldofgeese** [zeapo/Android-Password-Store#1988]
### Describe the bug

Any snapshot build will not sync when using OpenKeychain for auth. Release versions on my other phone function correctly.

### Steps to reproduce

1. Open Password Store
2. Pull to sync
3. Select OpenKeychain key
4. A password prompt for the repository will appear (this should not happen as there is no repo password)
5. Enter or do not enter a password. 
6. "Exhausted available auth methods"

### Expected behavior

When pulling to sync my password store Git repo should sync

### Screenshots

![Screenshot_20220709-083608](https://user-images.githubusercontent.com/59834693/178094890-5e6a8a33-1875-4708-808a-abda56bb6e9e.png)
![Screenshot_20220709-083449](https://user-images.githubusercontent.com/59834693/178094891-802c22f1-3383-44f5-beb2-5b4e38929875.png)
![Screenshot_20220709-084059](https://user-images.githubusercontent.com/59834693/178094892-590b8af4-75cc-473b-8581-1e1ca3e8721f.png)

### Device information

- Device: Google Pixel 6 Pro
- OS: GrapheneOS latest release as of July 9th
- App version snapshot build c11bdb4 (bug occurs in snapshot builds extending months back)

**Comment by worldofgeese** [comment]
Can I ask you to take a look at this @msfjarvis?

**Comment by msfjarvis** [comment]
> Can I ask you to take a look at this @msfjarvis?

I've [made the decision](https://msfjarvis.dev/aps/issue/1523) to remove OpenKeychain support completely and release v2 as a separate, backwards-incompatible update so OpenKeychain related bugs are now out of scope.

**Comment by worldofgeese** [comment]
By backwards-incompatible do you mean we will not be able to easily migrate our existing local repos out? I have a number of passwords I'd need to recreate since they won't sync to their remote currently.

**Comment by msfjarvis** [comment]
> By backwards-incompatible do you mean we will not be able to easily migrate our existing local repos out? I have a number of passwords I'd need to recreate since they won't sync to their remote currently.

Password Store has always had an export option to eject your store to user-accessible device storage so you can export the whole directory, Git repo and all, pull it onto a desktop machine and do the necessary Git operations to get the remote in sync with Password Store's copy. Afterwards you can set up the new version of the app with the remote URL as source and it'll work just the same.
