### ISSUE TITLE
[documentation request] Import existing list of passwords

### ISSUE THREAD

**Issue by crosser** [zeapo/Android-Password-Store#199]
It would be very helpful to have a wiki page about pre-filling the repository with existing list of passwords, for instance exported from OI Safe or other application.
I guess that I can prepare a repository on some server and specity "use existing repo" in the app. But what is the format of the data in the repo?

**Comment by wongma7** [comment]
The main goal of this app is to be compatible with http://www.passwordstore.org/ so the format is openpgp encrypted files in a git repository. This app can't migrate data from any apps, it's possible to implement if the other app has some kind of open source format but it's a lot of work

**Comment by crosser** [comment]
It would help to have a wiki page "data format" explaining that the is a tree structure, each password is in a single file, each file is an ascii-armored PGP envelope, and inside the first line is the password, and the rest of the lines are additional data. All of this was not obvious at the start. And it could be mentioned that the format is compatible with http://www.passwordstore.org/.

**Comment by sc-perth** [comment]
https://github.com/zeapo/Android-Password-Store/wiki/Migrating-to-Password-Store

**Comment by crosser** [comment]
@sc-perth , maybe mention [my script for migration from OI-Safe](https://github.com/zeapo/Android-Password-Store/tree/master/contrib/oisafe2pstore)? Thanks!

**Comment by sc-perth** [comment]
Took a look at your OI-Safe script, not bad, but it jumps out at me immediately that it contains hard coded strings you expect to be modified by the end users. That's a completely acceptable solution when something is only going to be used by the author, but will result in drama when released into the wild. Before adding that to the wiki, can you re-visit your script with the consideration that it will be used by many people?

Try fixing these portability/usability issues:
* Hard coded gpg2 path @ [L28](https://github.com/zeapo/Android-Password-Store/blob/master/contrib/oisafe2pstore/oisafe2pstore.hs#L28)
    - Perhaps [findExecutable](https://downloads.haskell.org/~ghc/6.12.2/docs/html/libraries/directory-1.0.1.1/System-Directory.html#v%3AfindExecutable)?
* Hard coded gpg key id @ [L30](https://github.com/zeapo/Android-Password-Store/blob/master/contrib/oisafe2pstore/oisafe2pstore.hs#L30)
    - Perhaps [getArgs](http://hackage.haskell.org/package/base-4.9.0.0/docs/System-Environment.html#v:getArgs)? ([StackOverflow](http://stackoverflow.com/a/14966463))
* Hard coded OI-Safe CSV path @ [L68](https://github.com/zeapo/Android-Password-Store/blob/master/contrib/oisafe2pstore/oisafe2pstore.hs#L68)
    - Again, perhaps getArgs
* No Usage output (--help/-help/-h/h)
* No [#! line](https://en.wikipedia.org/wiki/Shebang_%28Unix%29) informing the shell what program to use to execute this script.

**Comment by sc-perth** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Absolutely that should be mentioned!
As its author I can think of no one who will be more capable or authoratative to add it to the publicly editable wiki than yourself. :)
Please do make a note that your script is not included with pass, and obviously where to get it & so on.
- --
Between A & B there's C.
GPG: 0xe818cb04b0a635fc
5b55 a483 138e 69e8 7be1
6bbe e818 cb04 b0a6 35fc
https://sks-keyservers.net/pks/lookup?op=get&search=0xe818cb04b0a635fc
Sent from my phone usind K9 Mail, pardon the typos (I hate autocorrect).
-----BEGIN PGP SIGNATURE-----

iQFDBAEBCgAtJhxKb2huIEQuIEhhcmxhbiA8cGVydGhAc2VtaWNvc21pYy5uZXQ+
BQJYC+XGAAoJELHPXx+MTRDUz4MH/AgMuUpousn9YnsokV/kozgxpdAZFgUFPcEs
ZaY1ojKpvoMVWwTYRkOZxlVGZckSuDot77cPT57KZuNrWNEPFmkxKpiwblrWx6UO
QI4HKRlbS8aFdMa4CXv0FSP6/hjz4UvDjWt+/0oWGKexTCj/6lr3PPqRvWZZD8QL
dBpFCmT2Vm9eYZ2B0yf96zdFkV6z0r9YcDXxl7JRf81kBnozt7gaagQ/m8v0NLAb
059tU5cc5wObi8N31vobu+1GT2+AKnZZamY07V8+VpHw+IKqWB2oVouYqJF4QzSb
FytxyyjLa0GbMBydHKoMzAMh/O0ngDYSrzuFgXCzfPbFN5mP8D8=
=x9Jk
-----END PGP SIGNATURE-----

**Comment by sc-perth** [comment]
@wongma7 Should this be closed now?

**Comment by wongma7** [comment]
Sure, very well done docs. Can also link to it in the README if you want
