### ISSUE TITLE
no password could be read 

### ISSUE THREAD

**Issue by Caraffa-git** [zeapo/Android-Password-Store#2001]
### Describe the bug

I can't open any password.
Everything worked yesterday, but now no matter if password is old or freshly created i can't open it.

### Steps to reproduce

I don't know how you can recreate this bug. Something must have happened, but from my perspective i didn't do or see anything.

### Expected behavior

password window open and readable

### Screenshots

https://youtu.be/KbeyXCjuz3g

### Device information

- Xiaomi note 10 5G
- OS: Andorid 11 MIUI 12.5.1
- App version 1.13.5

**Comment by msfjarvis** [comment]
This is a XiaoMi bug that we can't do anything about, refer to the following links for workarounds.

https://msfjarvis.dev/aps/issue/518

https://docs.passwordstore.app/docs/users/background-killing-bugs
