### ISSUE TITLE
[FEATURE] Allow using PGP key for SSH

### ISSUE THREAD

**Issue by skewballfox** [zeapo/Android-Password-Store#2017]
**Is your feature request related to a problem? Please describe.**

With OpenKeychain it was possible to use your GPG key to authenticate over SSH, which is not supported with the PGPainless backend.

**Describe the solution you'd like**

Implement support for using a selected GPG key as the SSH authentication method.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by vanitasvitae** [comment]
I can look into adding support for this to the library.

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
