### ISSUE TITLE
[BUG] attempting to decrypt password encrypted with subkey on smart card prompts for password

### ISSUE THREAD

**Issue by skewballfox** [zeapo/Android-Password-Store#2018]
### Describe the bug

My gpg setup is one where I have a Master key with C capabilities, and a subkey with E capabilities which only exists on a hardware key(yubikey). When attempting to use a password which was encrypted with this (passwordless) private subkey, the application prompts for a password (I'm assuming for the master key). 

### Steps to reproduce

1. import public master-key
2. Click on any password encrypted with the encryption sub-key for the imported master-key
3. app prompts for password

### Expected behavior

The application should either:
1. detect that the master key doesn't have E(ncryption) capability, and check to see if a subkey has E capability, upon finding one prompt for the subkey. it should probably cache some config information for future operations.
2. have a dedicated settings menu for indicating this kind of setup.

### Device information

- Device: Google Pixel 4aXL
- OS: GrapheneOS Android 12
- App version: Development build

### Additional context

Most yubikey users who are using their device for gpg keys are probably using a setup extremely similar to this, as it was created following [a popular guide](https://github.com/drduh/YubiKey-Guide) on setting gpg up on a yubikey(or set of yubikeys). It's the third search result on google for "yubikey gpg", the first after the official documentation. It's probably safe to assume that if a user is using a gpg key stored on a yubikey with pass or a pass compatible tool, they are probably running the exact same setup.

**Comment by msfjarvis** [comment]
This is going to be fixed when #1786 is resolved so I'm going to go ahead and close this, please use the subscribe button in the right sidebar to get notified when there are updates shared on that issue.
