### ISSUE TITLE
Searching list of passwords incurs long UI delay

### ISSUE THREAD

**Issue by madduck** [zeapo/Android-Password-Store#2025]
I am enamoured with being able to use `pass` on Android, but there is something that drives me up the walls… I have roughly 1,300 passwords in my store, and when I fire up the UI (or try to use autofill) to search for a password, it takes a few seconds for the results to show up. I kinda expect filtering of the resultset to be instantaneous, and 1,300 entries isn't exactly a big search task even if search were to be done linearly, but the filesystem itself already does some sort of B-Tree, so this is a bit hard to understand.

This is also happening across two devices, one running LineageOS 18.1 (Android 11) and the other with GrapheneOS (Android 12).

**Comment by msfjarvis** [comment]
We have issue templates for a reason :)

Please create a new issue using [this](https://github.com/android-password-store/Android-Password-Store/issues/new?assignees=&labels=C-bug%2CS-awaiting-triage&template=bug_report.yaml&title=%5BBUG%5D+) link.

**Comment by madduck** [comment]
I am sorry @msfjarvis, but Github didn't offer me any templates. I just created a normal issue. Now if I hit "new issue", I am asked to use a template.
