### ISSUE TITLE
[BUG] Delay searching password list

### ISSUE THREAD

**Issue by madduck** [zeapo/Android-Password-Store#2026]
### Describe the bug

I have roughly 1,300 passwords in my store, and when I fire up the UI (or try to use autofill) to search for a password, it takes a few seconds for the results to show up. I kinda expect filtering of the resultset to be instantaneous, and 1,300 entries isn't exactly a big search task even if search were to be done linearly, but the filesystem itself already does some sort of B-Tree, so this is a bit hard to understand.

### Steps to reproduce

1. Open the app, or engage autofill
2. Enter search term into search field, e.g. "github"
3. Wait 2–3 seconds before the list is refreshed
4. …

### Expected behavior

As I hit 'g', I expect the list to hide all entries not containing a "g", and the "g" in matching entries to be boldened. When I hit "i", the list again updates instantaneously.

### Device information

- Device: Google Pixel 6 Pro
- OS: GrapheneOS, Android 12
- App version: 1.13.5

**Comment by msfjarvis** [comment]
I [added a benchmark to our fuzzy search library](https://github.com/android-password-store/sublime-fuzzy/commit/323feb50b143cd6ceab1ed2bfb8e6b36ea0666e5) and it was made abundantly clear that the problem is not with it after it was able to do 2000 matches of strings ranging in length from 0 to 2000 characters in an average time of 72ms


```
> Task :benchmark:jvmBenchmark
Running 'main' benchmarks for 'jvm'

… benchmark.FuzzyMatchBenchmark.fuzzyMatch

Warm-up 1: 72.604 ms/op
Warm-up 2: 71.629 ms/op
Warm-up 3: 71.327 ms/op
Warm-up 4: 71.534 ms/op
Warm-up 5: 74.636 ms/op
Iteration 1: 72.064 ms/op
Iteration 2: 71.990 ms/op
Iteration 3: 72.567 ms/op

  Success: 72.207 ±(99.9%) 5.729 ms/op [Average]
  (min, avg, max) = (71.990, 72.207, 72.567), stdev = 0.314
  CI (99.9%): [66.478, 77.936] (assumes normal distribution)


jvm summary:
Benchmark                       Mode  Cnt   Score   Error  Units
FuzzyMatchBenchmark.fuzzyMatch  avgt    3  72.207 ± 5.729  ms/op
```

I'll investigate the app side of things in a couple weeks and see if we can track the problem.

**Comment by msfjarvis** [comment]
Testing with our [pass-test](https://github.com/android-password-store/pass-test/tree/large-repo) dataset confirms that there is definitely delays in the UI, investigating now.

**Comment by msfjarvis** [comment]
The specific code block that causes the delay is [this](https://github.com/android-password-store/Android-Password-Store/blob/0e8bfd1b3b5acffea63ed160b9f6b573845b6b3e/app/src/main/java/app/passwordstore/util/viewmodel/SearchableRepositoryViewModel.kt#L239-L251) but I haven't yet figured out why it's slow. Will take another look later and see if I get any ideas.

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
