### ISSUE TITLE
[META] Clean up issues reported by Detekt

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#2029]
We recently introduced [Detekt](https://detekt.dev) to our CI suite and setup a [baseline](https://github.com/android-password-store/Android-Password-Store/tree/develop/detekt-baselines). Cleaning up the suppressed existing issues is a low effort, high value task that anyone can pick up without needing too much operational knowledge of how the app functions.

**Comment by aswarthm** [comment]
Hey I'd like to work on this. I believe it involves removing @suppress annotations in the code?

**Comment by msfjarvis** [comment]
> Hey I'd like to work on this. I believe it involves removing @Suppress annotations in the code?

Not particularly, since the suppressions have been kept limited to places where we wish to override Detekt's understanding of the code. In the [detekt-baselines](https://github.com/android-password-store/Android-Password-Store/tree/develop/detekt-baselines) directory of the repository you will find XML files for each module that contain a list of methods/variables/lines where Detekt has found issues.

The way to approach this would be to identify which module you would like to work on, then going through its baseline XML to identify issues, fixing them or `@Suppress`ing with a comment explaining why.

**Comment by NewtonCesarRoncari** [comment]
Hello, apparently there are many issues by detekt
![Captura de Tela 2022-10-07 às 15 07 18](https://user-images.githubusercontent.com/31870695/194622091-3a1dc40c-a843-487c-b496-a809b554ec78.png)

Is it possible for me to act on just a few simpler ones for now?, like hardcode and magic numbers or other things

![Captura de Tela 2022-10-07 às 15 13 16](https://user-images.githubusercontent.com/31870695/194623123-abe8a8e6-a5b8-4313-b343-2d1711c037ca.png)

**Comment by msfjarvis** [comment]
> Hello, apparently there are many issues by detekt ![Captura de Tela 2022-10-07 às 15 07 18](https://user-images.githubusercontent.com/31870695/194622091-3a1dc40c-a843-487c-b496-a809b554ec78.png)
> 
> Is it possible for me to act on just a few simpler ones for now?, like hardcode and magic numbers or other things

You can fix as many or as few as you want, there is no expectation to be tackling every single reported problem in one PR.

**Comment by NewtonCesarRoncari** [comment]
Great, i will take a look, if you want, can assign to me
