### ISSUE TITLE
“Clone From Server” cannot proceed

### ISSUE THREAD

**Issue by bignose-debian** [zeapo/Android-Password-Store#203]
I am unable to set up Password Store by cloning from an existing repository.

Steps to reproduce:

* Have an existing Password Store database in hidden storage.
* Install 1.2.0.51 over an older version.
* Go to Android's “Settings” → “Apps” → “Downloaded” → “Password Store”.
  * “Clear Data” is available.
* Select “Clear Data”, then confirm the action.
  * “Clear Data” option is no longer available.

This implies the app has no data, anywhere on the device.

* Start Password Store version 1.2.0.51.
  * Initial page prompts with “Settings”, “Use Local Directory”, “Clone From Server”.
* Select “Settings”.
* Select “Import SSH Key”, complete the steps to import the SSH public key.
* Select “Edit Git server settings”.
  * Prompt appears “Repository location”.
* Select “Hidden (Preferred)”.
  * Settings page for “Repository information” appears.
* Fill details for remote Git server via SSH.
* Select “Clone!”.
  * Prompt appears “Directory already exist”.
* Select “Delete Directory”.
  * Prompt disappears, settings page still shown.
  * No network activity.
  * Selecting “Clone!” button results in same as above.
  * Running app brings same initial page.

I infer from this result that the app has not in fact attempted a clone from the server, and no password store is created.

Expected:

* After “Clear Data” succeeds, the app should not have any data in its expected directory, and so should not prompt to delete that directory.
* Select “Clone!”.
  * The app clones from the remote Git repository and creates the password store in hidden storage.
  * The app presents all the password store in folders for normal use in the app.

**Comment by wongma7** [comment]
If you already have a database you created with the older version, it should not even show the initial 'use local directory'/'clone from server' page. Unless you were prompted to first uninstall the old version because of some mismatch etc.

What happens if you 'clear data' & start fresh? Did you try to do that, or reinstall, to work around this issue? Or does clone just not work and you are stuck in a loop of 'clone' -> 'delete directory' -> nothing happens.

(The delete button doesn't give any feedback if it fails i.e. the exceptions aren't bubbled up. So that is something I could do to make debugging this easier.)

**Comment by bignose-debian** [comment]
@wongma7:

> What happens if you 'clear data' & start fresh? Did you try to do that, or reinstall, to work around this issue? Or does clone just not work and you are stuck in a loop of 'clone' -> 'delete directory' -> nothing happens.

Thanks for asking. I have now updated the issue description with the steps that cover this.

In brief: yes, even starting from a cleared-data app, the “Clone” → “Delete directory” loop appears to achieve nothing.

**Comment by zeapo** [comment]
Thanks for the report. I will try to replicate it, will get back to you.

Sorry if it takes some time, I am on vacation :)

**Comment by bignose-debian** [comment]
I have tried numerous archived versions of the app, all of which worked (earliest I tried was 1.2.0.32) when I had originally upgraded to the version.

When I try now – clear data, uninstall, then install the specific version, perform the steps in the issue description – the result is the same: “Directory already exist”.

What could be causing even older once-working versions in this device, to fail as though the repository directory now exists and cannot be deleted?

**Comment by wongma7** [comment]
Can you see what happens in v1.2.0.52, just released? I think I have fixed https://github.com/zeapo/Android-Password-Store/issues/122, it should no longer say 'directory already exist' on a clean install, so now we can narrow down the issue.

**Comment by bignose-debian** [comment]
On Tue, 2016-08-02 17:08 -0700, Matthew Wong <notifications@github.com>
wrote:
> Can you see what happens in v1.2.0.52, just released?

I install packages via F-Droid. How would I install Password Store
1.2.0.52 now?

-- 
 \
  `\
_o__) Ben Finney <ben+debian@benfinney.id.au>

**Comment by bignose-debian** [comment]
Password Store 1.2.0.52 is available from F-Droid repository.

Installing that version, I see a different error message in response to the “Clone!” action.

This allows me to raise a new issue #205.
