### ISSUE TITLE
[BUG] fednetbank.com autofill does not fill password

### ISSUE THREAD

**Issue by pravi** [zeapo/Android-Password-Store#2047]
### Describe the bug

Initially with fednetbank.com as folder name it only offered to generate password. Once I moved it as work/fednetbank.com it showed option to fill but it was empty even after choosing the correct entry. This site works fine on Firefox and browser pass extension on laptop.

### Steps to reproduce

1. Go to fednetbank.com
2. Generate password
3. And try to autofill
4. The password field is empty.

### Expected behavior

It should autofill password

### Device information

- Device: Redmi Note 4
- OS: Carbon Rom
- App version [e.g. 3.1.0]

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
