### ISSUE TITLE
Invalid SSH private key should be rejected when importing

### ISSUE THREAD

**Issue by bignose-debian** [zeapo/Android-Password-Store#205]
When importing the SSH private key, no indication is given if the chosen file is not a valid SSH private key.

Instead, the process succeeds, implying the key data is valid and can be used.

Later, when the SSH connection is attempted, errors like “invalid privatekey [B@…” occur. This is too far removed from the time of importing the key data.

The expected behaviour is: When importing the SSH private key, that process should check the data and show an error if the key data is invalid. That way, a different file can be chosen or the operation can be cancelled.

**Comment by bignose-debian** [comment]
There is no comment here saying what has been done to resolve this issue. Why is this closed?

**Comment by zeapo** [comment]
Fixed here fd9e958d40a56a2a3b8dfbef86944d3d5f53fec2

Or am I understanding it wrongly?

**Comment by bignose-debian** [comment]
I don't know :-) I'll have to wait until new F-Droid packages arrive.

My concern was no information in this bug report saying why it was closed. Thanks for the response.
