### ISSUE TITLE
[FEATURE] age support

### ISSUE THREAD

**Issue by Akiiino** [zeapo/Android-Password-Store#2061]
### Is your feature request related to a problem? Please describe.

PGP's user experience is very lacking, and unless you spend significant amounts of time learning to use it, you might end up committing really simple mistakes compromising your security. it'd be really nice to have support for [age encryption](https://github.com/FiloSottile/age) / [passage](https://github.com/FiloSottile/passage) as an alternative to PGP/GPG.

### Describe the solution you'd like

Native integration of age encryption support into the app.

### Describe alternatives you've considered

Regular PGP, but see above.

### Additional context

I saw this discussed in #1486 , but the last comment there is soon to be 2 years old; has there been any progress?

**Comment by msfjarvis** [comment]
There were some updates in #1523 from other people asking about age support, but the TL;DR is that we have a Kotlin port of age [here](https://github.com/android-password-store/kage) that is at an MVP stage but it will not be included in Password Store until after the next major release.

**Comment by tennox** [comment]
That's great to read! :+1: 

what's the status on this? I see there is quite some activity going on - is there a WIP we could test?

**Comment by msfjarvis** [comment]
> That's great to read! 👍
> 
> what's the status on this? I see there is quite some activity going on - is there a WIP we could test?

There is nothing that can be used yet. Work on kage has stalled for the time being so there has also been no progress on the APS side.

**Comment by Akiiino** [comment]
I see there's been some progress on supporting age; is there hope for an age-compatible version of the app at some point? Willing to alpha-test :)

**Comment by msfjarvis** [comment]
> I see there's been some progress on supporting age; is there hope for an age-compatible version of the app at some point? Willing to alpha-test :)

I intend to introduce age support in the near future but it's all dependent on having a few days worth of free time which is hard to come by for the next couple months.

**Comment by skystar-p** [comment]
I'm also willing to alpha-test this feature. Is there any progress about this?

**Comment by msfjarvis** [comment]
> I'm also willing to alpha-test this feature. Is there any progress about this?

There is not.

**Comment by sewnie** [comment]
Anything new as of yet? I'm getting quite tired with GPG randomly locking up and not working properly.

**Comment by msfjarvis** [comment]
> Anything new as of yet? I'm getting quite tired with GPG randomly locking up and not working properly.

An update will be shared in this issue when there is.

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
