### ISSUE TITLE
Trojan FakeLook.A according to Windows Defender

### ISSUE THREAD

**Issue by danielvandenberg95** [zeapo/Android-Password-Store#211]
I've cloned the project and imported it into Android Studio.  Now Windows Defender recognizes one of the generated intermediates as a Trojan. 

![image](https://cloud.githubusercontent.com/assets/8654023/17830885/78769246-66da-11e6-8fbc-6f515062e2cb.png)

As this is a generated file it will give problems very often. I'd like to document this as an issue here, perhaps if it happens to more people or on more machines it is something that should be documented in the wiki? I'll try to find the source of this issue and append to this issue when I find anything.

**Comment by danielvandenberg95** [comment]
It is mentioned in Google Issue Tracker by [Issue 206229](https://code.google.com/p/android/issues/detail?id=206229). It is a false positive that seems to only be generated by Windows Defender.

The solution to this issue is to submit the file on https://www.microsoft.com/en-us/security/portal/submission/submit.aspx to make Microsoft recognize it as a false-positive and remove it from it's virus definitions.

Two possible workarounds are either temporarily disabling Windows Defender or switching to a different OS such as Linux.

This issue could in my opinion be closed, though future participants might run into the same issue. Perhaps there would be a place on for instance the wiki to mention this issue?

**Comment by zeapo** [comment]
Thanks for the info. The wiki is indeed a good place.
