### ISSUE TITLE
Repository Password

### ISSUE THREAD

**Issue by MrDoode** [zeapo/Android-Password-Store#2132]
I've setup a private repo with my passwords and established  that my Linux Maschine has access to it via ssh.
But when I try to do the same with password store. I get asked what my repository -password is. Ive no idea what this should be, since I also try to access the repo via ssh.

I've generated a key pair and added the public key to github. But when I try to connect via the app, the error accures.

Can anyone help me?

**Comment by msfjarvis** [comment]
Please use the [appropriate issue template](https://github.com/Android-Password-Store/Android-Password-Store/issues/new?assignees=&labels=C-bug%2CS-awaiting-triage&template=bug_report.yaml&title=%5BBUG%5D+) when creating issues in this repository.
