### ISSUE TITLE
No password select menu in webpages with Gello (CM13 stock browser)

### ISSUE THREAD

**Issue by shtrom** [zeapo/Android-Password-Store#214]
Recent CyanogenMod builds of CM13 ship with Gello (org.cyanogenmod.gello.browser; Chrome-based, I think) as the stock browser.

With this browser, password fields in HTML forms don't trigger the password selection menu. It still show in native UI (such as plain HTTP auth and other apps).

I'm not sure whether it's Password Store or Gello-related, but I thought I could explain the problem better in Password Store terms.

The bottomline question is: what is Password Store using to provide the password entry menu that Gello doesn't provide for HTML password input fields?

**Comment by wongma7** [comment]
The browser needs to send accessibility events. It doesn't bother unless the app recurses through the page elements til it finds a webview, which 'triggers' the sending of events. Since gello is chrome based this shouldn't be a problem. I'll try to get my hands on this browser and investigate

**Comment by zidhuss** [comment]
Feel free to re-open this issue if it's still present in the latest version.
