### ISSUE TITLE
[BUG] Repository password being requested on SSH authentication mode

### ISSUE THREAD

**Issue by anirudhgupta109** [zeapo/Android-Password-Store#2160]
### Describe the bug

When a repository (on GitHub) is added in the repository URL with the correct SSH URL (`git@github.com:{user}/{repository}.git`) and authentication mode set to SSH key with the key added to the user's GitHub account, it still requests for a password on selecting synchronize repository.

The same setup when done on the Play Store version of the app(1.13.5), works as intended (i.e. connection is made with no request of password)

### Steps to reproduce

1. Go to Settings>repository>Edit Git server settings
2. Enter correct SSH repository URL (private)
3. Select SSH key authentication mode
4. Add key to GitHub account
5. Synchronize repository from three dots
6. See prompt requesting for password

### Expected behavior

Should just synchronize repository instead of ask for a password

### Screenshots

![photo_2022-10-04_17-08-42](https://user-images.githubusercontent.com/29012333/193810538-410a45b7-3dd5-41df-86cf-10cdc5766f86.jpg)
![photo_2022-10-04_17-08-46](https://user-images.githubusercontent.com/29012333/193810544-133ae229-1d25-4188-9559-7b589e3f1258.jpg)

### Device information

- Device: OnePlus7T
- OS: Custom ROM Android 12
- App version: 2.0.0-SNAPSHOT (nonFree)

**Comment by msfjarvis** [comment]
Your SSH key failed to authenticate with GitHub and that's why the password prompt was presented as a fallback. The logcat will reveal why the authentication error happened.

**Comment by jkr** [comment]
This happened to me as well. My repo was not on GitHub. The key had been fine until that day. I uninstalled and reinstalled the app, made a new key, re-pulled, and then things worked. But something is definitely going on, beyond people just user error or some problem in the server side.

**Comment by msfjarvis** [comment]
If you can capture a log next time this happens to you and file an issue I can look into it, but so far it has always been user error.
