### ISSUE TITLE
Possible repository corruption

### ISSUE THREAD

**Issue by gilemk** [zeapo/Android-Password-Store#2168]
Hi,

I got a new phone (Pixel 6 Pro) and I am trying to setup the application to use the git repository. I have it setup with the same settings as the old phone (of course with a new ssh key). SSH authorization works, but I get an git error when I clone the git repository.

The repository works fine from my PC and the old phone, so I am sure the issue is local to the new phone.

![Screenshot_20220927-231934](https://user-images.githubusercontent.com/8150236/194757569-cbafca3a-1a67-40d3-8276-b3f9585f9efd.png)

Any hint on what I could do to troubleshoot this further?

Pixel 6 Pro (Android 13, but it was the same on version 12)

**Comment by msfjarvis** [comment]
Please use the issue template for bug reports and attach the relevant information requested there: https://github.com/Android-Password-Store/android-password-store/issues/new/choose
