### ISSUE TITLE
[BUG] git: Possible repository corruption

### ISSUE THREAD

**Issue by gilemk** [zeapo/Android-Password-Store#2169]
### Describe the bug

I got a new phone (Pixel 6 Pro) and I am trying to setup the application to use the git repository. I have it setup with the same settings as the old phone (of course with a new ssh key). SSH authorization works, but I get an git error when I clone the git repository.

The repository works fine from my PC and the old phone, so I am sure the issue is local to the new phone.

### Steps to reproduce

1. Go to Password Store
2. Click on three dots in the upper right corner
3. Scroll down to Synchronize repository
4. Unlock SSH key
5. "running git operation"
6. See error 
"An error occurred during a Git operation
remote: aborting due to possible repository corruption on the remote side"

Same happens if I delete the whole app and start from scratch.

### Expected behavior

The initialization of the repository should succeed so I can start using it to display and change/add passwords to it.

### Screenshots

![Screenshot_20220927-231934](https://user-images.githubusercontent.com/8150236/194758290-9f87e5f4-5c99-4dff-8400-1431fffcb0f0.png)

### Device information

- Device: Pixel 6 Pro
- OS: Stock Android v13 (same behavior with v12)
- App version 1.13.5

**Comment by gilemk** [comment]
Bump? I've tried many times and I can reproduce this quite easily. Anything else I can do in order to get some help?

**Comment by msfjarvis** [comment]
I haven't seen this issue anywhere so I'll need a repository that I can clone to reproduce this myself. In the mean time, can you try the [snapshot builds](https://docs.passwordstore.app/docs/users/release-channels/) and see if this happens there too?

**Comment by gilemk** [comment]
I tried and I get the exact same error.

**Comment by msfjarvis** [comment]
> I tried and I get the exact same error.

Great, can you share information about this Git host and the device logs from when you attempt to clone the repository and see the error?

**Comment by gilemk** [comment]
It is via ssh, I see that ssh connection is established then closed. I can't see any other logs, I did a tcpdump but of course the git transaction is encrypted. The git host, works fine with my older phone and my laptop, there are no issues there even with new commits.

**Comment by msfjarvis** [comment]
I have no information about the remote Git server and no way to replicate that environment so unless you are able to provide me a way to reproduce this bug on my end I will have to end up closing this is as unactionable.

**Comment by gilemk** [comment]
It's a local git server that I can not provide you access to. But if you tell me what steps to take and how to create debug logs that I can share, I am willing to do the work.

**Comment by msfjarvis** [comment]
> It's a local git server that I can not provide you access to. But if you tell me what steps to take and how to create debug logs that I can share, I am willing to do the work.

- Download the Android Platform Tools from [here](https://developer.android.com/studio/releases/platform-tools) and extract them into a directory
- Enable developer options on your device and turn on USB debugging by following [these steps](https://developer.android.com/studio/debug/dev-options)
- Enable debug logging for Password Store by going to Settings > Misc
- Open a new terminal in the directory where you extracted the platform tools
- Run `./adb shell am force-stop app.passwordstore` to close the app
- Launch the app again and replicate the issue
- Run `./adb logcat --pid=$(./adb shell pidof -s app.passwordstore) -d > log.txt` to capture the logs up till that point
- Upload `log.txt` either here or email it to `me` at username dot dev

**Comment by gilemk** [comment]
[log.txt](https://github.com/android-password-store/Android-Password-Store/files/9943531/log.txt)

Please take a look and let me know if you see something out of the ordinary.

**Comment by msfjarvis** [comment]
According to all references I can find online this is typically a problem with Git's `pack-objects` process being killed on the remote server. You can try changing these settings on the server to see if it helps

```
git config --global pack.windowMemory "100m"
git config --global pack.SizeLimit "100m" 
git config --global pack.threads "1"
git config --global pack.window "0"
```

**Comment by gilemk** [comment]
Thank you. I can clearly see that this is a local issue with the git server. It happens on the new phone just because I am doing an initial clone for whatever reason it's corrupted and I need to fix it. I can say we can close this.
