### ISSUE TITLE
[BUG] null array

### ISSUE THREAD

**Issue by kierun** [zeapo/Android-Password-Store#2172]
### Describe the bug

I tried to update via `Pull from remote` and got this error message.

```An error occurred during a Git operation

Error occured during the pull operation, Message from jgit: 
Attempt to get length of null array
Caused by:
null
Please check the FAQ for possible reasons why this error might occur.
```

### Steps to reproduce

1. Hit the three buttons.
2. Press "Pull from remote"
4. See error in screen shot above.

### Expected behavior

I expected `git pull` to work.

I tried a git clone using the same url and it worked on my Linux machine.

I re-generated the SSH key and updated it on the git side as well.

### Screenshots

![signal-2022-10-10-174907](https://user-images.githubusercontent.com/3079575/194916487-eedaa342-cf96-4044-928b-ee165a8e75fc.png)

### Device information

- Device: Pixel 4a
- OS: Android 13.
- App version: 1.3.3

### Additional context

I checked the old issues but nothing seemed correct, just one from 2019!

**Comment by msfjarvis** [comment]
You're on the wrong version of the app, you need to use this https://f-droid.org/en/packages/dev.msfjarvis.aps/

**Comment by kierun** [comment]
Yes, I have updated to the F-droid version and indeed, it works. Plus, it is much nicer than the Play Store version. :100: recommend anyone updated.

I am going to mark this as closed.
