### ISSUE TITLE
[BUG] Somehow updated from 1.3.2 to 1.3.5 lost all settings?

### ISSUE THREAD

**Issue by Gfurst** [zeapo/Android-Password-Store#2174]
### Describe the bug

For some reason F-droid was not updating (I was looking into another issue with syncing to my local repository and game null array).

So when I installed it from F-droid it gave a whole different version as opposed to upgrading the current one?  
Whats the deal here? Please if there is steps to not mess things up as I had a completely working setup before.

### Steps to reproduce

1. Try to update
2. Download from store
3. Have two concurrent versions

### Expected behavior

A proper update.

### Device information

- Device: Samsung J5P
- OS: Android 8.0
- App version [1.3.2] & [1.3.5]

**Comment by msfjarvis** [comment]
The versions are 1.3.2 and **1.13.5**. They're different apps because the project changed maintainers and the previous maintainer felt users should be aware that such a thing happened, hence the split.

There are no steps to share, you should simply re-add your repository the same way you did to the old version of the app.

**Comment by Gfurst** [comment]
Damn that is kind of annoying, well I'm not sure I can push the repository from my mobile to my server, so there is a possibility that something could be lost in the change.

**Comment by msfjarvis** [comment]
> Damn that is kind of annoying, well I'm not sure I can push the repository from my mobile to my server, so there is a possibility that something could be lost in the change.

There should be an export option in the older app as well, you can dump the Git repository wholesale into an accessible part of your phone storage, pull it to your computer and use it like any other Git repository to ensure you've pushed everything from it to your remote.
