### ISSUE TITLE
[BUG] Keys with AEAD algorithms set cannot be used with the app

### ISSUE THREAD

**Issue by ruedigerblock** [zeapo/Android-Password-Store#2179]
### Describe the bug

I am using the APS-freeRelease-2.2.0.0-SNAPSHOT (from 11.10.2022 (dd.mm.yyyy))

GPG Key Pair is created on MacOS using the --openpgp Flag.

As soon as I select a Password to decrypt and enter the Password for the Secret Key the following Exception is thrown:

```
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: app.passwordstore.crypto.errors.UnknownError
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository.access$decryptPgp(SourceFile:353)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository$decrypt$2.invokeSuspend(SourceFile:35)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:109)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(SourceFile:13)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:77)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: Caused by: java.util.NoSuchElementException: No direct-key signature and no user-id signature found.
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at org.pgpainless.key.info.KeyRingInfo.getPrimaryKeyExpirationDate(SourceFile:128)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at org.pgpainless.key.info.KeyRingInfo.getEncryptionSubkeys(SourceFile:1)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at org.pgpainless.decryption_verification.DecryptionStreamFactory.processPGPEncryptedDataList(SourceFile:674)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at org.pgpainless.decryption_verification.DecryptionStreamFactory.processPGPPackets(SourceFile:17)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at org.eclipse.jgit.lib.IndexDiff$1.withOptions(SourceFile:408)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository.access$decryptPgp(SourceFile:285)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	... 6 more
```

I am using `pass` on Mac and that works ok.
I suspect an issue with my GPG Key Pair but ran out of ideas on what to check / change.

### Steps to reproduce

1. Go to Passwords
2. Click on Password to be decrypted
3. Enter Secret Password
4. Message appears saying that the Password is wrong but it is not.

### Expected behavior

It should display the encrypted password

### Device information

- Device: [Sony Xperia XZ2 Compact]
- OS: [Lineage 19.1]
- App version [e.g. 3.1.0]

**Comment by msfjarvis** [comment]
Have you imported your key into the app? Password Store does not use OpenKeychain anymore.

**Comment by ruedigerblock** [comment]
Yes, I did. Using Settings -> PGP Settings -> Import PGP Key.

My Key (and the ID) is listed in the Key Manager.

**Comment by msfjarvis** [comment]
Can you generate another GPG keypair on your machine, zip it up and attach it here? You can use `John Doe <john.doe@example.com>` for the identity.

**Comment by ruedigerblock** [comment]
Sure. Private Key Password = `Password`
[gpg-pair.zip](https://github.com/android-password-store/Android-Password-Store/files/9765370/gpg-pair.zip)

**Comment by ruedigerblock** [comment]
Update: Created a fresh Repo and a Key Pair on my RaspberryPi:
$ gpg --version
gpg (GnuPG) 2.2.27
libgcrypt 1.8.8

and it works flawlessly !

On Mac on the other hand it does not:
❯ gpg --version
gpg (GnuPG) 2.3.7
libgcrypt 1.10.1

I don't know if you want to to dig into it further. If so I am more than happy to assist. 
But I got a work around.

**Comment by msfjarvis** [comment]
Looks like it might be related to [this](https://github.com/android-password-store/Android-Password-Store/discussions/1429) in that case.

**Comment by ruedigerblock** [comment]
Yes. But should'nt we make sure that Android Password Store also works with Keys generated in recent GPG versions ? Or at least it must be documented somewhere.

**Comment by msfjarvis** [comment]
> Yes. But should'nt we make sure that Android Password Store also works with Keys generated in recent GPG versions ? Or at least it must be documented somewhere.

I do intend to resolve this which is why the issue is still open. When I have the bandwidth for it I will submit a failing test upstream for the PGPainless maintainer to take a look at.

**Comment by msfjarvis** [comment]
https://msfjarvis.dev/aps/pr/2218#issuecomment-1296911526
