### ISSUE TITLE
Unticking "Show password" doesn't allow for sharing, nor editing.

### ISSUE THREAD

**Issue by danielvandenberg95** [zeapo/Android-Password-Store#218]
When the setting "Show the password" is disabled, it's impossible to
- Share a password
- Copy an entry in the password store
- Read the extra content (may be intended, maybe not?)

I think it would be a good idea to not close the PGPHandler right away when this setting is on? I'd expect it to really only do as it says, which is not show the password (just setting the TextViews visibility to GONE).

**Comment by zeapo** [comment]
I guess this is no longer an issue as you've fixed it :)
