### ISSUE TITLE
[FEATURE] Support of media types (jpg, png, pdf, docx)

### ISSUE THREAD

**Issue by WhiteBlackGoose** [zeapo/Android-Password-Store#2183]
### Is your feature request related to a problem? Please describe.

Among passwords and texts, I also store most important pictures and documents in `pass`. On my laptop I just decrypt and pipe it into a file with corresponding extension, open it, then, when finished, delete.

### Describe the solution you'd like

It would be nice to have a preview of files ending with jpg/png/pdf/etc. and/or exporting them into a file

### Describe alternatives you've considered

So options are:
1. Preview of a file with corresponding extension
2. Exporting into a file
3. Adding a possibility to open the text as file with corresponding extension with a given program (I guess the easiest option)

### Additional context

Thanks for this great app! :heart:

**Comment by msfjarvis** [comment]
I'm sorry but this is simply not worth the effort it would take to implement. I prefer keeping the app's scope as narrow as it can be while serving the 90% use case for the `pass` ecosystem and arbitrary files do not fall in that scope for me.

**Comment by WhiteBlackGoose** [comment]
Okay, that's np. Still a great app! I'll perhaps try to find a workaround later then
