### ISSUE TITLE
[FEATURE] PGP Armored encoding

### ISSUE THREAD

**Issue by ldepandis** [zeapo/Android-Password-Store#2189]
### Is your feature request related to a problem? Please describe.

I'm using Pass both on my Linux machines and on my iPhone, and I always use the armored encoding for every secret stored, so it can be ASCII-friendly but still encrypted.
While on Pass I can configure the environment variable to pass the --armor flag to GnuPG, and in Pass for iOS I can turn on the related switch, I couldn't find something similar to Password Store for Android, so whenever I save or edit a secret with this app it will be no armored.
Since I'd like to have consistency about the encoding of my secret, I'd like to ask you if such feature could be implemented.

### Describe the solution you'd like

I'd like a switch in the Settings options that can turn on the armoring encoding when PGP is encrypting the text, just like Pass for iOS.

### Describe alternatives you've considered

The alternative would be disabling the armoring encoding, so everything would be consistent again.
But since I have a lot of credentials, it would be very tedious to do for everything.

### Additional context

Screenshot from Pass for iOS

![E84EB3CD-025E-4A3C-86B3-D1A85809BB79](https://user-images.githubusercontent.com/77971920/196147998-e54474ec-7f72-4f97-b098-fb0e5f4197a6.jpeg)

**Comment by msfjarvis** [comment]
Implementation notes for whoever ends up picking this

- The decision to (not) ASCII armor is made [here](https://github.com/android-password-store/Android-Password-Store/blob/4b77e3bd0dba979f8f4bfd103af26b055a6ad157/crypto-pgpainless/src/main/kotlin/app/passwordstore/crypto/PGPainlessCryptoHandler.kt#L83)
- The method is called by app code [here](https://github.com/android-password-store/Android-Password-Store/blob/4b77e3bd0dba979f8f4bfd103af26b055a6ad157/app/src/main/java/app/passwordstore/data/crypto/CryptoRepository.kt#L49-L60), the `CryptoRepository` class can take in a `SharedPreferences` constructor parameter to signal the settings value
