### ISSUE TITLE
[BUG] SteamGuard totp not working properly when only issuer is set

### ISSUE THREAD

**Issue by igaryhe** [zeapo/Android-Password-Store#2191]
### Describe the bug

I had the totp uri like this: `otpauth://totp/Steam:username?secret=SECRETREDACTED&issuer=Steam`, and in the password view, in the "OTP" field it shows a 6 digits numeric string. if i append an `&digits=s` to the totp uri, it works properly, generating the steam 5 digits string. however, in `Otp.kt`, it shows that either `digits=s` or `issuer=Steam` should trigger the SteamGuard otp algorithm https://github.com/android-password-store/Android-Password-Store/blob/6d73b63435a2760ec9026090ecfea4846157b6ab/format-common/src/main/kotlin/app/passwordstore/util/totp/Otp.kt#L54-L62

### Steps to reproduce

- put line like `otpauth://totp/Steam:username?secret=SECRETREDACTED&issuer=Steam` inside a password file
- decrypt the password file
- it shows a 6 digits numeric string in the "OTP" field

### Expected behavior

if i have otpauth line like `otpauth://totp/Steam:username?secret=SECRETREDACTED&issuer=Steam` (without `digits=s`) should also produce SteamGuard's 5 digits otp string.

### Device information

- Device: Sony Xperia 5 II
- OS: Sony's Android 12
- App version 1.13.5

**Comment by msfjarvis** [comment]
I use a SteamGuard URI without the `digits=s` parameter and it generates codes just fine so I don't think this bug exists but I'd like to extend our test coverage for this either way.

Implementation notes for myself

- Move existing `OtpTest` to `app` module
- Rework it to use TOTP URIs and secrets
- Run the test against `UriTotpFinder` rather than a fake

**Comment by msfjarvis** [comment]
I added a test as part of that refactor PR that checks if Steam OTPs generate the same way for both `issuer=Steam` and `digits=s` which confirms that this is indeed not a bug that exists.
