### ISSUE TITLE
[FEATURE] add OTP support for autofill

### ISSUE THREAD

**Issue by formula-spectre** [zeapo/Android-Password-Store#2200]
### Is your feature request related to a problem? Please describe.

I'm mildly annoyed that each time I have to fill OTP I have to switch back and forth apps. It would be nice to have the option to autofill OTP in place

### Describe the solution you'd like

when the autofill popup opens, you can choose which  OTP the box should be filled with

### Describe alternatives you've considered

I've pondered separating my OTP from `pass`, and use a separate desktop client and Aegis Auth

### Additional context

I'm deeply sorry for the other FR, I was not aware there were template since I did it on mobile, I apologize.
I know that it would be a smarter move to separate OTPs from my pass account, so if that's compromised my OTPs are still safe, but having an option to choose would be good nontheless.

**Comment by msfjarvis** [comment]
I completely forgot that this was fixed over two years ago: #663

If there are examples of specific websites where you can't seem to make this work, please share them here.
