### ISSUE TITLE
Internal Exception occured

### ISSUE THREAD

**Issue by githlp** [zeapo/Android-Password-Store#2224]
### Describe the bug

I have installed the 1.13.5 from F-Droid Store, generated a RSA-key, added the provided key in my git-server and set up the  Server settings in the app to

Repository-URL
ssh://git@git.mydomain.de:2524/user/repo.git

Branch
master

Auth. method
SSH-KEY

But i cannot clone my repo from git server.

The error message reads:
`failed to connect to git.mydomain.de/[myextip] (port 2524) from /:: (port 48256): connect failed: ETIMEDOUT (Connection timed out)`

Since it works well with linux password-store and the Firewall indicates it passed the request from Android to the git server on port 2524 i don't get the problem why the Android password store cannot pull the repository..

### Expected behavior

should sync like the linux password-store

### Device information

- Device: Google Pixel 4a
- OS: GrapheneOS
- App version 1.13.5

**Comment by msfjarvis** [comment]
There's nothing to solve here, this is a timeout exception from the Android networking stack. If the system says the connection timed out, then it did time out.

**Comment by githlp** [comment]
It was the second FW. Your comment pointed me to the right direction to investigate, works now. Thx.
