### ISSUE TITLE
[BUG] Multi-key encryption does not work, if the keys have the same email

### ISSUE THREAD

**Issue by WhiteBlackGoose** [zeapo/Android-Password-Store#2227]
### Describe the bug

Password store only distinguishes keys by emails, whereas the whole key ID is a unique identifier, unlike email. So if you have 1 key with quack@aaa and two keys with duck@aaa, it will encrypt the password only with two keys (one key per email).

I think the wrong logic is [here](https://github.com/android-password-store/Android-Password-Store/blob/a2e7d0e5e23639d78eb0652e09cdbadd296341f6/app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt#L306):
```
OpenPgpUtils.splitUserId(identifier).email?.let { GpgIdentifier.UserId(it) }
```
where it only takes `email` field into account.

### Steps to reproduce

1. Using `gpg` on your computer, generate keys with the following IDs: `goose <goose@farm>`,  `duck <goose@farm>`, `matt <matt@company>`
2. Re-encrypt your passwords using `pass init "goose <goose@farm>", "duck <goose@farm>", "matt <matt@company>"`
3. Sync with the remote server
4. Pull it in Password Store Android
5. Send the public keys for all three Key IDs to your phone and import them in OpenKeyChain
6. Add a random entry `test` in Password Store Android
7. Sync with the remote server
8. Pull it to your PC
9. Run `gpg ~/.password-store/test.gpg`

In the end, you will see, that it is only encrypted with `goose <goose@farm>` and `matt <matt@company>`. The other key got lost -_-.

### Expected behavior

It should be encrypted with all 3 keys.
It should consider the whole Key ID instead of just email.

### Device information

- Device: Samsung Galaxy A22s
- OS: Android 12
- App version: 1.13.5

### Workarounds

Workaround 1: create another key with a unique email and export public key to your phone
Workaround 2: create another key with a unique email, but without exporting: then OpenKeyChain will be confused about list of recepients and you will be able to check all recepients

### Additional context

Great app, btw!

**Comment by WhiteBlackGoose** [comment]
Workaround 1: create another key with a unique email and export public key to your phone
Workaround 2: create another key with a unique email, but without exporting: then OpenKeyChain will be confused about list of recepients and you will be able to check all recepients

**Comment by msfjarvis** [comment]
This cannot be fixed for the 1.13.x release train due to Google Play's target SDK restrictions preventing the release of an update but I'll add a test for the PGPainless backend and implement a fix if required.

**Comment by WhiteBlackGoose** [comment]
Thanks! :heart:

**Comment by msfjarvis** [comment]
Took me a while but I've put down full tests for this use case in both the PGP key manager and the PGP cryptography handler. Both reveal that APS does not have issues with handling this pattern, with the following caveat:

Given two keys with the identities `Alice <owner@example.com>` and `Bob <owner@example.com>`, putting `owner@example.com` in your `.gpg-id` is not a fatal error. The key matcher will pick one of the two keys with no guarantees on which one it will be. I'm not yet sure if it should be a fatal error, or it being undefined is fine.

**Comment by WhiteBlackGoose** [comment]
It should encrypt with both though, not with one. I put both Key IDs in my .gpg-id:
```
$ cat .gpg-id
Alice <owner@example.com>
Bob <owner@example.com>
```

**Comment by msfjarvis** [comment]
> It should encrypt with both though, not with one. I put both Key IDs in my .gpg-id:
> 
> ```
> $ cat .gpg-id
> Alice <owner@example.com>
> Bob <owner@example.com>
> ```

You're on the older version of the app. Like I said in the previous discussion, APS no longer uses OpenKeychain. The tests I added confirm that this bug does not exist in the current PGP implementation.

**Comment by WhiteBlackGoose** [comment]
Oh! I see. Thanks so much.

Trying out the latest free snapshot right now, but it gives
```
An error occurred during a Git operation
Socket closed
```
sometimes alternating with
```
An error occurred during a Git operation
Timeout expired
```

Any idea what it could be? Trying to clone from github.com. I filled in the username, email, and generated the SSH key (and added it on github)

(also I was trying to figure out free vs non-free difference, but the page [build-types](https://docs.passwordstore.app/docs/users/release-channels/build-types) referred by [release-channels](https://docs.passwordstore.app/docs/users/release-channels/) doesn't exist )

**Comment by msfjarvis** [comment]
> Oh! I see. Thanks so much.
> 
> Trying out the latest free snapshot right now, but it gives
> 
> ```
> An error occurred during a Git operation
> Socket closed
> ```
> 
> sometimes alternating with
> 
> ```
> An error occurred during a Git operation
> Timeout expired
> ```
> 
> Any idea what it could be?

Both of them are network errors, the app doesn't have much control over it.

> 
> (also I was trying to figure out free vs non-free difference, but the page [build-types](https://docs.passwordstore.app/docs/users/release-channels/build-types) referred by [release-channels](https://docs.passwordstore.app/docs/users/release-channels/) doesn't exist )

[It does exist](https://docs.passwordstore.app/docs/users/build-types), the release channels page seems to be creating an invalid relative link. I'll look into it.

Edit: in the mean time I've changed the snapshot description to just link the build types page directly https://msfjarvis.dev/aps/007137494cce

**Comment by WhiteBlackGoose** [comment]
> Both of them are network errors, the app doesn't have much control over it.

Hm, I don't get it in the old version. And the internet works on the phone. (restarted the phone, but still the same)

Also, idk if it deserves a separate issue, but after (unsuccessful) trying to clone the repo with the new version, I can't open it. It freezes at a black screen (or just heavily lags)

**Comment by msfjarvis** [comment]
> > Both of them are network errors, the app doesn't have much control over it.
> 
> Hm, I don't get it in the old version. And the internet works on the phone. (restarted the phone, but still the same)
> 
> Also, idk if it deserves a separate issue, but after (unsuccessful) trying to clone the repo with the new version, I can't open it. It freezes at a black screen (or just heavily lags)

Please follow the steps [here](https://github.com/android-password-store/Android-Password-Store/issues/2169#issuecomment-1304459308) to capture a log and file a separate issue.
