### ISSUE TITLE
F-DROID repo not working

### ISSUE THREAD

**Issue by cerberii** [zeapo/Android-Password-Store#223]
Trying to download latest version on fdroid results in downlosd unsuccessful.  Also icon missing.

**Comment by zeapo** [comment]
That's an F-Droid issue.

Did you try with older verions? Other applications?

**Comment by gschwaer** [comment]
Works fine for me. (Android 4.4.2, F-Droid 0.101, Password Store 1.2.0.52)

**Comment by cerberii** [comment]
not working for me android 6.0.1 F-droid  Password Store only shows
1.2.0.48  F-droid 0.100.1  Even fdroid website says only version 0.100.1
(100150) available.  where are you using 0.101 ?  I see news release says
0.101 was released, but only available download is 0.100.1

**Comment by rfb** [comment]
@cerberii have you tried refreshing the fdroid repo? When I first tried to install it kept failing because the version of Password Store wasn't available. After refreshing the fdroid repo, 1.2.0.52 was availabe and installed.

**Comment by cerberii** [comment]
ok I had something wierd happened.  I unisntalled completely and rebooted
and fdroid was still there.  I uninstalled again and rebooted and it was
gone finally.  NOW reinstall and it worked!   Yes totally F-droid problem.
