### ISSUE TITLE
Can't clone git repo

### ISSUE THREAD

**Issue by XenGi** [zeapo/Android-Password-Store#224]
When I try to clone my git repo I get the following message:

```
Internal exception occurred

Message from jgit:
Invalid remote: origin
```

I don't understand what's wrong here. Shouldn't the git client name the remote what ever it wants?

**Comment by zeapo** [comment]
It should. By default it uses master.

We have an issue with jgit error messages :/

**Comment by XenGi** [comment]
Do you have any clue why I'm getting this?

My settings are similar to this:

  - username: gitolite
  - server url: 123.456.789.1
  - port: 2222
  - repo path: /var/lib/gitolite/repositories/password-store.git

So the resulting url looks like: 

```
gitolite@123.456.789.1:2222/var/lib/gitolite/repositories/password-store.git
```

For authentication I use a 4096bit RSA ssh-key.

**Comment by zeapo** [comment]
That looks like an issue we had before. Could you please add ssh:// before
the URL?

Le 21 sept. 2016 1:06 PM, "Ricardo Band" <notifications@github.com> a
écrit :

**Comment by XenGi** [comment]
The protocol is already set to `ssh://`. When I also add it to the resulting url it gets in the username field aswell. When I hit clone The password prompt for the keyfile appears and the `ssh://` prefix is removed in the background. On `OK` it shows me the same error message.

**Comment by zeapo** [comment]
Is your repository a bare repository?

Le 21 sept. 2016 1:11 PM, "Ricardo Band" <notifications@github.com> a
écrit :

**Comment by XenGi** [comment]
Yes. It's a gitolite repo.

**Comment by XenGi** [comment]
When I type in a wrong password for the key or misspell the username I get an authentication failure. So that part seems to work.
When I put in the wrong name of the git repo I get the same message as in the beginning, so maybe the directory isn't correct.

**Comment by zeapo** [comment]
Ah, I just noticed your path.

Does your user have access to that directory? Did you try to clone it on your machine?

**Comment by XenGi** [comment]
Got it. The App told me that I need to use a full path because I run SSH on a non standard port so I did. But now I tried using just the repo name (myrepo.git) and it worked.
