### ISSUE TITLE
Beta testing

### ISSUE THREAD

**Issue by IamPr377y** [zeapo/Android-Password-Store#227]
I know the current version of the app is already labeled beta on play store, but it would be nice to have a real beta version with the latest updates from git. It allows developer to make staged rollouts and I guess publishing is faster.

**Comment by gschwaer** [comment]
I don't see the problem here. If you want to have a fast development cycle just install [F-Droid](https://f-droid.org/). As long as the versions on play-store are stable I think it is better this way. But this is a matter of taste, I guess.

**Comment by IamPr377y** [comment]
I do not suggest to replace current stable version with beta. Google Play has optional [beta](https://support.google.com/googleplay/android-developer/answer/3131213?hl=en) tests that are available for users who want to participate. Using two "stores" is just not convenient.

**Comment by polyzen** [comment]
F-Droid is also capable of beta releases. :+1:

**Comment by zeapo** [comment]
It's indeed a good idea. This would alow play users to keep the same signature for the app. I have to check how to handle the build process etc

**Comment by zeapo** [comment]
The latest builds will be available here https://play.google.com/apps/testing/com.zeapo.pwdstore

**Comment by IamPr377y** [comment]
It says that beta testing is only available by invitation.

**Comment by zeapo** [comment]
could you check again?

**Comment by IamPr377y** [comment]
I am now a beta tester and updated to 1.2.0.53. The last thing to do is to change a title. Thank you!
