### ISSUE TITLE
[FEATURE] Allow ignoring TLD when searching password file

### ISSUE THREAD

**Issue by presto8** [zeapo/Android-Password-Store#2274]
### Is your feature request related to a problem? Please describe.

I currently have my password file set up with just the domain name, e.g., amazon.gpg, cloudflare.gpg, etc.

When searching for autofill in Firefox, Password Store does not seem to match on those, instead it seems it wants amazon.com.gpg for example.

### Describe the solution you'd like

When searching the password store, first try to match on the full domain (e.g., amazon.com) and if that doesn't have any matches, then strip off the TLD and try again (e.g., amazon).

### Describe alternatives you've considered

Alternative is for me to rename all of my files in my repository. However, I think it looks tidier to have them without the TLD.

### Additional context

Thank you!

**Comment by msfjarvis** [comment]
The search dialog has a button at the bottom that turns off phishing resistant search which will allow you to do a normal fuzzy search.

**Comment by presto8** [comment]
Thanks! I didn't think about phishing protection. D'oh! I am off to rename my hundreds of password files to add the TLD now :-)

I couldn't find the button for enabling the fuzzy search, but it doesn't matter anymore since I'll just rename my files.

Thanks!

**Comment by msfjarvis** [comment]
> Thanks! I didn't think about phishing protection. D'oh! I am off to rename my hundreds of password files to add the TLD now :-)
> 
> I couldn't find the button for enabling the fuzzy search, but it doesn't matter anymore since I'll just rename my files.
> 
> Thanks!

Fuzzy search is the default, phishing resistant search is an additional filter on top of it.

**Comment by presto8** [comment]
Thanks for your guidance. I did eventually find the filter. However, it does not seem to have any effect either way. Let's say I'm on chase.com but my pass file entry is "chase.gpg". The pop-up window on the phone does not show anything and it suggests to search Password Store for "chase.com". Then when I click that, chase.com is pre-populated in the search box. Toggling the phishing resistance checkbox makes no difference. However, manually removing the .com from the search box does finally find it.

I didn't really explain the original feature very well I see now. What I should have said, was, if I am on chase.com, and I have the password entry as chase.gpg, then it would be nice to have the in-app dialog find that without having to go to the search window.

Some other extensions work this way (like PassFF on Firefox and Pass on iOS). But I acknowledge the point that it is less secure, since it would match chase.org as well as chase.com.

**Comment by msfjarvis** [comment]
I don't think I'll implement that, I believe in secure defaults where possible and phishing resistant search for the initial dataset is the safer option. The browserpass extension I use does the same phishing check as Password Store so clearly there's no consensus.

**Comment by presto8** [comment]
I agree with you, it is definitely more secure to match against the full domain. I just wanted to document the current behavior in case anyone stumbles across this issue in the future.

In the meantime, I am slowly renaming all of my pass entries to add the TLD :-)
