### ISSUE TITLE
[BUG] Passwords are leaked with Android 13's clipboard editor overlay

### ISSUE THREAD

**Issue by franok** [zeapo/Android-Password-Store#2288]
### Describe the bug

When copying a password to the clipboard on Android 13, the clipboard content is shown as a sort of message toast in clear text. This leaks the password to every person looking at the screen.

### Steps to reproduce

1. Go to a password file and decrypt.
2. Click on "Copy password button"
3. See error: Password is leaked on screen.

### Expected behavior

Do not leak password in clear text on the screen when copied to clipboard.

Please issue a patch release for this, on F-Droid and Playstore. It is really critical.
Thank you!

### Screenshots

![Screenshot_2022-12-08-00-05-16-32_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/17296805/206316750-d0417be3-f7d8-416e-bf51-7047b7c9c943.jpg)

This is an example of copying a simple text. Behavior is the same when copying a password in android password store.

### Device information

- Device: OnePlus 8T
- OS: Android 13
- App version: 1.13.5 (from F-Droid store)

### Additional context

Seems like this problem can be solved by setting a flag, see:

- https://1password.community/discussion/132503/android-13-clipboard-preview-shows-passwords-on-screen
- https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#SensitiveContent

```
// When your app is compiled with the API level 33 SDK or higher
clipData.apply {
    description.extras = PersistableBundle().apply {
        putBoolean(ClipDescription.EXTRA_IS_SENSITIVE, true)
    }
}

// If your app is compiled with a lower SDK
clipData.apply {
    description.extras = PersistableBundle().apply {
        putBoolean("android.content.extra.IS_SENSITIVE", true)
    }
}
```

**Comment by msfjarvis** [comment]
This was already fixed five months ago https://github.com/android-password-store/Android-Password-Store/commit/ade73fd5bc38e8e1f1a4ab3b44132da63f2f7982. The snapshot releases might be of interest: https://docs.passwordstore.app/docs/users/release-channels/ .

**Comment by franok** [comment]
Thanks for the quick response :)

Great to hear this problem is already fixed.
The snapshot release is a workaround 👍🏻, but:
Will you consider publishing a patch release (1.13.6) to Playstore and F-Droid for rolling out this fix any time soon?
The snapshot build is a major version increase and I would prefer to have a stable version of APS for daily use.

**Comment by msfjarvis** [comment]
> Great to hear this problem is already fixed. The snapshot release is a workaround 👍🏻, but: Will you consider publishing a patch release (1.13.6) to Playstore and F-Droid for rolling out this fix any time soon? The snapshot build is a major version increase and I would prefer to have a stable version of APS for daily use.

I do not have the bandwidth to backport things for a patch release and even if I did, I can't publish it to Google Play due to the stricter enforcement of storage permission usage for updating apps. Working on v2 is the only reasonable option for me.

**Comment by franok** [comment]
I fully understand. On the other hand I also feel a little concerned regarding critical vulnerabilities.

In any ways: Thanks for your great work on APS & I'm looking forward  to the 2.x release :)

**Comment by msfjarvis** [comment]
> I fully understand. On the other hand I also feel a little concerned regarding critical vulnerabilities (e.g. log4j bug "log4shell", etc) not being patched. (However it looks like APS is not using log4j?)

There's no reason for APS to use Log4J and even if it did, the the actual vulnerability would never be triggered because the logging format is controlled by us.
