### ISSUE TITLE
[BUG] OpenKeychain integration no longer works rendering Password Store unusable

### ISSUE THREAD

**Issue by kensmith** [zeapo/Android-Password-Store#2289]
### Describe the bug

I'm not sure if this is an issue with Password Store, OpenKeychain (I've filed https://github.com/open-keychain/open-keychain/issues/2805 requesting help there), or if it has something to do with the latest Android security update. It seems to have broken today when I updated Android to the latest version, Android 13, build number TQ1A.221205.011.

### Steps to reproduce

1. Attempt to unlock any password
2. Present yubikey to unlock key in OpenKeychain
3. No result.
4. Repeating this a couple times results in a popup that says OpenKeychain keeps crashing.

### Expected behavior

1. Attempt to unlock any password
2. Present yubikey to unlock key in OpenKeychain
3. Password is unlocked and copied to the clipboard (depending on configuration)

### Screenshots

None would be helpful.

### Device information

* Device: Google Pixel 6 and Google Pixel 6a yield the same results
* OS: Android 13 build number TQ1A.221205.011
* Password Store version 1.13.5 (fdroid)
* OpenKeychain version 5.7.5

**Comment by msfjarvis** [comment]
If OpenKeychain is crashing then it's not a Password Store bug, and since we've already started work towards [not using OpenKeychain anymore](https://github.com/android-password-store/Android-Password-Store/issues/1195) there's nothing for us to do.
