### ISSUE TITLE
Fingerprint support

### ISSUE THREAD

**Issue by rti** [zeapo/Android-Password-Store#229]
Unlock gpg key with fingerprint sensor instead of password. 

Possibly helpful:
https://github.com/pro100svitlo/FingerprintAuthHelper

**Comment by zeapo** [comment]
This should be opened on OpenKeychain repository as it's the app handling the gpg key and not us.

**Comment by rti** [comment]
Ok. I understand. This is actually already being discussed for some time over there. 

https://github.com/open-keychain/open-keychain/issues/1642
