### ISSUE TITLE
[FEATURE] add support for `pass grep` searches

### ISSUE THREAD

**Issue by DurvalMenezes** [zeapo/Android-Password-Store#2309]
### Is your feature request related to a problem? Please describe.

I need to search *inside* the key contents (ie in the "extra content" area)  like `pass grep` does, but see no way to do that: the normal search function (via the magnifying glass icon) only searches the key names (a la `pass find`).

### Describe the solution you'd like

A great way to do that would be a setting to do the equivalent of `pass grep` instead of `pass find` while using the normal search (via the magnifying glass icon).

### Describe alternatives you've considered

A less convenient, but totally usable implementation, would be a 'grep' or 'content search' or similar option on the 'three vertical dots' menu.

**Comment by msfjarvis** [comment]
`pass grep` effectively decrypts all entries in your store which is fairly slow even on Linux and would be _prohibitively_ so on Android even with stores with around a 100 files. I can't justify working on such a large feature when it is basically guaranteed to be slow to the point of unusable.
