### ISSUE TITLE
[BUG] Seedvault Backup says that app does not allow data backup. Why?

### ISSUE THREAD

**Issue by bordenc** [zeapo/Android-Password-Store#2333]
### Describe the bug

Seedvault Backup (LineageOS 19.1) says that Password Store does not allow data backup. This means that I have to reinput everything from scratch when I reinstall Android and/or Password Store.

### Steps to reproduce

1. Open Backup in Android settings
2. (On LineageOS) configure Seedvault Backup
3. Click on Backup Status
4. Password Store is listed under "Apps that do not allow data backup"

### Expected behavior

Password Store is not listed under "Apps that do not allow data backup" and I can rest easy knowing that if I need to restore from a backup, I won't have to reenter all of the Password Store settings again.

### Device information

- Device: Google Pixel 2 XL
- OS: LineageOS 19.1 nightly
- App version: most recent on F-Droid

**Comment by msfjarvis** [comment]
There's no way for the app to specify who can back it up, only that it can be backed up. Under default configurations that will upload your entire store to Google Drive which is undesirable for us.

**Comment by bordenc** [comment]
> which is undesirable for us.

With respect, shouldn't the user decide what is right for them and not the developer?

**Comment by msfjarvis** [comment]
> > which is undesirable for us.
> 
> With respect, shouldn't the user decide what is right for them and not the developer?
> 
> 

There's no way for users to opt-out. We explicitly disabled backup after users were surprised that their stores were being automatically uploaded to Google Drive without their knowledge.

Edit: regarding "user should get to choose", that's absurd. You're using software I'm building for myself and providing gratis to the wider audience. The answer to every developer decision isn't "the user should get to choose", if they want the choice the fork button is right there.

**Comment by bordenc** [comment]
> You're using software I'm building for myself and providing gratis to the wider audience. The answer to every developer decision isn't "the user should get to choose", if they want the choice the fork button is right there.

I stand corrected. I thought this was a community. Thank you for clarifying

Edit: Good advice on forking the project. I trusted that this project wouldn't harvest my passwords, but that may have been a generous assumption.
