### ISSUE TITLE
[BUG] Autofill not working in FF and Chrome

### ISSUE THREAD

**Issue by sp1r1t** [zeapo/Android-Password-Store#2336]
### Describe the bug

The autofill is not filling in the form.

### Steps to reproduce

1. Go to a website login, e.g. gitlab.com/users/sign_in
2. Click on 'username or email'
3. The APS pop up opens, showing all entries for gitlab
4. Click on an entry
5. The pop up vanishes, otherwise nothing happens

### Expected behavior

1. - 4. Same as above
5. The username and password are filled in

### Device information

- Device: Galaxy Note 10+
- OS: Android 12
- App version 1.13.5

### Additional context

I enabled Autofill in the Settings. Otherwise I did not change any settings.

**Comment by msfjarvis** [comment]
We'll need a log: https://docs.passwordstore.app/docs/users/reporting-bugs

**Comment by sp1r1t** [comment]
Ok, I followed the instructions but it doesn't work for me.

ADB is installed, USB debugging is enabled, device is found:

```
./adb devices                                                                        
List of devices attached
RFCM802DV0H	device
```

BUT:
```
./adb shell am force-stop app.passwordstore                                                                           
./adb logcat --pid=$(./adb shell pidof -s app.passwordstore) -d > log.txt                                  
logcat: pid  out of range.
```

This is because  `./adb shell pidof -s app.passwordstore` does not return a value. It seams to me password store is not found by the activity manager.

I tried finding the service with `./adb shell dumpsys activity services pass`, but it just finds Samsung Pass (output is attatched). APS is open on the phone at the same time.

Am I missing a piece of the puzzle? How do I get the logs?

[adb-services-pass.txt](https://github.com/android-password-store/Android-Password-Store/files/10443435/adb-services-pass.txt)

Edit: Fix code formatting to multiline

**Comment by msfjarvis** [comment]
You're not doing anything incorrect, it's a problem with the docs. The package name `app.passwordstore` is for the in-development version of APS, and you should instead use `dev.msfjarvis.aps` instead.

Edit: updated the docs page [[commit](https://msfjarvis.dev/apsg/docs/e06fd664be4a)], the instructions should now work for all users.

**Comment by sp1r1t** [comment]
Oh yeah, calling things by their correct name is helpful of course (:

Log is attached.

[log.txt](https://github.com/android-password-store/Android-Password-Store/files/10444265/log.txt)

**Comment by msfjarvis** [comment]
According to the logs the app failed to communicate with OpenKeychain and raised a fatal error

```plaintext
01-18 10:31:29.304 12053 12417 E AutofillDecryptActivity$onStart: OpenPgpApi ACTION_DECRYPT_VERIFY failed
01-18 10:31:29.304 12053 12417 E AutofillDecryptActivity$onStart: java.lang.Exception: bindService() returned false!
01-18 10:31:29.304 12053 12417 E AutofillDecryptActivity$onStart: 	at me.msfjarvis.openpgpktx.util.OpenPgpServiceConnection.bindToService(OpenPgpServiceConnection.kt:7)
01-18 10:31:29.304 12053 12417 E AutofillDecryptActivity$onStart: 	at com.zeapo.pwdstore.autofill.oreo.ui.AutofillDecryptActivity.executeOpenPgpApi(AutofillDecryptActivity.kt:9)
01-18 10:31:29.304 12053 12417 E AutofillDecryptActivity$onStart: 	at com.zeapo.pwdstore.autofill.oreo.ui.AutofillDecryptActivity.decryptCredential(AutofillDecryptActivity.kt:19)
01-18 10:31:29.304 12053 12417 E AutofillDecryptActivity$onStart: 	at com.zeapo.pwdstore.autofill.oreo.ui.AutofillDecryptActivity$onStart$2.invokeSuspend(AutofillDecryptActivity.kt:6)
01-18 10:31:29.304 12053 12417 E AutofillDecryptActivity$onStart: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
01-18 10:31:29.304 12053 12417 E AutofillDecryptActivity$onStart: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
01-18 10:31:29.304 12053 12417 E AutofillDecryptActivity$onStart: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
01-18 10:31:29.304 12053 12417 E AutofillDecryptActivity$onStart: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

It is possible that OpenKeychain is being killed off by your OS, and the instructions [here](https://dontkillmyapp.com/samsung) could help.

**Comment by msfjarvis** [comment]
We can't do anything about it on our end so I'm going to go ahead and close this issue.

**Comment by sp1r1t** [comment]
I see. So the reason this failed is that OpenKeychain was not installed at all.
I never tried to view a password in-app. That's the only mention I found for it to be needed.

Works like a charm now (:

Maybe it would be good to put this info in the app store description or trigger the same dialog from the pop-up.

Anyway thanks for the fast bug replies!

**Comment by msfjarvis** [comment]
> I see. So the reason this failed is that OpenKeychain was not installed at all. I never tried to view a password in-app. That's the only mention I found for it to be needed.
> 
> Works like a charm now (:
> 
> Maybe it would be good to put this info in the app store description or trigger the same dialog from the pop-up.

This has been in the app for [around two years now](https://msfjarvis.dev/aps/pr/1005), but you found the one code path where it won't trigger :D
