### ISSUE TITLE
Missing permission request for key import

### ISSUE THREAD

**Issue by bclermont** [zeapo/Android-Password-Store#237]
On a first execution of Open Keychain (OK) I wanted to import my SSH private  key exported from my desktop and copied on Android internal storage. But I couldn't `EPERM (Permission Denied)`. 

It's only when I `Select external repository` that it asked for storage permission.  then I could import the key.

**Comment by zeapo** [comment]
That's weird, we added a request for External Storage permissions on startup.

**Comment by zeapo** [comment]
OK, found it. Thanks for noticing.

**Comment by zeapo** [comment]
fixed in ed698a26bf1c8559bd065373ed2fcf2f9ca6f36a
