### ISSUE TITLE
ln -s real.gpg link.gpg

### ISSUE THREAD

**Issue by mortenkjarulff** [zeapo/Android-Password-Store#2396]
Hi.

Would it be possible to support links?
Works fine in pass on Linux, but when synchronized to app on Android, i can't decrypt it.

/Morten

**Comment by msfjarvis** [comment]
Duplicate of #636 

TL;DR symlink support varies between Android versions and it is not possible to reliably support it. For future issues please take care to use the issue templates or I will close them without response.
