### ISSUE TITLE
[BUG] Unable to install on Android 13

### ISSUE THREAD

**Issue by kevinoid** [zeapo/Android-Password-Store#2403]
### Describe the bug

I'm unable to install [Password Store](https://play.google.com/store/apps/details?id=dev.msfjarvis.aps) from the Play Store because

> This app isn't available for your device because it was made for an older version of Android.

### Steps to reproduce

1. Go to the [Password Store](https://play.google.com/store/apps/details?id=dev.msfjarvis.aps) page in the Google Play store app.
2. Observe that the app is not installable and the error message "This app isn't available for your device because it was made for an older version of Android." is displayed.

### Expected behavior

The app would be installable via Google Play.

### Screenshots

<img src="https://user-images.githubusercontent.com/336433/223207233-1b903082-2a2d-4324-8b1e-bddfc3625155.png" alt="Screenshot of Password Store on Google Play showing the error message 'This app isn't available for your device because it was made for an older version of Android.'" height="512" />

### Device information

- Device: Google Pixel 5a
- OS: Android 13 build TQ1A.230205.001.D2
- App version:

**Comment by msfjarvis** [comment]
I'm aware of the issue, the app runs fine on Android 13 but I can't make the changes Google Play wants without breaking the app for a large chunk of its users. The current development branch is building towards a v2.0.0 release that will be published as a separate app with major, breaking changes but there is no ETA for it.

You can download the app from any of [the alternate release channels](https://docs.passwordstore.app/docs/users/release-channels), but be aware that the snapshot builds may have bugs not found in the 1.13.5 release available on GitHub releases and F-Droid.

**Comment by kevinoid** [comment]
Thanks @msfjarvis!  Is there an open issue that Android 13 users can follow to get notified when there is a supported release available?

**Comment by msfjarvis** [comment]
> Thanks @msfjarvis! Is there an open issue that Android 13 users can follow to get notified when there is a supported release available?

There is not.
