### ISSUE TITLE
LG Clipboard history not cleared with Clear clipboard 20 times

### ISSUE THREAD

**Issue by jfjallid** [zeapo/Android-Password-Store#241]
On my LG G4 the "Clear clipboard 20 times doesn't clear the clipboard history" After the app has tried to clear the clipboard I usually see some kind of number in the most resent slot and then the actual password pushed to the second slot still available for use.

Because the note says that it is useful on Samsung phones I assume it was just designed to work for them. Anyway, it would be nice if it also worked with LG's clipboard history feature.

**Comment by wongma7** [comment]
Hmm well that was never actually tested because I don't have access to such a phone. There probably needs to be a delay between each clipboard save

**Comment by jfjallid** [comment]
Yeah that seems likely to be the issue since I can manually overwrite the history by copying other text multiple times. The clipboard can hold 10 entries. Copying something 20 times should be more than enough to remove the password from the history.

**Comment by wongma7** [comment]
hi @jfjallid can you try version 1.2.0.56 and see if it fixes this issue? Thanks

**Comment by jfjallid** [comment]
@wongma7 I've tried it now and the clipboard is properly cleared on my LG G4 when I have selected the option to automatically copy the password. With manual copy however not even the first memory slot is overwritten. This however seems to be due to a bug mentioned in   #244
