### ISSUE TITLE
[BUG] Release build includes LeakCanary library

### ISSUE THREAD

**Issue by ghost** [zeapo/Android-Password-Store#2411]
I downloaded the `APS-freeRelease-2.0.0-SNAPSHOT.apk` file from the Android Password Store repository, and I noticed that the release build includes the LeakCanary library. As far as I understand, LeakCanary is typically used for debugging memory leaks during app development and **should not be included in release builds**.

I just wanted to bring this to your attention in case it was an oversight or unintentional. Please let me know if there's any additional information I can provide, and thank you for your work on this project.

**Comment by msfjarvis** [comment]
It's intentional for the snapshot builds we publish since they're meant to be used for testing and memory leaks are also a class of bugs. The default release configuration does not include LeakCanary.

**Comment by m5q5th** [comment]
Thank you for your response to my previous issue regarding the inclusion of LeakCanary in the snapshot build. However, I would like to request some guidance on how to make a build myself without LeakCanary.

While I understand that it may be useful for testing and debugging purposes, I prefer to have a leaner and more streamlined release build for my own use. I am not familiar with the build process for Android Password Store, so any assistance you could provide would be greatly appreciated.
