### ISSUE TITLE
[BUG] passwords cannot be read

### ISSUE THREAD

**Issue by itsanalias** [zeapo/Android-Password-Store#2426]
### Describe the bug

Hi, I use password-store on Android from f-droid

It worked until recently when I could no longer read the passwords stored in the app. When I try to access a password I get the result as in the following screenshot. The only thing that has changed is an update from huawei emui 11x to emui 12y.

### Steps to reproduce

1. Open passwordstore app
2. select any folder
3. select a login
4. your are not able to see a password

### Expected behavior

see the passwords. 

### Screenshots

screenshot impossible. here the content

/folder/
login
dernière modification le le 28/02/2022

### Device information

- Device: [Huawei p20]
- OS: [ Android 10]
- App version: [ 1.13.5]

**Comment by msfjarvis** [comment]
There's nothing particularly useful in this report so I can't do much. You can try the steps from here and see if they help: https://dontkillmyapp.com/huawei .
