### ISSUE TITLE
Password not clearing after manual copy

### ISSUE THREAD

**Issue by nzp** [zeapo/Android-Password-Store#244]
Not sure if this is perhaps by design. When password is manually copied, via the copy button at the top, to clipboard it doesn't get cleared at all. Password Store version 1.2.0.47, on both Android 4.4 and 6.0.1. When automatic copy to clipboard is enabled, it works fine.

Even if this is by design, the UI doesn't reflect this, the settings don't suggest that a manually copied password won't be cleared, and even the toast message claims the password *will be* cleared.

**Comment by zeapo** [comment]
Indeed, that should not happen. The password has to be cleared in all cases.
