### ISSUE TITLE
[BUG] Autofill not working in Samsung Browser

### ISSUE THREAD

**Issue by gutierri** [zeapo/Android-Password-Store#2444]
### Describe the bug

autofill not working in Samsung Browser, but working other browsers installed as Chrome.

### Steps to reproduce

1. Enable Autofill
2. Open Samsung Browser in a form

### Expected behavior

Pop-up with password selection by Password Store. Like behavior in Google Chrome.

### Device information

- Device: Galaxy S20 FE
- OS: 13
- App version: 1.13.5

**Comment by msfjarvis** [comment]
Even after adding support for it in Password Store I am unable to trigger Autofill on Samsung Internet. Do any other password managers work with it?

**Comment by gutierri** [comment]
As far as I have experience, only Samsung Pass and LastPass. But Lastpass uses accessibility resources to observe the screen and inject a "window" and not the autofill.

But bitwarden seems to add this support¹ and also experienced similar issues². I tried to create an account on the service, but without success I received an error, so I was unable to proceed with enabling this functionality.

---
[1] https://www.reddit.com/r/Bitwarden/comments/mtqhh5/bitwarden_now_works_on_samsung_internet_properly/
[2] https://github.com/bitwarden/mobile/issues/895

**Comment by msfjarvis** [comment]
According to the Bitwarden issue Samsung Internet only allows Autofill for a restricted set of apps they put on an allowlist so there is nothing we can fix on our end to make this work. Closing as a wontfix, open to revisiting it once they stop doing this nonsensical security theater.
