### ISSUE TITLE
[BUG] "Error from OpenKeyChain: Error occurred on reading input" when trying to access remotely synced passwords

### ISSUE THREAD

**Issue by CH4O7IC** [zeapo/Android-Password-Store#2449]
### Describe the bug

When trying to access my passwords in the app I get the error message from the title.
>NOTE: This might not be the exact error message for the english version since I am unable to change the In-App language to english. (However I might just be blind...). 
Log and original error message will be down below.

However this just happens for passwords I added to my pass-repo on my laptop (Apple MacBook Air M2) and synced via git to my phone.
For passwords I added on my phone directly (in the App of course) and synced back to my laptop they work just fine on both devices.

### Steps to reproduce

1. Go to 'password list'
2. Click on 'any password that is created on a desktop device and synced via git'
3. See error (popup)

### Expected behavior

See my selected password just like for passwords I added directly in the app.

### Device information

- Device: OnePlus Nord 2
- OS: OxygenOS 12.1 (Android 12)
- App version: 1.13.5

### Additional context

This is the original error message in German (my In-App language):
>Fehler von OpenKeyChain : Beim Einlesen der Eingabedaten ist ein Fehler aufgetreten!

Log:
[log.txt](https://github.com/android-password-store/Android-Password-Store/files/11121396/log.txt)

**Comment by msfjarvis** [comment]
You can try the workarounds described at https://dontkillmyapp.com/oneplus. Ultimately, OpenKeychain is unmaintained and abandoned so there's not much anybody can do about it.

The development branch of Password Store no longer uses OpenKeychain so you can try using the [snapshot builds](https://docs.passwordstore.app/docs/users/release-channels) instead.

**Comment by CH4O7IC** [comment]
Thanks for the quick response.
However OxygenOS killing OpenKeyChain in the background doesn't seem to be the issue for me...

If the long term goal is to migrate away from using OpenKeyChain altogether I think it would be best to do the same on my end and manage my gpg keys differently.
Sadly I don't really know how to do that so any help on that end - if possible - would be much appreciated :D

**Comment by CH4O7IC** [comment]
Actually I found a working solution for me for now:
As [posted by npes-95](https://github.com/android-password-store/Android-Password-Store/discussions/1429#discussioncomment-3490909) in a discussion on this repo I removed AEAD encryption.
Works like a charm now.
I would rather like to still have it enabled but for my own convenience's sake I can live with that.
