### ISSUE TITLE
App stops working with Folders in Homescreen

### ISSUE THREAD

**Issue by Spotlight0xff** [zeapo/Android-Password-Store#247]
Hello!

Thanks for the app first of all, love it!

I've got a LG G4 (H815) and the pwdstore App stops working when I open folders (also during other occasions, see below) on the home screen.

Here are some screenshots illustrating the issue:

Just opening a folder with some items in it:
![screenshot_2016-12-10-20-34-30](https://cloud.githubusercontent.com/assets/3098388/21075676/2d1d4646-bf18-11e6-9699-c4b77429bf42.png)

'Restyling' an app icon:
(That is, longpressing an icon and release the icon immediately allowing to change the app icon to some custom icon if wanted)
![screenshot_2016-12-10-20-36-51](https://cloud.githubusercontent.com/assets/3098388/21075691/91075c28-bf18-11e6-8084-43a9205e68e6.png)

Also just creating a new folder:
![screenshot_2016-12-10-20-38-37](https://cloud.githubusercontent.com/assets/3098388/21075708/d0af6078-bf18-11e6-8967-89909d52e8e7.png)

All these actions trigger the same exception, here is the relevant logcat report:
```
FATAL EXCEPTION: main
Process: com.zeapo.pwdstore, PID: 4117
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
	at com.zeapo.pwdstore.autofill.AutofillService.onAccessibilityEvent(AutofillService.java:100)
	at android.accessibilityservice.AccessibilityService$1.onAccessibilityEvent(AccessibilityService.java:658)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:751)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5525)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

So it looks like the issue is with [here](https://github.com/zeapo/Android-Password-Store/blob/master/app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.java#L100) where `onAccessibilityEvent` gets called with an event without providing a package name through `getPackageName()`, resulting in an NullPointerException.

I don't have experience with android development and don't really know how to handle this well in code (or why is that, just an device-specific issue?).
Maybe just return immediately when packageName is null?

Anyways, if you need any more info please ask. I'm willing to help track this down.

System information:
* LG-H815
* Android 6.0 (*no* custom ROM, all stock)
* Kernel 3.10.84
* Android security patch level: 2016-07-01
* Software version: V20g-EUR-XX

Cheers
André

**Comment by zeapo** [comment]
Hi,

Thanks for the report.
Until we start working on this, you can disable the autofill by disabling the accessibility service in your android settings.

**Comment by wongma7** [comment]
Will fix this weekend. Your proposed fix sounds good to me, there are many nullpointer exceptions I will need to clean up
