### ISSUE TITLE
Google Translate can obtain password

### ISSUE THREAD

**Issue by IamPr377y** [zeapo/Android-Password-Store#248]
Google Translate with Tap to Translate feature enabled can obtain password copied to clipboard. Even though it is an expected behavior, I wonder if there is a way to prevent Google Translate from doing that, considering Google's aggressive data collection policy.

**Comment by zeapo** [comment]
hmmmm, the only way I could think about is to disable automatic copy of passwords.
With the version .54 you can share the passwords in clear text to another app. 

The same issue happens with other apps, SwiftKey for instance has an integrated clipboard that you have to disable to avoid having your passwords showing there

**Comment by danielvandenberg95** [comment]
I think the only way to negate this would be to implement a keyboard ourselves, which has elaborately been discussed in #50.

**Comment by zeapo** [comment]
Autofill was meant to resolve this issue. Did you try to disable auto copy and enable auto fill?

**Comment by IamPr377y** [comment]
No, I didn't. Autofill is unreliable. That's not a big deal, Tap to Translate was annoying, hence I disabled it. I guess this issue stays unresolved for me, until Google implements clipboard permissions.

**Comment by zeapo** [comment]
Maybe we should concentrate on improving autofill :)
@IamPr377y What do you mean by "unreliable"? Any suggestions?

**Comment by IamPr377y** [comment]
I tried it with some apps, it didn't work, I disabled it. It's easier for me to just copy and paste, than trying to figure out what matching rules does this app use to get the correct password.
