### ISSUE TITLE
[FEATURE] Material You icon support

### ISSUE THREAD

**Issue by nbsp** [zeapo/Android-Password-Store#2489]
### Is your feature request related to a problem? Please describe.

with android's Material Design 3 (Material You), icons can be set to dynamic to automatically change with the user's theme. this does not happen with password-store, which keeps its blue theme no matter what

### Describe the solution you'd like

maybe look into [the android developer documentation](https://developer.android.com/about/versions/13/features#themed-app-icons) on Material You themed app icons

### Describe alternatives you've considered

it's not a dealbreaker or anything it'd just be nice imo

### Additional context

as an aside, i saw that Material Design 3 stylesets are implemented in the app, and yet i don't see them. are they unfinished?

**Comment by msfjarvis** [comment]
Dynamic theming and icon is implemented in the development branch, they haven't been released in any stable channel.
