### ISSUE TITLE
Cannot select key OpenPGP-Key ID

### ISSUE THREAD

**Issue by avanc** [zeapo/Android-Password-Store#251]
In the settings I cannot select an OpenPGP key ID. If I click on the field, OpenKeychain opens and my key is shown (called 'Password Store'). However, I cannot select it, I can push the entry, but it gets never selected and thus a cannot click Okay:
![Openkeychain](https://cloud.githubusercontent.com/assets/2905029/20806405/0a49ee18-b7fb-11e6-860c-d762838b6854.png "Screenshot")

I don't know if this is a Password Store problem or OpenKeychain problem. I can use Password Store to decrypt but not to encrypt (aka add new entry). Although, I can encrypt data by using OpenKeychain directly.

**Comment by zeapo** [comment]
The little green check at the right means that it's selected, just click "okay". You key id should then be shown under the option "select openkeychain id" in password store app. 

However, this is a OpenKeychain related.

**Comment by avanc** [comment]
I thought I need a check in the left box. Thanks for the quick response.
