### ISSUE TITLE
Cant select key on lolipop

### ISSUE THREAD

**Issue by alex9099** [zeapo/Android-Password-Store#252]
Hi, I have lolipop on my phone and this app seems to not be working as expected (it works fine on a kitkat phone i have), when i select the key to encrypt the files i get a "floating message" (i think it is called toast) saying something like this:

`Error from OpenKeyChain: attemp to invoke method 'android.content.intent org.openintents.openpgp.IOpenPgpService2.execute(android.content.intent, android.or.parcelfiledescriptor, int)' on a null object reference`

The error may not be exactly the same as the one that showed on screen because i dont know how to copy toast messages

(i created a almost equal on openkeychain issue trackes)

**Comment by alex9099** [comment]
@zeapo , can you help me?

**Comment by zeapo** [comment]
Oh sorry just noticed the issue, I will look into it tonight

Le 2 janv. 2017 11:48 PM, "Alexandre Badalo" <notifications@github.com> a
écrit :

**Comment by zeapo** [comment]
Which version of the app are you using?

**Comment by alex9099** [comment]
It is the latest on F droid
1.2.0.56

**Comment by zeapo** [comment]
Can you create another key on openkeychain and test if you can select it. 

I don't see how this could have happened :/

**Comment by alex9099** [comment]
Still, same error, created a key with and without password (it should not matter but it's worth trying :) )

maybe it is a problem with the openkeychain API/intents?

**Comment by zeapo** [comment]
Could you try with other versions of openkeychain?

Le 4 janv. 2017 9:51 PM, "Alexandre Badalo" <notifications@github.com> a
écrit :

**Comment by alex9099** [comment]
Do you know where can i get that versions? which version specifically ?
May i go to any older release and compile it myself?

**Comment by zeapo** [comment]
Try with F-Droid they keep multiple versions

**Comment by alex9099** [comment]
Neither 4.0.3 nor 4.0.1 works :/

Maybe it is a problem with lolipop API, do you think it may be anything solvable?

**Comment by zeapo** [comment]
are you able to use the key to encrypt/decrypt a text? using openkeychain alone

**Comment by alex9099** [comment]
This can be closed, it works fine with manufacturer ROM, strange thing :/

**Comment by zeapo** [comment]
Oh, this could be related to fs access rights.

Le 14 janv. 2017 8:55 PM, "Alexandre Badalo" <notifications@github.com> a
écrit :
