### ISSUE TITLE
[FEATURE] Allow using only public key

### ISSUE THREAD

**Issue by mattyspangler** [zeapo/Android-Password-Store#2522]
Android-Password-Store requires a secret key to function, and does not allow doing anything if you only provide it a public key. Could it be updated to allow using only a public key?

**Comment by msfjarvis** [comment]
I might be confused but I don't believe a public key is meant to be able to decrypt messages, only to encrypt them so that the owner of the corresponding secret key is able to retrieve the plaintext.

Either way, this is a limitation of OpenKeychain that only they can address so I'm closing this.
