### ISSUE TITLE
JSchException: Auth fail

### ISSUE THREAD

**Issue by tobia** [zeapo/Android-Password-Store#254]
I'm trying to setup Password Store. 

I already have a working SSH key that I generated with JuiceSSH (it's an `ecdsa-sha2-nistp384`)

So I imported it into the app and tried connecting to the server. It asks for the private key password (and correctly refuses wrong passwords) but then terminates the connection early, with the following dialog:

> Error occurred during the clone operation, Message from jgit: ssh://*****: Auth fail

If I run sshd on my server with `LogLevel DEBUG` I get the following:

	Connection from **.**.**.** port 35145 on **.**.**.** port 222
	debug1: Client protocol version 2.0; client software version JSCH-0.1.53
	debug1: no match: JSCH-0.1.53
	debug1: Enabling compatibility mode for protocol 2.0
	debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
	debug1: permanently_set_uid: 104/65534 [preauth]
	debug1: list_hostkey_types: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
	debug1: SSH2_MSG_KEXINIT sent [preauth]
	debug1: SSH2_MSG_KEXINIT received [preauth]
	debug1: kex: client->server aes128-ctr hmac-md5 none [preauth]
	debug1: kex: server->client aes128-ctr hmac-md5 none [preauth]
	debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
	debug1: SSH2_MSG_NEWKEYS sent [preauth]
	debug1: expecting SSH2_MSG_NEWKEYS [preauth]
	debug1: SSH2_MSG_NEWKEYS received [preauth]
	debug1: KEX done [preauth]
	debug1: userauth-request for user ***** service ssh-connection method none [preauth]
	debug1: attempt 0 failures 0 [preauth]
	debug1: PAM: initializing for "*****"
	debug1: PAM: setting PAM_RHOST to "**.**.**.**"
	debug1: PAM: setting PAM_TTY to "ssh"
	error: Received disconnect from **.**.**.**: 3: com.jcraft.jsch.JSchException: Auth fail [preauth]
	debug1: do_cleanup [preauth]
	debug1: monitor_read_log: child log fd closed
	debug1: do_cleanup
	debug1: PAM: cleanup
	debug1: Killing privsep child 11825
	debug1: audit_event: unhandled event 12

It seems that JSch disconnects early with a message saying JSchException: Auth fail. 

Do I need to import the host key into Password Store? How would I do that?

Do I need to use a different private key? But the one I imported works well with JuiceSSH, [which is also using JSch](https://twitter.com/juicessh/status/322467448701976576).

**Comment by zeapo** [comment]
Sadly this is sadly not possible right now see #134

**Comment by zidhuss** [comment]
Will continue discussion in #448
