### ISSUE TITLE
[BUG] Please update the app on Google Play

### ISSUE THREAD

**Issue by kupospelov** [zeapo/Android-Password-Store#2553]
### Describe the bug

The app cannot be installed on newer phones via Google Play, presumably because it was not updated for almost 2 years. 

What I see is "This app isn't available for your device because it was made for an older version of Android".

### Steps to reproduce

1. Click the "Get it on Google Play" link.

### Expected behavior

The app should be installable.

### Device information

- Device: Google Pixel 7 Pro
- OS: Android 13
- App version: N/A

### Additional context

I assume that using F-Droid could help work around this problem, but I have a work profile configured, so the only available app store in this case is Google Play.

I also own another device that runs Android 11, and this device seems to have the same issue (I managed to install the app via F-Droid though).

This is not a request to release the new version faster, but rather a request to double-check the Google Play page to see if something actually blocks installing the app on newer Android phones :)

**Comment by msfjarvis** [comment]
There's nothing to fix on Google Play, things are working correctly. There is a relatively new policy that prevents fresh installations of apps that target a too-old version of Android in the interest of privacy and security. The Play Store build of APS targets Android 9, which is enough versions behind 13 to run afoul of this requirement.

**Comment by kupospelov** [comment]
Are there any plans to update the target version? I am not an expert in Android apps, but from what I have seen this should not affect compatibility. Android 13 users can install OpenKeychain via Google Play for example, even though the app still supports Android 4.

**Comment by msfjarvis** [comment]
It's already updated in the development branch, it can't be done for Google Play because it will break storage access features.

FYI, OpenKeychain [targets API level 31](https://github.com/open-keychain/open-keychain/blob/8d69181b65c2d5364f40845466a9e5305ca8c91b/OpenKeychain/build.gradle#L92), and the Google Play build of APS targets 28.

**Comment by kupospelov** [comment]
Thanks for clarification! I'm looking forward to the new release then :)
