### ISSUE TITLE
[BUG] Unhelpful error message on exception during decryption, with `gpg 2.40` Curve25519 AEAD

### ISSUE THREAD

**Issue by pjungkamp** [zeapo/Android-Password-Store#2586]
#### Background

I just started learning about PGP and password-store, so i started by creating a key on my Linux system to initialize my password store. I figured that using the default values of GnuPG during the creation of my key would yield the best compatibility.

I was using GnuPG 2.4.0, the defaults of which created a Curve25519 key with AEAD support enabled. As AEAD is supposed to supersede MDC, no MDC verificataion is attached to the encrypted data. PGPainless does not implement OpenPGP v6 yet. The default configuration enforces a hard requirement for MDC verification and throws an exception if none is found.

This is working (or rather not working) as expected, and OpenPGP v6 seems be on PGPainless' agenda, so no problem here.

How did I figure out that decryption was failing, due to the MDC, expected by PGPainless, missing on my files? `adb logcat`

#### The bug

If decryption using PGPainless fails for any reason, the app reopens the password prompt and reports 'wrong password'. Which was really misleading.

### Steps to reproduce

1. Create a GPG key using the default settings of:
```shell
$ gpg --version
gpg (GnuPG) 2.4.0
libgcrypt 1.10.2
```

This gives me a key with these preferences:
```shell
$ gpg --full-generate-key
... (9) ECC (sign and encrypt) *default*
... (1) Curve 25519 *default*
$ gpg --edit-key THE_NEW_KEY
>showpref
     Cipher: AES256, AES192, AES, 3DES
     AEAD: OCB
     Digest: SHA512, SHA384, SHA256, SHA224, SHA1
     Compression: ZLIB, BZIP2, ZIP, Uncompressed
     Features: MDC, Keyserver no-modify
```

2. Use that key for your password store. E.g. `pass init THE_NEW_KEY`
3. import that password store into the app.
4. Try to view any password

### Expected behavior

The app shows a popup error message saying that the file couldn't be decrypted, with the error message from PGPainless' exception attached.

### Device information

- Device: Google Pixel 7
- OS: Android 13
- App version: 2.0.0-SNAPSHOT from 3rd of July

### Additional context

I think it's really unfortunate that the defaults of a recent `gpg` are not compatible with this application. I'd just like to see a note about missing AEAD support in PGPainless in this repo. That took me *HOURS* and was a terrible beginner experience. i can appreciate a concise error message!

You can check whether `gpg` uses `AEAD` by running
```shell
$ gpg --edit-key YOUR_KEY
>showpref
```

If the `AEAD:` line is not empty, `gpg ` will *always* prefer AEAD over MDC, which leads to an exception in PGPainless...

You can check this by running `gpg --list-packets` on a file encrypted by that key. If you see a line starting with `aead:`, the file will not be accepted by PGPainless.

As a workaround, you can disable the AEAD support using `setpref` in the `gpg --edit-key` menu.

**Comment by pjungkamp** [comment]
This is the part of `adb logcat` which gave me a hint:
```
07-04 00:26:53.862 24860 24928 D org.pgpainless.decryption_verification.OpenPgpMessageInputStream: Symmetrically Encrypted Data Packet at depth 0 encountered
07-04 00:26:53.862 24860 24928 W org.pgpainless.decryption_verification.OpenPgpMessageInputStream: Symmetrically Encrypted Data Packet is not integrity-protected.
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: app.passwordstore.crypto.errors.UnknownError
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository.access$decryptPgp(Unknown Source:497)
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository$decrypt$2.invokeSuspend(Unknown Source:38)
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:115)
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: 	at androidx.core.app.ActivityRecreator$1.run(Unknown Source:464)
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: Caused by: org.bouncycastle.openpgp.PGPKeyValidationException: Message is encrypted using a 'Symmetrically Encrypted Data' (SED) packet, which enables certain types of attacks. A 'Symmetrically Encrypted Integrity Protected' (SEIP) packet should be used instead.
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: 	at org.pgpainless.decryption_verification.OpenPgpMessageInputStream.consumePackets(Unknown Source:1162)
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: 	at org.pgpainless.decryption_verification.OpenPgpMessageInputStream.<init>(SourceFile:62)
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: 	at shark.ProguardMappingReader.withOptions(Unknown Source:48)
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository.access$decryptPgp(Unknown Source:343)
07-04 00:26:53.863 24860 24860 E StandaloneCoroutine: 	... 6 more
```

---

The tracking issue for AEAD and OpenPGP v6 support in PGPainless is here: https://github.com/pgpainless/pgpainless/issues/343

---

This is the line in the `gpg --list-packets FILE` output that indicates AEAD:
```
:aead encrypted packet: cipher=9 aead=2 cb=16
	length: 123
```

This is how it looks for MDC:
```
:encrypted data packet:
	length: 76
	mdc_method: 2
```

---

Here is a forum post explaining how to edit the key: https://unix.stackexchange.com/questions/697579/gpg-failing-with-no-error-for-one-of-my-encrypted-files

---

Thank you very much for this awesome application! I hope this issue can save other people some time and frustration.

**Comment by msfjarvis** [comment]
The author of PGPainless has [explained in our issue tracker](https://github.com/android-password-store/Android-Password-Store/pull/2218#issuecomment-1296911526) why there is no AEAD support and when, if at all, we can expect it to happen. I don't believe there's anything I can do on my end to warn users ahead of time, but I'll double check that anyway.

Reprompting for the password unconditionally is definitely dodgy UX that is on my to-do list, but this project can't pay my bills so the effort I can dedicate is quite limited.

**Comment by msfjarvis** [comment]
https://github.com/android-password-store/Android-Password-Store/compare/496a1c4cb77743f724ccd3414115f92291345dbd...0c8bed4e546ac248be118b41cfa4b002a357e12f

I was able to find a runtime check that reliably fails against AEAD keys which I've now put in the key addition code path. This is what you'll see going forward when importing an AEAD key

<img src="https://github.com/android-password-store/Android-Password-Store/assets/13348378/e0f749c0-89f0-4cff-849a-b58d6a86ae6b" width="270"/>
