### ISSUE TITLE
[FEATURE] Support installation on Android 13

### ISSUE THREAD

**Issue by Minipada** [zeapo/Android-Password-Store#2587]
### Is your feature request related to a problem? Please describe.

I want to install the application on Android 13

### Describe the solution you'd like

I want to install the application on Android 13 on the store

### Describe alternatives you've considered

Or through any other way

**Comment by msfjarvis** [comment]
Duplicate of #2553, #2533 and #2417.

There's a reason the issue template asks you to search existing issues :)
