### ISSUE TITLE
[BUG] Can't switch my password branch from "master" to "main"

### ISSUE THREAD

**Issue by blargg** [zeapo/Android-Password-Store#2617]
### Describe the bug

When syncing from a remote repo, I attempted to switch from using "master" to "main". Both existed at the same on origin. When I updated the branch in the settings of the app, it did not pull from main (the new branch).

It behaved like it was still pulling from master, but I didn't fully test this. It would display "everything up to date" but nothing changed (things were up to date with the master branch).

I set it back to use master in the settings, then updated master on both and everything worked fine.

### Steps to reproduce

1. Set up a remote repo using "master" as the branch name.
2. Set up the app to pull from that repo and branch.
3. Create a new branch "main" and push to the remote repo (not using the android app).
4. Go to settings > edit git server > set branch to main.
5. Pull

### Expected behavior

I expected this to either pull from the main branch (updating all my passwords to the main branch, etc).

Otherwise, it could provide some error about the operation not being supported and instructions on how to address it.

### Device information

- Device: Pixel 7
- OS: Android 13
- App version: 1.13.5

**Comment by msfjarvis** [comment]
This was fixed by #2275. You can install a [snapshot build](https://docs.passwordstore.app/docs/users/release-channels) to get a testing version with the fix included.
