### ISSUE TITLE
Git - Exception caught during execution of fetch command

### ISSUE THREAD

**Issue by ag-n** [zeapo/Android-Password-Store#263]
Hi, when I try to clone a password store from my laptop using git and SSH, I get this error : "Message from jgit : Exception caught during execution of fetch command".

It happens every time I reinstall the app and try to clone a repo using git. Changing to password auth changes nothing.

**Comment by zeapo** [comment]
Hi, 

Is your repository a bare one? 
Is it on your home directory? 
Are you using a particular git server?

**Comment by ag-n** [comment]
Hi, I don't know what a "bare repository" is. It's the kind you would get if you did "pass init" then "pass git init" on a Linux machine.

It's in my $HOME, at the default path (~/.password-store).

I'm not using anything other than standard git, on Ubuntu.

**Comment by zeapo** [comment]
I see.

`pass init` will just initialize a repository in you home directory. However, this repository is not meant to be cloned, pushed to and pulled from. You need a [bare](http://www.saintsjd.com/2011/01/what-is-a-bare-git-repository/) is what you need to sync your passwords.

You could also create a private repository on gitlab or bitbucket to do the work.

> Make sure to only clone from bare repositories (see [git-clone(1)](http://git-scm.com/docs/git-clone) for how to create a bare repository from an existing one). Otherwise the clone will fail.

**Comment by ag-n** [comment]
I'm getting the same error trying to clone from a bare repository.

Also, please note that I was able to clone and sync from a normal repo created with `pass init && pass git init`, I just have no idea how I did it, I randomly tried to change settings in the app before it suddently worked. Now that I reinstalled the app, of course, the old settings are gone.

**Comment by ag-n** [comment]
The exception is said to come from jgit, but the problem doesn't even seem to be related to Git : I just tried with password auth, and I get the same message, even with a wrong SSH key/password.

So the app seems to be unable to connect to my laptop. The keys are set up properly, and the laptop is accessible (no firewall, SSH on port 22 and the key is in ~/.ssh/authorized_keys).

Whatever the problem is, I find this error message extremely misleading. Maybe the app could show git's actual output, so that the user can at least know what the problem is ?

**Comment by ag-n** [comment]
OK, (last) update : I just removed the "22" I had typed in the "port" field (it's 22 by default so that should have changed nothing), and I was able to pull from the repository.

It seems that manually choosing the port causes this bug, which is beyond my comprehension. I'm pretty sure that i've found a bug now.

**Comment by zeapo** [comment]
fixed
