### ISSUE TITLE
[BUG] Password store don't see my secret key in openkeychain

### ISSUE THREAD

**Issue by korolipliaja** [zeapo/Android-Password-Store#2634]
### Describe the bug

<details>
<summary>Details</summary>

![Screenshot_20230801-192115](https://github.com/android-password-store/Android-Password-Store/assets/69907714/eaec0270-480d-4ce0-90bf-8e43f70eb322)
![Screenshot_20230801-192038](https://github.com/android-password-store/Android-Password-Store/assets/69907714/a7940502-9310-415d-bb38-a2060e0ecd97)

</details>

### Steps to reproduce

I have a repository on GitHub with my encrypted passwords, I exported my secret key to asc format and threw it on my phone, inserted it into openkeychain, it is displayed, but as soon as I go to the Password store applications, I am prompted to select a key, and the list itself is empty  although it worked before

### Expected behavior

my secret key will appear in the list

### Screenshots

<details>
<summary>Details</summary>

![Screenshot_20230801-192509](https://github.com/android-password-store/Android-Password-Store/assets/69907714/f21ac4a4-3794-4f81-a15d-576c864ba815)
![Screenshot_20230801-192503](https://github.com/android-password-store/Android-Password-Store/assets/69907714/c58f9728-c0cc-4e94-a1b7-bcc098675101)
![Screenshot_20230801-192456](https://github.com/android-password-store/Android-Password-Store/assets/69907714/8ffff91a-7a40-45f1-92b6-246276f61fe9)

</details>

### Device information

Pixel 6 pro
Android 13 
Password store 1.13.5
Open key chain 5.8.2

### Additional context

1

**Comment by msfjarvis** [comment]
The key selection UI is fully owned by OpenKeychain, there is no Password Store bug here. I would double check if the key has an encryption subkey.

**Comment by enricoflor** [comment]
@korolipliaja did you fix this? I have the same problem even though everything worked on another phone with the same apps, same versions.
