### ISSUE TITLE
[BUG]  The default username functionality does not seem to be working anymore

### ISSUE THREAD

**Issue by colonelpanic8** [zeapo/Android-Password-Store#2635]
### Describe the bug

Entries without a default username just fill in the name of the entry, rather than the default username

### Steps to reproduce

1. Set a default username
2. Add an entry that only has a password
3. Autofill that entry somewhere for a username
4. Observe that the name of the entry has been used instead of the default username

### Expected behavior

The default username should be filled in instead

### Device information

- Device: Pixel 7 Pro
- OS: 
- App version: 1.13.5

**Comment by msfjarvis** [comment]
Works fine in the development branch so if there was a bug, it is since resolved.

**Comment by colonelpanic8** [comment]
@msfjarvis will there be a release soon:

AFAICT, there's a pretty huge diff between HEAD of develop and the release:

659 files changed, 31160 insertions(+), 39735 deletions(-)

**Comment by msfjarvis** [comment]
It'll be released once the V2 board is done  https://github.com/orgs/android-password-store/projects/1
