### ISSUE TITLE
Can't select key from OpenKeychain

### ISSUE THREAD

**Issue by jfjallid** [zeapo/Android-Password-Store#264]
I have cloned a remote git repo and am trying to select OpenPGP key IDs which fails.
I have selected OpenKeychain as my OpenPGP Provider but when I try to select any of the keys listed as receipient the screen is just refreshed and all the keys are listed without any selections.

**Comment by dschuermann** [comment]
Hey, this was a regression bug on our side, it should be fixed in 4.2.1 I just uploaded. See https://github.com/open-keychain/open-keychain/issues/1990
