### ISSUE TITLE
[BUG] Internal Exception with custom port and username

### ISSUE THREAD

**Issue by candlewithhare** [zeapo/Android-Password-Store#2641]
### Describe the bug

When trying to access my gitolight repository via the URL git@onetwothree.customip.org:1234 I get an Internal Exception: Host unreachable although the URL is correct and accessible.
I tested this on two Smartphones. On one of those, it is actually working with an older version of Password store (1.13.5[not working] vs 1.3.3.[working])

### Steps to reproduce

1.  Go to 'Edit Git server settings'
2.  Type an url with port and username 'git@onetwothree.customip.org:1234'
3.  Accept
It does not make any difference which authentication method is being selected, it always results in the internal error.

### Expected behavior

The connection should work, or it should suggest the correct syntax of the URL.

### Device information

- Device: Samsung Galaxy S23 and Samsung Galaxy S7
- OS: Android 13 and 8.1.0
- App version: 1.13.5

**Comment by msfjarvis** [comment]
Seems like the same bug as #2494, closing as duplicate. Feel free to subscribe to status notifications on that to be notified when it's fixed.
