### ISSUE TITLE
[BUG] the master key android-keystore://sshkey exists but is unusable

### ISSUE THREAD

**Issue by wahuffman** [zeapo/Android-Password-Store#2649]
### Describe the bug

I got into a state where I could not generate a new ssh key.  When trying to generate a new key during initial setup, I got the error message: "the master key android-keystore://sshkey exists but is unusable".  Android's "clear storage" didn't fix it.  In fact it first appeared after clearing storage.  I was able to get around it by unchecking the box to have the key secured by Android.  At that point the ssh and git pull worked.

### Steps to reproduce

1. Something happens, not sure what.
2. Clear storage through Android.
3. Open the app and select to clone a repository
4. Fill in repository details and click clone
5. Select generate key
6. Make sure the box to secure key with Android is checked
7. Click button to generate key
8. Touch biometric sensor.
9. Get error message: "the master key android-keystore://sshkey exists but is unusable"

### Expected behavior

If I understand correctly, password store might delete the offending key and replace it.

### Device information

- Device: moto go power 5G - 2023.  Hardware version PVT.  Model number: XT2311-3
- OS: Android 13  (5.10.149)
- App version: 1.13.5

### Additional context

As background, I cleared state because pulls weren't working and I figured some state was corrupted.  I noticed also that the initial ssh connection never closed according to logs on the target.

**Comment by msfjarvis** [comment]
Dupe of #1144 and #1415. TL;DR on some devices the Android KeyStore fails to delete keys when it should. This causes stale key material to be left behind which the app can neither read nor overwrite. As you've discovered, opting to not use the KeyStore at all solves it, and so does uninstalling and reinstalling the app. As far as I know, there's no fix for this that I can implement in APS.

**Comment by wahuffman** [comment]
Thanks for your answer.  I only looked among recent bugs - sorry for the duplicate.

I meant to include, but I see forgot, that I actually did un-install and re-install the app and that didn't fix the bad state.

Thanks for a very useful program.  I'm appreciating it.

      Bill
