### ISSUE TITLE
Adding git setting in later stage makes app to skip git clone.

### ISSUE THREAD

**Issue by EliasGabrielsson** [zeapo/Android-Password-Store#268]
## What:
Adding Git settings after using a local repository makes the app to skip `git clone` and throw error when using `git pull`.

## Expected behavior:
Enforce a `git clone` if the local repo does not exist or show an error msg telling the user to make a "fresh" `git clone`.

## How to reproduce:

1. Press: "Use local directory"
2. Choose "Hidden (preferred)
3. Setting -> "Edit git server settings", add credentials I used `ssh` as protocol. Press: `save`
4. In folder menu, press "Pull from remote".
5. Application throws error: `org.eclipse.jgit.errors.MissingObjectException` probebly due missing `git clone`

If step number three is skipped another non intuitive error message is thrown. 

## Version:
App: `1.2.0.57`
Android `7.1.1`

**Comment by zeapo** [comment]
Thanks for the report, just fixed in 8dc1efe405b9a1172f5470d6c6b88c080f41e406
