### ISSUE TITLE
autofill does not work on firefox

### ISSUE THREAD

**Issue by alex9099** [zeapo/Android-Password-Store#269]
Hi. How can i make password store to work with firefox?

BTW: how secure pass is?

**Comment by wongma7** [comment]
Please see https://github.com/zeapo/Android-Password-Store/issues/176 . In short, it's not possible without support from Firefox :(

as for how secure...well pass uses the openPGP standard for encryption. The rest is up to you: your passphrase, storing your key, where you put your password files, etc.

**Comment by alex9099** [comment]
Thanks, so which browser would you sugest?
