### ISSUE TITLE
Error: Transceive failed

### ISSUE THREAD

**Issue by nh2** [zeapo/Android-Password-Store#271]
I'm using the YubiKey Neo.

Android-Password-Store has worked great with that in the past, but for some time now I always get `Error: Transceive failed` when touching the key via NFC.

The key works perfectly fine when using it with OpenKeyChain, so I suspect that it's a change in Android-Password-Store that broke it.

Please advise how I can debug it. Thanks!

**Comment by zeapo** [comment]
Did it work with previous versions?

Le 9 févr. 2017 4:32 AM, "Niklas Hambüchen" <notifications@github.com> a
écrit :

**Comment by nh2** [comment]
> Did it work with previous versions?

@zeapo Yes.

**Comment by zeapo** [comment]
Which version are you using?

**Comment by nh2** [comment]
Play Store says I have `1.2.0.56`.

**Comment by nh2** [comment]
`adb logcat` says:

```
E/Keychain( 5369): failed to establish secure messaging
E/Keychain( 5369): org.sufficientlysecure.keychain.securitytoken.SecureMessagingException: failed to retrieve secure messaging key attributes
E/Keychain( 5369): 	at org.sufficientlysecure.keychain.securitytoken.SCP11bSecureMessaging.establish(SCP11bSecureMessaging.java:298)
E/Keychain( 5369): 	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenHelper.connectToDevice(SecurityTokenHelper.java:211)
E/Keychain( 5369): 	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity.handleSecurityToken(BaseSecurityTokenActivity.java:444)
E/Keychain( 5369): 	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:172)
E/Keychain( 5369): 	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:162)
E/Keychain( 5369): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/Keychain( 5369): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/Keychain( 5369): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/Keychain( 5369): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/Keychain( 5369): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/Keychain( 5369): 	at java.lang.Thread.run(Thread.java:841)
```

**Comment by zeapo** [comment]
Maybe @dschuermann can help with this.
Do you have any idea why this exception happens?

**Comment by nh2** [comment]
Wait, this might be an OpenKeyChain problem. I had only tried signing something with OpenKeyChain, which works fine with the Yubikey (despite the above trace still appearing when I do it), but actually **decrypting** fails even in OpenKeyChain.

So this regression might be in OpenKeyChain, not in Android-Password-Store.

**Comment by nh2** [comment]
I created https://github.com/open-keychain/open-keychain/issues/2049

**Comment by dschuermann** [comment]
@zeapo You can close here, this is in OpenKeychain :)

**Comment by nh2** [comment]
I found the commit that broke it in OpenKeychain in the linked ticket.

Thanks for your help!
