### ISSUE TITLE
No release since 2021

### ISSUE THREAD

**Issue by andrey-utkin** [zeapo/Android-Password-Store#2719]
Hi, I am a user of this app via F-Droid distribution.

I am a bit concerned that the version on F-Droid was released in 2021. I initially thought that the app has been abandoned, but now I see the development is ongoing, it just doesn't get released to F-Droid, and there are even no newer release tags.

Would that make sense to issue a new release?
Could you please do it?
Can I help?

I read that you had some difficulties with propagation of updates to F-Droid in 2020, but I hope there is no ongoing hostility.

**Comment by msfjarvis** [comment]
The app is not being released anywhere. It's in the middle of a major rework with a lot of breaking changes and a completely new cryptographic core that currently has poor UX and basically no security review. Making a release just for the sake of it would be disastrous and simply leave users with a worse app.
