### ISSUE TITLE
Git Commit Customization

### ISSUE THREAD

**Issue by nvonbulow** [zeapo/Android-Password-Store#272]
I think that being able to customize the commit author and message as well as signing the commit with a GPG key would be really helpful. I really like consistent git histories, and currently, I have to do a git rebase on my PC every time I add a password from my phone!

**Comment by zeapo** [comment]
That's a good idea. We'll see how we can get these features :)

**Comment by michamos** [comment]
I would say GPG signing of commits is quite important, otherwise it is vulnerable to password file spoofing (see point 2. of the following reddit comment for an explanation https://www.reddit.com/r/linux/comments/5v0gu5/keepass_vs_pass/ddyxp40/ ).

**Comment by zidhuss** [comment]
Similar to #170. Can continue discussion in that issue.
