### ISSUE TITLE
does not show extra content if password is empty

### ISSUE THREAD

**Issue by otizonaizit** [zeapo/Android-Password-Store#274]
The app works very well, thank you!

The only (mis-)feature I don't like is that the app does not show the extra content of the password file if the password itself is empty.

I use password files to store additional info (like IBAN of bank accounts, but I don't always have a password to store, nor anything that I would obviously want to copy to the clipboard... 

Is this by design, or it is a bug due to the app not expecting empty passwords?

**Comment by zeapo** [comment]
Thanks for the report.

Indeed! we'll have to see how to enable this case :)
