### ISSUE TITLE
[FEATURE] Allow exporting settings for re-use across devices

### ISSUE THREAD

**Issue by kiozet** [zeapo/Android-Password-Store#2740]
### Is your feature request related to a problem? Please describe.

When you try to install and configure APS on the new device, you need to do all and encounter with some problems once again. 

### Describe the solution you'd like

I think it will be useful, if user can fast export config with settings/keys and password storage(if its local or with github settings).

### Describe alternatives you've considered

N/A

**Comment by msfjarvis** [comment]
I don't personally see much value to this, plus the idea of exporting authentication keys ranges from impossible (SSH key in device keystore) to irresponsible so this is not something I intend to build myself. 

I will leave the issue open for someone else to take a stab at it, but I'd recommend discussing the proposed design here before picking up implementation.

**Comment by daiaji** [comment]
I think exporting settings is necessary, especially in version 2.0, even if the data directory is backed up, but the OS is restored to its factory state, I still cannot restore the data directory of APS to work, which causes me to have to reinstall and configure APS every time I reset the system, which makes me frustrated.

**Comment by msfjarvis** [comment]
https://github.com/android-password-store/Android-Password-Store/issues/2779 has a suggestion for the same thing but instead driven by QR codes.

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
