### ISSUE TITLE
[FEATURE] Passkey integration with Android CredentialManager

### ISSUE THREAD

**Issue by jmandel** [zeapo/Android-Password-Store#2741]
### Is your feature request related to a problem? Please describe.

Now that more web sites and apps are supporting passkeys, it'd be nice to store my passkeys in Android-Password-Store, alongside my passwords.

### Describe the solution you'd like

Android-Password-Store already integrates with Android's autofill infrastructure. Supporting passkeys on Android 14+ would be consistent and helpful functionality. https://developer.android.com/training/sign-in/credential-provider#handle-queries-passkey-creation documents the requirements.

### Describe alternatives you've considered

Just storing passkeys in Google's OS-bundled password manager. But I am a happy user of `pass` / Android-Password-Store :-)

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
