### ISSUE TITLE
[BUG] cannot read data encripted by pass

### ISSUE THREAD

**Issue by lesar** [zeapo/Android-Password-Store#2743]
### Describe the bug

dont read all data

### Steps to reproduce

on openkeychain I have imported my openpgp key. the key has 3 identity inside.  
the key has full healthy.  
I synchronize my git repo on Password Store successfully.
on my linux desktop too  
on my pc I can read and write data write by pc and by on Password Storeon android... all data
on Password Store on android I can read only data I have write by on Password Store but not data write by Linux pc

when I try to read data stored by linux I get error by openkeychain.   

It can be a permission error on file not created by on Password Store?  

the pgp key imported on android is the same using on pc linux  

best regards
Leonardo 

### Expected behavior

all data must be readable

### Device information

- Device: [e.g. Google Pixel 2] motorola edge 20 lite
- OS: [e.g. Android R] android 12
- App version: [e.g. 1.13.5] 1.13.5

**Comment by msfjarvis** [comment]
It's not a permission error, please include the actual OpenKeychain error itself rather than make guesses at what the problem might be.

**Comment by lesar** [comment]
On android I don't know where to find the log

**Comment by msfjarvis** [comment]
> On android I don't know where to find the log

https://docs.passwordstore.app/docs/users/reporting-bugs

**Comment by lesar** [comment]
Sorry I'm only an user. I'm will not download android SDK etc.  
If the app don't work and don't show error is better to remove pass and pass android app.

**Comment by msfjarvis** [comment]
> Sorry I'm only an user. I'm will not download android SDK etc. If the app don't work and don't show error is better to remove pass and pass android app.

I hear Bitwarden is nice 👍🏼
