### ISSUE TITLE
[BUG] Creation of password file with mutlpile nested missing parent folders fails.

### ISSUE THREAD

**Issue by G3sit** [zeapo/Android-Password-Store#2755]
### Describe the bug

When a password file is created from the "Generate Password" option of the autofill dialog and multiple parent folders of the file don't exist then the password file isn't created.

### Steps to reproduce

1. Enable Autofill.
2. Go to 'https://fill.dev/form/registration-simple'
3. Click in the password input field.
4. Choose "Generate password" form the drop down menu
5. Change the folder path to one with multiple non existing folders
6. Try to save.
7. See error message "Folder couldn't get created"

### Expected behavior

The file saves normally.

### Device information

- Device: OnePlus 6
- OS: Android 11 (OxygenOS: 11.1.2.2)
- App version: 1.13.5

**Comment by msfjarvis** [comment]
Welp, that's an oversight. I'll try to get a fix in soon.
