### ISSUE TITLE
"Synchronize repository" action creates empty Git commits

### ISSUE THREAD

**Issue by maxb** [zeapo/Android-Password-Store#276]
It appears that "synchronize" used to be pull+push, but now it is add+commit+pull+push.

This issue with this is that the commit command seems to commit unconditionally, even if doing so creates an empty commit.

This is kind of annoying if you want your Git history to be as readable as practical.

Ideally, the operation would only commit if it was going to create a commit with actual tree changes.

**Comment by zeapo** [comment]
Strange, it shouldn't. I will check.

**Comment by stuart12** [comment]
If you look at https://github.com/stuart12/passtest/commits/master you will see lots of empty commits. I created them just by pressing "Synchronize repository" a few times. I'm running 1.2.0.57.
