### ISSUE TITLE
[FEATURE] Offer setup of the app via qr-code

### ISSUE THREAD

**Issue by chmduquesne** [zeapo/Android-Password-Store#2779]
### Is your feature request related to a problem? Please describe.

Whenever I need to configure this application, I am always frustrated because I need to type a lot of text to configure it. It would be very nice if I could just scan a few qr codes and be done with the configuration.

### Describe the solution you'd like

A good first step would be to offer the option to scan a qr code whenever one needs to fill a long text. For example: the repository url.

A second idea would be to do the same when exporting the public ssh key of the app: I would enjoy if I could just export it as a qr code. Then I would use zbarcam on my computer to scan it in order to add it to the remote repo.

### Describe alternatives you've considered

I am doing all of this manually, using a qr-code scanner app that can export to the clipboard. I am just suggesting a flow that would automate some of these steps.

**Comment by msfjarvis** [comment]
Merging this into #2740 since any progress here depends on that issue moving forward.
