### ISSUE TITLE
"Select OpenPGP Key Id" show nothing

### ISSUE THREAD

**Issue by eexpress** [zeapo/Android-Password-Store#279]
I had import secret key into OpenKeyChain through asc file. In it main page, one key is shown.
I had cp my .password-store directory in android mobile, and setup Password-Store to use this directory, and Password-Store can show all sub-dir name in main page. 
But in Password-Store->setting->Select OpenPGP Key Id, nothing here. 
![screenshot_2017-03-11-17-32-08](https://cloud.githubusercontent.com/assets/700793/23822242/35d960a4-0684-11e7-9903-fa56703aa2ac.png)
![screenshot_2017-03-11-17-53-47](https://cloud.githubusercontent.com/assets/700793/23822243/35ddb8c0-0684-11e7-9dfa-492c718f046c.png)
![screenshot_2017-03-11-17-54-16](https://cloud.githubusercontent.com/assets/700793/23822244/360bf514-0684-11e7-8d1f-128d8ad7950a.png)

**Comment by zeapo** [comment]
When you click the select openpgp key, you should see a list of keys with checkbox on the left. Click on it and click on Okay on the top right of your screen.

**Comment by suiang** [comment]
I have also encountered the same problem

**Comment by suiang** [comment]
@eexpress 我也遇到了同样的问题 不知道你解决了没有

**Comment by vc12345679** [comment]
I also meet this problem on my Nubia Z9.
BTW are u using nubia too? @eexpress

**Comment by suiang** [comment]
@vc123456789 我用的魅族pro6 plus保持openkeychain 运行就可以选了

**Comment by suiang** [comment]
保持后台运行，我在手机管家里面关闭了自动后台就没问题了，K9mail也能选了

**Comment by vc12345679** [comment]
@suiang 多谢，试过了，没用啊

**Comment by suiang** [comment]
@vc123456789 打开openkeychain悬窗权限试试看

**Comment by vc12345679** [comment]
I've tried the four combinations with Password-Store(v1.2.0.56, v1.2.0.57) & Open-Keychain(v4.2.3, v4.2.4) on Nubia Z9 (Android 5.1.1). Unfortunately, nothing helps.
Would anyone mind tell me how to locate the problem?

**Comment by vc12345679** [comment]
@suiang 还是老样子…

**Comment by vc12345679** [comment]
@zeapo After clicked 'choose openpgp key id', it led to a blank password browse screen, with top banner (BACK/"Password Store"/SHARE/COPY/EDIT), and the screen snapshot couldn't been captured. Neither key IDs nor checkboxes showed.

**Comment by zeapo** [comment]
@vc12345679 Thanks for your effort :+1: 

I will close this issue then.
