### ISSUE TITLE
Support for Android O Autofill Framework

### ISSUE THREAD

**Issue by wiktor-k** [zeapo/Android-Password-Store#282]
I know it's really early but the Autofill Framework looks like a perfect match for the Password Store. 

https://developer.android.com/preview/features/autofill.html

**Comment by c4software** [comment]
Nice idea.

**Comment by felixb** [comment]
Please note this [blog post] and this [white paper] regarding the autofill framework.

[blog post]: https://commonsware.com/blog/2017/08/08/autofill-services-security.html
[white paper]: https://github.com/commonsguy/AutofillFollies/blob/master/WHITE_PAPER.md

**Comment by wongma7** [comment]
I don't intend to work on this, anybody who does is welcome to dump and rewrite the existing autofill ui and whatnot. Caveat: I'm not sure how other password managers are handling this, but I imagine the old framework will need to be maintained for a while longer given Android's update situation (this app's userbase is surely more savvy and likely to keep up-to-date, but still). I've not done the best job helping maintain it and other stuff but it seems in a mostly okay state, aside from a couple device specific issues I've never been able to track down, and the non-ideal performance which we can mostly blame on having to hack the accessibility framework  

Good news is the whitepaper says "UPDATE 2017-09-27: the documentation has been incrementally improved)" so working on this maybe won't be too much of a difficult security nightmare.

**Comment by tsnieman** [comment]
For what it's worth, Bitwarden just implemented Android O Autofill if any contributors want to use their code as an example of implementation: https://github.com/bitwarden/mobile/issues/57

Bitwarden experienced some roughness setting it all up (i.e. figuring out how to get around autofill prompts on search fields), so I imagine their example will be helpful.

**Comment by ashkitten** [comment]
Hi, is anyone working on this?

**Comment by jannickfahlbusch** [comment]
I started to implement the functionality recently.

**Comment by zidhuss** [comment]
Some progress has been made with this issue in #410.
