### ISSUE TITLE
[BUG] AGP 8.3.0-alpha16 is not compatible with newest Android Studio Canary

### ISSUE THREAD

**Issue by Mortal** [zeapo/Android-Password-Store#2820]
### Describe the bug

In a fresh install of Android Studio Iguana 2023.2.1, gradle sync fails with the error message:

> Unsupported Java. 
> Your build is currently configured to use Java 21 and Gradle 8.5.
> 
> Possible solution:
>  - Open Gradle wrapper settings, change `distributionUrl` property to use compatible Gradle version and reload the project

In the stdout/stderr of Android Studio, the actual error message is found:

> Caused by: com.android.tools.idea.gradle.project.sync.AndroidSyncException: The project is using an incompatible preview version (AGP 8.3.0-alpha16) of the Android Gradle plugin. Current compatible preview version is AGP 8.3.0-alpha17. at:

It works fine if I put `agp = "8.3.0-alpha17"` in gradle/libs.versions.toml, but the file .github/renovate.json5 has a comment saying "alpha17 and alpha18 have regressions with installing APKs https://issuetracker.google.com/issues/315337463" so I'm not sure if it's OK to bump the AGP version?

### Steps to reproduce

1. Install AS Canary and switch from Java 17 to Java 21 in settings
2. Open Android-Password-Store on the develop branch
3. Run Gradle sync

### Expected behavior

Successful Gradle sync

### Device information

- OS: Arch Linux

**Comment by msfjarvis** [comment]
The bug in question breaks `./gradlew install[NonFree]Release` which is why I downgraded it to 8.3.0-alpha16, Google makes it difficult to find older canary builds so I can see why it's a problem on the IDE front. I'll downgrade AGP to the stable track.

**Comment by Mortal** [comment]
A thousand thanks for handling this so quickly, and also for merging my PR (#2819) so quickly!
