### ISSUE TITLE
passkeys

### ISSUE THREAD

**Issue by nikilson** [zeapo/Android-Password-Store#2839]
### Is your feature request related to a problem? Please describe.

big companies like Google, Microsoft, Apple... are promoting passkeys. I think people will start adapting to passkeys which are very convenient and safe to use. Please try to integrate that into this app. I can help you with whatever help you want from me. I am an Android developer. I love this app.

### Describe the solution you'd like

Apps like Bitwarden, started to implement passkeys into their. We need to implement this feature mixing the way they do and unix pass manager simple and easy to maintain using gpg keys. 

### Describe alternatives you've considered

It would be nice if we could encrypt the passkey itself with the master gpg key and save the encrypted passkeys in git repository like typical passwords.

**Comment by msfjarvis** [comment]
I have no idea what happened here.

**Comment by nikilson** [comment]
I saw a similar feature request so I closed it sorry. Love your work btw.

**Comment by nikilson** [comment]
I'd like to help you with this. nikilson30@gmail.com my email.

**Comment by msfjarvis** [comment]
I don't wanna email you, if you have a proposal then discuss the code in the other issue or send in a PR.
