### ISSUE TITLE
[FEATURE] Support external storage

### ISSUE THREAD

**Issue by freijon** [zeapo/Android-Password-Store#2848]
### Is your feature request related to a problem? Please describe.

In the  version 1.13.5 I was able to use an external store location. I use PasswordStore as a read-only app with Syncthing to update my passwords on all devices. But with current snapshot builds this concept no longer works because only the internal (hidden) storage seems to be supported.

### Describe the solution you'd like

Bring back external storage support

### Describe alternatives you've considered

I considered using `git` but I don't want to setup a git server and I don't want my passwords in the cloud.

### Additional context

I'm stuck with 1.13.5 until this is resolved.

**Comment by msfjarvis** [comment]
External storage support is simply too much complexity for a feature I will never use. Password Store is enough work as-is for me, and I would rather keep the scope limited enough for me to be able to continue maintaining it.

**Comment by jidhub** [comment]
freijon, I suggest that you try to unhide the "(hidden)" internal storage, by patching this with something like `Runtime.getRuntime().exec("chmod 1755 /data/data/app.passwordstore");` like done in [this minimal app](https://stackoverflow.com/a/33499591/2987828).
