### ISSUE TITLE
[FEATURE] Support other storage providers (OneDrive, Google Drive)

### ISSUE THREAD

**Issue by WIcheese** [zeapo/Android-Password-Store#2851]
### Is your feature request related to a problem? Please describe.

Not all users of password-store (or QtPass or other compatible apps) have their password store published via git.  Any directory works.  OneDrive or other file syncing services that can sync a local directory on the PC to a cloud account are common for this.

However, because Android Password Store uses an older file picker and doesn't see all the storage locations synced to a device, even with OneDrive installed & signed in & all other apps seeing my OneDrive as a location, Android Password Store doesn't, and can't open the repository that is located within OneDrive.

### Describe the solution you'd like

I would like to be able to use the repository in my OneDrive.

### Describe alternatives you've considered

Alternative #1: Stick with Keepass2Android.  I used to be a KeePass user and syncing was no issue then.  However, I've upgraded to hardware-backed security & only password-store compatible solutions let me cryptographically require a touch from my YubiKey on every decryption, so this alternative would be a step backwards.

Alternative #2: Manually copy the repository folder to local storage on my phone after every change.  Very laborious.

Alternative #3: Switch to git.  The odds that a private repository on Github becomes non-free in the future are much greater than the odds that not only OneDrive, but ALL apps that can sync a storage location to your phone and make it available to all apps become non-free.

### Additional context

I don't care if OneDrive is natively implemented or just use the dependency on the app

**Comment by msfjarvis** [comment]
Storage Access Framework is not supported because maintaining two code paths for all store operations is additional complexity that I am not ready to take on for a feature I will never use and thus cannot ensure a reasonable level of quality for. Since I'm the only active maintainer I would rather keep a smaller scope and have everything work rather than try to appease everybody and end up with an app that nobody is happy with.
