### ISSUE TITLE
[FEATURE] Convert "Disable screen mirroring while creating and viewing passwords" into an optional feature

### ISSUE THREAD

**Issue by ArcherN9** [zeapo/Android-Password-Store#2860]
### Is your feature request related to a problem? Please describe.

I'm an Android Developer and I generally have up to 3 devices connected to my laptop at any given time. As one would imagine, this creates a clutter at my table and the constant shift of glances left and right to check the devices is a deterrent to my productivity _Not to mention the headache it used to give me_.

I stuck the primary device that I need throughout the day to the back of my laptop so its constantly wired in during my working hours and I use Android Studio to mirror the screen on my laptop. The laptop being an enterprise issued workstation, does not provide access to all websites/applications _like pass on my terminal et all_ due to which I use Pass app from my phone to copy the passwords of whatever it is I'm trying to access. I liked the ability of the older v1.x Pass application to not request PGP password on every decrypt request.

Though the screen blacked out in the earlier version as well, it would copy the content to the phone's clipboard and to my systems' while screen mirroring. Since the SNAPSHOT/v2 asks for the GPG password on every decrypt, I have to close the laptop lid every time I have to enter the password.

This has been going on for a couple of hours today and I feel extremely irritated.

### Describe the solution you'd like

An additional configuration option under the _General_ header to disable the feature _Disable screen mirroring while decrypting or creating new passwords_. The setting should be enabled by default to retain the core functionality for majority of the users.

### Describe alternatives you've considered

1. Drop down to the older 1.x version of the application. It works well and does not hinder the workflow. _I would prefer to use the latest versions too however_
2. Decrypt the password on another phone, share it my _Me_ chat on Teams, fix the text formatting due to the way clipboard works with Teams and paste on the target input field on the laptop. _An infuriating flow_

### Additional context

I would be interested to take this up if you can guide a on where to look and offer review of the solution design.

**Comment by Skrilltrax** [comment]
> Since the SNAPSHOT/v2 asks for the GPG password on every decrypt, I have to close the laptop lid every time I have to enter the password.

You can cache the GPG passphrase by going to Settings > PGP Settings > Enable passphrase caching. That way you'll just have to use your fingerprint on the device instead of entering password every time. Would that solve your issue?

**Comment by msfjarvis** [comment]
Adding an option to disable FLAG_SECURE is not an acceptable solution for this particular use case. As Aditya mentioned, there is a passphrase cache that takes care of the problem of being prompted for your passphrase, and I've [just fixed the copy-on-decrypt feature from v1](https://msfjarvis.dev/aps/3a7d298a6f5d) so you can enable that in settings and get back the behavior you had earlier.

**Comment by ArcherN9** [comment]
> > Since the SNAPSHOT/v2 asks for the GPG password on every decrypt, I have to close the laptop lid every time I have to enter the password.
> 
> You can cache the GPG passphrase by going to Settings > PGP Settings > Enable passphrase caching. That way you'll just have to use your fingerprint on the device instead of entering password every time. Would that solve your issue?

I tried it. Reasons why this doesn't work.

1. Once enabled, tapping on each password requires the chosen lock mode from screen lock to be unlocked. That screen does not show up while screen mirroring either.
2. The device is stuck to the laptop, to use the fingerprint reader, I would have to close the lid.


> Adding an option to disable FLAG_SECURE is not an acceptable solution for this particular use case. As Aditya mentioned, there is a passphrase cache that takes care of the problem of being prompted for your passphrase, and I've [just fixed the copy-on-decrypt feature from v1](https://msfjarvis.dev/aps/3a7d298a6f5d) so you can enable that in settings and get back the behavior you had earlier.

As I understand, the copy on decrypt in conjunction with passphrase caching should fix the issue. The screen lock prompt that replaces the GPG password Dialog does not show up while screen mirroring either.

However, it does give me the ability to type out an easy PIN blind.
Open Pass > Pick a password > _blacked out screen_ > enter the PIN ensuring the window mirroring the phone has focus > Tap enter > a Toast message confirms password has been copied > Tap back > _Screen mirroring continues_.

This does work; I concur this is extremely niche and may not be prudent to have this for **everyone**. I'll have a look at where `FLAG_SECURE` is added and make a personal build.

**Comment by msfjarvis** [comment]
> This does work; I concur this is extremely niche and may not be prudent to have this for everyone. I'll have a look at where FLAG_SECURE is added and make a personal build.

It's set here https://github.com/android-password-store/Android-Password-Store/blob/3a7d298a6f5dc8a3f5c0df045dfc180678251fdd/app/src/main/java/app/passwordstore/ui/crypto/BasePGPActivity.kt#L83

**Comment by ArcherN9** [comment]
For anyone looking for this feature, its implemented through commit [#751d4a8](https://github.com/ArcherN9/Android-Password-Store/commit/751d4a8d780d734097f765c147efa9e6d7961c09).
