### ISSUE TITLE
[BUG]  Error OpenKeyChain: Error opening input data stream

### ISSUE THREAD

**Issue by kr1vi4** [zeapo/Android-Password-Store#2866]
### Describe the bug

installed on another phone OpenKeyChain and Pssword-Store, imported the key, selected it, gave permission to work with Password-Store, synchronized git, when trying to decrypt the passwords it says: Error opening the input data stream. 

### Expected behavior

Tell me what could be wrong?

### Device information

- Device: Honor HRY-LX1
- OS: Android 10
- App version: [e.g. 1.13.5]

**Comment by msfjarvis** [comment]
OpenKeychain is no longer supported.
