### ISSUE TITLE
Extra content not shown until password copy

### ISSUE THREAD

**Issue by Ozymandias117** [zeapo/Android-Password-Store#288]
Disabling "Automatically Copy Password" causes the "Extra content:" box to remain hidden - no matter the setting of "Show Password". Manually pressing the copy button then makes the "Extra content:" fields visible.

The only time the R.id.crypto_extra_show text view is set to visible is in onPreExecute in DelayShow.
The only callchain I see to that is copyToClipBoard->setTimer->executeOnExecutor.

I believe that, at the very least, extra content should be set to visible in the PgpCallback onReturn if show_password is true. My personal preference would be for extra content to be visible even with the password hidden.

Thoughts on always making extra content visible?

**Comment by mftrhu** [comment]
I would like to see a toggle to always show the extra content. I mostly use pass to store sensitive data that I don't trust lying around in plaintext, and having to copy an inexistent password to get it to show is a bit irritating.
