### ISSUE TITLE
[FEATURE] Support local non-Git stores

### ISSUE THREAD

**Issue by M-u-m-p-i-t-z** [zeapo/Android-Password-Store#2904]
### Is your feature request related to a problem? Please describe.

I don't want to store my passwords online. I do backups only in my local network but not with a git server.
My Phone is not rooted (GrapheneOS) so I also cant import my old 300 password rep.
This new Snapshot build  doesnt yet support a local password rep on readable device memory and I cant change the folder like in old F-Droid Version.

### Describe the solution you'd like

 So may I ask will I get this Feature back? It would be great to use the new version of the app.

### Describe alternatives you've considered

an import function is also nice, but my auto backup will not work too because of not readable hidden rep folder.

### Additional context

Thank you and greetings!

**Comment by msfjarvis** [comment]
It shouldn't be impossible to support an import flow for files on disk but I personally have no intention of working on this. If someone wants to take it up I'll be more than happy to review a PR.

Edit: I missed the part about having stores in public folders, support for that is not coming back because it severely complicates the code around file handling and I don't want the additional maintenance overhead for a feature I will never use and thus won't receive any testing.

**Comment by M-u-m-p-i-t-z** [comment]
Ok thanks anyway, then I have to find another solution. Do you know if I can copy my repo with adb (via wifi) to the hidden folder?
@msfjarvis

**Comment by msfjarvis** [comment]
> Ok thanks anyway, then I have to find another solution. Do you know if I can copy my repo with adb (via wifi) to the hidden folder? @msfjarvis

You cannot, the only supported solution is Git.

**Comment by cprussin** [comment]
Does that mean that there's effectively no way to use the new version of APS with a password store synced via something like Syncthing or some other file sync tool?

**Comment by msfjarvis** [comment]
> Does that mean that there's effectively no way to use the new version of APS with a password store synced via something like Syncthing or some other file sync tool?

Correct.

**Comment by cprussin** [comment]
Ah that's unfortunate.  If someone were to want to contribute something back, do you have any suggestion for what to contribute to make that workflow possible?  I likely don't have the time or expertise but if I get motivated and you have advice on the right approach, I'll try to give it a shot!

**Comment by msfjarvis** [comment]
> Ah that's unfortunate.  If someone were to want to contribute something back, do you have any suggestion for what to contribute to make that workflow possible?  I likely don't have the time or expertise but if I get motivated and you have advice on the right approach, I'll try to give it a shot!

The [`PasswordRepository`](https://github.com/android-password-store/Android-Password-Store/blob/cd0a6381060aae859cb66f03edf64fc5ecbafffe/app/src/main/java/app/passwordstore/data/repo/PasswordRepository.kt) class would need an alternate implementation that can properly handle files on external storage, which entails not using `java.io.File` and replacing it with [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider).

**Comment by grigorii-horos** [comment]
@M-u-m-p-i-t-z @msfjarvis I need this feature too. I use Sycthing for file sync, and I have a password-store folder in my internal storage, so I want to use this dir in this app. 

Now I use the old app, and I can't upgrade it

**Comment by msfjarvis** [comment]
That's great, but as I've stated already I have no intention of working on the feature. The only way it gets implemented is by someone contributing it, which I am willing to review and merge.

**Comment by mahlonsmith** [comment]
Found this ticket after updating the app, only to have it start crashing because of a lack of a .git repo on my synced password directory.

I've worked around this for now by initializing a git repo on the remote side and letting it sync.  This at least makes things usable again, and I'm roughly ignoring the git specifics, though it does feel unnecessarily redundant (for my use case), and a surprise that it was a requirement.

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
