### ISSUE TITLE
[FEATURE]  support URL in gpg file

### ISSUE THREAD

**Issue by Schueni1** [zeapo/Android-Password-Store#2908]
### Is your feature request related to a problem? Please describe.

I tried to use this password organization scheme. But autofill does not detect the URL if it is only in the encrypted file.

- application.gpg
  password
  login: bob
  pin: 1234
  url: example.com
  otpauth://totp/...

### Describe the solution you'd like

Detect 'url:' in the gpg file

### Describe alternatives you've considered

Use a different organization scheme

### Additional context

This is one of the schemes supported by passff

**Comment by msfjarvis** [comment]
`passff` appears to decrypt the entire store on extension init to index the `URL` keys, that is not feasible on Android for both speed and practicality reasons. The existing organization schemes will have to suffice, or if they don't work for you the app will remember what password file was used to autofill which website/app and present that in the future.

**Comment by Schueni1** [comment]
Ok thanks for the info
