### ISSUE TITLE
No extra content is shown when password line is empty

### ISSUE THREAD

**Issue by q1x0te** [zeapo/Android-Password-Store#291]
No extra content is shown when an entry file has no password stored (the first line of the file is empty) and the file has additional information on subsequent lines.

**Comment by gattazr** [comment]
I'm having the same problem so I'll +1 this issue :-)

**Comment by zeapo** [comment]
It has been fixed in https://github.com/zeapo/Android-Password-Store/commit/8663ee92f80d6ab143de7a8ec5221ceebaaf132b 

Will available in Play Store as Alpha Version 1.2.0.58 and on F-Droid
