### ISSUE TITLE
[BUG] passwordstore.app is offline, domain is expired?

### ISSUE THREAD

**Issue by c-mart** [zeapo/Android-Password-Store#2917]
### Describe the bug

- Loading <https://passwordstore.app> results in "secure connection failed"
- `curl http://passwordstore.app` returns a 302 redirect to <http://domain-registrar.storage.googleapis.com/expired.html?passwordstore.app>

### Steps to reproduce

1. Go to https://passwordstore.org in your browser (or `curl` it)

### Expected behavior

See the web site

### Screenshots

![image](https://github.com/android-password-store/Android-Password-Store/assets/13605043/85ded070-9439-4051-9c5e-96617e558c86)

### Device information

- Device: Multiple (phone, tablet, laptop)
- OS: GrapheneOS, Debian Linux
- App version: Firefox 116, Firefox Mobile 119

**Comment by msfjarvis** [comment]
Yes I was planning to migrate the domain to Porkbun but life got in the way. I've paid for the transfer now, it should be back up in a few hours.
