### ISSUE TITLE
How to import ssh keys

### ISSUE THREAD

**Issue by realcomplex** [zeapo/Android-Password-Store#292]
Hey!

I'm trying to use this app for the first time, and I'm pretty confused about how to get started, even though I think I have a fair understanding about pass, ssh keys and git repositories.

I want to clone an existing git repository that holds my password store. So I select "clone from server", chose the "hidden" option, enter the details of my git repository, and press "Clone!". Then, I am prompted to import my ssh key, and select the key file `/sdcard/key.asc` that I put there earlier. I am then notified that "ssh-key imported". However, immediately afterwards the app prompts me with the message "Unable to open the ssh-key, please check that it was imported". But I was just told that the key was imported! The git cloning fails.

The way I got the `key.asc` file in `/sdcard/` was by running `gpg --export-secret-key [my-id] > key.asc`, and then `adb push key.asc /sdcard/key.asc`.

What am I doing wrong? Maybe it would be an idea to write a little more documentation (in the wiki) about what the recommended procedure is to import ssh keys, including the process of exporting them on your laptop/desktop computer, and transferring them to your android device?

Thanks in advance for the help; once I get this working I'm sure it'll be great!

**Comment by zeapo** [comment]
Hi,
The key you just exported is your "gpg" key to be used within OpenKeychain. The ssh-key has to be generated using `ssh-keygen` or using the integrated key-generator in the app.

Please see : https://github.com/zeapo/Android-Password-Store#generate-a-ssh-key-for-your-git-repo

Cheers

**Comment by realcomplex** [comment]
Okay that totally solved it, I feel pretty stupid now. Thanks for the help, all is good!
