### ISSUE TITLE
[BUG] Message "Wrong password" on decrypt, log says "Subkey ... was never validly bound"

### ISSUE THREAD

**Issue by meliache** [zeapo/Android-Password-Store#2921]
### Describe the bug

I use pass for year on my computer and also the previous version of Android-password-store on my phone. Now I tried the new developer snapshot 9eac07efc32bd3aca1075536e556c9036fc7ccb4 (non-free) and cannot decrypt passwords, I always get a "Wrong password" message.

Initially I thought this might be https://github.com/android-password-store/Android-Password-Store/discussions/2868, but it's not. It does not matter whether the password was created on my PC or on Android and my GPG key has seems to have no AEAD bit anyway.

However, my GPG-key has many other bells and whistles. It has several notations (used for [my keyoxide](https://keyoxide.org/546908C782383AD0E7D894EC1B8F95C8125DCE31)) and also a second UID with a JPG attached. I was worried that this might trip the PGP implementation up, so I used `gpg --edit-key` to remove the unneeded UID and notations (on a copy of the key in a temporary GPG homedir) and exported with `--export-options export-minimal`, but that didn't help or make any difference.

Then for the bug report I produced the log and noticed that I get the error messages:
```
... OpenPgpMessageInputStream: Encountered PKESK for recipient 733FE709A39E5251
... KeyRingInfo: Subkey 733FE709A39E5251 was never validly bound.
... OpenPgpMessageInputStream: Subkey 733fe709a39e5251 cannot be used for decryption.
... OpenPgpMessageInputStream: Skipping PKESK because no matching key 733FE709A39E5251 was provided
... OpenPgpMessageInputStream: Failed to decrypt encrypted data packet
```
[(Full Log)](https://github.com/android-password-store/Android-Password-Store/files/14427104/android-password-store-log.txt)

But I don't really understand *why* that key supposedly cannot be used for decryption, as I could successfully use it on my PC and in Openkeychain.

Here is some info for the key:
```
$ gpg --expert --edit-key 733FE709A39E5251
gpg (GnuPG) 2.4.4; Copyright (C) 2024 g10 Code GmbH
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Secret key is available.

sec  rsa2048/1B8F95C8125DCE31
     created: 2013-06-22  expires: 2025-12-04  usage: SC  
     trust: ultimate      validity: ultimate
ssb  rsa2048/733FE709A39E5251
     created: 2013-06-22  expires: never       usage: E   
[ultimate] (1). Michael Eliachevitch <m.eliachevitch@posteo.de>
```

Maybe something is wrong with my key, if so, I would be happy if you could tell me.

### Steps to reproduce

- Export my private GPG key on my computer
  `gpg --output private.gpg --armor --export-secret-keys  m.eliachevitch@posteo.de`
- Import the key in android-password-store
- Click on a password (that I had synced from PC, or one that was generated in the app, could reproduce it with both)
- Get error: "Wrong password"

### Expected behavior

Show password

### Device information

- Device: Google Pixel 7a 
- OS: Android 14 (with security update from 5th February 2024)
- App version: Snapshot 9eac07efc32bd3aca1075536e556c9036fc7ccb4 (non-free)

**Comment by meliache** [comment]
I managed to fix my problem and make the key usable, but not sure what exactly did that. I wanted to check if having an expiration day might help, inspired by https://github.com/pgpainless/pgpainless/issues/421. When I googled how to change expiration dates in the CLI, I learned that the gpg repl also allow selecting subkeys to act upon. So I selected the ssb subkey, set an expiration date and just for good measure also set the trust to `ultimate`

```
gpg --edit-key m.eliachevitch@posteo.de
> key 1
> expire 2y
> trust 5
```

And when I imported this key, decryption suddenly worked. But then I set the expiration back to 0 (no expiration) and the key still worked. So seems like the trust is what fixed it? But does the encryption-key (ssd) really have a trust? When I type `list` in gpg --edit-key` , I only see a trust for the sec key and in front of the UID, and they were all `ultimate` already before, so not sure if the trust really changed. Maybe a side effect of what I did fixed the bug.

In https://github.com/pgpainless/pgpainless/issues/421 somebody also comments that pgpainless rejects SHA1 signatures, not sure if that could have something to do with it :shrug:

**Comment by msfjarvis** [comment]
I believe trust is local to the GnuPG installation and not set on the key itself. PGPainless does reject SHA-1 signatures and expired keys so it's possible the key was in an inconsistent state w.r.t. expiration and manually setting it to 2 years and back to no expiration fixed it. The app currently defaults to surfacing all PGP errors as incorrect password but it's being tracked and will get fixed. Closing this issue since it seems like everything's resolved now.

**Comment by meliache** [comment]
> The app currently defaults to surfacing all PGP errors as incorrect password but it's being tracked and will get fixed.

That would be great. It would be very helpful to have a searchable error message, even some way to view the debug log from within the app. It is a bit of a hurdle for non-devs to set up adb and put the phone into developer mode to extract the log.

But I saw from other issues that you are mostly a lone developer on this project and doing a big transition, so thanks a lot for your work :pray: . I always thought that `pass` has some popularity among Linux users, so I would assume that there are a number of people relying on this app. But as always, few contribute when (as long as nothing seems broken).
