### ISSUE TITLE
[BUG] Password form does not accept the key password

### ISSUE THREAD

**Issue by GregTheMadMonk** [zeapo/Android-Password-Store#2924]
### Describe the bug

When trying to view the contents of the entry, the "Password" dialog shows up and doesn't accept the correct key password. I've tried changing the key and re-signing the password storage (pulling the git repo after that, of course), changing the encryption algorithm or removing the password altogether, but nothing works.

### Steps to reproduce

1. Set up Password Store with a git repo and import the PGP secret key
2. Click on the entry
3. The "Password" dialog shows up
4. Enter anything there (correct key password, incorrect key password, nothing) and click OK
5. Get the "Wrong password" error

### Expected behavior

Correct key password should be accepted

### Device information

- Device: Poco X3 Pro
- OS: /e/ OS 1.19.1
- App version: 2.0.0-SNAPSHOT

**Comment by msfjarvis** [comment]
Please capture a log https://docs.passwordstore.app/docs/users/reporting-bugs

**Comment by GregTheMadMonk** [comment]
[log.txt](https://github.com/android-password-store/Android-Password-Store/files/14432152/log.txt)

I've removed the address of my password store repo, but otherwise the log is unmodified

**Comment by msfjarvis** [comment]
> [log.txt](https://github.com/android-password-store/Android-Password-Store/files/14432152/log.txt)
> 
> I've removed the address of my password store repo, but otherwise the log is unmodified

Your key has AEAD enabled, which the app does not work with due to GnuPG opting to diverge from the OpenPGP standard for AEAD. You'll need to disable it https://unix.stackexchange.com/questions/697579/gpg-failing-with-no-error-for-one-of-my-encrypted-files

**Comment by GregTheMadMonk** [comment]
This solved the issue. Thank you!

Maybe there is a way to detect that in-app and warn the user?

**Comment by msfjarvis** [comment]
> This solved the issue. Thank you!
> 
> Maybe there is a way to detect that in-app and warn the user?

Cryptography errors in general require a lot of improvement, it's just a matter of me being a lone maintainer without enough time to pick up the work.

**Comment by naisanzaa** [comment]
what's the difference between the MacOS and iOS app, where it doesn't have this issue with AEAD in the gpg key? 

only android has this issue with importing a key with AEAD.
