### ISSUE TITLE
Filling fields in browser etc using keyboard

### ISSUE THREAD

**Issue by kwlg** [zeapo/Android-Password-Store#293]
An appreciated feature would be to fill forms in browsers or arbitrary apps. I recently read https://github.com/zeapo/Android-Password-Store/issues/176, where it is said that filling in Firefox is not possible due to the fact that Firefox doesn't send accessibility events out like Chrome does.

However, Lastpass uses a keyboard where the user is able to manually choose what information to fill in. For example, if I were to log in to Github, I would navigate to Github in Firefox, tap the password field, switch keyboards to Lastpass's keyboard, choose Github and it would fill my password in for me in the field of my choice.

From the readme of this project, it says the following
> ~~Implement a keyboard to replace the copy/paste and avoid clipboard hijicking (see #50)~~ (Autofill does the job)

In comparison to an autofill feature, a keyboard have some benefits:
* A keyboard would, however, have benefits such as filling in information in browsers or arbitrary apps.
* Keyboards don't need accessibility settings to work.
* I suppose autofill could be deceived into filling invisible fields in e.g. overlay apps such as screen filters. A keyboard would decrease that risk since the user would manually choose what fields to fill.

I would really appreciate a keyboard! Would that be reconsidered?

**Comment by wongma7** [comment]
I don't think it means straight up, if you try to contribute a keyboard it
will be rejected. It's just a matter of prioritization, autofill is
sufficient for enough use-cases and there's other bugs/tech-debt to work
on. FWIW I agree a keyboard would be nice, the experience of switching
between keyboards has improved a lot over the last couple android versions.
But with android O adding an official autofill framework I'd put a keyboard
even lower in priority, because I'd rather see the official autofill
implemented.

**Comment by kwlg** [comment]
Yes, of course! I forgot about the Autofill API! Let's wait and see how it works :)

**Comment by brcha** [comment]
I've just switched to pass from keepassx, and the keyboard would be a welcome addition. Ofc, if Android O is getting new API which is (hopefully) going to be supported by Firefox as well, than it's not that important of a feature.https://github.com/PhilippC/keepass2android/tree/master/src/java/KP2ASoftkeyboard_AS

**Comment by kwlg** [comment]
I'm sorry to ask, but are there plans to implement the Android O autofill API in the app? :)

**Comment by wongma7** [comment]
@kwlg see https://github.com/zeapo/Android-Password-Store/issues/282, we can discuss there

**Comment by zidhuss** [comment]
Continued in #410.
