### ISSUE TITLE
[FEATURE] Remember password for a specific amount of time configurable in the Snapshot build of APS

### ISSUE THREAD

**Issue by AkechiShiro** [zeapo/Android-Password-Store#2940]
### Is your feature request related to a problem? Please describe.

It is frustrating to always type your master password when in need of a password on the new beta/alpha app (latest pre-release).

### Describe the solution you'd like

It should be configurable for how long the password is retained inside memory/similar to how the OpenPGP application (old backend) behaved.

### Describe alternatives you've considered

There could be also biometrics that could be used to maybe unlock the master password if it was previously input (like during the past 24 hours for instance)

**Comment by msfjarvis** [comment]
There is already a passphrase cache available in the PGP settings.

**Comment by AkechiShiro** [comment]
Hm I didn't see any settings regarding settings the duration for expiration of the passphrase caching, but there is one marked as very experimental, and needs the lockscreen to work, not sure if it expires and when/how?

**Comment by msfjarvis** [comment]
> Hm I didn't see any settings regarding settings the duration for expiration of the passphrase caching, but there is one marked as very experimental, and needs the lockscreen to work, not sure if it expires and when/how?

There is no expiry as of now, the password is written to disk in an encrypted key-value store separate from the app's normal settings.

**Comment by AkechiShiro** [comment]
Thanks maybe this should be clarified in the application (option description) thanks a lot, that's good for me, I may wish to make it expire at some point but right now it's not needed.
