### ISSUE TITLE
[BUG] Unable to connect to github repo with generated ssh-key pair

### ISSUE THREAD

**Issue by Jimmy2027** [zeapo/Android-Password-Store#2942]
### Describe the bug

I have the android password store "latest" from last week and am unable to pull my passwords from my private github repository.
When opening the app the first time, I generated a ssh-key pais and added the public key to my github profile.

After doing these steps, I'm unable to pull from the remote. I'm getting the error pop-up: `An error occurrec during a Git operation\n Socket closed` after unlocking the key with the finger print reader.

This is the log:
[log_.txt](https://github.com/android-password-store/Android-Password-Store/files/14546659/log_.txt)

### Steps to reproduce

1. Get the latest app version from github
2. Generate a new ssh-key pair
3. Add the key to the github account
4. Pull from remote

### Expected behavior

Expecting to be able to pull from remote.

### Device information

- Device: Samsung Galaxy S10 
- OS: Android 12

**Comment by Jimmy2027** [comment]
I wasn't able to reproduce the issue with the following steps:

1. Download the latest snapshot from today
2. When opening the app, add the ssh clone url 
3. generate a new ssh-key pair (using the `ed25519` algorighm instead of the `sha2`)
4.  immediately add the public key to the github account, before pulling
5. pull

**Comment by qfire** [comment]
I ran into this same issue with snapshot from today, from revision 88facd7.

I was able to workaround by unchecking the option to protect the generated ssh key using the phone lock.

**Comment by msfjarvis** [comment]
This is an issue with a small subset of devices where a hardware-encrypted key goes "bad" and can neither be used to decrypt data by the app nor allowed to be cleared. Reinstallation is one workaround, the other one is not protecting the key with device encryption in the first place as mentioned by qfire. There isn't a lot we can do here.

**Comment by madeddie** [comment]
> Reinstallation is one workaround

What do you mean with reinstallation here? Reinstalling the app or factory resetting the whole device?

**Comment by msfjarvis** [comment]
> > Reinstallation is one workaround
> 
> What do you mean with reinstallation here? Reinstalling the app or factory resetting the whole device?

The app.

**Comment by rcorre** [comment]
I can confirm. I had this problem on a fresh install on a pixel 8. I generated an ssh key in the app, uploaded it to gitlab, and cloned, and got "socket closed". I reinstalled APS and went through the same steps again, and it succeeded :shrug:
