### ISSUE TITLE
Error from OpenKeyChain: Encountered OpenPGP Exception during operation!

### ISSUE THREAD

**Issue by bydmiller** [zeapo/Android-Password-Store#2963]
### Describe the bug

I cannot see my passwords in Android Password Store (APS). I imported my private key into OpenKeychain for APS. Following issue #2653, I removed AEAD encryption from my key and reset the password store with it. However, the problem still persists.

### Steps to reproduce

1. Execute `gpg --output private.pgp --armor --export-secret-key youremail@email.com` to export the private key.
2. Import this exported key into OpenKeychain.
3. Clone the pass GitHub repository in Android Password Store using HTTPS along with the password.
4. Provide your passphrase for the OpenKeychain key when prompted.

### Expected behavior

The passwords need to be visible without any error in Android Password Store. 

### Device information

- Device: Samsung S8
- OS: Android 9
- App version: 1.13.5

**Comment by msfjarvis** [comment]
We'll at least need a log (make sure to use the package name of OpenKeychain to get logs from it) https://docs.passwordstore.app/docs/users/reporting-bugs

FYI OpenKeychain bugs are out of scope for APS now that we do not use it in the app so it's better to report issues to them rather than here.

**Comment by bydmiller** [comment]
Thank you for replying so soon. Because i was unable to find any documentation on how to use Android Password store without openkeychain.

**Comment by msfjarvis** [comment]
> Thank you for replying so soon. Because i was unable to find any documentation on how to use Android Password store without openkeychain.

The in-development version of Password Store available in the [snapshot channel](https://docs.passwordstore.app/docs/users/release-channels) does not use OpenKeychain. The app will walk you through the setup.

Closing this since there is nothing actionable here, for further questions about Password Store feel free to create a discussion [here](https://github.com/android-password-store/Android-Password-Store/discussions).

**Comment by bydmiller** [comment]
I've experimented with snapshot versions of the Android password store, yet despite entering the correct password, I'm consistently encountering a "wrong password" error message. I've imported my private key via the settings menu, specifically navigating through settings > pgp_settings > key_manager.

**Comment by Padswynn** [comment]
I would like to add just in case anyone stumbled across this, I solved a similar problem with the OpenKeychain exception and the incorrect password loop on snapshot via this:

https://docs.passwordstore.app/docs/users/common-issues/#gnupg-aead-encryption-2974-2963-2921-2924-2653-2461-2586-2179
