### ISSUE TITLE
[BUG] AEAD error is reported as incorrect passphrase

### ISSUE THREAD

**Issue by PtitLutinn** [zeapo/Android-Password-Store#2974]
### Describe the bug

When I type my password It says it's false but I'm 99% sure it's not. 
can't open my password

### Steps to reproduce

1. Go to the app
2. Click on a password entry
3. Put your password (I cc mine for accuracy)
4. . See error

### Expected behavior

The pass entry unlock

### Device information

- Device: Huawai P8 lite 2017
- OS: Last EMUI version
- App version: 2.0.0.SNAPSHOOT 

### Additional context

I used this turn around : https://github.com/android-password-store/Android-Password-Store/issues/1277#issuecomment-759274302 for the app to reconise my gpg key
the log file as asked [log.txt](https://github.com/android-password-store/Android-Password-Store/files/14742490/log.txt)
can't do openkeychain work with the official app, so I switch to the snapshoot

**Comment by msfjarvis** [comment]
It's a bug with how the app surfaces errors, the issue is that your key uses AEAD which GnuPG does in a non standard way. You'll need to remove it, you can find examples in the issue tracker itself.
