### ISSUE TITLE
Adding new passwords/moving existing ones don't update in git

### ISSUE THREAD

**Issue by hughdavenport** [zeapo/Android-Password-Store#299]
I'm adding new passwords and they don't show up in the git commit (it is empty, just the title). Moving just deletes it. Deleting works as expected.

**Comment by zeapo** [comment]
Hi, thanks for the report. Which version are you using?
This has been fixed in .58 in 824845bf41227c9ee0891f6d0299efe0f067ce00

If it's still not fixed for you, could you provide a way to reproduce this?

**Comment by hughdavenport** [comment]
Yep i got .58 from fdroid. I'll see if i can create a dummy repo and try reproduce

**Comment by zeapo** [comment]
would be great thx.

I will try to reproduce it too :)

**Comment by qv1x0te** [comment]
I’m having the same problem, version 1.2.0.58 from Google Play

**Comment by Aventura5** [comment]
I have the same problem, 1.2.0.58 from F-Droid. I tried deleting and re-cloning the repo but no luck. It commits and syncs but the commit is empty.

**Comment by zeapo** [comment]
:(

I will try to reproduce it this weekend.

Thanks

**Comment by jayme-github** [comment]
Same here with .59 from F-Droid.

**Comment by zeapo** [comment]
Looks like it has been introduced in 58...

**Comment by jayme-github** [comment]
> Looks like it has been introduced in 58...

Confirmed. Reverting to .57 fixes this for me.

**Comment by zeapo** [comment]
fixed, sorry guys, that was a dumb copy/paste 👎
