### ISSUE TITLE
Crash when opening a password: "Max number of dynamic shortcuts exceeded"

### ISSUE THREAD

**Issue by SimenCodes** [zeapo/Android-Password-Store#300]
After one of the recent updates (not sure which one), I noticed it started crashing when opening most (but not all) passwords. Logcat explains it all:

>05-24 20:45:32.639 17911-17911/? E/AndroidRuntime: FATAL EXCEPTION: main
>                                                   Process: com.zeapo.pwdstore, PID: 17911
>                                                   java.lang.IllegalArgumentException: Max number of dynamic shortcuts exceeded
>                                                       at android.os.Parcel.readException(Parcel.java:1688)
>                                                       at android.os.Parcel.readException(Parcel.java:1637)
>                                                       at android.content.pm.IShortcutService$Stub$Proxy.addDynamicShortcuts(IShortcutService.java:430)
>                                                       at android.content.pm.ShortcutManager.addDynamicShortcuts(ShortcutManager.java:560)
>                                                       at com.zeapo.pwdstore.PasswordStore.decryptPassword(PasswordStore.java:412)
>                                                       at com.zeapo.pwdstore.PasswordFragment$2.onFragmentInteraction(PasswordFragment.java:120)
>                                                       at com.zeapo.pwdstore.utils.PasswordRecyclerAdapter$2.onClick(PasswordRecyclerAdapter.java:72)
>                                                       at android.view.View.performClick(View.java:5637)
>                                                       at android.view.View$PerformClick.run(View.java:22429)
>                                                       at android.os.Handler.handleCallback(Handler.java:751)
>                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                       at android.os.Looper.loop(Looper.java:154)
>                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
>                                                       at java.lang.reflect.Method.invoke(Native Method)
>                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
>                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
>05-24 20:45:32.641 3772-6282/? W/ActivityManager:   Force finishing activity com.zeapo.pwdstore/.PasswordStore`

Device: Nexus 6P, stock Android 7.1, Pixel Launcher

**Comment by regagain** [comment]
Just wanted to chime in to say that I'm facing the same issue. It started occurring a couple of days ago.

Device: Nexus 6P, Copperhead Android 7.1.2

**Comment by zeapo** [comment]
Hi, this was introduced in the latest version. I will roll a fix ASAP.

Thanks for reporting!

**Comment by zeapo** [comment]
fixed in 0043c82b23fcc803807b7c8ade38c3757247a208
