### ISSUE TITLE
[BUG] No keys are provided to decrypt a file located in subdirectories that contain their own .gpg-id.

### ISSUE THREAD

**Issue by OlehKopeykin** [zeapo/Android-Password-Store#3005]
### Describe the bug

When decrypting a file located in subdirectories that have their own .gpg-id, the APS fails to obtain the appropriate PGP identifiers.

### Case 1: Decrypting a file within APS.

1. Download the [pass-test](https://github.com/android-password-store/pass-test/tree/main) repository to APS.
1. Add the public key [john@doe.org.pub](https://github.com/android-password-store/pass-test/blob/main/john%40doe.org.pub) (fingerprint 36A07AF3971BCD932FB3D4DFB950AE2813841585) to the Key Manager.
1. Add the secret key [john@doe.org.sec](https://github.com/android-password-store/pass-test/blob/main/john%40doe.org.sec) (fingerprint 36A07AF3971BCD932FB3D4DFB950AE2813841585) to the Key Manager.
1. Open the file  _subdir_with_fingerprint/test_with_fingerprint_.
1. Enter the passphrase _12345678_.
1. APS returns an error message saying "Passphrase is invalid" and prompts you to try again.

APS catches the following exception and logs it:

```
2024-04-17 09:40:39.142  6757-6757  DecryptActivity         app.passwordstore.debug              E  NoKeysProvidedException
    at app.passwordstore.crypto.PGPainlessCryptoHandler.decrypt-iWd_AH8(PGPainlessCryptoHandler.kt:52)
    at app.passwordstore.data.crypto.CryptoRepository.decryptPgp-iWd_AH8(CryptoRepository.kt:62)
    at app.passwordstore.data.crypto.CryptoRepository.access$decryptPgp-iWd_AH8(CryptoRepository.kt:26)
    at app.passwordstore.data.crypto.CryptoRepository$decrypt$2.invokeSuspend(CryptoRepository.kt:46)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
```

### Case 2: Decrypting within autofilling

1. Download the [pass-test](https://github.com/android-password-store/pass-test/tree/main) repository to the APS.
1. Add the public key [john@doe.org.pub](https://github.com/android-password-store/pass-test/blob/main/john%40doe.org.pub) (fingerprint 36A07AF3971BCD932FB3D4DFB950AE2813841585) to the Key Manager.
1. Add the secret key [john@doe.org.sec](https://github.com/android-password-store/pass-test/blob/main/john%40doe.org.sec) (fingerprint 36A07AF3971BCD932FB3D4DFB950AE2813841585) to the Key Manager.
1. Open a Login/Pass form.
1. Choose Autofill.
1. Find a file _subdir_with_fingerprint/test_with_fingerprint_.
1. Enter passphrase _12345678_
1. APS return empty string as pass

The method [repository.decrypt](https://github.com/android-password-store/Android-Password-Store/blob/0d7d6eae79dc00500e0988d23094ddaa0d407e07/app/src/main/java/app/passwordstore/ui/autofill/AutofillDecryptActivity.kt#L173) returns a NoKeysProvidedException, but this error is not being handled by APS and is not visible in the log.

### Expected behavior

When decrypting a file located in subdirectories that have their own .gpg-id, the APS obtains the appropriate PGP identifiers and decrypts the file.

### How to solve the issue
1. Improve the [DecryptActivity.kt](https://github.com/android-password-store/Android-Password-Store/blob/87738477be87afb639509f5ebdf5da979ba0bd04/app/src/main/java/app/passwordstore/ui/crypto/DecryptActivity.kt) file by adding the path to the subdirectory that contains the encrypted file as a parameter to the "getPGPIdentifiers" method.
1. Improve the [AutofillDecryptActivity.kt](https://github.com/android-password-store/Android-Password-Store/blob/0d7d6eae79dc00500e0988d23094ddaa0d407e07/app/src/main/java/app/passwordstore/ui/autofill/AutofillDecryptActivity.kt) file by obtaining the PGP identifiers in the "decrypt" method by calling "getPGPIdentifiers" with the path to the subdirectory that contains the encrypted file, and passing them as parameters to all subsequent methods that require them.

### Device information

- Device: Xiaomi Mi 10T
- OS: Android S
- App version: 2.0.0, branch develop, commit [8f68b8730f0443f342062a648bd6b06c33392016](https://github.com/android-password-store/Android-Password-Store/commit/8f68b8730f0443f342062a648bd6b06c33392016)

**Comment by OlehKopeykin** [comment]
I have fixed the bug as described above and I am ready to submit a pull request.

**Comment by msfjarvis** [comment]
Thanks for the detailed bug report! Your fix looks reasonable, please send in the PR.
