### ISSUE TITLE
[BUG] password required for repository

### ISSUE THREAD

**Issue by just-walk** [zeapo/Android-Password-Store#3018]
### Describe the bug

When syncing my repo, I used to be able to just use biometric authentication and git would sync to my repo. For the last several months, I've gotten a prompt for a repo password that I have no idea about.

### Steps to reproduce

1. Go to main screen
2. Scroll down to refresh (synchronize) the repo
3. Use biometric for authentication
4. Box with message "Please provide the password for this repository
5. Error message "An error occurred during a Git operation: Problem getting private key from com.zeapo.pwdstore.git.sshj.SshKey@KeystoreWrappedEd25519KeyProvider@4b5a95c

### Expected behavior

I would expect for this dialog to not exist. Use of the ssh key has already been authenticated biometrically, and the gpg key authentication has been checked.

### Device information

- Device: Google Pixel 6a
- OS: Lineage 21 (Android 14)
- App version: 1.13.5

**Comment by msfjarvis** [comment]
Password authentication is invoked as a fallback, so it means your SSH key was unable to be used by the app. If you can attach a log like the issue creation wizard asked you to I can confirm why it happened.

**Comment by just-walk** [comment]
Here's the log:

[log.txt](https://github.com/android-password-store/Android-Password-Store/files/15063917/log.txt)

**Comment by msfjarvis** [comment]
> Here's the log:
> 
> [log.txt](https://github.com/android-password-store/Android-Password-Store/files/15063917/log.txt)

The log indicates an error occurred in the system keystore itself which prevented it from handing off the key to APS. You can try generating a fresh SSH key in the app and it should clear out the broken one.

**Comment by just-walk** [comment]
That worked. Thanks.
