### ISSUE TITLE
Add full path to commit messages 

### ISSUE THREAD

**Issue by jayme-github** [zeapo/Android-Password-Store#302]
Currently just the basename of the password store file is added to the git commit messages:
```
    [ANDROID PwdStore] Add  anotheruser  from store.

    [ANDROID PwdStore] Edit  theuser
```

As this leads to duplicate messages for multiple identical usernames in different directories it would be nice if the commit messages would contain the full path like the ones from "pass" do:
```
    Add given password for tests/Linux/theuser to store
```

**Comment by zidhuss** [comment]
Added in #455.
