### ISSUE TITLE
email validator is very strict

### ISSUE THREAD

**Issue by jayme-github** [zeapo/Android-Password-Store#303]
I just use "user@host" style (which is a completely valid mail domain in local context) mail addresses for my pass repos as I just want to be able to distinguish the host/device that introduced the change. The current email validation regex is currently very harsh and does not accept that.

I suggest https://davidcel.is/posts/stop-validating-email-addresses-with-regex/ - makes life pretty easy and should not do any harm for this use case.

**Comment by zeapo** [comment]
indeed, fixed in 9b646222ce942d6044575623181e68ae9b9a9569
