### ISSUE TITLE
 [FEATURE] Support Pass-file

### ISSUE THREAD

**Issue by toure00** [zeapo/Android-Password-Store#3032]
### Is your feature request related to a problem? Please describe.

Currently, the Pass application is primarily used for managing passwords in text format, lacking support for file encryption and decryption. Users may need to securely store and retrieve files, such as text files, certificates, etc. Using the same secure encryption mechanism provided by pass would be extremely convenient.

### Describe the solution you'd like

I wish to add pass-file functionality, which allows users to encrypt and decrypt specified files within the pass repository.

### Describe alternatives you've considered

If you do not intend to add this feature, could there be a way to hide encrypted files added with pass-file from the interface? Currently, when I click on an encrypted file, especially if the file size is a few MB, there is a chance that the application might freeze.

**Comment by msfjarvis** [comment]
I'm not interested in support for arbitrary files, and since all encrypted files "look" the same from outside regardless of their contents there is no way for APS to hide them.
