### ISSUE TITLE
[FEATURE] Recognise 'Vanadium' as browser

### ISSUE THREAD

**Issue by josefscript** [zeapo/Android-Password-Store#3033]
### Is your feature request related to a problem? Please describe.

Password store does not recognise GrapheneOs's standard browser Vanadium as browser, so when searching for a password the search term will always be the app's name and not the web address. 

### Describe the solution you'd like

When using Vanadium the search term should be the web address and not the app's name 'Vanadium'. 

### Describe alternatives you've considered

None so far. 

### Additional context

I think password store and GrapheneOs attract the same users: people who care about security. This implies that they work seamlessly together.

**Comment by msfjarvis** [comment]
https://github.com/android-password-store/Android-Password-Store/issues/1631#issuecomment-1332161606

It's already supported.
