### ISSUE TITLE
Doesn't launch OpenKeychain

### ISSUE THREAD

**Issue by wb9688** [zeapo/Android-Password-Store#304]
Sometimes it doesn't launch OpenKeychain, it doesn't even say "Authentication Required". It'll only start working again after a reboot of my device, which is pretty annoying.

**Comment by zeapo** [comment]
Is this issue still happening with the current version of the app?

**Comment by wb9688** [comment]
I forgot about this issue, but it was working again after a reboot.

**Comment by zeapo** [comment]
Thanks for the info
