### ISSUE TITLE
Have to enter GPG passcode every time?

### ISSUE THREAD

**Issue by dsmaynard** [zeapo/Android-Password-Store#305]
Whenever I select an autofill password in chrome, the password store prompts me to enter my gpg password to decrypt the password. Is this normal behavior, or is there a way to turn this off? I'd rather not have to constantly enter my GPG password all the time, as this sort of defeats the purpose of autofill and is really not very secure.

Thanks!

**Comment by wongma7** [comment]
this is openkeychain's responsibility, iirc there is now a dropdown menu under the password window that says something like 'remember for 5 minutes/until screen lock'

**Comment by zeapo** [comment]
There should be a dropdown that asks how long you want to remember the password. The default is "until the screens shuts down", there is "1 hour" and "1 day". There is no option for remembering "forever".

**Comment by dsmaynard** [comment]
OK-- is it possible to use a different openPGP provider besides openkeychain?

**Comment by zeapo** [comment]
no, only OpenKeychain is supported.

**Comment by mittwinter** [comment]
Actually, you can configure OpenKeychain to show an option to remember password forever: In OpenKeychain, go to Settings, Passwords and PINs, Customize 'Remember' choices. There you can configure up to 3 choices for timespans, including "forever".
