### ISSUE TITLE
[BUG] How to install on android 13

### ISSUE THREAD

**Issue by andrewufrank** [zeapo/Android-Password-Store#3054]
### Describe the bug

I cannot find it in the playstore on my new moto 13 with android 13; I can see it on my old moto g5 with android 8. should i install it from f-droid? 
thank you for clarification! andrew

### Steps to reproduce

open playstore, type search 'password store' - 
nothing found (works on other phone with older android)

### Expected behavior

find password store in playstore

### Device information

- Device: [e.g. Google Pixel 2]  moto g13
- OS: [e.g. Android R] android 13
- App version: [e.g. 1.13.5] not installed yet!

**Comment by msfjarvis** [comment]
Please use the discussions section for questions. You need the snapshot builds from here https://docs.passwordstore.app/docs/users/release-channels/

**Comment by andrewufrank** [comment]
thank you for the information, i will try, but I would recommend, that you add some suggestions on the home page (both, about what to do if the playstore does not show the app and on the snapshots, where the text on the home pages i not suggest it for new users. - 
thank you - i hope to use it on my phone. it is attractive to have the same system on the desktop and the mobile!
andrew

**Comment by sebastianrasor** [comment]
> Please use the discussions section for questions. You need the snapshot builds from here https://docs.passwordstore.app/docs/users/release-channels/

@msfjarvis Is there any way that you could push a new stable release to the play store that can run on Android 13? The security policy on my phone prevents sideloading apps, so I can't just get on the snapshot. In addition, I'm pretty sure the snapshot is unsuitable for my situation anyways, as I use Yubikey for both GPG and SSH. In the past I know this has worked with this app, however from what I can tell this no longer works in the 2.0 snapshots. That's a different issue though, I'd just really like to be able to actually use the app on my phone.

**Comment by msfjarvis** [comment]
> > Please use the discussions section for questions. You need the snapshot builds from here [docs.passwordstore.app/docs/users/release-channels](https://docs.passwordstore.app/docs/users/release-channels/)
> 
> @msfjarvis Is there any way that you could push a new stable release to the play store that can run on Android 13?

There is not. If I publish a new build to Google Play it will at minimum require removing support for external storage which will break the app completely for users who get automatically updated by Play Store.
