### ISSUE TITLE
[FEATURE] Use a monospace font for displaying passwords

### ISSUE THREAD

**Issue by raxod502** [zeapo/Android-Password-Store#3066]
### Is your feature request related to a problem? Please describe.

It's probably self-evident what the problem is here:

![image](https://github.com/android-password-store/Android-Password-Store/assets/6559064/146897c7-8db6-472d-a9e2-2ec915bc9855)

### Describe the solution you'd like

Any monospace font (or really, any font that allows distinguishing between characters like ``` |Il 0O ``''" ```) would be fine.

### Describe alternatives you've considered

Realistically if I need to enter one of these passwords onto another device, I have to either look up my password on something that's not Android-Password-Store, or copy the password from APS into something like Termux and read it from there.

### Additional context

Related to https://github.com/android-password-store/Android-Password-Store/issues/80 which was fixed in 2015, but it looks like some upstream change broke things yet again in the intervening decade.

**Comment by msfjarvis** [comment]
I think I have a rough idea what broke this, I'll get it sorted right away.

**Comment by raxod502** [comment]
The `0/O` characters are still a bit similar, but this is already 10x better, thank you!

![image](https://github.com/android-password-store/Android-Password-Store/assets/6559064/acafb001-cf71-4aa2-a4d8-7ba9ee7a252a)

**Comment by msfjarvis** [comment]
> The `0/O` characters are still a bit similar, but this is already 10x better, thank you!
> 
> ![image](https://github.com/android-password-store/Android-Password-Store/assets/6559064/acafb001-cf71-4aa2-a4d8-7ba9ee7a252a)
> 

Unfortunately that's dependent on the system monospace typeface, but I can look into bundling something better later today.

**Comment by msfjarvis** [comment]
Switched over to JetBrainsMono (https://github.com/android-password-store/Android-Password-Store/commit/4939153e8150) since the creators have taken extra care to resolve the problem of ambiguous characters, not too thrilled about the extra 200 kilobytes but it's acceptable for now.

**Comment by raxod502** [comment]
Beautiful and completely unambiguous now!

![PXL_20240616_035444053](https://github.com/android-password-store/Android-Password-Store/assets/6559064/98b14a54-fca2-4196-88c6-045be64715a8)
