### ISSUE TITLE
[FEATURE] Support for pass coffin

### ISSUE THREAD

**Issue by pjhfggij** [zeapo/Android-Password-Store#3068]
### Is your feature request related to a problem? Please describe.

On desktop I use [pass-coffin](https://github.com/ayushnix/pass-coffin) to hide file names within a single tar archive. It would be useful if Android-password-store supported that as well.

### Describe the solution you'd like

I think the best thing to do would be to read contents of the coffin.tar.gpg file and store metadata in app's private storage. Then only open that file in the coffin.tar.gpg that user needs when prompted to fill in a password.

### Describe alternatives you've considered

termux, but couldn't integrate it

**Comment by msfjarvis** [comment]
I can't take on the maintenance burden of such a feature.

**Comment by pjhfggij** [comment]
no worries, I will try to do it from termux then. pass coffin depends on systemd-run, which probably doesn't have an equivalent on termux and will need to figure out how to use okc-gpg, so there will be some complexity, but it may be doable.
