### ISSUE TITLE
Push creates empty commit

### ISSUE THREAD

**Issue by Kaitsh** [zeapo/Android-Password-Store#308]
Hi,

if I push to my private repository on github, Password Store creates only an empty commit but pushes no data. I'm using version 1.2.0.59 from PlayStore on my HTC 10.

![image](https://cloud.githubusercontent.com/assets/8351869/26746876/a5655446-47f2-11e7-97c1-6e3e5d912236.png)

Also, if I pull from github, the repository on my smartphone doesn't get updated. The only way it gets updated is delete everything and clone the github repo.

Maybe you have an idea how I can solve this issue.

**Comment by zeapo** [comment]
Hi,

This was a bug introduced in  58, fixed in 60.

In 61 (tomorrow) the non committed passwords will be handled without any
action from the user.

**Comment by Kaitsh** [comment]
alright, thank you very much! 😄
