### ISSUE TITLE
[FEATURE] Allow cleartext HTTP traffic when cloning repositories

### ISSUE THREAD

**Issue by RJSent** [zeapo/Android-Password-Store#3087]
### Is your feature request related to a problem? Please describe.

I host my password store on a server local to my network and cannot clone the repository over HTTP as "Cleartext HTTP traffic is not permitted". As the server is local and the passwords are already encrypted I don't need to worry about a man-in-the-middle, so setting up HTTPS is overkill.

### Describe the solution you'd like

Either a) HTTP traffic is universally permitted or b) A toggle is present that, when enabled, allows HTTP traffic.

### Describe alternatives you've considered

The solutions discussed at https://stackoverflow.com/questions/45940861 are app-level changes. There doesn't seem to be a device-level setting on my end.

I considered cloning over SSH however my machines use gpg-agent to use a gpg key stored on a YubiKey for SSH authentication, which does not appear to be supported on Android. I also would like to minimize the amount of control my phone has over my server.

### Additional context

Version 1.13.5

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
