### ISSUE TITLE
Remote pull or push fail silently

### ISSUE THREAD

**Issue by bignose-debian** [zeapo/Android-Password-Store#309]
The remote operations – Synchronise, Pull Push – are failing silently. When I select the option from the menu, it registers the tap, but apparently does nothing else.

This behaviour is on version 1.2.0.61.

Version 1.2.0.60 did not have this behaviour (the remote operations correctly pushed and/or pulled the remote repository).

**Comment by zeapo** [comment]
Must be authentication not showing. Will fix it promptly.

**Comment by zeapo** [comment]
fixed

**Comment by bignose-debian** [comment]
> fixed

This doesn't say which commit fixes the issue. When closing an issue, can you please always make sure there is a link in the issue that leads to the commit fixing the issue?
