### ISSUE TITLE
[FEATURE] Support ChromeOS

### ISSUE THREAD

**Issue by nexus-uw** [zeapo/Android-Password-Store#3092]
### Is your feature request related to a problem? Please describe.

The application is not available on the Play Store for Chrome OS.

![Screenshot 2024-06-12 21 06 01](https://github.com/android-password-store/Android-Password-Store/assets/3188890/7d4d2d76-5ca6-4d6f-9256-4775bba85567)

my current device info
>Google Chrome: Version 124.0.6367.95 (Official Build)  (64-bit)
Platform: 15823.40.0 (Official Build) stable-channel atlas
Channel: stable-channel
Firmware Version: Google_Atlas.11827.198.0
ARC Enabled: true
ARC: 11755342
Enterprise Enrolled: false
Developer Mode: false

### Describe the solution you'd like

Application to be available through the PlayStore for ChromeOS

### Describe alternatives you've considered

I have used the linux environment to have access to Pass on my chromebook but it is pretty involved for a relatively simple program

### Additional context

restarting issue from https://github.com/android-password-store/Android-Password-Store/issues/1361

it left off 2years ago trying to run a custom built APK on a Chromebook to verify if the proposed fix would work

**Comment by msfjarvis** [comment]
This is still missing information on whether side loading the app works.

**Comment by msfjarvis** [comment]
Closing as stale.
