### ISSUE TITLE
[BUG] Autofill keeps reverting to off

### ISSUE THREAD

**Issue by bagnaram** [zeapo/Android-Password-Store#3102]
### Describe the bug

After initially enabling Autofill it launches the autofill service selector. When selecting _Password Store_ it brings me back to the settings -> autofill section with it toggled off again.

I can sometimes get autofill to work by selecting _None_ and then selecting _Password Store_ again. However this is short lived because it seems to disable itself again after a while.

### Steps to reproduce

1. When selecting _Password Store_ it brings me back to the settings -> autofill section with it toggled off again.

### Expected behavior

Autofill should stay enabled when selected

### Device information

- Device: unihertz Jelly Star
- OS: Android 13
- App version: 1.13.5

**Comment by msfjarvis** [comment]
I can't reproduce on the latest development builds, can you please test with the snapshot builds from [here](https://docs.passwordstore.app/docs/users/release-channels/) and see if you still face the issue?

**Comment by bagnaram** [comment]
I didn't realize the v2 builds is diverging from the current FDroid version. I tested the new version on a blank store since I use hardware tokens and I see the same behavior

**Comment by msfjarvis** [comment]
Do other autofill providers exhibit the same issue? Nobody else has reported this problem in the past 5 years so I'm inclined to place blame on unihertz here.

**Comment by bagnaram** [comment]
Something weird happened. The issue seems to have cleared up after installing and removing the 2.0 release of the program
