### ISSUE TITLE
Outdated play store app version

### ISSUE THREAD

**Issue by theaino** [zeapo/Android-Password-Store#3106]
I can't install the app through play store - it says it's outdated. I'm running android 14

**Comment by msfjarvis** [comment]
Duplicate of #2927, #2764, #2669, #2663, https://github.com/android-password-store/Android-Password-Store/issues/2644, https://github.com/android-password-store/Android-Password-Store/issues/2587, https://github.com/android-password-store/Android-Password-Store/issues/2553, https://github.com/android-password-store/Android-Password-Store/issues/2533 and https://github.com/android-password-store/Android-Password-Store/issues/2417.

**Comment by msfjarvis** [comment]
Next time you file an issue, please search the issue tracker and actually follow the issue template that's in place.
