### ISSUE TITLE
unpack-objects abnormal exit

### ISSUE THREAD

**Issue by jfjallid** [zeapo/Android-Password-Store#312]
When I try to push to my repo I get the following error:
`error occurred during unpacking on the remote end: unpack-objects abnormal exit`
Pull works fine. I can push and pull without a problem to the same repo from my computer but not from my phone using Android Password Store

Android version 6.0
Android Pasword Store version: 1.2.0.56

**Comment by andresmr** [comment]
I'm not sure if it's the same problem, but I couldn't push until I allowed permission manually and then try again. Now works fine

**Comment by jfjallid** [comment]
@andresmr What permission are you referring to?

**Comment by zeapo** [comment]
It does look like a permission issue, however my first thought when I've read the error message is that it's a server issue. Does the user you're authenticating as have the right to alter the git directory?

**Comment by jfjallid** [comment]
At a first glance it looked as my user had correct permissions but after some digging I found that a few subdirs of the objects directory had changed ownership. After I changed them back to the correct ownership it works again. Thanks for your input!
