### ISSUE TITLE
ssh sync error: Invalid packet line header [32

### ISSUE THREAD

**Issue by kkkorica** [zeapo/Android-Password-Store#313]
Hello,

I'm using APS minor version 64 (latest at the moment). Whe I try to synchronize from my PC over ssh I get following error

> Invalid packet line header: [32

PC is running Debian Stretch. Auth done by passwordless ssh key. Tried with new empty bare repo - no luck. It seems the problem is with jgit and ssh connection.

**Comment by zeapo** [comment]
Hi,

Can you double check your git url?

**Comment by kkkorica** [comment]
I am sorry, this was my mistake. .bashrc generated some output even in uninteractive shell so jgit failed to parse it.
