### ISSUE TITLE
[BUG] autofill-decrypt: wrong passphrase input remains uncaught & passphrase caching attempt even when disabled in settings

### ISSUE THREAD

**Issue by agrahn** [zeapo/Android-Password-Store#3131]
### Describe the bug

Two autofill-related issues:

1. https://github.com/android-password-store/Android-Password-Store/blob/a064116e8027997fe8f3bb7f19778dd1bebbe441/app/src/main/java/app/passwordstore/ui/autofill/AutofillDecryptActivity.kt#L216 A wrong passphrase processed in `repository.decrypt(...)` does not end up in the `.onFailure` branch  but goes straight to `.onSuccess` instead.
2. https://github.com/android-password-store/Android-Password-Store/blob/a064116e8027997fe8f3bb7f19778dd1bebbe441/app/src/main/java/app/passwordstore/ui/autofill/AutofillDecryptActivity.kt#L226 Also with passphrase caching *dis*abled, caching is attempted which leads to `android.security.keystore.UserNotAuthenticatedException: User not authenticated` error.

It seems that the issues can be worked around by the following changes:

```
diff --git a/app/src/main/java/app/passwordstore/ui/autofill/AutofillDecryptActivity.kt b/app/src/main/java/app/passwordstore/ui/autofill/AutofillDecryptActivity.kt
index c6441283..b0f2ec79 100644
--- a/app/src/main/java/app/passwordstore/ui/autofill/AutofillDecryptActivity.kt
+++ b/app/src/main/java/app/passwordstore/ui/autofill/AutofillDecryptActivity.kt
@@ -213,7 +213,8 @@ class AutofillDecryptActivity : BasePGPActivity() {
         runCatching {
             withContext(dispatcherProvider.io()) {
               val outputStream = ByteArrayOutputStream()
-              repository.decrypt(password, identifiers, encryptedInput, outputStream)
+              if (!repository.decrypt(password, identifiers, encryptedInput, outputStream).isOk)
+                throw Exception("Decryption failed")
               outputStream
             }
           }
@@ -223,7 +224,8 @@ class AutofillDecryptActivity : BasePGPActivity() {
           }
           .onSuccess { result ->
             return runCatching {
-                passphraseCache.cachePassphrase(this, identifiers.first(), password)
+                if (features.isEnabled(EnablePGPPassphraseCache))
+                  passphraseCache.cachePassphrase(this, identifiers.first(), password)
                 val entry = passwordEntryFactory.create(result.toByteArray())
                 AutofillPreferences.credentialsFromStoreEntry(this, file, entry, directoryStructure)
               }
```

### Steps to reproduce

Steps to reproduce the behavior (with device connected to USB & USB debugging enabled):

1. Make sure that passphrase caching is *dis*-abled in the PGP settings and that Autofill is enabled.
2. Force-stop APS  
3. Go to a log-in site known to APS
4. Start logging  
5. Tap the suggested autofill option for this site and enter a wrong passphrase in the Password dialog --> "Decryption failed" should be written into the terminal but does not show up. Further down the log, UserNotAuthenticatedException is thrown.

### Expected behavior

Entering a correct passphrase should auto-fill the input fields when caching is *dis*abled.

### Device information

Motorola moto g82 5G, Android 13, Build No T1ISUS33.1-124-6-8-3

**Comment by msfjarvis** [comment]
I've fixed this and refactored the CryptoRepository APIs to make such a mistake harder to re-introduce later: https://msfjarvis.dev/aps/06fbe6cf9c1b
