### ISSUE TITLE
[FEATURE] Display all OTP in a list view

### ISSUE THREAD

**Issue by sarg** [zeapo/Android-Password-Store#3140]
### Is your feature request related to a problem? Please describe.

While APS supports OTP, it's a bit frustrating to use as I have to navigate through the folder structure to find the required entry. 

### Describe the solution you'd like

The app could present all found OTPs in a list view, similar to various OTP apps (e.g. andOTP which I currently use). 

### Describe alternatives you've considered

The alternative is to use a separate OTP app and export the data from `pass` in a compatible format. E.g.
```
pass grep -l otpauth | grep -v '(standard input)' | sed -e 's/\x1b\[[0-9;]*m//g;s/://' | xargs -n1 pass otp uri -q
```

**Comment by msfjarvis** [comment]
That would require the app to decrypt every single entry in your store which will be significantly slower than searching or navigating to the required entry.

I have plans to re-do the whole password list UI in the future which might introduce an option to mark entries as favorites that will be displayed separately and be faster to access.
