### ISSUE TITLE
[BUG] Accepts a PGP public key

### ISSUE THREAD

**Issue by sewnie** [zeapo/Android-Password-Store#3171]
### Describe the bug

When importing a GPG key, you can import a public one, which doesn't work when decrypting and just prompts 'Invalid password'

### Steps to reproduce

1. Import public GPG key
2. Decrypt entry
3. 'Invalid password'

### Expected behavior

Errors out when given a public GPG key, as it expects a private key.

### Device information

Yes, i am dumb enough to do this.

**Comment by msfjarvis** [comment]
The error is incorrect but accepting a public key is intentional, it allows people to share password stores between themselves and having shared secrets without requiring the secret key of the other individual.
