### ISSUE TITLE
[FEATURE] Handle AEAD  

### ISSUE THREAD

**Issue by naisanzaa** [zeapo/Android-Password-Store#3180]
### Is your feature request related to a problem? Please describe.

- MacOS app doesn't have issues with AEAD
- iOS app doesn't have issues with AEAD

### Describe the solution you'd like

Handle AEAD in android-password-store app

### Describe alternatives you've considered

Can't use android-password-store

### Additional context

GPG key was made in 2015.

**Comment by msfjarvis** [comment]
https://github.com/android-password-store/Android-Password-Store/pull/2218#issuecomment-1296911526
