### ISSUE TITLE
[BUG] APS crashes when trying to decrypt a password with imported key

### ISSUE THREAD

**Issue by strikesmeasodd** [zeapo/Android-Password-Store#3227]
### Describe the bug

After importing my key through the key manager,  when I try to decrypt a password it says "Found .gpg-id, but it contains an invalid key ID, fingerprint or user ID."

I followed the instructions [here](https://docs.passwordstore.app/docs/users/invalid-gpg-key-id) and deleted the .gpg-id file, but now the app crashes every time I try to decrypt a password.

The key was exported from my laptop with a working password store using the command [given in the wiki](https://github.com/android-password-store/Android-Password-Store/wiki/Your-GPG-key)

I'm using the latest snapshot build APS-freeRelease-2.0.0-SNAPSHOT.apk . I previously used the F-Droid release with no problems.

### Steps to reproduce

1. Import key with key manager
2. Delete .gpg-id
3. Try to decrypt a password
4. App crashes

### Expected behavior

Password is decrypted 

### Device information

- Device: Samsung Galaxy A15
- OS: Android 14
- App version: Free release 2.0.0 snapshot from revision [341c5fa](https://github.com/android-password-store/Android-Password-Store/commit/341c5faac1a431d3345cb1b8cfc2e18dc724e849)

**Comment by msfjarvis** [comment]
The issue template asks to attach a log for bug reports: https://docs.passwordstore.app/docs/users/reporting-bugs

**Comment by strikesmeasodd** [comment]
[log.txt](https://github.com/user-attachments/files/17096389/log.txt)

**Comment by msfjarvis** [comment]
Your `.gpg-id` file is still empty, v2 doesn't yet try to automatically populate the `.gpg-id` so the advice on the docs is stale. Sorry about that, I'll add a note there soon.

In the mean time you can add your full key ID manually using a text editor or via `pass init keyid` on a Linux machine. Just putting in the email associated with the key as the key ID should do the job.

**Comment by strikesmeasodd** [comment]
I deleted and re-cloned the repo from my laptop, to restore the .gpg-id with the key's name. Now the app stopped crashing when I try to decrypt , but it's back to saying "Found .gpg-id, but it contains an invalid key ID, fingerprint or user ID."

The key doesn't have an associated email address, only a name. Could that be what's causing the problem? 

Thank you

**Comment by Deniero** [comment]
I have the same problem. I was using an older 2.0.0 Build, when I suddenly got the error message "Found .gpg-id, but it contains an invalid key ID, fingerprint or user ID." whenever I try to open a password file.
I did not change anything. I tried the newest build, its still not working.
Only the released version in the play store works.

**Comment by msfjarvis** [comment]
https://github.com/android-password-store/Android-Password-Store/actions/runs/11052077025

Try the new snapshot build once this CI run has completed

**Comment by Deniero** [comment]
I installed this new snapshot. I sadly still get this error.
Shown in this log file: 
[log_output.txt](https://github.com/user-attachments/files/17163878/log_output.txt)

Thank you!

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
