### ISSUE TITLE
[BUG] Selecting text from extra content window

### ISSUE THREAD

**Issue by FloatingLizard** [zeapo/Android-Password-Store#3230]
### Describe the bug

I have several entries that have content in the Extra content and if I need to select a portion of the text, it never selects requested text and selects text above and then when trying to select the correct portion and never does and sometimes it copies the selected text and paste new content that was never intended. 

### Steps to reproduce

1. Go to open the gpg file
2. Click on the file needed 

### Expected behavior

To be able to select the text. 

### Device information

- Device: Pixel 8 Pro
- OS: Graphene Android 14
- App version: 1.13.5

**Comment by msfjarvis** [comment]
Please install the snapshot build and see if you can reproduce it there: https://docs.passwordstore.app/docs/users/release-channels

**Comment by FloatingLizard** [comment]
Can it be install without loosing my files?

On September 23, 2024 12:46:18 PM GMT+02:00, Harsh Shandilya ***@***.***> wrote:
>Please install the snapshot build and see if you can reproduce it there: https://docs.passwordstore.app/docs/users/release-channels
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/android-password-store/Android-Password-Store/issues/3230#issuecomment-2367852495
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Saves Yourselves

**Comment by msfjarvis** [comment]
> Can it be install without loosing my files?

Yes, it's a separate app with a different package ID.

**Comment by FloatingLizard** [comment]
> > Can it be install without loosing my files?
> 
> Yes, it's a separate app with a different package ID.

OK

**Comment by FloatingLizard** [comment]
It does work..  Able to select and copy 

On September 23, 2024 2:57:41 PM GMT+02:00, Harsh Shandilya ***@***.***> wrote:
>> Can it be install without loosing my files?
>
>Yes, it's a separate app with a different package ID.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/android-password-store/Android-Password-Store/issues/3230#issuecomment-2368148604
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Saves Yourselves

**Comment by FloatingLizard** [comment]
It does work.  Now when I delete the pp and it does delete the repo it created as well and the secret key is gone too, right?

**Comment by msfjarvis** [comment]
Yes, deleting the app does delete its data as well.

Since this works on the snapshots there's nothing to be done here, if you want to obtain the bugfix then you'll have to use those builds.

**Comment by FloatingLizard** [comment]
One last question is there a difference between the version I have and the proposed one?

**Comment by FloatingLizard** [comment]
OK, I cloned a repo and unfortunately I am unable to see the content in the extra content window.  I have to click edit to view the content.

**Comment by msfjarvis** [comment]
> One last question is there a difference between the version I have and the proposed one?

https://github.com/android-password-store/Android-Password-Store/blob/develop/CHANGELOG.md#unreleased

> OK, I cloned a repo and unfortunately I am unable to see the content in the extra content window. I have to click edit to view the content.

Can you create a sample of the text that renders incorrectly? Everything works fine on my end and without seeing it I can't say what's going wrong.

**Comment by FloatingLizard** [comment]
I think a text that takes more than the extra content does not include more than 5 lines.  I will provide an example when I get time to do this.
