### ISSUE TITLE
[BUG] biometric authentication seems to crash

### ISSUE THREAD

**Issue by kent-rasmussen** [zeapo/Android-Password-Store#3236]
### Describe the bug

when using biometric authentication I see three results:
1. it returns to the main screen (not decoding the password I asked for, I think this is when I'm asking for a password, log1.txt)
2. it moves to another "Authenticate" screen (I think when syncing my repo, and gpg is not the only option, log2.txt)
3. it works as expected (at least for biometric on open)
[log2.txt](https://github.com/user-attachments/files/17138997/log2.txt)
[log1.txt](https://github.com/user-attachments/files/17138998/log1.txt)

### Steps to reproduce

Open with biometric on open, click on biomentric to open.
1a. scroll to a password I want to decrypt, click on it.
1b. respond to the biometric request, it returns to the first screen.
2a. ask to sync with gitlab
2b. respond to biometric request, it returns a password request

### Expected behavior

the biomentric should authenticate and show the requested password (1) or sync the repository (2)

### Device information

- Device: Moto G power 5G
- OS: Android 13
- App version: 2.0.0 (17 sept)

### Additional context

One point maybe tangential to this issue, is the UI for password entry. Because the need to put in a password after biometric fails is unexpected, it isn't always clear to me which password it is looking for. Is this my gitlab password, because the gitlab ssh key failed for some reason? or my phone password, because my phone biometric didn't unlock my key? or some other password.
I assume that the two logs above are the same issue, with the biometric not unlocking my gpg key, on the one hand, and my ssh key, on the other. But if it helps to split this into two issues, that's fine with me.

**Comment by kent-rasmussen** [comment]
this feels similar to a bug that I reported [here](https://github.com/android-password-store/Android-Password-Store/issues/2726), but failed to follow up on in a timely manner; Sorry about that.
At that point (of 2.0.0) I was getting fails on biometrics, but if I put in my phone password, it worked fine. Now, If I ask for a password to be decrypted and put in my phone password, I get a "Password" request (sorry, not sure what password it is asking about, see "additional context" above). Because this may be another thing, I'll call it case 4, with [log4.txt](https://github.com/user-attachments/files/17139128/log4.txt)

**Comment by kent-rasmussen** [comment]
I just pulled and installed last night's 2.0.0, which produced the same results

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
