### ISSUE TITLE
[BUG] Does not start

### ISSUE THREAD

**Issue by RapidRotator** [zeapo/Android-Password-Store#3237]
### Describe the bug

After installation, I could successfully set up my repo and see my passwords. After closing, I can no longer open the app. When tapped on, it just doesn't open.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to the application drawer
2. Click on the icon for the password-app
3. Notice it won't start

### Expected behavior

When clicking the app, open it.

### Device information

- Device: Fairphone 4
- OS: Calyxos 5.11.1
- App version: 1.13.5

**Comment by msfjarvis** [comment]
#2802
