### ISSUE TITLE
1.2.0.66 doesn't actually copy to clipboard

### ISSUE THREAD

**Issue by betsythefc** [zeapo/Android-Password-Store#324]
Model: Sprint Galaxy Note 4
Non-rooted, stock rom

Since upgrading, auto copy, and clicking to copy do not enter the password into the clipboard. I have to edit the password, select it and copy.

**Comment by spidernetlabs** [comment]
Same issue with Moto G5 plus (stock).

**Comment by zeapo** [comment]
Thanks for the report. Did it work on 1.2.0.65?

**Comment by zeapo** [comment]
Fixed by 1046634a3c9d285e37216e328b1a013b5addb159
