### ISSUE TITLE
[BUG] password is not saved (generated or typed)

### ISSUE THREAD

**Issue by kent-rasmussen** [zeapo/Android-Password-Store#3241]
### Describe the bug

generate a password and click save (or save all) icon

### Steps to reproduce

1. generate a password and click save (or save all) icon > screen flickers and returns to previous
2. click on the same password > the field is empty

### Expected behavior

the field should contain the generated or typed password

### Device information

- Device: Moto G power 5G
- OS: Android 13
- App version: 2.0.0 1 Oct 2024

### Additional context

[log.txt](https://github.com/user-attachments/files/17216056/log.txt)

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
