### ISSUE TITLE
[FEATURE] OTP notification

### ISSUE THREAD

**Issue by Vintodrimmer** [zeapo/Android-Password-Store#3249]
### Is your feature request related to a problem? Please describe.

Currently, if there is an OTP code, after auto-filling the main login/password, I have to open APS, find the entry, unlock the DB again, and copy the OTP code, then come back to whatever app is asking for it and paste it.

### Describe the solution you'd like

I want a notification to appear after the password auto-fill if the APS entry contains an OTP field, similar to how it's done in Pass4iOS.
That way, after the main password is filled, I can look at the notification with the OTP code and insert it without having to switch the apps and unlock the password database again to copy the OTP.

### Describe alternatives you've considered

Having OTP copied automatically could also probably work, but this is not a good solution, as the timer might be near 0 at the time OTP is being copied.

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
