### ISSUE TITLE
pass-otp support

### ISSUE THREAD

**Issue by juicetin** [zeapo/Android-Password-Store#326]
Hi,

Would support for the OTP format in pass-otp (e.g. `otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example
`) happen to already be in the works? 
https://github.com/tadfisher/pass-otp#readme

The underlying logic probably wouldn't be hard to implement, though to have the feature integrated nicely (vs. manual file creation/typing out of the parameters in the above format) may require a little bit of extra work with having the 'Add New Password' screen having something like a dropdown near the top to be able to choose between 'password' and 'OTP' or something along those lines.

**Comment by zeapo** [comment]
Absolutely!

Thanks for the idea.

**Comment by maximbaz** [comment]
I wonder if it would make sense to approach this iteratively, first implement generating tokens from already configured OTP accounts, and then separately implement configuring OTP for new accounts. I think it's quite safe to assume that people who know about `pass-otp` have all their accounts already configured, so generating tokens from existing configuration should be a much more requested feature than configuring new accounts. Also, hopefully should be simpler to implement! 🙂

**Comment by c4software** [comment]
Nice idea. Would be really great ! I have it on my desktop, it's would be really great to see the support of otp on the mobile too.

**Comment by polyzen** [comment]
Support included since Jan.

**Comment by erayd** [comment]
@polyzen Not on the Play store it's not. That hasn't been updated since November 19th last year.

Any chance whoever is responsible for the relevant Play account could roll a new release there?

**Comment by polyzen** [comment]
> @polyzen Not on the Play store it's not. That hasn't been updated since November 19th last year.

If you use F-Droid, that's up-to-date.

**Comment by erayd** [comment]
> If you use F-Droid, that's up-to-date.

Thanks - That's good to know :-). The Play store app still needs updating though.

**Comment by AluminumTank** [comment]
Is HOTP support still being worked on?

**Comment by wiktor-k** [comment]
Nope, it you check the Readme you'll see that the project is currently unmaintained.
