### ISSUE TITLE
Show password age 

### ISSUE THREAD

**Issue by chrboe** [zeapo/Android-Password-Store#330]
It would be nice to be able to display the "age" of a password (i.e. days since last change or something). Old passwords (older than 30, 60, 90,... days) could additionally be highlighted in red or a similar alarming color.

**Comment by zeapo** [comment]
Good idea, we can use git commits to know when the file was last updated.

**Comment by chrboe** [comment]
Exactly. It's actually pretty easy, I've written something similar in go before: https://github.com/chrboe/pass-age

**Comment by chrboe** [comment]
And the same thing as a bash one-liner, for inspiration :)
`git ls-files *[^.gpg-id] | while read f; do echo -e "$(git log -1 --format="%ai %ar" -- $f) \t $f"; done | sort -r | cut -d' ' -f4-`
