### ISSUE TITLE
update 1.2.0.66 doesn't copy to clipboard

### ISSUE THREAD

**Issue by hughdavenport** [zeapo/Android-Password-Store#331]
Workaround is to edit, select all then copy, then it stays in clipboard until you copy something else

**Comment by zeapo** [comment]
Fix is in .67, still not available on F-Droid :/

**Comment by hughdavenport** [comment]
Swt, I'm happy to wait for that and use that workaround :)

**Comment by zeapo** [comment]
I'm OK with keeping the issue open so that people see your workaround :)

**Comment by Bridouz** [comment]
Thanks for the workaround. 👍

**Comment by arobase-che** [comment]
Ahah guys 😂

Thanks for the workaround, but i downgrade insteed. That bug makes me experience a very bad time. I hope it will be soon available on F-droid.

I **REALY** enjoy your work 🍪
