### ISSUE TITLE
Import SSH key setting stopped working

### ISSUE THREAD

**Issue by mooninite** [zeapo/Android-Password-Store#332]
With versions higher than 1.2.0.64 the "Import SSH key" option in Settings does not work. Clicking on it results in no file manager being displayed.

Phone: Nexus 5
Android: 6.0.1 - Stock image from Google

**Comment by zeapo** [comment]
Thanks for the report. Just fixed in e6fc3bb177b7d846b52acc1ce8c28bede6898479
