### ISSUE TITLE
Update Clone URL when switching between https:// and ssh://

### ISSUE THREAD

**Issue by anoadragon453** [zeapo/Android-Password-Store#345]
In Server Settings, the clone URL isn't updated until one of the text fields is typed into.

I had filled out the details with ssh:// which it had constructed a URL for, but after selecting https:// and then typing in my password, it complained the URL wasn't correct. Turns out that until I updated one of the fields, only then would the URL update to use https:// instead of ssh://. I then had to type my password again.

URL should be updated when choosing between ssh:// and https:// as well as when typing in a field.

**Comment by zeapo** [comment]
fixed in 70-alpha on alpha PlayStore, coming in 71 to F-Droid

**Comment by anoadragon453** [comment]
Great, thanks very much!
