### ISSUE TITLE
Password not cleared after timeout

### ISSUE THREAD

**Issue by afmayer** [zeapo/Android-Password-Store#351]
I am using version 1.2.0.69 on LineageOS 14.1 with a Yubikey Neo.

I have the "Automatically clear the clipboard after copy" option enabled, but after the timeout expires the clipboard is not cleared and still contains the password.

**Comment by vinieich** [comment]
Hi. I am using stock android version 6.0.1 with a Samsung S5 Mini and have this problem too.

**Comment by zeapo** [comment]
Thanks for reporting.
