### ISSUE TITLE
Internal exception occurred

### ISSUE THREAD

**Issue by sverresto** [zeapo/Android-Password-Store#37]
When pulling from my public accessible gitosis repository, i get

Internal exception occurred
Message from jgit: /
ngit@my.gitserver.no:pass.git:
invalid privatekey: [B@42a4f638

I have tried different private keys and different key sizes created from Irssi connectBot, and openssl. This is with the password store version 1.2-a3 from F-Droid, and the one in google palay give the same error.

**Comment by micressor** [comment]
I had the same issue with password store 1.2.0.15 from f-droid.org.

Did not work:
ssh-keygen -C droid_phone -b 4096 -t rsa -f /tmp/id_rsa_droid

That was my solution:
ssh-keygen -C droid_phone -b 2048 -t rsa -f /tmp/id_rsa_droid

May be there is a problem with big keys?

Thanks.
