### ISSUE TITLE
Push & synchronize fails

### ISSUE THREAD

**Issue by KaaJaryi** [zeapo/Android-Password-Store#370]
Hi,
Push or synchronizing my phone repo to the one on my computer fails systematically. "reason: branch is currently checked out". But the repo on my computer is clean, with nothing to commit…

And of course: Thanks for everything!

**Comment by HorribleGeek** [comment]
Try to delete and create the repo again.

If you have totp enabled then create a new app password and use that to login.

**Comment by zidhuss** [comment]
Feel free to re-open this issue if it's still present in the latest version.
