### ISSUE TITLE
Tapping on "show password" does nothing

### ISSUE THREAD

**Issue by zuglufttier** [zeapo/Android-Password-Store#392]
First of all, thank you for this great app!

I'm using version 1.2.0.75 and the show password button does nothing for me. All the rest is working nicely!

**Comment by sevenmaxis** [comment]
Same here. Also app is not asking master key anymore. I think somehow related to each other.

**Comment by zuglufttier** [comment]
Meanwhile I upgraded to android 8.1 and I cannot replicate this behaviour anymore. I did not reinstall this app.
Holding "show password" will display the password.

**Comment by leem53** [comment]
After installing a system update, I experienced the same problem today. Password store wouldn't ask for the master key and if I tried to show or copy a password it was empty. However all I needed to do to get it working again was opening the OpenKeychain App once.

**Comment by msaitz** [comment]
I've been experiencing this since I started using the app. As the previous comment mentions you have to open openkeychain app beforehand and then the master key prompt will appear.
It's quite annoying as makes the app much less usable.

**Comment by msfjarvis** [comment]
Cause is duplicated with #518, closing this one as solutions have been found over there.
