### ISSUE TITLE
Allow folders and files to be sorted alphabetically

### ISSUE THREAD

**Issue by benlindsay** [zeapo/Android-Password-Store#398]
First, thanks so much for making this app! It's very nice.

The default behavior in pass is to list all folders and files alphabetically, regardless of whether they are folders or files. This app places folders first, then files, and sorts alphabetically within each item type. Would it be possible to either change the behavior to match that of pass, or maybe add an option to toggle both ways of sorting? This would help me, because I have mine set up so that I'll have i.e. a google.com folder with files for multiple profiles stored in the folder, and single files like reddit.com if I just have one profile. I usually can't remember immediately if I have one password or more passwords for a particular website, so it makes more sense for me to have everything alphabetically sorted irrespective of files/folders.

Thanks!

**Comment by erayd** [comment]
If this changes, I'd prefer for there to be an option to keep the current behaviour. I use the same folder structure as the OP, and often navigate directly to the logon I want when it's in a folder (I have <20 folders, but over 300 individual logins). When I know it's not, then I search for it, but searching is a slower action to complete.

**Comment by benlindsay** [comment]
@erayd That's fair, I would be perfectly happy with leaving the current behavior as default, but I would be very grateful if there was an option to toggle between the two sorting methods.
