### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by zeapo** [zeapo/Android-Password-Store#400]
As said on https://github.com/zeapo/Android-Password-Store/commit/cbf8b753b4ba3404a7e7e509f3a061c38eb44a1a. I hoped to get some free time to work on this project... but sadly now, I'd rather spend the little time I have with family and kids, they grow so fast :)

If someone is interested. Please open some PRs fixing bugs, implementing features and so on. If things go well, I'll give you write access. Later one, we'll transfer the project somewhere else. I'll keep the keys to the play store version, and will build / upload the apk.

**Comment by zidhuss** [comment]
I use this app on a daily basis. I'd be interested in maintaining the project.

**Comment by etiago** [comment]
Hi @zeapo,

I just recently started migrating from LastPass to Pass and your app is a must have 😄 therefore I'd be happy to maintain it as well.

There's a first piece of work I'd very much like to do: bring in dependency injection with Dagger2 and things like Butterknife (to remove much of the boilerplate currently in there).

These changes wouldn't mean anything functionally. The app would still do the same. But it would become a lot easier to maintain.

Also... either Kotlin or Java 😄 using both is a bit of a headache.

**Comment by Kirrrr** [comment]
Excuse me guys for disturbing you, but are any news on the subject? Will the project be alive? 

Regards!

**Comment by zidhuss** [comment]
@zeapo I'm still interested in contributing and maintaining this app's momentum.

**Comment by raindev** [comment]
Are there any updates on the status of the project maintainership?  I see the message about looking for a new maintainer was removed from the readme a few days ago (6ab252981184e039fadbe5d3b4651ee592fa77d4).

**Comment by zidhuss** [comment]
After some discussions, I've been added as a maintainer to the APS project.

I look forward to helping @zeapo move this project forward.

**Comment by raindev** [comment]
Great to know this has been resolved. Thanks @zidhuss for stepping up!
