### ISSUE TITLE
'Extra' field does not show if the password is empty

### ISSUE THREAD

**Issue by jakubtopic** [zeapo/Android-Password-Store#409]
I don't know if this is an intention of design, but now if I open a record without a password (eg a credit card in my case), I have to click `edit` to see any extra information (other than the first line of the text file).

**Comment by zidhuss** [comment]
I've not been able to reproduce this. 

Was the password created on the CLI or the app?

**Comment by zidhuss** [comment]
Feel free to re-open this issue if it's still present in the latest version.
