### ISSUE TITLE
Enable non-git password stores

### ISSUE THREAD

**Issue by kevincox** [zeapo/Android-Password-Store#41]
While I use git to track changes to my passwords I don't actually use it to pull and push them anywhere.  I currently use a different tool to keep the passwords on my phone up to date.  I was hoping that there would be an option added so that I could point the app at an existing directory and use that.

**Comment by sspind** [comment]
Would be very interested in seeing this feature as well! Any update on the status?

**Comment by zeapo** [comment]
I started working on it today. Will be ready in 2 or 3 weeks :)

**Comment by sspind** [comment]
Wow, quick reply :D Very good to hear, thanks a lot for the good work!

**Comment by kevincox** [comment]
Awesome!  If you need any testers let me know.

**Comment by sspind** [comment]
Ditto. Would also be available for coding / reviewing :)

**Comment by zeapo** [comment]
I'm in vacation for the next 10 days.

**Comment by zeapo** [comment]
the commit 458282b5e19a17f19377731e5db3ddcb5aae3980 allows you to clone into an *existing* external folder on the sdcard.
All usual features still work (push/pull), add password (with commit message) and delete.

If you want to test, check this apk: https://github.com/zeapo/Android-Password-Store/blob/external_dir/app/app-debug.apk

**Comment by kevincox** [comment]
I tried this out and it works!  It is a little confusing that you have to kill the app (tbh I didn't really read the above instructions) as I first tried the refresh button which did nothing.  But other then the minor UI issues it appears to be fully functional.  Thanks so much!  I'll continue using the beta and report any issues I come across.

**Comment by zeapo** [comment]
Glad it works. Download the apk from last commit. You will no longer need to kill the app.

**Comment by kevincox** [comment]
I just downloaded https://github.com/zeapo/Android-Password-Store/blob/external_dir/app/app-release.apk and I still had to restart the app.  Either way I am thrilled that I can now use pass on my phone.  Thank you so much.

**Comment by zeapo** [comment]
@kevincox could you check again, by uninstalling the app. Installing either the release or the debug apk. It should not require a close of the app for a refresh.

**Comment by djl** [comment]
This is working almost flawlessly for me except for one (mostly cosmetic) issue. It seems like the app always assumes it will be working with a git repo?

When adding a new item to a plain directory the app displays an error:

    Internal exception occurred

    Message from jgit:
    Exception caught during exection of add command


Hitting 'OK' dismisses the error and quits the app. The item is still created, though.

**Comment by kevincox** [comment]
Yeah, I had this same problem.  The command still worked however.
