### ISSUE TITLE
Add support for ssh auth with OpenKeyChain

### ISSUE THREAD

**Issue by etam** [zeapo/Android-Password-Store#417]
TermBot is a terminal application that supports using OpenKeyChain for authentication.

It would be great to have this in PasswordStore for ssh connection.

**Comment by alex005005** [comment]
+1

**Comment by Mo-Et** [comment]
+1

**Comment by alex005005** [comment]
I'll see what I can do about it myself this weekend.

**Comment by Mo-Et** [comment]
Awesome, i'd like to help but have never developed on Android yet. Any tips on which part of which code i should look at? Thanks

**Comment by zidhuss** [comment]
Duplicate of #71
