### ISSUE TITLE
Generate SSH key

### ISSUE THREAD

**Issue by Beanow** [zeapo/Android-Password-Store#43]
For authentication I prefer to have an SSH key for each device.
It would be great if the application can generate a new key and share the public key.

**Comment by zeapo** [comment]
If anybody wants to work on this, see : http://www.jcraft.com/jsch/examples/KeyGen.java.html

We already use jsch (via jgit).

**Comment by tverlaan** [comment]
What about using this: https://play.google.com/store/apps/details?id=com.madgag.ssh.agent&hl=en as a solution for SSH keys.

**Comment by zeapo** [comment]
Nice! That would definitely be useful for me too. We've got to check that they have good intent api for third party apps

**Comment by zeapo** [comment]
@Beanow This feature is now merged.
