### ISSUE TITLE
App crashes immediately on startup after upgrade to 1.3.0

### ISSUE THREAD

**Issue by gabm** [zeapo/Android-Password-Store#437]
Since 1.3.0 from f-droid, password-store crashes when i start the app on MIUI 10... I attached a log that I could extract.

https://imgur.com/a/nA6KUbW

**Comment by zidhuss** [comment]
Thanks for pointing this out.  Looks the offending line is [here](https://github.com/zeapo/Android-Password-Store/blob/master/app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.java#L283). I'll release a patch later today.
