### ISSUE TITLE
F-Droid 1.3.0 upgrade is broken

### ISSUE THREAD

**Issue by ieure** [zeapo/Android-Password-Store#438]
I upgraded to version 1.3.0 today via F-Droid, and Password Store crashed instantly when I launched it.  I was unable to downgrade to the last version.  I had to completely uninstall and reinstall it.

Using an Xperia XZ1 Compact with Android 8.0.0.

**Comment by benoliver999** [comment]
Pointed out here: https://github.com/zeapo/Android-Password-Store/issues/437

Fixed here: https://github.com/zeapo/Android-Password-Store/commit/85df10af04fdb3a87f47d28fec5bb3f5045acf1b

**Comment by ieure** [comment]
Thank you!
