### ISSUE TITLE
unbale to start: Password Store has stopped!

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [zeapo/Android-Password-Store#439]
Version: 1.3.0 from f-droid
Android 8.1.0 (lineage 15.1-20181016)

**Comment by c-e-p-x-u-o** [comment]
[logcat.txt](https://github.com/zeapo/Android-Password-Store/files/2489606/logcat.txt)

**Comment by Thor77** [comment]
I guess it was fixed by 85df10af04fdb3a87f47d28fec5bb3f5045acf1b

**Comment by zidhuss** [comment]
I pushed the patch. The new version: `v1.3.1` should be available through f-droid soon.

**Comment by c-e-p-x-u-o** [comment]
fixed in 1.3.1
