### ISSUE TITLE
Not "Clean paths on password list view." but "objects duplication".

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [zeapo/Android-Password-Store#443]
The one of the main rule of programming and design is "do not duplicate objects".

I's UGLY. unreadable, and not clean;

![hell](https://user-images.githubusercontent.com/14617699/47259930-5df2d100-d4ba-11e8-9820-778dedaa6920.png)

shop shop shop shop shop shop shop shop shop shop
STOP! OK! I KNOW! I'm in the shop folder. I'm not stupid. One time is enough.

Full path should be specified on the separate sticky line on the top.

Please remove this hell.

**Comment by zeapo** [comment]
You know that you're not righting a review for a paid product, right? You
also know that what you're looking at is something built by few people
during their limited free time?

If you want to help, just describe the issue *politely* or open a pr if you
are a coder.

Closing the issue.

**Comment by c-e-p-x-u-o** [comment]
Could you explain, what exactly is 'unpolitely" in this issue?
