### ISSUE TITLE
Ugly list duplications.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [zeapo/Android-Password-Store#444]
I's ugly. unreadable, and not clean:
![hell](https://user-images.githubusercontent.com/14617699/47260372-13298700-d4c3-11e8-88d1-f0393723cfdc.png)

Full path should be specified on the separate sticky line on the top.

**Comment by c-e-p-x-u-o** [comment]
this is politely version of unpolitely #443 issue

**Comment by zidhuss** [comment]
Hi, thanks for your opinion. The full path to the password entry has always been included in the list. In the latest release, thanks to #425, it was made cleaner by removing the trailing slashes.

If you don't like the way this looks and you can think of a better way of displaying the password list then I welcome your pull request. We can then review your changes and merge them in.

**Comment by c-e-p-x-u-o** [comment]
Why have you close it?

**Comment by zidhuss** [comment]
You hadn't responded to the issue in a while.

**Comment by c-e-p-x-u-o** [comment]
This is not the reason to close it.
What was the question that I should response?

**Comment by 532910** [comment]
I still believe this issue is actual and hope Harsh will agree with my position: the current path should be shown the only once on the top. In addition this will make all records the same heights, as now it depends on path.

**Comment by msfjarvis** [comment]
> I still believe this issue is actual and hope Harsh will agree with my position: the current path should be shown the only once on the top. In addition this will make all records the same heights, as now it depends on path.

The reason that we still have the path is because the the top bar can fit much lesser characters than the actual entry can, so we put the current directory at the top and the full directory path into each entry. Both serve their purpose, and will stay as-is for now.

**Comment by 532910** [comment]
> the top bar can fit much lesser characters

what limits it?

take a look at [MaterialFiles](https://github.com/zhanghai/MaterialFiles) for example

![Screenshot_20201105-225423_Material_Files](https://user-images.githubusercontent.com/14617699/98289874-dfdac780-1fb9-11eb-9298-0064ef5821fb.png)

**Comment by msfjarvis** [comment]
> > the top bar can fit much lesser characters
> 
> what limits it?
> 
> take a look at [MaterialFiles](https://github.com/zhanghai/MaterialFiles) for example
> 
> ![Screenshot_20201105-225423_Material_Files](https://user-images.githubusercontent.com/14617699/98289874-dfdac780-1fb9-11eb-9298-0064ef5821fb.png)

What you're looking at is a separate widget. The part I'm talking about is what reads 'Files' on your screen. There are many ways to do what you're asking for, but it is simply not a high enough priority right now.

**Comment by 532910** [comment]
> not a high enough priority right now

I don't say it must be fixed ASAP. Let's start by acknowledging the problem and issue reopening.

**Comment by msfjarvis** [comment]
> > not a high enough priority right now
> 
> I don't say it must be fixed ASAP. Let's start by acknowledging the problem and issue reopening.

I will file a separate design updates RFC over the weekend which will include some thoughts on this.

**Comment by 532910** [comment]
OK! This way I have another design problesm: horizontal lines are too obtrusive. They should be barely noticeable, but better to completely hide them. See the same MaterialFiles, dialer or any other material app for example.
