### ISSUE TITLE
'Extra' field is single-line only

### ISSUE THREAD

**Issue by reroman** [zeapo/Android-Password-Store#453]
The 'Extra' field does not allow text in multiple lines. The issue was fixed in e72038f, but it looks like it came back in version 1.3.1.

**Comment by abonny** [comment]
I'm seeing the same thing as reroman.  I notice on "read" it will show multiple lines but when you go to "edit" it is ONE long line.

**Comment by zidhuss** [comment]
Thanks for pointing this out.

That commit wasn't included in v1.3.1. I've pushed out a new release with that change included.
