### ISSUE TITLE
Export password in one file (.csv)

### ISSUE THREAD

**Issue by axac** [zeapo/Android-Password-Store#454]
Bonjour,
Is it possible to export all the passwords in one file ?.
Thanks

**Comment by zidhuss** [comment]
There's no easy way to do this on the app but if you have the command line password store (https://www.passwordstore.org/), you could easily create a bash script to export your passwords.

**Comment by axac** [comment]
Thanks. I see this https://github.com/reinefjord/pass2csv, but i think there is no lige. And it's Just export password not username and url.

**Comment by zidhuss** [comment]
No problem. I don't think this is something that we'll include in Android Password Store app so I'll close this issue.
