### ISSUE TITLE
Unable to generate 8 digit OTP

### ISSUE THREAD

**Issue by ReekyMarko** [zeapo/Android-Password-Store#457]
An otpauth:// url created by [python-bna](https://github.com/jleclanche/python-bna) is 8 digits. This is generated fine with [pass-otp](https://github.com/tadfisher/pass-otp) on Linux but on Android-Password-Store it is 6 digits.

For reference, here is an example otp url:
`otpauth://totp/Battle.net:US123456789123?secret=ABCDEFGHIJKLMN&issuer=Battle.net&digits=8`

EDIT: It seems that the missing digits are the first 2 digits of the 8 digit OTP

**Comment by zidhuss** [comment]
Looks like it's hard-coded to handle 6 digits at the moment.

https://github.com/zeapo/Android-Password-Store/blob/eea0e68dda1eb7248c6d458f52baeedb318b466a/app/src/main/java/com/zeapo/pwdstore/utils/Otp.java#L20 .

Should be able to handle 8 digits codes too.

**Comment by ReekyMarko** [comment]
Agreed, it's not very common to have different lengths, but it happens some times. This is way out of my level of expertise, but I think it wouldn't be too hard to read the `&digits=x` from the uri and use that as the CODE_DIGITS variable. If there is no such variable in the uri, use 6 digits.

**Comment by igaryhe** [comment]
This issue has been solved.

**Comment by MSF-Jarvis** [comment]
Fixed with 94bf103b337d9df1d6232d85f5edf4673ede651c
