### ISSUE TITLE
cannot clone pass.git from bare git repo

### ISSUE THREAD

**Issue by franok** [zeapo/Android-Password-Store#458]
I decided to choose your implementation of an android pass app, as it looks very up to date, compared to others (and for sure because it's open source).
I assume it also works nicely but unfortunately I encounter a bug when trying to clone my-pass.git repo.

EDIT: actually I'm not really sure what the problem is, anymore. First I thought it's a concatenation issue with the default port in the resulting URL (but now I think it's only a visual issue).

~When I enter my own git server credentials in the settings the resulting URL is not correct if the default port 22 is used/entered. Also manual editing of the URL doesn't help.~

I get error dialogs like:
```
An error occurred during a git operation

Error occured during the clone operation, Message from jgit: Invalid remote: origin
Caused by: org.eclipse.jgit.errors.NoremoteRepositoryException: myuser@myserver.com/home/myuser/my-pass.git: not found.
Please check the FAQ [...]
```

example:
protocol: `ssh`
user name: `myuser`
server-url: `myserver.com` (port `22`)
repo path: `/home/myuser/my-pass.git`
auth: user/password

resulting URL: `myuser@myserver.com:/home/myuser/my-pass.git`

the colon after the TLD shouldn't appear in the resulting URL (or should be there with the default port).
Working examples with git clone:
```
git clone ssh://myuser@myserver.com/home/myuser/my-pass.git
git clone ssh://myuser@myserver.com:22/home/myuser/my-pass.git
```

**Comment by franok** [comment]
Suggested workaround: provide the option to simply let the user enter the complete URL (without comparing to the mask).
In my case it would look like `ssh://myuser@myserver.com/home/myuser/my-pass.git`

**Comment by franok** [comment]
[SOLVED] Cumbersome!
I just fiddled around a little longer and together with the suggested workaround in #357 I got it working.
The final URL is now (protocol ssh://) `myuser@myserver.com:/home/myuser/my-pass.git/`. Note the `/` at the end. That's what the jgit Exception was trying to tell me.

P.S. Would be nice if you could fix the little visual thing with the colon when default port is used.

**Comment by justinacolmena** [comment]
"Cumbersome! I just fiddled around a little longer and together with the suggested workaround ..."

No go.

Doesn't work for me. Too many jgit exceptions and no debugging tools. I only have consumer level access. I can't even copy and paste the error message.

GnuPG 2.2 series doesn't read or import my secret key from OpenKeychain, either, and it would likely have to be the same key.
