### ISSUE TITLE
Clipboard history is not cleared 20 times

### ISSUE THREAD

**Issue by tomasz-oponowicz** [zeapo/Android-Password-Store#465]
### Steps

1. Given the clipboard history is cleared
1. Given the "Clear clipboard 20 times" is enabled in Password Store
1. Given the "Automatically Copy Password" is enabled in Password Store
1. Given the "Automatically clear the clipboard adter..." is enabled in Password Store
1. Open password store
1. Open an entry. A password will be copied automatically.
1. Wait till the clipboard clearing is triggered
1. Open a Samsung keyboard (for example use a text field in any app)
1. Go to _Clipboard history_

### Expected

The clipboard history doesn't contain the copied password.

### Actual

The clipboard history contains following entries:

`18, 17, ... 0, <copied password>`

### Environment

Android: 8.0
Version: 1.3.2

**Comment by ashfaqfarooqui** [comment]
I have the same issue on my Samsung phone.

**Comment by zeapo** [comment]
fixed in  #487
