### ISSUE TITLE
jGit error while pulling from remote

### ISSUE THREAD

**Issue by evahlis** [zeapo/Android-Password-Store#47]
When I do pull from remote, I get the following error message:
jgit: /nCould not read an object while parsing commit <commit id here>

Any ideas what could be wrong?

**Comment by jonblack** [comment]
Just in case anyone else ends up here, you also get this error when the SSH key isn't setup on GitHub correctly. I was adding mine as a Deploy Key in the repository settings, but it should be in added in the SSH Key section in your global account settings, not just for the single repository.
