### ISSUE TITLE
Use a plain folder instead of Git/SSH

### ISSUE THREAD

**Issue by duncannz** [zeapo/Android-Password-Store#48]
I have a symbolic link on my computer from `Dropbox/password-store` to `.password-store` so this means my passwords are synced via Dropbox including the app on my phone.

As an alternative to setting up a Git remote that the passwords are stored in, can there not just be a "Select Folder" option which would open Android's native folder selection dialogue? From there one can just choose Dropbox in the left column and select the folder from there, and the same could be done with any other app that provides a file selection helper.

I see #41 is similar but I do not wish to run an SSH server and I prefer the sync feature offered by Dropbox that would also work when not on the local network. (For security reasons I would not want an SSH server unnecessarily exposed to the Internet).

**Comment by rafi** [comment]
I'm using syncthing on all my devices, and among others, my pass folder is sync'ed on my android. It's very convenient and hands-free. Can we have a 3rd option in initial setup, "Use existing directory"?

**Comment by polyzen** [comment]
There's a poll for this [here](http://www.poll-maker.com/poll264179x2406412a-10) da87c19

**Comment by kevincox** [comment]
I'm pretty sure the solution to #41 solves this problem.  I downloaded the testing package and I could point pass at any directory and it just works!  I'm using syncthing but I can't see why dropbox would be and different.
