### ISSUE TITLE
Crashes if server has GSSAPI support enabled

### ISSUE THREAD

**Issue by jelmer** [zeapo/Android-Password-Store#49]
Password Store appears to crash if GSSAPI authentication is offered by the SSH server, even if other authentication methods are available:

E/AndroidRuntime(19961): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(19961): Process: com.zeapo.pwdstore, PID: 19961
E/AndroidRuntime(19961): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(19961): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(19961): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(19961): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(19961): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(19961): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(19961): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(19961): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(19961): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(19961): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/ietf/jgss/Oid;
E/AndroidRuntime(19961): 	at com.jcraft.jsch.jgss.GSSContextKrb5.create(GSSContextKrb5.java:55)
E/AndroidRuntime(19961): 	at com.jcraft.jsch.UserAuthGSSAPIWithMIC.start(UserAuthGSSAPIWithMIC.java:125)
E/AndroidRuntime(19961): 	at com.jcraft.jsch.Session.connect(Session.java:463)
E/AndroidRuntime(19961): 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
E/AndroidRuntime(19961): 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
E/AndroidRuntime(19961): 	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
E/AndroidRuntime(19961): 	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
E/AndroidRuntime(19961): 	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
E/AndroidRuntime(19961): 	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
E/AndroidRuntime(19961): 	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1115)
E/AndroidRuntime(19961): 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
E/AndroidRuntime(19961): 	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:261)
E/AndroidRuntime(19961): 	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:78)
E/AndroidRuntime(19961): 	at com.zeapo.pwdstore.GitAsyncTask.doInBackground(GitAsyncTask.java:43)
E/AndroidRuntime(19961): 	at com.zeapo.pwdstore.GitAsyncTask.doInBackground(GitAsyncTask.java:16)
E/AndroidRuntime(19961): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(19961): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(19961): 	... 4 more
E/AndroidRuntime(19961): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.ietf.jgss.Oid" on path: DexPathList[[zip file "/data/app/com.zeapo.pwdstore-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime(19961): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(19961): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(19961): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(19961): 	... 21 more
E/AndroidRuntime(19961): 	Suppressed: java.lang.ClassNotFoundException: org.ietf.jgss.Oid
E/AndroidRuntime(19961): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(19961): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(19961): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(19961): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(19961): 		... 22 more
E/AndroidRuntime(19961): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
W/ActivityManager( 2006):   Force finishing activity com.zeapo.pwdstore/.GitHandler

**Comment by zeapo** [comment]
I maked it as wontfix as there is a patch for jsch to solve this. However, jsch didn't include it yet and jgit is using an older version. We'll have to wait until they apply the patch.

**Comment by lsowen** [comment]
Could a workaround be put in place?  Namely setting `PreferredAuthentications` to `password,pubkey`, as suggested in http://stackoverflow.com/a/28965796/3108853?

**Comment by lsowen** [comment]
Implemented (and confirmed it worked) in PR #91.
