### ISSUE TITLE
Can't clone github repo

### ISSUE THREAD

**Issue by bit9tream** [zeapo/Android-Password-Store#490]
Protocol: ssh://
Username:   git
Server URL: github.com
Repo path:   bit9tream/.password-store.git
Aunthentication Mode: ssh-key

Resulting url: git@github.com:bit9tream/.password-store.git

Error occured during the sync operation. Message from jgit: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectld.w1' on a null object reference 
Caused by: null

**Comment by mikzuit** [comment]
Similar error here "Error occured during the pull operation , Message from jgit: Attempt to get length of null array Caused by: null". Using auto-generated ssh-key , Protocol ssh:// .

**Comment by bit9tream** [comment]
I generated ssh-key pair with Password Store app and added pub key to the GitHub. I doesn't work.

**Comment by alfredopalhares** [comment]
I also get this bug.

**Comment by piotryordanov** [comment]
Facing the same problem here. Any idea what should be done @zeapo ?

**Comment by FHantke** [comment]
This [comment](https://github.com/zeapo/Android-Password-Store/issues/357#issuecomment-349833720) worked for me. Hope it helps!

**Comment by CaptainFrosty** [comment]
beginning to wonder if development is on hiatus...

**Comment by bit9tream** [comment]
It is working with my own git repo, so I close the issue.
