### ISSUE TITLE
totp keys are not supported (only otpauth://totp urls work)

### ISSUE THREAD

**Issue by colemickens** [zeapo/Android-Password-Store#495]
This entry will provide the TOTP code in the Android app.
gopass
```
password
url: foo.com
username: foo
otpauth://totp/foo?secret=zvunxxxx....
```

This one will not:

```
password
url: foo.com
username: foo
totp: E5NP2NOPOO....
```

**Comment by AluminumTank** [comment]
Maybe I'm just confused, but can't you just format the TOTP string as an `otpauth://totp/foo?secret=E5NP2NOPOO....`?

The OTP implementation is designed to match that of  the `pass-otp` project, BTW. I believe Android-Password-Store is focused on reimplementing already existing features from pass and several other CLI addons, not implementing new features.

**Comment by erayd** [comment]
@AluminumTank For what it's worth, I also store my OTP seeds in the format `totp: <my totp seed>`, the same as @colemickens . I don't use pass-otp, but instead have a dmenu script which reads these lines, and fills the generated code directly into wherever the cursor focus is currently set.

> ...focused on reimplementing already existing features from pass and several other CLI addons, not implementing new features.

I don't feel that this is a new feature - rather, it's the same, existing feature, just with an alternative syntax for specifying the OTP seed.

**Comment by colemickens** [comment]
Ah, @AluminumTank, I hadn't realized this wasn't a standard `pass-otp` feature -- it's something that `gopass` supports.

Since, I only have one entry that is in this alternative form, I'm actually more likely to standardize it back to `otpauth://totp/name?secret=key` in hopes of being compliant with more tooling.

Since someone else is interested, I'll leave this open but obviously please close this, if appropriate. Thanks.

**Comment by AluminumTank** [comment]
@erayd I think this is a fair point, especially since gopass implements it with this syntax.
