### ISSUE TITLE
Android clipboard is vulnerable to hijacking

### ISSUE THREAD

**Issue by emilecantin** [zeapo/Android-Password-Store#50]
As evidenced [here](http://stackoverflow.com/questions/22277598/permanently-listen-to-clipboard-changes), it is apparently possible for any app on the device to listen for changes on the system clipboard and to get its contents.

Another password manager, Keepass2Android, implements a keyboard to get around this problem. I think we should do the same.

**Comment by c4software** [comment]
Hi,

Its a nice implementation, but if (like me) you use Password Store in a Chrome context, its seems not working (because its a Website not an app). The idea of an input method is still not an option ?

**Comment by wongma7** [comment]
It is still a possibile option I think. I believe in the latest versions of Android switching keyboards is more convenient and usable too. I'll work on it but no eta

**Comment by polyzen** [comment]
In kp2a(keepass2android), you can have it [automatically switch to the kp2a kb and back](https://keepass2android.codeplex.com/wikipage?title=Advanced%20usage%20of%20the%20Keepass2Android%20keyboard) (doesn't seem to work inside terminals, but eh).

Also, `pass` seems to use "username" as the standard field. `passff` uses "login", but that's configurable

**Comment by JasperWeiss** [comment]
When using autofill, does it utillize the clipboard? It requested some sort of permisson for autofill so I assumed this was some sort of android 5.0 feature that circumvents the need for the (insecure) clipboard

**Comment by zeapo** [comment]
Autofill does not use the clipboard and the recently added share button allows to share the password in clear text to another app if needed.
