### ISSUE TITLE
Clipboard not clearing.

### ISSUE THREAD

**Issue by zimlokks** [zeapo/Android-Password-Store#505]
Was doing a test run before I fully commit to using Password Store(1.3.2).

I set everything up, reduced the amount of time the passwords would stay on the clipboard to 10 seconds and double checked that it would wipe the clipboard 20 times. Yet it didn't work. If I'm missing something please let me know.

Device: OnePlus 6T 
Build Number: A6013_34_190403
Password Store Version: 1.3.2 (Google Play Store)
Keyboard: Google Keyboard

**Comment by zeapo** [comment]
Hi, some keyboards keep a copy of the clipboard. Check that such option is
not enabled.

Le mer. 1 mai 2019 à 10:15, Erik Alvarado <notifications@github.com> a
écrit :
