### ISSUE TITLE
Can't access to gitlab repo. 

### ISSUE THREAD

**Issue by c4pointer** [zeapo/Android-Password-Store#507]
![Screenshot_20190503_184606_com zeapo pwdstore](https://user-images.githubusercontent.com/30981336/57153179-4936b480-6dde-11e9-854d-450e03aead50.jpg)
![Screenshot_20190503_184639_com zeapo pwdstore](https://user-images.githubusercontent.com/30981336/57153190-4e93ff00-6dde-11e9-9f8d-cf10bf023121.jpg)
  I tried to install from other applications store, f droid and play market. No any changes. My repo is not empty and its a master. 
It's a test account. I am a new user of git.
Please help.

**Comment by dubcl** [comment]
Hi, same problem here, any fix or workaround? Cheers.

**Comment by lazyfox81** [comment]
I have a same problem too.

**Comment by santhoshtr** [comment]
For me, https://github.com/zeapo/Android-Password-Store/issues/357#issuecomment-349833720 worked

**Comment by msfjarvis** [comment]
Looks like this is solved. Closing.
