### ISSUE TITLE
Pixel 3a - Autofill Service Not Showing Android Password Store (Zeapo)

### ISSUE THREAD

**Issue by wenindoubt** [zeapo/Android-Password-Store#509]
Android Password Store (Zeapo) installed via Play Store.

Autofill Service shows **None** & **Google**, by default.

If I tap **add a service**, Android Password Store (Zeapo) does **not** show up. It only shows the following:

- Enpass Password Manager
- BlackBerry Password Keeper
- LastPass Password Manager
- Dashlane Password Manager
- Keeper Password Manager & Secure Vault
- 1Password

**Comment by kakolisgay** [comment]
Pretty sure the (android) autofill service isn't supported. The current autofill is using an accessibility service

**Comment by msfjarvis** [comment]
There is none to begin with. Track progress for this in #410.
