### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by bricewge** [zeapo/Android-Password-Store#513]
It has been 6 months since the last release and I can't wait to try #486. Would it be possible to have a new release with this feature or a per-release?

If you consider this a noisy issue fell free to close it.

**Comment by MSF-Jarvis** [comment]
> It has been 6 months since the last release and I can't wait to try #486. Would it be possible to have a new release with this feature or a per-release?
> 
> If you consider this a noisy issue fell free to close it.

Hello, thanks for bringing this up! We're still working on many small bugfixes and features at the moment, including the massive refactor being tracked at #260. I'm divided on whether to wait for it to release a new build or release beforehand and take some pressure off, allowing for a better review and testing process. I'll let other maintainers weigh in with their opinions :)

**Comment by zeapo** [comment]
Same opinion as @MSF-Jarvis , better wait with a stable #260. If you'd like an unstable (signed) build, I can provide that.

**Comment by bricewge** [comment]
Thank you for the answers. I'll wait wait some more for the official release with multiple password stores then.
@zeapo it would be very kind of you!

**Comment by colemickens** [comment]
@zeapo I'd also greatly appreciate a signed unstable build. I'd also use an unsigned build as an interim solution, but I don't necessarily see CI builds or anything like that. Thank you to @zeapo and @MSF-Jarvis !

**Comment by MSF-Jarvis** [comment]
I suppose we can configure CI to start uploading build artifacts to GitHub releases on a per-commit basis. I'll look into it soon.

**Comment by zeapo** [comment]
They won't be signed by the same key as the one on the play store :/

Le jeu. 23 mai 2019 à 08:08, Harsh Shandilya <notifications@github.com> a
écrit :

**Comment by zeapo** [comment]
Oh speaking of the play store. I can make an apha release there... I'll
deploy it this evening.

Le jeu. 23 mai 2019 à 08:09, Mohamed Zenadi <mohamed.zenadi@gmail.com> a
écrit :

**Comment by MSF-Jarvis** [comment]
> They won't be signed by the same key as the one on the play store :/

We can implement something like [this](https://github.com/MSF-Jarvis/viscerion/commit/170b3a86157175b3080405d6421956d45a07ecd8) to check in the keystore to this git repo and sign CI builds with.

**Comment by zeapo** [comment]
@bricewge @colemickens https://github.com/zeapo/Android-Password-Store/blob/master/app/release/app-release.apk

**Comment by bricewge** [comment]
Thanks you @zeapo for the binary. Just a side note, putting binaries in git isn't good for the health of the repository in the long term.
