### ISSUE TITLE
Function "Synchronize repository" and "Refresh list" unclear

### ISSUE THREAD

**Issue by avanc** [zeapo/Android-Password-Store#524]
I'm a very glad user of Password Store since more than two years.
However, I'm still unsure for what "Synchronize repository" and "Refresh list" is used for. Thus, I'm always doing the following to be sure everything is synced correctly after adding a new password:

- "Pull from remote"
- "Push to remote"
- "Synchronize repository"
- "Refresh list"

I tried to get the meaning form the source code but got stuck:

> "Synchronize repository" -> R.id.git_sync -> GitActivity.REQUEST_SYNC -> syncRepository(REQUEST_SYNC) -> startActivityForResult(..., REQUEST_SYNC)
> "Pull from remote" -> R.id.git_pull -> GitActivity.REQUEST_PULL -> syncRepository(REQUEST_PULL) -> startActivityForResult(..., REQUEST_PULL)
> "Push to remote" -> R.id.git_push -> GitActivity.REQUEST_PUSH -> syncRepository(REQUEST_PUSH) -> startActivityForResult(..., REQUEST_PUSH)
> "Refresh list" -> R.id.refresh -> updateListAdapter -> plist.updateAdapter() 

In addition, it would be helpful to know how git merge conflicts are handled.

**Comment by MSF-Jarvis** [comment]
- Pull from remote: Runs `git pull origin master`, fails on conflicts
- Push to remote: Runs `git push origin master`, fails if remote rejects the push
- Synchronize repository: Commits current state, pulls remote branch with `--rebase` passed, then pushes that state to the remote.
- Refresh list: Traverses store filesystem to load all passwords and folders

For the most part, the app breaks down upon conflicts and requests users to resolve it on the remote. When the rebase step in `Synchronize repository` fails, the app presents a [new option](https://github.com/zeapo/Android-Password-Store/commit/064a3fad99d5852d50634a98023cb92c4a915606) to checkout a new branch, from that state, abort rebase and push that new branch to the remote for conflicts to be resolved.

The source code for all the operations is [here](http://github.com/zeapo/Android-Password-Store/tree/master/app/src/main/java/com/zeapo/pwdstore/git/). Hope that clears up the queries.

**Comment by avanc** [comment]
Thanks for the quick reply! This makes it more clear to me. But still having some questions...

Adding a key wouldn't result in a commit? So changing/adding something and than doing a push wouldn't do anything remotely, as no commit was done?

For what is push used, if commits are not created automatically?

I understand, I have to do pull to get new keys from remote. Do I have to initiate a refresh to get changes shown in the UI?

**Comment by zeapo** [comment]
It will result in a commit. The one made in sync is in case you make a
change out of the app.

**Comment by MSF-Jarvis** [comment]
> Adding a key wouldn't result in a commit? So changing/adding something and than doing a push wouldn't do anything remotely, as no commit was done?

It would result in a _local_ commit, but Git does not automatically push changes to remote and nor does APS.

> 
> For what is push used, if commits are not created automatically?
> 

To update the remote branch.

> I understand, I have to do pull to get new keys from remote. Do I have to initiate a refresh to get changes shown in the UI?

Not usually, no. The UI should refresh automatically but if for some reason it does not, the refresh option will force it.

**Comment by avanc** [comment]
So `Synchronize repository` is sufficient the most time and Pull, Push, Refresh is only useful in very rare cases as I can also use `Synchronize repository` for pull or push new data?
How about to move the three actions to to a separate position in the UI (maybe into settings) to avoid confusion for new users?

**Comment by MSF-Jarvis** [comment]
> So `Synchronize repository` is sufficient the most time and Pull, Push, Refresh is only useful in very rare cases as I can also use `Synchronize repository` for pull or push new data?
> How about to move the three actions to to a separate position in the UI (maybe into settings) to avoid confusion for new users?

By the time #519 is ready to land, most git options will be in the Git utils submenu in settings.

**Comment by avanc** [comment]
Sounds great!
Thanks for all the details. This helped a lot in understanding the backgrounds.
