### ISSUE TITLE
Default to last-changed date 

### ISSUE THREAD

**Issue by madduck** [zeapo/Android-Password-Store#530]
I just switched from using a Git repo on the phone to a simple directory export managed by Syncthing (because I always seem to have forgotten to pull from my laptop when I need a new password, and then I never have the laptop handy). This works just fine, except whenever I select an entry, I am shown a toast:

> Failed to get last changed date

I suspect the app is trying to infer from Git the last modification date, and since there is no `/.git` in my case, this fails.

Would it be possible to default to using the file modification time in this case?

Thanks!

**Comment by madduck** [comment]
Oh wow, this is perhaps the fastest turnaround I've ever seen. Thanks so much, @msfjarvis!

**Comment by msfjarvis** [comment]
> Oh wow, this is perhaps the fastest turnaround I've ever seen. Thanks so much, @msfjarvis!

Your timing was fortunate :)
