### ISSUE TITLE
Play store release

### ISSUE THREAD

**Issue by lbischof** [zeapo/Android-Password-Store#534]
It seems the latest version in the `app/release` directory is different from the play store version (even though the version numbers are the same?). Could you release a new version to the play store?

**Comment by VolatileDream** [comment]
Would it also be possible to release to FDroid as well? The version posted there is almost 10 months old.

**Comment by lo-dash** [comment]
@zeapo @zidhuss please release a new version, the one in f-droid is quite old indeed...

**Comment by zidhuss** [comment]
I'll make it a priority to release a new version this weekend.

**Comment by lo-dash** [comment]
@zidhuss Awesome, thanks so much :)

**Comment by XenGi** [comment]
As of today:

- [F-Droid][fdroid]: Version 1.3.2 - Added on 2018-12-27
- [Playstore][playstore]: Version 1.3.2 - Added on 2019-01-01

Seems like the priority for the weekend wasn't high enough. ;)

A new release would be nice. Can we help with anything? What is needed to achieve the task?

[fdroid]: https://f-droid.org/en/packages/com.zeapo.pwdstore/
[playstore]: https://play.google.com/store/apps/details?id=com.zeapo.pwdstore&hl=en_US

**Comment by zeapo** [comment]
It'll be scheduled for tonight. The play store version will be a beta one.
on fdroid, it should be available tomorrow.

I'll update this thread later.

Le lun. 9 sept. 2019 à 16:10, Harsh Shandilya <notifications@github.com> a
écrit :

**Comment by zeapo** [comment]
The play store version was released in beta. you can opt-in using this link https://play.google.com/apps/testing/com.zeapo.pwdstore 
The release was also tagged for F-Droid to pick it up. Hopefully it'll be available tomorrow.

Please bear in mind that this release is not the most tested ever. I've already found two (non-blocking issues), we'll deal with them :)

**Comment by lo-dash** [comment]
@zeapo looks like FDroid did not pick this up. Any insights?

**Comment by VolatileDream** [comment]
There's a pull request pending on the FDroid side: https://gitlab.com/fdroid/fdroiddata/merge_requests/5504
