### ISSUE TITLE
Copy password when saving

### ISSUE THREAD

**Issue by durka** [zeapo/Android-Password-Store#536]
Another feature request: Optionally copy the password right away when saving it. This would be similar to the `pass generate -c ...` command-line option.

**Comment by msfjarvis** [comment]
Implemented by 367e55de3cfb0821898c41413ecdb6d284763081, thanks for the contribution!

**Comment by durka** [comment]
I found a bug in this feature... It doesn't work with newly created
passwords. Something throws and the password doesn't get saved. Will
investigate.
