### ISSUE TITLE
Can't select key from OpenKeychain on Xiaomi devices

### ISSUE THREAD

**Issue by Shiroukoji** [zeapo/Android-Password-Store#542]
Hey,

when I tap on "Select OpenPGP Key id" there is an animation of open an new App but then I'm back in the PasswordStore App. So I can't select an key. I tried it with the beta and the normal version. I'm using a Xiaomi Mi 9, other Apps like K9-Mail are working with OpenKeychain

**Comment by Shiroukoji** [comment]
I found something in the log, maybe it helps:

gpActivity: RESULT_CODE_USER_INTERACTION_REQUIRED
09-25 21:39:17.739  1457  3003 I ActivityManager: START u0 {cmp=org.sufficientlysecure.keychain/.remote.ui.RemoteRegisterActivity (has extras)} from uid 10171
09-25 21:39:17.739  1457  3003 D com.android.server.am.ExtraActivityManagerService: MIUILOG- Permission Denied Activity : Intent { cmp=org.sufficientlysecure.keychain/.remote.ui.RemoteRegisterActivity (has extras) } pkg : org.sufficientlysecure.keychain uid : 10171 tuid : 10177

**Comment by Shiroukoji** [comment]
Fixed. The permission "start in background" have to be allowed on Xiaomi devices. Don't why it works on other apps without this permission but it solved it. 

Sry for this short and self-fixed issue, but the idea for this came immediately after opening this issue.

**Comment by mintar** [comment]
Thanks, I had the same problem on a Xiaomi Redmi Note 3. For clarification: The app that you need to grant the "start in background" permission to is OpenKeychain.

**Comment by lewisdiamond** [comment]
On MIUI 11, it's called `Display pop-up windows while running in the background`
