### ISSUE TITLE
Random password generation

### ISSUE THREAD

**Issue by lack** [zeapo/Android-Password-Store#58]
It would be nice to incorporate a random password generator one could optionally use to fill in the password blank.  When signing up for a new account you could flip over to Password Store, add an entry, bok on the button, and have an unguessable password ready to go.

**Comment by aminb** [comment]
`pass` [uses](http://git.zx2c4.com/password-store/tree/src/password-store.sh#n455) [`pwgen`](http://sourceforge.net/projects/pwgen/) for generating passwords; which in turn [uses](http://sourceforge.net/p/pwgen/code/ci/master/tree/randnum.c#l35) `/dev/urandom` at heart if possible.

I was looking around and saw [pwgen-android](https://github.com/aweinert/pwgen-android) by @aweinert. However, it only [uses](https://github.com/aweinert/pwgen-android/blob/02a7677289fa2a42275901298894e582bb925504/src/com/alexweinert/pwgen/RandomGenerator.java#L3) `java.util.Random`.

We can fork it and have it use [`java.security.SecureRandom`](https://developer.android.com/reference/java/security/SecureRandom.html).

Also, as an aside, [worth reading](http://android-developers.blogspot.ca/2013/08/some-securerandom-thoughts.html).

What are your thoughts?

**Comment by zeapo** [comment]
Looks good. Could you create a PR for it?

**Comment by aminb** [comment]
@zeapo Here's a **very** rough-around-the-edges and early-progress branch on my fork: https://github.com/aminb/Android-Password-Store/tree/pwgen

Please clone and build it and take a look at it.

Basically, I've forked [aweinert/pwgen-android](https://github.com/aweinert/pwgen-android) into [aminb/pwgen-android](https://github.com/aminb/pwgen-android), and added the `SecureRandomGenerator` class. Then, copied over the stuff from my fork into this repo.

Here's the things I plan on doing, preferably before opening a PR:
- Improve the generator layout 
- Option to choose the password length
- Send the generated password back to the `PgpHandler` activity

**Comment by zeapo** [comment]
Tried it briefly, a small issue where setting "must not" on lowercase does not do anything. 
could you create a pull request for it so that I can comment on it?

Also, we should probably make it as a dialog.

**Comment by aminb** [comment]
Yeah I noticed the lowercase issue as well. Will add to my to-be-fixed list.

Dialog would be nice, but I can't remember, are we using material-styled dialogs in the app?

I just opened a PR at your request.

**Comment by zeapo** [comment]
merged in #101
