### ISSUE TITLE
git settings not saved

### ISSUE THREAD

**Issue by rolandf** [zeapo/Android-Password-Store#63]
After an initial git pull that worked ok and an initial push that was ok too (I use bitbucket to store my repository) I did the following:

1) Created a new password on my desktop computer
2) Push to BitBucket
3) Verify BitBucket the password has been commited succesfully
4) Open PasswordStore on Android Smartphone
5) Pull from bitbucket
6) Notice failure
7) Check settings to find that last working settings where not saved.

Settings where https protocol using user and password.

**Comment by zeapo** [comment]
Probably solved in 88a6876238ecfff3926a5e4ba79b79bd6c2f7faa
Check tomorrow with v1.2.0.12 (F-Droid), play store version not built yet.

**Comment by zeapo** [comment]
Can you check with today's build (v.1.2.0.12) https://f-droid.org/repository/browse/?fdid=com.zeapo.pwdstore

**Comment by rolandf** [comment]
I can't get it to work. I entered the bitbucket url 3 different ways.
Wouldn't it be more user friendly if we could just cut and paste the URL from Bitbucket ?

**Comment by zeapo** [comment]
you can, just paste it into the Resulting url field.

On Mon, Jan 5, 2015 at 7:38 PM, Frédéric Roland <notifications@github.com>
wrote:

> I can't get it to work. I entered the bitbucket url 3 different ways.
> Wouldn't it be more user friendly if we could just cut and paste the URL
> from Bitbucket ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zeapo/Android-Password-Store/issues/63#issuecomment-68753609>
> .
>



-- 
Mohamed Zenadi

mail: mohamed@zenadi.com
webpage: http://zenadi.com

**Comment by zeapo** [comment]
(are you talking about #61 ? :)

**Comment by rolandf** [comment]
@zeapo yes I was sorry to mix issues.
I still have problems with #61 but this times settings were saved between my tests to get an initial repository clone from bitbucket.
