### ISSUE TITLE
Recent update seems render passwords inaccessible but does not

### ISSUE THREAD

**Issue by bjoseru** [zeapo/Android-Password-Store#69]
On both devices (S3 mini and Galaxy Tab 4) of my wife the password store (beta) was on auto update. Everything was fine up until the last update.

Now, as I start password store on either device it looks like I had it never set up for use before. I am greeted with "Welcome to Password Store. In This screen you can either create a new repository or clone your git repository onto your device." 

Looking at the settings of the app, apparently the git server is still configured correctly, the app just does not remember it.

So I click on "CREATE NEW", answer "Which connection method do you prefer?" with "ssh-key", as that is what I had before. And suddenly, all the passwords re-appear.

So luckily, this is not a big issue anymore, but it was quite a shocker yesterday night to find all my wife's passwords no longer accessible. And guess who was blamed for that ;)

**Comment by zeapo** [comment]
Sorry for that :)

I have changed the way we detect an existing store. I will deploy a
temporary version to fix that until every body has opened the store at
least once.
