### ISSUE TITLE
Password store app stops when I try to insert a new password

### ISSUE THREAD

**Issue by bjoseru** [zeapo/Android-Password-Store#70]
Now that the passwords are accessible again, I tried to enter a new password. Clicking the "+" icon resulted in the app stopping or being stopped repeatedly. However, at about the third attempt is seems to be working. 

I did this on a Galaxy tab 4 with the most recent version available through Google Play.

**Comment by zeapo** [comment]
Thanks for the report. I have yet to rewrite this part. Could you report
the issue when you get a force crash, it'd be very helpful.

**Comment by zeapo** [comment]
I just fixed it, I see how, but not why your crash happened. I have to investigate this more to find the root of the problem.
