### ISSUE TITLE
Use GPG Key for SSH

### ISSUE THREAD

**Issue by the-kenny** [zeapo/Android-Password-Store#71]
One can use GPG subkeys as SSH keys. I store/generate my keys on a Yubikey which allows using them under Android.

It would be really nice if android-password-store could use the keys on the smartcard via OpenKeychain so I don't have to store the ssh-key on the device.

**Comment by zeapo** [comment]
That would be great indeed.

**Comment by zeapo** [comment]
From my investigations, we will have to write some code for both OpenKeychain app and openpgp-api-lib to support that. Neither of them offer an intent (or api for the later) to export a key or sub-key.

regarding the ssh-key import, you can delete the key once you imported it. we make a copy inside the data folder to avoid that other apps access it without permission (root necessary)

**Comment by shtrom** [comment]
:+1:

**Comment by jfjallid** [comment]
Any progress on this? This feature would be really useful!

**Comment by zeapo** [comment]
This will have to wait for https://github.com/open-keychain/open-keychain/issues/908

**Comment by jcgruenhage** [comment]
Afaict the open-keychain part has been done, and PRs have been submitted to ConnectBot already.

**Comment by saro** [comment]
Apparently https://github.com/open-keychain/termbot is a fork of connectbot with the new Authentication API. Isn't clear from https://github.com/connectbot/connectbot/pull/567 if this feature will be included in the main ConnectBot project.

**Comment by languitar** [comment]
Can someone explain why connect bot is in the loop here? Or is this just a sidenote that others are already using the API?

**Comment by jcgruenhage** [comment]
@languitar just a sidenote

**Comment by colemickens** [comment]
@alex005005 you'd mentioned working on this, any progress? I switched my entire life over to `gopass` before realizing that this isn't implemented (I mistook the existing OpenKeychain support) so I'm keen on trying to get this working. I don't know much about Android, but I know enough Java to probably copy code from TermBot to this app.

**Comment by colemickens** [comment]
Heh, looks like more code than I expected, go figure. In case someone more proficient in Android is interested, it looks like the TermBot authors are still working on upstreaming to ConnectBot  so it's actually quite easy to see the diff to add support for OpenKeychain here: https://github.com/connectbot/connectbot/pull/567

**Comment by zidhuss** [comment]
Added in #486.
