### ISSUE TITLE
App unable to push to repo

### ISSUE THREAD

**Issue by yohlane** [zeapo/Android-Password-Store#74]
I have pass server with git (last version, build from git) and the app (from the market.
When I add an entry from the server I can pull it from the app but the app seems unable to push new entries to the server.

From logcat:

03-23 12:01:50.590  28818-28818/com.zeapo.pwdstore D/PASS﹕ Menu item 2131427457 pressed
03-23 12:01:50.590  28818-28818/com.zeapo.pwdstore I/Timeline﹕ Timeline: Activity_launch_request id:com.zeapo.pwdstore time:53927730
03-23 12:01:51.176  28818-28818/com.zeapo.pwdstore I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@42534420 time:53928319
03-23 12:02:03.621  28818-28818/com.zeapo.pwdstore W/IInputConnectionWrapper﹕ finishComposingText on inactive InputConnection
03-23 12:02:03.621  28818-28818/com.zeapo.pwdstore W/IInputConnectionWrapper﹕ finishComposingText on inactive InputConnection
03-23 12:02:03.621  28818-28818/com.zeapo.pwdstore D/PASS﹕ Check, dir: /data/data/com.zeapo.pwdstore/files/store
03-23 12:02:03.871  28818-28818/com.zeapo.pwdstore I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@426abd20 time:53941008

**Comment by zeapo** [comment]
Sorry for the delay, I forgot about this issue.

Are you still able to reproduce it? If so, do you have the logs from the server side?

**Comment by zeapo** [comment]
This has probably been fixed with #89
