### ISSUE TITLE
Add a "sync" command

### ISSUE THREAD

**Issue by dainnilsson** [zeapo/Android-Password-Store#78]
I find myself running pull and push consecutively each time I want to synchronize my passwords with the remote repo. I propose adding (preferably replacing the existing pull and push commands) a "sync" command, that pulls from the remote repo and then pushes if there are local commits. This would save me from having to enter the SSH passphrase twice, and is easier to use.

**Comment by micressor** [comment]
That would be greate! +1

**Comment by zeapo** [comment]
indeed :)
