### ISSUE TITLE
Use a font with distinctive characters for passwords.

### ISSUE THREAD

**Issue by kevincox** [zeapo/Android-Password-Store#80]
Currently it is very difficult to tell the difference between similar characters such as "I" and "l".  It would be nice if a better font wad chosen so that all characters were distinct.

**Comment by zeapo** [comment]
Indeed, when I wrote the piece of code on kitkat, I used the monospaced font available with android and it worked OK. I dunno what happened since the support library. 
Anyhow, I have added a true mono font. Available in next build.

**Comment by timvisee** [comment]
I'm still having trouble distinguishing between `0` and `O` in the latest build. Could a different mono font be used with for example, has a dot inside the `0`?
