### ISSUE TITLE
Allow gpg subkeys with detached master key to be used

### ISSUE THREAD

**Issue by phenguin** [zeapo/Android-Password-Store#81]
I want to use a subkey exported detached from my main signing gpg key to encrypt / decrypt my password store files.  This works fine on my laptop, however after setting up  openkeychain, exporting the subkey (via gpg --export-secret-subkeys -a KEYNAME! > key.asc), and importing it into openkeychain, I am unable to complete the final step of selecting the key from the password store interface.  In the password store settings under "Select OpenPGP Key Id" -> Account key, I can see the key I have imported, however it is greyed out, leaving me unable to select it.  Is this a known issue / am I doing something obviously wrong?  Thanks

**Comment by zeapo** [comment]
Sorry for the delay.
The "Select OpenPGP Key Id" is no longer available (as of version v1.2.0.16) as it is not useful anymore.

If you want to select the key from OpenKeyChain, just try to decrypt a password, you'll be prompted to select the key you want to use.

**Comment by DelusionalLogic** [comment]
The "Select OpenPGP Key Id" is still available in 1.2.0.23. I'm having the exact same issue. I can't select my imported detached subkey.

If i try to add a password it creates an empty file. If i them try to open them i obviously get a "No signed or encrypted data found" error from OpenKeychain.

**Comment by DelusionalLogic** [comment]
So it turns out i created the wrong kind of key when i made my new subkey. It's no wonder i couldn't select a signing only key as encryption.

I created a new encryption key, and it works now.

**Comment by zeapo** [comment]
Glad it works.

**Comment by Gfurst** [comment]
Can someone please provide more info on this... I'm pretty lost and the "how to setup" is bare bones...

So what are you supposed to do when importing from a already created repository? I'm a total gpg newb, but my guess is I should need to import from the already existing gpg key in my pc. However I ran into the issue described above, even though I import the key and have it verified, pass won't let me open any file with it.

**Comment by hughdavenport** [comment]
Hi @Gfurst.

As this bug seems to be fixed for the original report, I would recommend opening a new bug for this if you are still stuck. Reading the setup instructions at https://github.com/zeapo/Android-Password-Store/wiki/First-time-setup and the FAQ for openkeychain at https://www.openkeychain.org/faq/ will help a lot.

Cheers,

Hugh
