### ISSUE TITLE
please support HTTP Basic authentication over https

### ISSUE THREAD

**Issue by bjmgeek** [zeapo/Android-Password-Store#82]
I tried to clone my password store git repo over https using HTTP Basic authentication, but Password-Store still asks for my ssh private key passphrase.  Please add support for HTTP Basic authentication.  This is supported by standard command line git.

thanks,
Brian

**Comment by zeapo** [comment]
Hm, if you select HTTPS in the clone view, you shall not have the passphrase requested, just the password for your username.

**Comment by bjmgeek** [comment]
Here are a couple screenshots:
https://drive.google.com/file/d/0B1mWxyc9f_e9LWVCaEhUaWFCaWc/view?usp=sharing
https://drive.google.com/file/d/0B1mWxyc9f_e9b0ZSY1dEWHZvcjA/view?usp=sharing

**Comment by zeapo** [comment]
will make a build soon and you'll be able to download it from playstore/f-droid
