### ISSUE TITLE
Blank password store window in recent apps switcher

### ISSUE THREAD

**Issue by hnk** [zeapo/Android-Password-Store#83]
When I open the recent app switcher, the password store entry shows the last view of whatever password I had opened. This may also show a password or other sensible information.

Android apparently has the ability to 'blank' the apps entry in the recent task switcher and to prevent screen shots of an app:
http://stackoverflow.com/questions/9984083/show-black-preview-screen-in-task-manager-on-ics

I would very much welcome this as an enhancement, as I have just experienced a password being shown in the recent task switcher, even after the password timeout has run out!

I love this app and use it daily, keep up the good work!

**Comment by zeapo** [comment]
Thanks for the suggestion. Will be available in the next build.

**Comment by hnk** [comment]
Awesome, thanks!
