### ISSUE TITLE
Encrypt: Account name empty

### ISSUE THREAD

**Issue by mvdbos** [zeapo/Android-Password-Store#84]
When I try to create a new password, the following error is thrown:

```
Account name empty! Please set your OpenKeyChain account (email) in the preferences
```

I can *de*crypt passwords, just not encrypt.

Somehow the integration between OpenKeyChain and Password Store is not completely working.
It seems `accountName = settings.getString("openpgp_account_name", "");` in the encrypt() method results in an empty string here: [PgpHandler.java line 447](https://github.com/zeapo/Android-Password-Store/blob/v1.2.0.16/app/src/main/java/com/zeapo/pwdstore/crypto/PgpHandler.java#L447)

I have set OpenKeyChain as my OpenPGP provider and have selected an allowed key in the Password Store app settings within OpenKeyChain.

Versions tested: 
* Password Store 1.2.0.16
* OpenKeyChain: 3.2.1

**Comment by zeapo** [comment]
@mvdbos Thanks for spotting it. I missed this test as the account was already set on my devices.

**Comment by mvdbos** [comment]
That's fast. Thanks! :+1:
