### ISSUE TITLE
Unable to push to git repo

### ISSUE THREAD

**Issue by tgrosinger** [zeapo/Android-Password-Store#87]
I am sure this is just something I am doing wrong, but it doesn't seem like pushing new passwords created in the app is working. I can successfully pull new passwords into the app and view them however new ones are never visible on the computer hosting the git repo.

Version: 1.2.0.17
Pass Version: 1.4.2
Git repo path: `.password-store`
Auth-mode: ssh key

Let me know if there is more info I can provide.

**Comment by zeapo** [comment]
Hi,

You are using a non-bare repository. http://www.gitguys.com/topics/shared-repositories-should-be-bare-repositories/

**Comment by tgrosinger** [comment]
You are right, thank you. I have it working now.
It would be cool if that was in the documentation on the main Pass page. Maybe I just missed it.

**Comment by zeapo** [comment]
It is in the [FAQ](https://github.com/zeapo/Android-Password-Store#faq) :)
