### ISSUE TITLE
force close on LineageOS 17.1 after selecting storage location

### ISSUE THREAD

**Issue by gitwah** [zeapo/Android-Password-Store#881]
Hello,
I'm on a Xiaomi Mi Note 2 with Lineage 17.1. I installed the latest app version from f-droid. After setting up the app I get an immediate force close, same happens every time I try starting the app again. Crashes apparently happen as soon as the app comes into contact with my password-folder.

How to reproduce:
1 install app via f-droid
2 open the app
3 click settings, connect to open keychain, select your pgp key
4 copy your password-folder from desktop via usb to a folder on your phone (everything fine so far)
5 in the app: settings > external storage > choose said folder
6 system prompts "allow the app to read local storage?" > accept
7 force close, app never opens again

After deleting the app data, it starts up again just fine. I tried granting storage permission beforehand via android settings, that didn't help. When using the hidden storage option, everything is fine again until I push my password-folder there via adb. on opening the folder, the app crashes again. 

my folder there doesn't contain anything ununsual, just a few folders and .gpg-id, on LineageOS 16 it worked just fine with the same setup. I'm clueless. 

Any ideas?

**Comment by msfjarvis** [comment]
Would you be able to get a system log? [This](https://developer.android.com/studio/command-line/logcat) page explains how to go about it.

**Comment by bbenne10** [comment]
@gitwah: You may also want to check your version. It seems I was able to somehow install a 1.3.3 version from F-Droid this morning and had a similar issue when setting up the store. When installing from the correct link ([here](https://f-droid.org/en/packages/dev.msfjarvis.aps)), the issue disappeared.

**Comment by gitwah** [comment]
Apparently, something went wrong with f-droid. Wanting to look into this issue again, I opened f-droid and installed password store from there, somehow resulting in two versions of the app being installed (the new being version 1.8.1) next to each other. Uninstalled the old one and the issue described in OP disappeared. Weird.

**Comment by msfjarvis** [comment]
Sigh, we really need to get that old listing off F-Droid. @FabianHenneke any way for us to fast track this?

**Comment by fmeum** [comment]
> Sigh, we really need to get that old listing off F-Droid. @FabianHenneke any way for us to fast track this?

Someone is helping us here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7028
