### ISSUE TITLE
[FEATURE] Reselect a ssh key during initial setup

### ISSUE THREAD

**Issue by Schueni1** [zeapo/Android-Password-Store#883]
**Is your feature request related to a problem? Please describe.**
When selecting a wrong ssh-key on a clean/fresh installed app there is no way back. You would have to go into the android settings and clear cache and data to be able to reselect the correct ssh key and try setting up the app again. 

**Describe the solution you'd like**
An option in the initial setup interface to select/reselect the ssh-key would be nice.

**Describe alternatives you've considered**
Prompt to select a different ssh-key if it fails during the initial setup.

**Comment by msfjarvis** [comment]
Coming back to this, I'm still thinking of what a good UX for this entire process would be. Maybe make the SSH key selection a part of the server config screen? That'd certainly increase the information density in the screen to a possibly alarming level but it'd certainly unblock a few other things I'm working towards. @FabianHenneke @Skrilltrax care to weigh in?

**Comment by fmeum** [comment]
We might want to wait until the new Keystore-backed key generation has been merged. With it, I would like to make generation of a new SSH key the default during initial setup. Importing an SSH key should still be possible (and not just once), but I would not put it into the server config screen.

**Comment by msfjarvis** [comment]
> We might want to wait until the new Keystore-backed key generation has been merged. With it, I would like to make generation of a new SSH key the default during initial setup. Importing an SSH key should still be possible (and not just once), but I would not put it into the server config screen.

Sounds good to me 👍

**Comment by Skrilltrax** [comment]
> Coming back to this, I'm still thinking of what a good UX for this entire process would be. Maybe make the SSH key selection a part of the server config screen? That'd certainly increase the information density in the screen to a possibly alarming level but it'd certainly unblock a few other things I'm working towards. @FabianHenneke @Skrilltrax care to weigh in?

I think we should add SSH keys to the initial setup. Then it can be reused to update user preference.

**Comment by Knusper** [comment]
Hi, great app... But I just wasted a bit of time on this when setting up a new device, where I selected the wrong SSH key for my repo. It is not at all intutive how to change the key after such an user error ... Basically I ended up deleting the apps cache & storage and start again after finding this bug report...  So yes, I think this is still relevant... sorry for the noise

**Comment by skewballfox** [comment]
I'm currently trying to investigate this, but I'm running into an issue where the language server I'm using is having trouble finding a specific import. 

inside `Android-Password-Store/app/src/main/java/app/passwordstore/ui/onboarding/fragments/CloneFragment.kt` it seems it can't find the following import: `import app.passwordstore.databinding.FragmentCloneBinding`, mainly the `databinding` folder/module, which doesn't seem to exists. Is this leftover code from earlier in the project, something that is generated at build time or something else?

**Comment by msfjarvis** [comment]
> I'm currently trying to investigate this, but I'm running into an issue where the language server I'm using is having trouble finding a specific import.
> 
> inside `Android-Password-Store/app/src/main/java/app/passwordstore/ui/onboarding/fragments/CloneFragment.kt` it seems it can't find the following import: `import app.passwordstore.databinding.FragmentCloneBinding`, mainly the `databinding` folder/module, which doesn't seem to exists. Is this leftover code from earlier in the project, something that is generated at build time or something else?

It is generated at build time by the Android Gradle Plugin. https://developer.android.com/topic/libraries/view-binding

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
