### ISSUE TITLE
[BUG] SSH Key Auth Failure on Google Cloud Source Repositories in 1.9.x

### ISSUE THREAD

**Issue by ProjectMoon** [zeapo/Android-Password-Store#912]
**Describe the bug**
In 1.9.x, both FDroid and Google Play, I cannot synchronize a Google Cloud Source Repository, with either an RSA or ED25519 key. At first, I thought it was a variant of #875. But I'm not sure that's the case now. With either key, it simply does not work. I get "exhausted all available authentication methods" as an error back. 

**To Reproduce**
1. Add a Google Cloud Source Repository for the Git server.
2. Import an RSA key.
2. Attempt to synchronize/push/pull
3. Observe error

Note, to add a GCP repository, you probably have an email as your login, so your username in the app should be something like `myusername%40gmail.com` for `myusername@gmail.com`.

If the Git URL is something like `ssh://myusername@gmail.com@source.developers.google.com:2022/p/my-project/r/my-pass-repo`:
* The username will be as above: `myusername%40gmail.com`
* The port will obviously be `2022`
* Server will be `source.developers.google.com`
* The repository path will be `/p/my-project/r/my-pass-repo`

**Expected behavior**
No error, passwords update.

**Screenshots**

**Device information (please complete the following information):**
 - Device: OnePlus 6
 - OS: OmniROM MicroG version (Android 10)
 - App version 1.9.0 (FDroid), 1.9.2 (Google Play)

**Comment by fmeum** [comment]
I don't think that percent encodings would work here, so the username would have to be `myusername@gmail.com`. But a user part with an '@' is not accepted by JGit's `URIish`, which then proceeds to connect to the host `gmail.com@source.developers.google.com` and fail.

The only possible fix I see is to manually fix this up in `SshjSession` (although that feels horrible).

**Comment by ProjectMoon** [comment]
To be clear, the login method described above works perfectly fine in versions before 1.9, and is in fact how I'm using it with app version 1.8.

**Comment by fmeum** [comment]
> To be clear, the login method described above works perfectly fine in versions before 1.9, and is in fact how I'm using it with app version 1.8.

We switched the SSH backend since the old one does not support modern cryptographic algorithms. But apparently it dealt better with weird URIs.

**Comment by msfjarvis** [comment]
Might be worth reporting it over at SSHJ as well and see what Jeroen thinks.

**Comment by fmeum** [comment]
> Might be worth reporting it over at SSHJ as well and see what Jeroen thinks.

He can't fix it, it's JGit's URIish that is broken. Maybe JSch never used its parsing capabilities and just reparsed the string representation?

**Comment by msfjarvis** [comment]
> > Might be worth reporting it over at SSHJ as well and see what Jeroen thinks.
> 
> He can't fix it, it's JGit's URIish that is broken. Maybe JSch never used its parsing capabilities and just reparsed the string representation?

It's certainly possible. If we can work around it I think we should do it.

**Comment by fmeum** [comment]
> > > Might be worth reporting it over at SSHJ as well and see what Jeroen thinks.
> > 
> > 
> > He can't fix it, it's JGit's URIish that is broken. Maybe JSch never used its parsing capabilities and just reparsed the string representation?
> 
> It's certainly possible. If we can work around it I think we should do it.

We can. @ProjectMoon Could you verify whether #913 fixes the issue for you? If you don't want to build PS yourself, we could merge the PR and you could try our snapshot APKs.

@msfjarvis This seems to be a regression, would you say it warrants another point release? Could you take care of the Changelog entry?

**Comment by msfjarvis** [comment]
> @msfjarvis This seems to be a regression, would you say it warrants another point release? Could you take care of the Changelog entry?

It does need a changelog entry but I'm hesitant to publish another release. The bug doesn't seem to affect a lot of people and I believe @ProjectMoon can switch to the snapshot builds for the next few weeks until 1.10 is due.

**Comment by ProjectMoon** [comment]
I don't have the capability to build android apps at the moment (haven't set up android studio or anything like that). But I can try a snapshot APK.

**Comment by msfjarvis** [comment]
> I don't have the capability to build android apps at the moment (haven't set up android studio or anything like that). But I can try a snapshot APK.

All good, [here](https://dl.msfjarvis.dev/share/app-release.apk)'s an APK. GitHub Actions seems to be having trouble right now so I doubt the automatic snapshot deployment would work. The version code for this build is higher than the Play Store version, so you will not be able to downgrade to the Store version without having to reinstall (hopefully we haven't broken anything that would make that necessary, but please let us know if we have!).
