### ISSUE TITLE
[FEATURE] Edit Entry Mode

### ISSUE THREAD

**Issue by TinfoilSubmarine** [zeapo/Android-Password-Store#922]
**Is your feature request related to a problem? Please describe.**
If I need to add some piece of information to a password file and that piece of information is stored in my clipboard, I am unable to quickly paste into the file. This is because whenever I open a password, the password is immediately copied to the clipboard and overwrites whatever data I had in my clipboard. Sometimes, this is just a nuisance, since I can just go re-copy the data to my clipboard by switching back to whatever app I copied from, but sometimes this is not possible.

**Describe the solution you'd like**
As a compromise to avoid the above frustration from happening but also not removing the automatic copy to clipboard feature which I also use, it would be great if the user could long press a password entry and choose to edit the password instead, skipping past the view screen and not copying anything into the clipboard.

**Describe alternatives you've considered**
Another possibility for this is, as hinted at, to disable automatically copying to clipboard, which is already available in the settings. Then, the user can use any of the available options to copy the password. This is my current workflow to avoid running into this issue.

**Comment by msfjarvis** [comment]
The flow you're using is the recommended one for now. The ability to directly edit passwords was removed for technical reasons and there are no plans at the moment to change this. If there's time left in the July development cycle I will consider tackling this.

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
