### ISSUE TITLE
[BUG] Renamed site.com to site.com\username - file vanishes

### ISSUE THREAD

**Issue by AeliusSaionji** [zeapo/Android-Password-Store#928]
Some while back i transitioned from username in file to the file is the username, but I still have some entries I never updated.

I attempted to update an entry from Android-Password-Store just now and it responded by losing the file entirely!

**Comment by msfjarvis** [comment]
Please don't remove the issue template in the future, some effort put in by you greatly improves our ability to triage and resolve the problem.

**Comment by AeliusSaionji** [comment]
I guess this could be a bug report and a feature request depending on how we approach this- either sanitize the input against a user trying to do this, or implement a routine to create a folder (which is what I hoped might happen).

**Comment by msfjarvis** [comment]
This is more of a we-should-make-things-clear situation as opposed to an actual bug. If you change the directory in the category name above the name of the password, you'll see that it properly creates the path and moves the file in.
