### ISSUE TITLE
[BUG] Generate SSH key not available on clean install

### ISSUE THREAD

**Issue by matthijskooijman** [zeapo/Android-Password-Store#937]
**Describe the bug**
[Documentation](https://github.com/android-password-store/Android-Password-Store/wiki/Generate-SSH-Key
) suggests to use "Settings > Generate SSH key pair" to generate an SSH key. However, I could not find this option in the settings when I tried today, so I ended up using OpenKeyChain instead.

Then, after succesfully cloning the git repo, the generate option suddenly appeared in the settings. It is under the "Repository" category, so I suspect that this entire category is hidden when no valid repository is present?

**To Reproduce**
1. Clean install of password store (or probably also "Settings" -> "Delete repository"
2. Click on "Settings"
3. Cannot find "Generate SSH key pair" option.

**Expected behavior**
The option should be listed.

**Device information (please complete the following information):**
 - Device: Fairphone 2
 - OS: Stock ROM (Fairphone Open OS), Android 7
 - App version: 1.9.2

**Comment by msfjarvis** [comment]
Your assessment [is correct](https://github.com/android-password-store/Android-Password-Store/blob/d4379a47791ea0002eda9821f35c632f1e224962/app/src/main/java/com/zeapo/pwdstore/UserPreference.kt#L99). I think we can do away with this.
