### ISSUE TITLE
Can't sync to a gitolite repository

### ISSUE THREAD

**Issue by jpro-personal** [zeapo/Android-Password-Store#945]
Hi, 

I'm trying to setup Android-Password-Store against a gitolite repository, but whatever I try I get the jgit error invalid origin. 

If I clone the gitolite repo to a bare repo for a normal user account I can sync straight away.

Looking through similar issues I wonder if it is because I'm can't give the full path to the repo - e.g /home/git/pass.git instead of just pass.git as gitolite wants. Using the full path doesn't help. 

I'm running the latest version from either F-Droid or Google Play - v1.9.2.

I can't see how to see the full URL as some people seem to do in the other issues - maybe that would help ? 

Do you have any suggestions ?

Thanks

Jeremy

**Comment by msfjarvis** [comment]
I don't have a local gitolite setup so I used the first one that came to mind (git.zx2c4.com) and was able to clone from it with no problems. I believe there's some confusions about our URL builder that's causing a configuration issue. Here's the settings I used.
![screenshot-20200721-142637](https://user-images.githubusercontent.com/13348378/88034488-5f08d480-cb5e-11ea-9d75-02ec187b5608.png)

**Comment by jpro-personal** [comment]
Hi, 

Sorry that was user error on my end !

I hadn't given the Android Password Store ssh key access to the repo on the gitolite server. As soon as I did that it worked fine.

I was using the logs in /var/log/secure to check for valid logs instead of the gitolite logs.

Thanks very much for your response and sorry it was just my mistake.

Jeremy
