### ISSUE TITLE
Can't select OpenPGP Key id

### ISSUE THREAD

**Issue by etam** [zeapo/Android-Password-Store#95]
Password Store: 1.2.0.21 from F-Droid
OpenKeychain: 3.2.3  from F-Droid
Device: Jolla - uses myriad alien dalvik. It's not a native android, but so far had no problems with it.

I've successfully imported pgp key (it has no e-mail nor identity included) into OpenKeychain.
In Password Store I've selected my key.
- In settings I press "Select OpenPGP Key id"
- OpenKeychain shows up
- I select my key id
- OpenKeychain closes
- Back in Password Store a small pop-up shows saying "PGP key selected", but in settings page there's still "No key selected".

**Comment by zeapo** [comment]
Are you able to clone/create a new repository?

This issue should not prevent you from using password store.

**Comment by etam** [comment]
Well, it's a bit complicated. Most of the time, no messages are displayed and absolutely nothing happens. Sometimes some files appear in .git directory. Once I successfully cloned existing repo, but I couldn't repeat that. But that's a material for another bug report.

**Comment by etam** [comment]
So I managed to clone my existing repo once again. Decrypting stored passwords works fine.

**Comment by karlgrz** [comment]
See the exact same behavior on OnePlus One running OxygenOS.
