### ISSUE TITLE
[BUG] otp not being generated anymore

### ISSUE THREAD

**Issue by mithodin** [zeapo/Android-Password-Store#954]
**Describe the bug**
At some point, sadly I can't really pin down the release, but it must have been a few weeks ago at least, android-password-store stopped generating otp codes.

**To Reproduce**
1. Add otpauth:// url to a password file
2. Open in android-password-store
3. See url, but no OTP

**Expected behavior**
Generate OTP code

**Screenshots**

**Device information (please complete the following information):**
 - Device: Wileyfox Swift (Lineage OS 17), Motorola Moto G7 Power (crDroid), Samsung A71 (stock Android 10)
 - Version 1.9.2

**Comment by msfjarvis** [comment]
The TOTP feature was removed in 1.9.0 for a variety of reasons and was rewritten for 1.10.0 with extra features and test coverage. The update is available on the Play Store.
