### ISSUE TITLE
Missing settings for OpenPGP

### ISSUE THREAD

**Issue by joshcangit** [zeapo/Android-Password-Store#956]
**Describe the bug**
Missing options in the settings to select OpenPGP Provider and OpenPGP Key id.

**Device information (please complete the following information):**
- Android version:
10
- Device manufacturer:
samsung
- Device model:
SM-G973F
- App version:
1.10.0

**Comment by msfjarvis** [comment]
They're not missing, we removed them intentionally. We'll evaluate whether they need to return in #955.
