### ISSUE TITLE
Free and non-free releases, what is the difference?

### ISSUE THREAD

**Issue by crabvk** [zeapo/Android-Password-Store#964]
I've checked the wiki and FAQ and can't find any info about the difference between free and non-free versions.
It would be helpful to add such info to readme or wiki.

**Comment by msfjarvis** [comment]
Apologies for that confusion, we'll certainly update the documentation.

The `free` version is built without Google Play Services dependencies that are used by the `nonFree` variant to provide SMS OTP Autofill support.
