### ISSUE TITLE
Symlink support

### ISSUE THREAD

**Issue by tverlaan** [zeapo/Android-Password-Store#98]
I have a few symlinks in my password store. The Android app is unable to read them and with git push it changes the symlinks to regular files destroying my original symlinks (when I pull from the other end).
The first issue is a bit annoying, but the second one is preventing me from inserting passwords from my phone and getting them on my laptop. I would love to see that fixed (not a Java developer though).

**Comment by wongma7** [comment]
Attempt at explanation: jgit determines somehow that the file system has no symlink support (Java 6?). So in .git/config it sets core.symlinks = false, which causes what you observe as destruction of the original symlinks. If you manually set core.symlinks = true, you will get an exception "Symlinks are not supported with this OS/JRE" when you attempt git operations. My understanding is that this issue would be fixed by upgrading to jgit 4+ but we can't because it depends on some classes not offered by Android?

We could make the app able to read symlinks in the meantime, if they are created locally somehow, but you and other git users wouldn't benefit from that.

**Comment by zeapo** [comment]
@wongma7 why jgit 4.0 wont work?

@tverlaan are you using the external store feature? (i.e. on the sdcard)

**Comment by wongma7** [comment]
@zeapo It says, class not found Java.nio.file.path when you try to run it.

**Comment by tverlaan** [comment]
@zeapo no I'm not storing it on the sdcard. Should I or would it make it easier?

I'm also open to other solutions, but can't think of any now.

**Comment by zeapo** [comment]
In fact you should not store it on the sdcard as it's a fat32 and it does not support symlink.

I didn't have the time to debug it yet, sorry.

**Comment by tverlaan** [comment]
I stopped using symlinks. This issue wasn't the only reason for me to not using them anymore :-)

I would say you can close this unless you really want to fix it. Symlinks are not a native feature of the password store anyway. Although, if you don't fix it please put a small warning in a FAQ or something.

**Comment by zeapo** [comment]
Sorry to hear that.
I've been extremely busy lately so unable to work on APS, thankfully @wongma7 is here :)

Also, I started thinking of writing a v2 from scratch as the project was not meant to be that big from the start :)

**Comment by tverlaan** [comment]
I see this issue is still open.  Already found a way of solving it? I came across a setting which helps with working with symlinks when you have to support FAT as well. If you set core.symlinks[1] to false the symlink will just be stored as a file. I tried it but it didn't help. Maybe you can use this setting in the app as well? Perhaps then it would work (still no decryption on the phone, but not changing the git repo on files you're not touching).

It should also be possible to just add and commit the actually changed files if I'm correct. Right now it seems to do `git add .`. But please correct me if I'm wrong.

[1] https://www.kernel.org/pub/software/scm/git/docs/git-config.html

**Comment by gattazr** [comment]
Hi. More than a year later I'm running into the same problem.

Do you think there is anything that could be done ?

**Comment by zeapo** [comment]
Sadly I will have to mark this as WONTFIX as it's an Android issue (does not support Java7 files API) and jgit needs that for symlink support.

**Comment by c-e-p-x-u-o** [comment]
But you can handle plain files with other file name inside (that jgit makes core.symlinks = false) and handle them.

**Comment by petr-nehez** [comment]
What if you upgrade JGit to >= 4.0.1?
Woudn't solve this issue?

**Comment by raxod502** [comment]
@zeapo I understand if the underlying issue can't be fixed, but I just wasted a bunch of time debugging why my symlinks somehow got trashed without my knowing. Could the app at least display a warning before allowing you to commit, if any symlinks are detected?
