### ISSUE TITLE
Add TOTP button shows even when TOTP is present

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#981]
**Describe the bug**

Add TOTP button shows on password edit screen even when TOTP is present in extra content

**To Reproduce**

1. Select any entry with a TOTP secret/OTPAUTH URL in extra content
2. Press the edit icon
3. Observe add TOTP button is shown alongside TOTP secret/OTPAUTH URL in extra content

**Expected behavior**

Add TOTP button does not show on screen when a secret is already present.

**Screenshots**

None needed

**Device information (please complete the following information):**

 - Device: Google Pixel 2
 - OS: Android 11 Beta 2.5
 - App version: 1.10.1

**Additional context**

I looked into this but it seems our `hasTotp` check just isn't working? My code is [here](https://github.com/msfjarvis/Android-Password-Store/commits/fixup-totp-check).

**Comment by fmeum** [comment]
@msfjarvis What's causing this bug is that we are using `return@with` instead of `return@apply` in `updateViewState`.

**Comment by msfjarvis** [comment]
> @msfjarvis What's causing this bug is that we are using `return@with` instead of `return@apply` in `updateViewState`.

I will now proceed to kill myself.
