### ISSUE TITLE
[BUG] VerifyError on AutofillSmsActivity crashes AutofillService on OTP fields

### ISSUE THREAD

**Issue by fmeum** [zeapo/Android-Password-Store#989]
**Describe the bug**
Play Store version 1.10.2 crashes with a `java.lang.VerifyError` when Autofill triggers on a field that is recognized as an OTP field.

This is pretty bad since the Autofill service is not restarted automatically after this happens, so it's not just the new OTP filling features that are broken by this. I don't want to say it, but we probably need a 1.10.3 release.

The logs have the following to say:
```
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: FATAL EXCEPTION: main
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: Process: dev.msfjarvis.aps, PID: 32149
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class com.zeapo.pwdstore.autofill.oreo.ui.AutofillSmsActivity: java.lang.Object com.zeapo.pwdstore.autofill.oreo.ui.AutofillSmsActivity.waitForSms(kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.zeapo.pwdstore.autofill.oreo.ui.AutofillSmsActivity.waitForSms(kotlin.coroutines.Continuation): [0xA1] register v9 has type Reference: com.google.android.gms.common.api.ResolvableApiException but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef (declaration of 'com.zeapo.pwdstore.autofill.oreo.ui.AutofillSmsActivity' appears in base.apk)
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: 	at com.zeapo.pwdstore.autofill.oreo.OreoAutofillService.onFillRequest(OreoAutofillService.kt:94)
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: 	at android.service.autofill.-$$Lambda$I0gCKFrBTO70VZfSZTq2fj-wyG8.accept(Unknown Source:8)
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:307)
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-30 19:58:17.515 10242 32149 32149 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**To Reproduce**
1. Enable Autofill.
2. Tap on a field that is likely to be recognized as an OTP field. The particular crash above was a result of focusing the 2FA SMS OTP field on twitter.com.

**Expected behavior**
No exception.

**Screenshots**
N/A, the crash happens before any Autofill UI is shown.

**Device information (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android 11 Beta
 - App version: 1.10.2

**Additional context**
I have never seen this error before and can't reproduce it on debug builds.

**Comment by fmeum** [comment]
@msfjarvis This might be related to [this issue](https://github.com/Kotlin/kotlinx.coroutines/issues/2049), which would explain why we didn't encounter the crash on debug builds: We are using Kotlin 1.4 on develop. Will try what happens with Kotlin 1.3.X.

**Comment by msfjarvis** [comment]
Oh I know this error, I've faced it in #865. We need to uprev coroutines to 1.4 for this to work. I fixed it with [this](https://github.com/android-password-store/Android-Password-Store/pull/865/commits/42e4d7ac0e51c01829a21dc191d61bd4643beb63).

**Comment by msfjarvis** [comment]
Guess we're shipping 1.4 into release builds then

**Comment by fmeum** [comment]
Alternatively, according to https://github.com/Kotlin/kotlinx.coroutines/issues/2049#issuecomment-665006691, we might only need to downgrade Coroutines to 1.3.6. I will see whether that helps.
