### ISSUE TITLE
[BUG] Unable to access password and crypto settings

### ISSUE THREAD

**Issue by gromgit** [zeapo/Android-Password-Store#993]
**Describe the bug**
I've been using `pass` on Linux for a long time now, and I just installed v1.10.3 along with OpenKeychain v5.5, both from the Google Play Store and both current as of this writing. I loaded my Linux password-store GPG key in OpenKeychain, then started the Password Store app and cloned my Linux password repo via SSH. I'm able to view all the same subfolders and key entries that I can on the Linux command line, but when I tap on any entry to view its contents, the display flips as if to show the password page, then immediately flips back to the entry list.

I also noticed that the Settings page does _not_ have a Crypto section at all.

**To Reproduce**
1. Go to any password folder
2. Tap on any entry
3. See the screen "flip" to the left, then immediately flip back again to the folder list in [1].

**Expected behavior**
I expected to be prompted for my PGP key password, then be shown the password entry that I tapped on.

**Screenshots**
None available

**Device information (please complete the following information):**
 - Device: Redmi Note 7
 - OS: MIUI Global 11.0.6 (Android 9)
 - App version: 1.10.3, OpenKeychain 5.5

**Additional context**
N/A

**Comment by msfjarvis** [comment]
Same problem as https://github.com/android-password-store/Android-Password-Store/issues/518, Xiaomi's fucking up their software.

**Comment by gromgit** [comment]
Huh, it really was that simple. Thanks much!

**Comment by gromgit** [comment]
Since I went (unsuccessfully) looking in the FAQ before posting this issue, I've updated the FAQ accordingly, so that other folks after me won't have to guess.
