### ISSUE TITLE
[FEATURE] Create directories with different gpg keys

### ISSUE THREAD

**Issue by Schueni1** [zeapo/Android-Password-Store#994]
It would be cool, if it was possible to create new directories and encrypt them with different gpg keys.

Right now I have to create these special directories on my laptop and then sync them with the app.

In pass this is possible with:
```
pass init [-p path] <gpg-id>
```

**Comment by msfjarvis** [comment]
I don't have a lot of good ideas on how to achieve it, but the least terrible one that comes to mind is adding another option to the overflow menu along with push/pull, titled along the lines of 'Set GPG key ID for this directory' that makes you select a key in OpenKeychain and then writes it into `.gpg-id`.

**Comment by fmeum** [comment]
Let's make this a bit easier: When creating a new folder, add a checkbox to the dialog asking for the name of the new folder. If checked, trigger the same flow we run if no top-level .gpg-id exists, but for the new folder. 

Changing the id for existing folders is too complicated as it may involve reencryption and multiple IDs.

**Comment by msfjarvis** [comment]
> Let's make this a bit easier: When creating a new folder, add a checkbox to the dialog asking for the name of the new folder. If checked, trigger the same flow we run if no top-level .gpg-id exists, but for the new folder.
> 
> Changing the id for existing folders is too complicated as it may involve reencryption and multiple IDs.

Certainly overlooked re-encryption. Going to implement your proposal sometime this week.

**Comment by msfjarvis** [comment]
Actually, will tackle it after #865 lands.
